Django: django.test.utils Namespace Reference
django.test.utils Namespace Reference
Classes
class Approximate
class CaptureQueriesContext
class ContextList
class IgnoreDeprecationWarningsMixin
class IgnorePendingDeprecationWarningsMixin
class override_settings
class TransRealMixin
Functions
def instrumented_test_render (self, context)
def setup_test_environment ()
def teardown_test_environment ()
def get_warnings_state ()
def restore_warnings_state (state)
def get_runner
def setup_test_template_loader
def restore_template_loaders ()
def compare_xml (want, got)
def strip_quotes (want, got)
def str_prefix (s)
def patch_logger (logger_name, log_level)
Variables
tuple __all__
string RESTORE_LOADERS_ATTR = '_original_template_source_loaders'
tuple TZ_SUPPORT = hasattr(time, 'tzset')
tuple warn_txt
tuple requires_tz_support
Function Documentation
def django.test.utils.compare_xml (want, got)
Tries to do a 'xml-comparison' of want and got.  Plain string
comparison doesn't always work because, for example, attribute
ordering should not be important. Comment nodes are not considered in the
comparison.
Based on http://codespeak.net/svn/lxml/trunk/src/lxml/doctestcompare.py
Definition at line 271 of file utils.py.
References django.template.defaultfilters.join(), and django.test.utils.strip_quotes().
Referenced by django.test.testcases.SimpleTestCase.assertXMLEqual(), django.test.testcases.SimpleTestCase.assertXMLNotEqual(), and django.test.simple.OutputChecker.check_output_xml().
def django.test.utils.get_runner (settings, test_runner_class = None)
Definition at line 156 of file utils.py.
References django.utils.encoding.force_str, and django.template.defaultfilters.join().
Referenced by django.core.management.commands.test.Command.create_parser(), and django.core.management.commands.test.Command.handle().
def django.test.utils.get_warnings_state ()
Returns an object containing the state of the warnings module
Definition at line 136 of file utils.py.
def django.test.utils.instrumented_test_render (self, context)
An instrumented Template render method, providing a signal
that can be intercepted by the test system Client
Definition at line 79 of file utils.py.
def django.test.utils.patch_logger (logger_name, log_level)
Context manager that takes a named logger and the logging level
and provides a simple mock-like list of messages received
Definition at line 428 of file utils.py.
Referenced by django.contrib.auth.tests.test_views.ChangelistTests.test_changelist_disallows_password_lookups(), django.contrib.sessions.tests.SessionTestsMixin.test_decode_failure_logged_to_security(), django.contrib.auth.tests.test_views.PasswordResetTest.test_poisoned_http_host(), and django.contrib.auth.tests.test_views.PasswordResetTest.test_poisoned_http_host_admin_site().
def django.test.utils.restore_template_loaders ()
Restores the original template loaders after
:meth:`setup_test_template_loader` has been run.
Definition at line 200 of file utils.py.
def django.test.utils.restore_warnings_state (state)
Restores the state of the warnings module when passed an object that was
returned by get_warnings_state()
Definition at line 147 of file utils.py.
def django.test.utils.setup_test_environment ()
Perform any global pre-test setup. This involves:
    - Installing the instrumented test renderer
    - Set the email backend to the locmem email backend.
    - Setting the active locale to match the LANGUAGE_CODE setting.
Definition at line 88 of file utils.py.
References django.utils.translation.trans_null.deactivate.
def django.test.utils.setup_test_template_loader (templates_dict, use_cached_loader = False)
Changes Django to only find templates from within a dictionary (where each
key is the template name and each value is the corresponding template
content to return).
Use meth:`restore_template_loaders` to restore the original loaders.
Definition at line 171 of file utils.py.
def django.test.utils.str_prefix (s)
Definition at line 367 of file utils.py.
def django.test.utils.strip_quotes (want, got)
Strip quotes of doctests output values:
>>> strip_quotes("'foo'")
"foo"
>>> strip_quotes('"foo"')
"foo"
Definition at line 336 of file utils.py.
Referenced by django.test.simple.OutputChecker.check_output_json(), and django.test.utils.compare_xml().
def django.test.utils.teardown_test_environment ()
Perform any global post-test teardown. This involves:
    - Restoring the original test renderer
    - Restoring the email sending functions
Definition at line 112 of file utils.py.
Variable Documentation
tuple django.test.utils.__all__
Initial value:
 = (
     'Approximate', 'ContextList',  'get_runner', 'override_settings',
     'requires_tz_support', 'setup_test_environment', 'teardown_test_environment',
 )
Definition at line 25 of file utils.py.
tuple django.test.utils.requires_tz_support
Initial value:
 = skipUnless(TZ_SUPPORT,
         "This test relies on the ability to run a program in an arbitrary "
         "time zone, but your operating system isn't able to do that.")
Definition at line 467 of file utils.py.
string django.test.utils.RESTORE_LOADERS_ATTR = '_original_template_source_loaders'
Definition at line 30 of file utils.py.
tuple django.test.utils.TZ_SUPPORT = hasattr(time, 'tzset')
Definition at line 31 of file utils.py.
tuple django.test.utils.warn_txt
Initial value:
 = ("get_warnings_state/restore_warnings_state functions from "
     "django.test.utils are deprecated. Use Python's warnings.catch_warnings() "
     "context manager instead.")
Definition at line 131 of file utils.py.