Django: django.db.transaction Namespace Reference
django.db.transaction Namespace Reference
Classes
class Atomic
Decorators / context managers #.
class Transaction
Deprecated decorators / context managers #.
class TransactionManagementError
Functions
def get_connection
def abort
Deprecated private APIs #.
def enter_transaction_management
def leave_transaction_management
def is_dirty
def set_dirty
def set_clean
def is_managed
def managed
def commit_unless_managed
def rollback_unless_managed
def get_autocommit
Public APIs #.
def set_autocommit
def commit
def rollback
def savepoint
def savepoint_rollback
def savepoint_commit
def clean_savepoints
def get_rollback
def set_rollback
def atomic
def non_atomic_requests
def autocommit
def commit_on_success
def commit_manually
def commit_on_success_unless_managed
Detailed Description
This module implements a transaction manager that can be used to define
transaction handling in a request or view function. It is used by transaction
control middleware and decorators.
The transaction manager can be in managed or in auto state. Auto state means the
system is using a commit-on-save strategy (actually it's more like
commit-on-change). As soon as the .save() or .delete() (or related) methods are
called, a commit is made.
Managed transactions don't do those commits, but will need some kind of manual
or implicit commits or rollbacks.
Function Documentation
def django.db.transaction.abort (using = None)
Deprecated private APIs #.
Roll back any ongoing transactions and clean the transaction management
state of the connection.
This method is to be used only in cases where using balanced
leave_transaction_management() calls isn't possible. For example after a
request has finished, the transaction state isn't known, yet the connection
must be cleaned up for the next request.
Definition at line 48 of file transaction.py.
References django.db.transaction.get_connection().
def django.db.transaction.atomic (using = None, savepoint = True)
Definition at line 375 of file transaction.py.
References django.utils.six.callable.
Referenced by django.db.transaction.commit_on_success_unless_managed().
def django.db.transaction.autocommit (using = None)
Decorator that activates commit on save. This is Django's default behavior;
this decorator is useful if you globally activated transaction management in
your settings file and want the default behavior in some view functions.
Definition at line 455 of file transaction.py.
References django.db.transaction.enter_transaction_management(), and django.db.transaction.leave_transaction_management().
def django.db.transaction.clean_savepoints (using = None)
Resets the counter used to generate unique savepoint ids in this thread.
Definition at line 169 of file transaction.py.
References django.db.transaction.get_connection().
def django.db.transaction.commit (using = None)
Commits a transaction and resets the dirty flag.
Definition at line 135 of file transaction.py.
References django.db.transaction.get_connection().
Referenced by django.db.transaction.commit_on_success().
def django.db.transaction.commit_manually (using = None)
Decorator that activates manual transaction control. It just disables
automatic transaction control and doesn't do any commit/rollback of its
own -- it's up to the user to call the commit and rollback functions
themselves.
Definition at line 502 of file transaction.py.
References django.db.transaction.enter_transaction_management(), and django.db.transaction.leave_transaction_management().
def django.db.transaction.commit_on_success (using = None)
This decorator activates commit on response. This way, if the view function
runs successfully, a commit is made; if the viewfunc produces an exception,
a rollback is made. This is one of the most common ways to do transaction
control in Web apps.
Definition at line 472 of file transaction.py.
References django.db.transaction.commit(), django.db.transaction.enter_transaction_management(), django.db.transaction.is_dirty(), django.db.transaction.leave_transaction_management(), and django.db.transaction.rollback().
def django.db.transaction.commit_on_success_unless_managed (using = None, savepoint = False)
Transitory API to preserve backwards-compatibility while refactoring.
Once the legacy transaction management is fully deprecated, this should
simply be replaced by atomic. Until then, it's necessary to guarantee that
a commit occurs on exit, which atomic doesn't do when it's nested.
Unlike atomic, savepoint defaults to False because that's closer to the
legacy behavior.
Definition at line 520 of file transaction.py.
References django.db.transaction.atomic(), and django.db.transaction.get_connection().
def django.db.transaction.commit_unless_managed (using = None)
Definition at line 111 of file transaction.py.
def django.db.transaction.enter_transaction_management (managed = True, using = None, forced = False)
Enters transaction management for a running thread. It must be balanced with
the appropriate leave_transaction_management call, since the actual state is
managed as a stack.
The state and dirty flag are carried over from the surrounding block or
from the settings, if there is no surrounding block (dirty is always false
when no current block is running).
Definition at line 60 of file transaction.py.
References django.db.transaction.get_connection().
Referenced by django.db.transaction.autocommit(), django.db.transaction.commit_manually(), and django.db.transaction.commit_on_success().
def django.db.transaction.get_autocommit (using = None)
Public APIs #.
Get the autocommit status of the connection.
Definition at line 123 of file transaction.py.
References django.db.transaction.get_connection().
def django.db.transaction.get_connection (using = None)
Get a database connection by name, or the default database connection
if no name is provided.
Definition at line 35 of file transaction.py.
Referenced by django.db.transaction.Atomic.__enter__(), django.db.transaction.Atomic.__exit__(), django.db.transaction.abort(), django.db.transaction.clean_savepoints(), django.db.transaction.commit(), django.db.transaction.commit_on_success_unless_managed(), django.db.transaction.enter_transaction_management(), django.db.transaction.get_autocommit(), django.db.transaction.get_rollback(), django.db.transaction.is_dirty(), django.db.transaction.leave_transaction_management(), django.db.transaction.rollback(), django.db.transaction.savepoint(), django.db.transaction.savepoint_commit(), django.db.transaction.savepoint_rollback(), django.db.transaction.set_autocommit(), django.db.transaction.set_clean(), django.db.transaction.set_dirty(), and django.db.transaction.set_rollback().
def django.db.transaction.get_rollback (using = None)
Gets the "needs rollback" flag -- for *advanced use* only.
Definition at line 175 of file transaction.py.
References django.db.transaction.get_connection().
def django.db.transaction.is_dirty (using = None)
Returns True if the current transaction requires a commit for changes to
happen.
Definition at line 80 of file transaction.py.
References django.db.transaction.get_connection().
Referenced by django.db.transaction.commit_on_success().
def django.db.transaction.is_managed (using = None)
Definition at line 103 of file transaction.py.
def django.db.transaction.leave_transaction_management (using = None)
Leaves transaction management for a running thread. A dirty flag is carried
over to the surrounding block, as a commit will commit all changes, even
those from outside. (Commits are on connection level.)
Definition at line 72 of file transaction.py.
References django.db.transaction.get_connection().
Referenced by django.db.transaction.autocommit(), django.db.transaction.commit_manually(), and django.db.transaction.commit_on_success().
def django.db.transaction.managed (flag = True, using = None)
Definition at line 107 of file transaction.py.
def django.db.transaction.non_atomic_requests (using = None)
Definition at line 393 of file transaction.py.
References django.utils.six.callable.
def django.db.transaction.rollback (using = None)
Rolls back a transaction and resets the dirty flag.
Definition at line 141 of file transaction.py.
References django.db.transaction.get_connection().
Referenced by django.db.transaction.commit_on_success().
def django.db.transaction.rollback_unless_managed (using = None)
Definition at line 115 of file transaction.py.
def django.db.transaction.savepoint (using = None)
Creates a savepoint (if supported and required by the backend) inside the
current transaction. Returns an identifier for the savepoint that will be
used for the subsequent rollback or commit.
Definition at line 147 of file transaction.py.
References django.db.transaction.get_connection().
def django.db.transaction.savepoint_commit (sid, using = None)
Commits the most recent savepoint (if one exists). Does nothing if
savepoints are not supported.
Definition at line 162 of file transaction.py.
References django.db.transaction.get_connection().
def django.db.transaction.savepoint_rollback (sid, using = None)
Rolls back the most recent savepoint (if one exists). Does nothing if
savepoints are not supported.
Definition at line 155 of file transaction.py.
References django.db.transaction.get_connection().
def django.db.transaction.set_autocommit (autocommit, using = None)
Set the autocommit status of the connection.
Definition at line 129 of file transaction.py.
References django.db.transaction.get_connection().
def django.db.transaction.set_clean (using = None)
Resets a dirty flag for the current thread and code streak. This can be used
to decide in a managed block of code to decide whether a commit or rollback
should happen.
Definition at line 95 of file transaction.py.
References django.db.transaction.get_connection().
def django.db.transaction.set_dirty (using = None)
Sets a dirty flag for the current thread and code streak. This can be used
to decide in a managed block of code to decide whether there are open
changes waiting for commit.
Definition at line 87 of file transaction.py.
References django.db.transaction.get_connection().
def django.db.transaction.set_rollback (rollback, using = None)
Sets or unsets the "needs rollback" flag -- for *advanced use* only.
When `rollback` is `True`, it triggers a rollback when exiting the
innermost enclosing atomic block that has `savepoint=True` (that's the
default). Use this to force a rollback without raising an exception.
When `rollback` is `False`, it prevents such a rollback. Use this only
after rolling back to a known-good state! Otherwise, you break the atomic
block and data corruption may occur.
Definition at line 181 of file transaction.py.
References django.db.transaction.get_connection().