Django: django.test.utils.TransRealMixin Class Reference
django.test.utils.TransRealMixin Class Reference
Public Member Functions
def flush_caches (self)
def tearDown (self)
Detailed Description
This is the only way to reset the translation machinery. Otherwise
the test suite occasionally fails because of global state pollution
between tests.
Definition at line 445 of file utils.py.
Member Function Documentation
def django.test.utils.TransRealMixin.flush_caches (self)
Definition at line 449 of file utils.py.
Referenced by django.test.utils.TransRealMixin.tearDown().
def django.test.utils.TransRealMixin.tearDown (self)
Definition at line 457 of file utils.py.
References django.test.utils.TransRealMixin.flush_caches().
Referenced by django.utils.unittest.case.TestCase.debug(), and django.utils.unittest.case.TestCase.run().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/test/utils.py