Django: django.contrib.formtools.wizard.storage.session.SessionStorage Class Reference
django.contrib.formtools.wizard.storage.session.SessionStorage Class Reference
Public Member Functions
def __init__ (self, args, kwargs)
Public Member Functions inherited from django.contrib.formtools.wizard.storage.base.BaseStorage
def __init__
def init_data (self)
def reset (self)
def get_step_data (self, step)
def set_step_data (self, step, cleaned_data)
def current_step_data (self)
def get_step_files (self, step)
def set_step_files (self, step, files)
def current_step_files (self)
def update_response (self, response)
Properties
data = property(_get_data, _set_data)
Additional Inherited Members
Public Attributes inherited from django.contrib.formtools.wizard.storage.base.BaseStorage
prefix
request
file_storage
data
Static Public Attributes inherited from django.contrib.formtools.wizard.storage.base.BaseStorage
string step_key = 'step'
string step_data_key = 'step_data'
string step_files_key = 'step_files'
string extra_data_key = 'extra_data'
tuple current_step = lazy_property(_get_current_step, _set_current_step)
tuple extra_data = lazy_property(_get_extra_data, _set_extra_data)
Detailed Description
Definition at line 4 of file session.py.
Constructor & Destructor Documentation
def django.contrib.formtools.wizard.storage.session.SessionStorage.__init__ (self, args, kwargs)
Definition at line 6 of file session.py.
References django.contrib.formtools.wizard.storage.base.BaseStorage.init_data(), and django.contrib.formtools.wizard.storage.base.BaseStorage.prefix.
Property Documentation
django.contrib.formtools.wizard.storage.session.SessionStorage.data = property(_get_data, _set_data) static
Definition at line 19 of file session.py.
Referenced by django.db.models.query_utils.QueryWrapper.as_sql(), django.forms.forms.BaseForm.changed_data(), django.db.models.deletion.Collector.delete(), django.utils.dateformat.DateFormat.e(), django.forms.formsets.BaseFormSet.forms(), django.utils.dateformat.DateFormat.I(), django.forms.models.BaseModelFormSet.initial_form_count(), django.db.models.deletion.Collector.instances_with_model(), django.forms.formsets.BaseFormSet.management_form(), django.forms.forms.BaseForm.non_field_errors(), django.db.models.deletion.Collector.sort(), django.utils.dateformat.DateFormat.T(), django.utils.dateformat.DateFormat.U(), django.forms.forms.BoundField.value(), and django.utils.dateformat.DateFormat.Z().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/formtools/wizard/storage/session.py