Django: django.contrib.gis.shortcuts Namespace Reference
django.contrib.gis.shortcuts Namespace Reference
Functions
def compress_kml (kml)
def render_to_kml (args, kwargs)
def render_to_kmz (args, kwargs)
def render_to_text (args, kwargs)
Function Documentation
def django.contrib.gis.shortcuts.compress_kml (kml)
Definition at line 8 of file shortcuts.py.
References django.utils.six.BytesIO.
Referenced by django.contrib.gis.shortcuts.render_to_kmz().
def django.contrib.gis.shortcuts.render_to_kml (args, kwargs)
Definition at line 17 of file shortcuts.py.
def django.contrib.gis.shortcuts.render_to_kmz (args, kwargs)
Compresses the KML content and returns as KMZ (using the correct
MIME type).
Definition at line 22 of file shortcuts.py.
References django.contrib.gis.shortcuts.compress_kml().
Referenced by django.contrib.gis.tests.geoapp.test_regress.GeoRegressionTests.test_kmz().
def django.contrib.gis.shortcuts.render_to_text (args, kwargs)
Definition at line 30 of file shortcuts.py.