Django: django.forms.widgets.NullBooleanSelect Class Reference
django.forms.widgets.NullBooleanSelect Class Reference
Public Member Functions
def __init__
def render
def value_from_datadict (self, data, files, name)
Public Member Functions inherited from django.forms.widgets.Select
def __init__
def render
def render_option (self, selected_choices, option_value, option_label)
def render_options (self, choices, selected_choices)
Public Member Functions inherited from django.forms.widgets.Widget
def __init__
def __deepcopy__ (self, memo)
def subwidgets
def render
def build_attrs (self, extra_attrs=None, kwargs)
def value_from_datadict (self, data, files, name)
def id_for_label (self, id_)
Public Member Functions inherited from django.forms.widgets.MediaDefiningClass
def __new__ (cls, name, bases, attrs)
Additional Inherited Members
Public Attributes inherited from django.forms.widgets.Select
choices
Public Attributes inherited from django.forms.widgets.Widget
attrs
Static Public Attributes inherited from django.forms.widgets.Select
allow_multiple_selected = False
Static Public Attributes inherited from django.forms.widgets.Widget
is_hidden = False
needs_multipart_form = False
is_localized = False
is_required = False
Detailed Description
A Select Widget intended to be used with NullBooleanField.
Definition at line 538 of file widgets.py.
Constructor & Destructor Documentation
def django.forms.widgets.NullBooleanSelect.__init__ (self, attrs = None)
Definition at line 542 of file widgets.py.
References django.utils.translation.ugettext_lazy.
Member Function Documentation
def django.forms.widgets.NullBooleanSelect.render (self, name, value, attrs = None, choices = ())
Definition at line 548 of file widgets.py.
Referenced by django.forms.widgets.ChoiceInput.__str__(), django.forms.widgets.ChoiceFieldRenderer.__str__(), django.templatetags.i18n.BlockTranslateNode.render(), and django.template.loader_tags.BlockNode.super().
def django.forms.widgets.NullBooleanSelect.value_from_datadict (self, data, files, name)
Definition at line 555 of file widgets.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/forms/widgets.py