Django: django.utils.dateformat.Formatter Class Reference
django.utils.dateformat.Formatter Class Reference
Public Member Functions
def format (self, formatstr)
Detailed Description
Definition at line 30 of file dateformat.py.
Member Function Documentation
def django.utils.dateformat.Formatter.format (self, formatstr)
Definition at line 31 of file dateformat.py.
References django.utils.encoding.force_text(), and django.template.defaultfilters.join().
Referenced by django.utils.dateformat.DateFormat.r(), and django.utils.dateformat.DateFormat.T().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/utils/dateformat.py