Django: django.templatetags.tz Namespace Reference
django.templatetags.tz Namespace Reference
Classes
class datetimeobject
class GetCurrentTimezoneNode
class LocalTimeNode
class TimezoneNode
Functions
def localtime (value)
def utc (value)
def do_timezone (value, arg)
def localtime_tag (parser, token)
def timezone_tag (parser, token)
def get_current_timezone_tag (parser, token)
Variables
pytz = None
tuple register = Library()
Function Documentation
def django.templatetags.tz.do_timezone (value, arg)
Converts a datetime to local time in a given time zone.
The argument must be an instance of a tzinfo subclass or a time zone name.
If it is a time zone name, pytz is required.
Naive datetimes are assumed to be in local time in the default time zone.
Definition at line 43 of file tz.py.
Referenced by django.templatetags.tz.localtime(), and django.templatetags.tz.utc().
def django.templatetags.tz.get_current_timezone_tag (parser, token)
Stores the name of the current time zone in the context.
Usage::
    {% get_current_timezone as TIME_ZONE %}
This will fetch the currently active time zone and put its name
into the ``TIME_ZONE`` context variable.
Definition at line 182 of file tz.py.
def django.templatetags.tz.localtime (value)
Converts a datetime to local time in the active time zone.
This only makes sense within a {% localtime off %} block.
Definition at line 25 of file tz.py.
References django.templatetags.tz.do_timezone().
def django.templatetags.tz.localtime_tag (parser, token)
Forces or prevents conversion of datetime objects to local time,
regardless of the value of ``settings.USE_TZ``.
Sample usage::
    {% localtime off %}{{ value_in_utc }}{% endlocaltime %}
Definition at line 132 of file tz.py.
def django.templatetags.tz.timezone_tag (parser, token)
Enables a given time zone just for this block.
The ``timezone`` argument must be an instance of a ``tzinfo`` subclass, a
time zone name, or ``None``. If is it a time zone name, pytz is required.
If it is ``None``, the default time zone is used within the block.
Sample usage::
    {% timezone "Europe/Paris" %}
        It is {{ now }} in Paris.
    {% endtimezone %}
Definition at line 156 of file tz.py.
def django.templatetags.tz.utc (value)
Converts a datetime to UTC.
Definition at line 35 of file tz.py.
References django.templatetags.tz.do_timezone().
Variable Documentation
django.templatetags.tz.pytz = None
Definition at line 6 of file tz.py.
tuple django.templatetags.tz.register = Library()
Definition at line 13 of file tz.py.