Django: django.template.base.NodeList Class Reference
django.template.base.NodeList Class Reference
Public Member Functions
def render (self, context)
def get_nodes_by_type (self, nodetype)
def render_node (self, node, context)
Static Public Attributes
contains_nontext = False
Detailed Description
Definition at line 831 of file base.py.
Member Function Documentation
def django.template.base.NodeList.get_nodes_by_type (self, nodetype)
Definition at line 846 of file base.py.
def django.template.base.NodeList.render (self, context)
Definition at line 836 of file base.py.
References django.utils.encoding.force_text(), django.template.defaultfilters.join(), django.utils.safestring.mark_safe(), and django.template.base.NodeList.render_node().
Referenced by django.templatetags.i18n.BlockTranslateNode.render().
def django.template.base.NodeList.render_node (self, node, context)
Definition at line 853 of file base.py.
Referenced by django.template.base.NodeList.render().
Member Data Documentation
django.template.base.NodeList.contains_nontext = False static
Definition at line 834 of file base.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/template/base.py