Django: django.utils.termcolors Namespace Reference
django.utils.termcolors Namespace Reference
Functions
def colorize (text='', opts=(), kwargs)
def make_style (opts=(), kwargs)
def parse_color_setting (config_string)
Variables
tuple color_names = ('black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white')
tuple foreground = dict([(color_names[x], '3%s' % x) for x in range(8)])
tuple background = dict([(color_names[x], '4%s' % x) for x in range(8)])
string RESET = '0'
dictionary opt_dict = {'bold': '1', 'underscore': '4', 'blink': '5', 'reverse': '7', 'conceal': '8'}
string NOCOLOR_PALETTE = 'nocolor'
string DARK_PALETTE = 'dark'
string LIGHT_PALETTE = 'light'
dictionary PALETTES
DEFAULT_PALETTE = DARK_PALETTE
Detailed Description
termcolors.py
Function Documentation
def django.utils.termcolors.colorize (text = '', opts = (), kwargs)
Returns your text, enclosed in ANSI graphics codes.
Depends on the keyword arguments 'fg' and 'bg', and the contents of
the opts tuple/list.
Returns the RESET code if no parameters are given.
Valid colors:
    'black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white'
Valid options:
    'bold'
    'underscore'
    'blink'
    'reverse'
    'conceal'
    'noreset' - string will not be auto-terminated with the RESET code
Examples:
    colorize('hello', fg='red', bg='blue', opts=('blink',))
    colorize()
    colorize('goodbye', opts=('underscore',))
    print(colorize('first line', fg='red', opts=('noreset',)))
    print('this should be red too')
    print(colorize('and so should this'))
    print('this should not be red')
Definition at line 14 of file termcolors.py.
References django.template.defaultfilters.join().
Referenced by django.utils.termcolors.make_style().
def django.utils.termcolors.make_style (opts = (), kwargs)
Returns a function with default parameters for colorize()
Example:
    bold_red = make_style(opts=('bold',), fg='red')
    print(bold_red('hello'))
    KEYWORD = make_style(fg='yellow')
    COMMENT = make_style(fg='blue', opts=('bold',))
Definition at line 58 of file termcolors.py.
References django.utils.termcolors.colorize().
def django.utils.termcolors.parse_color_setting (config_string)
Parse a DJANGO_COLORS environment variable to produce the system palette
The general form of a pallete definition is:
    "palette;role=fg;role=fg/bg;role=fg,option,option;role=fg/bg,option,option"
where:
    palette is a named palette; one of 'light', 'dark', or 'nocolor'.
    role is a named style used by Django
    fg is a background color.
    bg is a background color.
    option is a display options.
Specifying a named palette is the same as manually specifying the individual
definitions for each role. Any individual definitions following the pallete
definition will augment the base palette definition.
Valid roles:
    'error', 'notice', 'sql_field', 'sql_coltype', 'sql_keyword', 'sql_table',
    'http_info', 'http_success', 'http_redirect', 'http_bad_request',
    'http_not_found', 'http_server_error'
Valid colors:
    'black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white'
Valid options:
    'bold', 'underscore', 'blink', 'reverse', 'conceal'
Definition at line 123 of file termcolors.py.
Variable Documentation
tuple django.utils.termcolors.background = dict([(color_names[x], '4%s' % x) for x in range(8)])
Definition at line 9 of file termcolors.py.
tuple django.utils.termcolors.color_names = ('black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white')
Definition at line 7 of file termcolors.py.
string django.utils.termcolors.DARK_PALETTE = 'dark'
Definition at line 71 of file termcolors.py.
django.utils.termcolors.DEFAULT_PALETTE = DARK_PALETTE
Definition at line 121 of file termcolors.py.
tuple django.utils.termcolors.foreground = dict([(color_names[x], '3%s' % x) for x in range(8)])
Definition at line 8 of file termcolors.py.
string django.utils.termcolors.LIGHT_PALETTE = 'light'
Definition at line 72 of file termcolors.py.
string django.utils.termcolors.NOCOLOR_PALETTE = 'nocolor'
Definition at line 70 of file termcolors.py.
dictionary django.utils.termcolors.opt_dict = {'bold': '1', 'underscore': '4', 'blink': '5', 'reverse': '7', 'conceal': '8'}
Definition at line 12 of file termcolors.py.
dictionary django.utils.termcolors.PALETTES
Definition at line 74 of file termcolors.py.
string django.utils.termcolors.RESET = '0'
Definition at line 11 of file termcolors.py.