Django: django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests Class Reference
django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests Class Reference
Public Member Functions
def setUp (self)
def test_view_flatpage (self)
def test_view_non_existent_flatpage (self)
def test_view_authenticated_flatpage (self)
def test_fallback_flatpage (self)
def test_fallback_non_existent_flatpage (self)
def test_post_view_flatpage (self)
def test_post_fallback_flatpage (self)
def test_post_unknown_page (self)
Public Attributes
client
Static Public Attributes
list fixtures = ['sample_flatpages', 'example_site']
string urls = 'django.contrib.flatpages.tests.urls'
Detailed Description
Definition at line 23 of file test_csrf.py.
Member Function Documentation
def django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests.setUp (self)
Definition at line 27 of file test_csrf.py.
Referenced by django.utils.unittest.case.TestCase.debug(), django.test._doctest.DocTestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests.test_fallback_flatpage (self)
Definition at line 52 of file test_csrf.py.
References django.test.testcases.SimpleTestCase.assertContains(), and django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests.test_fallback_non_existent_flatpage (self)
Definition at line 58 of file test_csrf.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests.test_post_fallback_flatpage (self)
Definition at line 68 of file test_csrf.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests.test_post_unknown_page (self)
Definition at line 73 of file test_csrf.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests.test_post_view_flatpage (self)
Definition at line 63 of file test_csrf.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests.test_view_authenticated_flatpage (self)
Definition at line 42 of file test_csrf.py.
References django.test.testcases.SimpleTestCase.assertContains(), django.utils.unittest.case.TestCase.assertEqual(), and django.test.testcases.SimpleTestCase.assertRedirects().
def django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests.test_view_flatpage (self)
Definition at line 30 of file test_csrf.py.
References django.test.testcases.SimpleTestCase.assertContains(), and django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests.test_view_non_existent_flatpage (self)
Definition at line 36 of file test_csrf.py.
References django.utils.unittest.case.TestCase.assertEqual().
Member Data Documentation
django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests.client
Definition at line 28 of file test_csrf.py.
list django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests.fixtures = ['sample_flatpages', 'example_site'] static
Definition at line 24 of file test_csrf.py.
string django.contrib.flatpages.tests.test_csrf.FlatpageCSRFTests.urls = 'django.contrib.flatpages.tests.urls' static
Definition at line 25 of file test_csrf.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/flatpages/tests/test_csrf.py