Django: django.test._doctest.DocTestFinder Class Reference
django.test._doctest.DocTestFinder Class Reference
Public Member Functions
def __init__
def find
Detailed Description
DocTest Finder
A class used to extract the DocTests that are relevant to a given
object, from its docstring and the docstrings of its contained
objects.  Doctests can currently be extracted from the following
object types: modules, functions, classes, methods, staticmethods,
classmethods, and properties.
Definition at line 776 of file _doctest.py.
Constructor & Destructor Documentation
def django.test._doctest.DocTestFinder.__init__ (self, verbose = False, parser = DocTestParser(), recurse = True, exclude_empty = True)
Create a new doctest finder.
The optional argument `parser` specifies a class or
function that should be used to create new DocTest objects (or
objects that implement the same interface as DocTest).  The
signature for this factory function should match the signature
of the DocTest constructor.
If the optional argument `recurse` is false, then `find` will
only examine the given object, and not any contained objects.
If the optional argument `exclude_empty` is false, then `find`
will include tests for objects with empty docstrings.
Definition at line 786 of file _doctest.py.
References django.test._doctest.DocTestFinder._exclude_empty, django.test._doctest.DocTestFinder._parser, django.test._doctest.DocTestFinder._recurse, and django.test._doctest.DocTestFinder._verbose.
Member Function Documentation
def django.test._doctest.DocTestFinder.find (self, obj, name = None, module = None, globs = None, extraglobs = None)
Return a list of the DocTests that are defined by the given
object's docstring, or by any of its contained objects'
docstrings.
The optional parameter `module` is the module that contains
the given object.  If the module is not specified or is None, then
the test finder will attempt to automatically determine the
correct module.  The object's module is used:
    - As a default namespace, if `globs` is not specified.
    - To prevent the DocTestFinder from extracting DocTests
      from objects that are imported from other modules.
    - To find the name of the file containing the object.
    - To help find the line number of the object within its
      file.
Contained objects whose module does not match `module` are ignored.
If `module` is False, no attempt to find the module will be made.
This is obscure, of use mostly in tests:  if `module` is False, or
is None but cannot be found automatically, then all objects are
considered to belong to the (non-existent) module, so all contained
objects will (recursively) be searched for doctests.
The globals for each DocTest is formed by combining `globs`
and `extraglobs` (bindings in `extraglobs` override bindings
in `globs`).  A new copy of the globals dictionary is created
for each DocTest.  If `globs` is not specified, then it
defaults to the module's `__dict__`, if specified, or {}
otherwise.  If `extraglobs` is not specified, then it defaults
to {}.
Definition at line 807 of file _doctest.py.
References django.test._doctest.DocTestFinder._exclude_empty, django.test._doctest.DocTestFinder._find(), django.test._doctest.DocTestFinder._find_lineno(), django.test._doctest.DocTestFinder._from_module(), django.test._doctest.DocTestFinder._get_test(), django.test._doctest.DocTestFinder._recurse, and django.test._doctest.DocTestFinder._verbose.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/test/_doctest.py