Django: django.contrib.flatpages.views Namespace Reference
django.contrib.flatpages.views Namespace Reference
Functions
def flatpage (request, url)
def render_flatpage (request, f)
Variables
string DEFAULT_TEMPLATE = 'flatpages/default.html'
Function Documentation
def django.contrib.flatpages.views.flatpage (request, url)
Public interface to the flat page view.
Models: `flatpages.flatpages`
Templates: Uses the template defined by the ``template_name`` field,
    or :template:`flatpages/default.html` if template_name is not defined.
Context:
    flatpage
        `flatpages.flatpages` object
Definition at line 20 of file views.py.
References django.contrib.sites.models.get_current_site(), django.shortcuts.get_object_or_404(), and django.contrib.flatpages.views.render_flatpage().
Referenced by django.contrib.flatpages.middleware.FlatpageFallbackMiddleware.process_response().
def django.contrib.flatpages.views.render_flatpage (request, f)
Internal interface to the flat page view.
Definition at line 48 of file views.py.
References django.utils.safestring.mark_safe(), and django.contrib.auth.views.redirect_to_login().
Referenced by django.contrib.flatpages.views.flatpage().
Variable Documentation
string django.contrib.flatpages.views.DEFAULT_TEMPLATE = 'flatpages/default.html'
Definition at line 10 of file views.py.