Django: django.db.models.base.ModelBase Class Reference
django.db.models.base.ModelBase Class Reference
Public Member Functions
def __new__ (cls, name, bases, attrs)
def copy_managers (cls, base_managers)
def add_to_class (cls, name, value)
Detailed Description
Metaclass for all models.
Definition at line 54 of file base.py.
Member Function Documentation
def django.db.models.base.ModelBase.__new__ (cls, name, bases, attrs)
Definition at line 58 of file base.py.
References django.db.models.loading.get_model, django.db.models.loading.register_models, and django.db.models.base.subclass_exception().
def django.db.models.base.ModelBase.add_to_class (cls, name, value)
Definition at line 262 of file base.py.
References django.db.models.fields.related.add_lazy_relation(), django.utils.functional.curry(), and django.template.defaultfilters.join().
def django.db.models.base.ModelBase.copy_managers (cls, base_managers)
Definition at line 253 of file base.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/db/models/base.py