Django: django.contrib.gis.gdal.tests.test_driver.DriverTest Class Reference
django.contrib.gis.gdal.tests.test_driver.DriverTest Class Reference
Public Member Functions
def test01_valid_driver (self)
def test02_invalid_driver (self)
def test03_aliases (self)
Detailed Description
Definition at line 22 of file test_driver.py.
Member Function Documentation
def django.contrib.gis.gdal.tests.test_driver.DriverTest.test01_valid_driver (self)
Definition at line 24 of file test_driver.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_driver.DriverTest.test02_invalid_driver (self)
Definition at line 30 of file test_driver.py.
References django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.gdal.tests.test_driver.DriverTest.test03_aliases (self)
Definition at line 35 of file test_driver.py.
References django.utils.unittest.case.TestCase.assertEqual().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/gdal/tests/test_driver.py