Django: django.contrib.auth.tests.test_auth_backends.NoBackendsTest Class Reference
django.contrib.auth.tests.test_auth_backends.NoBackendsTest Class Reference
Public Member Functions
def setUp (self)
def test_raises_exception (self)
Public Attributes
user
Detailed Description
Tests that an appropriate error is raised if no auth backends are provided.
Definition at line 364 of file test_auth_backends.py.
Member Function Documentation
def django.contrib.auth.tests.test_auth_backends.NoBackendsTest.setUp (self)
Definition at line 368 of file test_auth_backends.py.
Referenced by django.utils.unittest.case.TestCase.debug(), django.test._doctest.DocTestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.contrib.auth.tests.test_auth_backends.NoBackendsTest.test_raises_exception (self)
Definition at line 371 of file test_auth_backends.py.
References django.utils.unittest.case.TestCase.assertRaises().
Member Data Documentation
django.contrib.auth.tests.test_auth_backends.NoBackendsTest.user
Definition at line 369 of file test_auth_backends.py.
Referenced by django.contrib.comments.models.Comment.get_as_text(), django.contrib.flatpages.templatetags.flatpages.FlatpageNode.render(), and django.contrib.auth.tests.test_auth_backends.BaseModelBackendTest.test_authentication_timing().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_auth_backends.py