Django: django.templatetags.l10n Namespace Reference
django.templatetags.l10n Namespace Reference
Classes
class LocalizeNode
Functions
def localize (value)
def unlocalize (value)
def localize_tag (parser, token)
Variables
tuple register = Library()
Function Documentation
def django.templatetags.l10n.localize (value)
Forces a value to be rendered as a localized value,
regardless of the value of ``settings.USE_L10N``.
Definition at line 9 of file l10n.py.
References django.utils.encoding.force_text().
Referenced by django.template.debug.DebugVariableNode.render(), django.template.base.render_value_in_context(), and django.contrib.sitemaps.tests.test_http.HTTPSitemapTests.test_localized_priority().
def django.templatetags.l10n.localize_tag (parser, token)
Forces or prevents localization of values, regardless of the value of
`settings.USE_L10N`.
Sample usage::
    {% localize off %}
        var pi = {{ 3.1415 }};
    {% endlocalize %}
Definition at line 40 of file l10n.py.
def django.templatetags.l10n.unlocalize (value)
Forces a value to be rendered as a non-localized value,
regardless of the value of ``settings.USE_L10N``.
Definition at line 17 of file l10n.py.
References django.utils.encoding.force_text().
Variable Documentation
tuple django.templatetags.l10n.register = Library()
Definition at line 6 of file l10n.py.