Django: django.contrib.auth.tests.test_forms.PasswordChangeFormTest Class Reference
django.contrib.auth.tests.test_forms.PasswordChangeFormTest Class Reference
Public Member Functions
def test_incorrect_password (self)
def test_password_verification (self)
def test_success (self)
def test_field_order (self)
Static Public Attributes
list fixtures = ['authtestdata.json']
Detailed Description
Definition at line 201 of file test_forms.py.
Member Function Documentation
def django.contrib.auth.tests.test_forms.PasswordChangeFormTest.test_field_order (self)
Definition at line 241 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.auth.tests.test_forms.PasswordChangeFormTest.test_incorrect_password (self)
Definition at line 205 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertFalse(), and django.utils.encoding.force_text().
def django.contrib.auth.tests.test_forms.PasswordChangeFormTest.test_password_verification (self)
Definition at line 217 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertFalse(), and django.utils.encoding.force_text().
def django.contrib.auth.tests.test_forms.PasswordChangeFormTest.test_success (self)
Definition at line 230 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertTrue().
Member Data Documentation
list django.contrib.auth.tests.test_forms.PasswordChangeFormTest.fixtures = ['authtestdata.json'] static
Definition at line 203 of file test_forms.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_forms.py