Django: django.contrib.gis.gdal.libgdal Namespace Reference
django.contrib.gis.gdal.libgdal Namespace Reference
Functions
def std_call (func)
def gdal_version ()
def gdal_full_version ()
def gdal_version_info ()
def err_handler (error_class, error_number, message)
def function (name, args, restype)
Variables
tuple logger = logging.getLogger('django.contrib.gis')
lib_path = settings.GDAL_LIBRARY_PATH
lib_names = None
tuple lgdal = CDLL(lib_path)
tuple lwingdal = WinDLL(lib_path)
tuple _version_info = std_call('GDALVersionInfo')
Version-information functions.
tuple version_regex = re.compile(r'^(?P<major>\d+)\.(?P<minor>\d+)(\.(?P<subminor>\d+))?')
tuple _verinfo = gdal_version_info()
tuple GDAL_MAJOR_VERSION = int(_verinfo['major'])
tuple GDAL_MINOR_VERSION = int(_verinfo['minor'])
list GDAL_SUBMINOR_VERSION = _verinfo['subminor']
tuple GDAL_VERSION = (GDAL_MAJOR_VERSION, GDAL_MINOR_VERSION, GDAL_SUBMINOR_VERSION)
tuple CPLErrorHandler = CFUNCTYPE(None, c_int, c_int, c_char_p)
tuple err_handler = CPLErrorHandler(err_handler)
tuple set_error_handler = function('CPLSetErrorHandler', [CPLErrorHandler], CPLErrorHandler)
Function Documentation
def django.contrib.gis.gdal.libgdal.err_handler (error_class, error_number, message)
Definition at line 98 of file libgdal.py.
References django.contrib.gis.gdal.libgdal.err_handler.
def django.contrib.gis.gdal.libgdal.function (name, args, restype)
Definition at line 102 of file libgdal.py.
References django.contrib.gis.gdal.libgdal.std_call().
Referenced by django.dispatch.saferef.BoundMethodWeakref.__init__(), django.utils.unittest.case.TestCase.debug(), and django.utils.unittest.case.TestCase.doCleanups().
def django.contrib.gis.gdal.libgdal.gdal_full_version ()
Definition at line 78 of file libgdal.py.
References django.contrib.gis.gdal.libgdal._version_info.
def django.contrib.gis.gdal.libgdal.gdal_version ()
Definition at line 74 of file libgdal.py.
References django.contrib.gis.gdal.libgdal._version_info.
Referenced by django.contrib.gis.gdal.libgdal.gdal_version_info().
def django.contrib.gis.gdal.libgdal.gdal_version_info ()
Definition at line 83 of file libgdal.py.
References django.contrib.gis.gdal.libgdal.gdal_version().
def django.contrib.gis.gdal.libgdal.std_call (func)
Returns the correct STDCALL function for certain OSR routines on Win32
platforms.
Definition at line 57 of file libgdal.py.
Referenced by django.contrib.gis.gdal.libgdal.function().
Variable Documentation
tuple django.contrib.gis.gdal.libgdal._verinfo = gdal_version_info()
Definition at line 89 of file libgdal.py.
tuple django.contrib.gis.gdal.libgdal._version_info = std_call('GDALVersionInfo')
Version-information functions.
Definition at line 70 of file libgdal.py.
Referenced by django.contrib.gis.gdal.libgdal.gdal_full_version(), and django.contrib.gis.gdal.libgdal.gdal_version().
tuple django.contrib.gis.gdal.libgdal.CPLErrorHandler = CFUNCTYPE(None, c_int, c_int, c_char_p)
Definition at line 97 of file libgdal.py.
tuple django.contrib.gis.gdal.libgdal.err_handler = CPLErrorHandler(err_handler)
Definition at line 100 of file libgdal.py.
Referenced by django.contrib.gis.gdal.libgdal.err_handler().
tuple django.contrib.gis.gdal.libgdal.GDAL_MAJOR_VERSION = int(_verinfo['major'])
Definition at line 90 of file libgdal.py.
tuple django.contrib.gis.gdal.libgdal.GDAL_MINOR_VERSION = int(_verinfo['minor'])
Definition at line 91 of file libgdal.py.
list django.contrib.gis.gdal.libgdal.GDAL_SUBMINOR_VERSION = _verinfo['subminor']
Definition at line 92 of file libgdal.py.
tuple django.contrib.gis.gdal.libgdal.GDAL_VERSION = (GDAL_MAJOR_VERSION, GDAL_MINOR_VERSION, GDAL_SUBMINOR_VERSION)
Definition at line 93 of file libgdal.py.
tuple django.contrib.gis.gdal.libgdal.lgdal = CDLL(lib_path)
Definition at line 47 of file libgdal.py.
list django.contrib.gis.gdal.libgdal.lib_names = None
Definition at line 23 of file libgdal.py.
tuple django.contrib.gis.gdal.libgdal.lib_path = settings.GDAL_LIBRARY_PATH
Definition at line 17 of file libgdal.py.
tuple django.contrib.gis.gdal.libgdal.logger = logging.getLogger('django.contrib.gis')
Definition at line 12 of file libgdal.py.
tuple django.contrib.gis.gdal.libgdal.lwingdal = WinDLL(lib_path)
Definition at line 55 of file libgdal.py.
tuple django.contrib.gis.gdal.libgdal.set_error_handler = function('CPLSetErrorHandler', [CPLErrorHandler], CPLErrorHandler)
Definition at line 108 of file libgdal.py.
tuple django.contrib.gis.gdal.libgdal.version_regex = re.compile(r'^(?P<major>\d+)\.(?P<minor>\d+)(\.(?P<subminor>\d+))?')
Definition at line 82 of file libgdal.py.