Django: django.contrib.flatpages.tests.test_models.FlatpageModelTests Class Reference
django.contrib.flatpages.tests.test_models.FlatpageModelTests Class Reference
Public Member Functions
def test_get_absolute_url_urlencodes (self)
def test_get_absolute_url_honors_script_prefix (self)
Detailed Description
Definition at line 10 of file test_models.py.
Member Function Documentation
def django.contrib.flatpages.tests.test_models.FlatpageModelTests.test_get_absolute_url_honors_script_prefix (self)
Definition at line 16 of file test_models.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.core.urlresolvers.clear_script_prefix(), and django.core.urlresolvers.set_script_prefix().
def django.contrib.flatpages.tests.test_models.FlatpageModelTests.test_get_absolute_url_urlencodes (self)
Definition at line 12 of file test_models.py.
References django.utils.unittest.case.TestCase.assertEqual().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/flatpages/tests/test_models.py