Django: django.contrib.gis.tests.test_geoforms.GeometryFieldTest Class Reference
django.contrib.gis.tests.test_geoforms.GeometryFieldTest Class Reference
Public Member Functions
def test_init (self)
def test_srid (self)
def test_null (self)
def test_geom_type (self)
def test_to_python (self)
def test_field_with_text_widget (self)
Detailed Description
Definition at line 14 of file test_geoforms.py.
Member Function Documentation
def django.contrib.gis.tests.test_geoforms.GeometryFieldTest.test_field_with_text_widget (self)
Definition at line 77 of file test_geoforms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertFalse(), and django.utils.unittest.case.skipUnless().
def django.contrib.gis.tests.test_geoforms.GeometryFieldTest.test_geom_type (self)
Definition at line 50 of file test_geoforms.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.tests.test_geoforms.GeometryFieldTest.test_init (self)
Definition at line 16 of file test_geoforms.py.
References django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.tests.test_geoforms.GeometryFieldTest.test_null (self)
Definition at line 38 of file test_geoforms.py.
References django.utils.unittest.case.TestCase.assertIsNone().
def django.contrib.gis.tests.test_geoforms.GeometryFieldTest.test_srid (self)
Definition at line 22 of file test_geoforms.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.gis.tests.test_geoforms.GeometryFieldTest.test_to_python (self)
Testing to_python returns a correct GEOSGeometry object or
a ValidationError
Definition at line 64 of file test_geoforms.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertRaises().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/tests/test_geoforms.py