Django: django.contrib.admin.validation.BaseValidator Class Reference
django.contrib.admin.validation.BaseValidator Class Reference
Public Member Functions
def __init__ (self)
def validate (self, cls, model)
def check_field_spec (self, cls, model, flds, label)
def validate_raw_id_fields (self, cls, model)
def validate_fields (self, cls, model)
def validate_fieldsets (self, cls, model)
def validate_exclude (self, cls, model)
def validate_form (self, cls, model)
def validate_filter_vertical (self, cls, model)
def validate_filter_horizontal (self, cls, model)
def validate_radio_fields (self, cls, model)
def validate_prepopulated_fields (self, cls, model)
def validate_ordering (self, cls, model)
def validate_readonly_fields (self, cls, model)
Detailed Description
Definition at line 16 of file validation.py.
Constructor & Destructor Documentation
def django.contrib.admin.validation.BaseValidator.__init__ (self)
Definition at line 17 of file validation.py.
Member Function Documentation
def django.contrib.admin.validation.BaseValidator.check_field_spec (self, cls, model, flds, label)
Validate the fields specification in `flds` from a ModelAdmin subclass
`cls` for the `model` model. Use `label` for reporting problems to the user.
The fields specification can be a ``fields`` option or a ``fields``
sub-option from a ``fieldsets`` option component.
Definition at line 27 of file validation.py.
Referenced by django.contrib.admin.validation.BaseValidator.validate_fields(), and django.contrib.admin.validation.BaseValidator.validate_fieldsets().
def django.contrib.admin.validation.BaseValidator.validate (self, cls, model)
Definition at line 22 of file validation.py.
Referenced by django.forms.fields.Field.clean(), django.db.models.fields.Field.clean(), django.core.management.commands.validate.Command.handle_noargs(), and django.core.management.commands.runserver.Command.inner_run().
def django.contrib.admin.validation.BaseValidator.validate_exclude (self, cls, model)
Definition at line 101 of file validation.py.
References django.contrib.admin.validation.check_isseq().
def django.contrib.admin.validation.BaseValidator.validate_fields (self, cls, model)
Definition at line 70 of file validation.py.
References django.contrib.admin.validation.BaseValidator.check_field_spec(), and django.contrib.admin.validation.check_isseq().
def django.contrib.admin.validation.BaseValidator.validate_fieldsets (self, cls, model)
Definition at line 81 of file validation.py.
References django.contrib.admin.validation.BaseValidator.check_field_spec(), django.contrib.admin.validation.check_isdict(), django.contrib.admin.validation.check_isseq(), and django.contrib.admin.util.flatten_fieldsets().
def django.contrib.admin.validation.BaseValidator.validate_filter_horizontal (self, cls, model)
Definition at line 124 of file validation.py.
References django.contrib.admin.validation.check_isseq(), and django.contrib.admin.validation.get_field().
def django.contrib.admin.validation.BaseValidator.validate_filter_vertical (self, cls, model)
Definition at line 114 of file validation.py.
References django.contrib.admin.validation.check_isseq(), and django.contrib.admin.validation.get_field().
def django.contrib.admin.validation.BaseValidator.validate_form (self, cls, model)
Definition at line 108 of file validation.py.
def django.contrib.admin.validation.BaseValidator.validate_ordering (self, cls, model)
Definition at line 167 of file validation.py.
References django.contrib.admin.validation.check_isseq(), and django.contrib.admin.validation.get_field().
def django.contrib.admin.validation.BaseValidator.validate_prepopulated_fields (self, cls, model)
Definition at line 150 of file validation.py.
References django.contrib.admin.validation.check_isdict(), django.contrib.admin.validation.check_isseq(), and django.contrib.admin.validation.get_field().
def django.contrib.admin.validation.BaseValidator.validate_radio_fields (self, cls, model)
Definition at line 134 of file validation.py.
References django.contrib.admin.validation.check_isdict(), and django.contrib.admin.validation.get_field().
def django.contrib.admin.validation.BaseValidator.validate_raw_id_fields (self, cls, model)
Definition at line 59 of file validation.py.
References django.contrib.admin.validation.check_isseq(), and django.contrib.admin.validation.get_field().
def django.contrib.admin.validation.BaseValidator.validate_readonly_fields (self, cls, model)
Definition at line 188 of file validation.py.
References django.utils.six.callable, and django.contrib.admin.validation.check_isseq().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/admin/validation.py