Django: django.contrib.formtools.tests.wizard.wizardtests.tests.WizardFormKwargsOverrideTests Class Reference
django.contrib.formtools.tests.wizard.wizardtests.tests.WizardFormKwargsOverrideTests Class Reference
Public Member Functions
def setUp (self)
def test_instance_is_maintained (self)
def test_queryset_is_maintained (self)
Public Attributes
rf
normal_user
staff_user
Detailed Description
Definition at line 365 of file tests.py.
Member Function Documentation
def django.contrib.formtools.tests.wizard.wizardtests.tests.WizardFormKwargsOverrideTests.setUp (self)
Definition at line 366 of file tests.py.
Referenced by django.utils.unittest.case.TestCase.debug(), django.test._doctest.DocTestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.contrib.formtools.tests.wizard.wizardtests.tests.WizardFormKwargsOverrideTests.test_instance_is_maintained (self)
Definition at line 375 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertNotEqual().
def django.contrib.formtools.tests.wizard.wizardtests.tests.WizardFormKwargsOverrideTests.test_queryset_is_maintained (self)
Definition at line 392 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertNotEqual().
Member Data Documentation
django.contrib.formtools.tests.wizard.wizardtests.tests.WizardFormKwargsOverrideTests.normal_user
Definition at line 372 of file tests.py.
django.contrib.formtools.tests.wizard.wizardtests.tests.WizardFormKwargsOverrideTests.rf
Definition at line 368 of file tests.py.
django.contrib.formtools.tests.wizard.wizardtests.tests.WizardFormKwargsOverrideTests.staff_user
Definition at line 373 of file tests.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/formtools/tests/wizard/wizardtests/tests.py