Django: django.template.base Namespace Reference
django.template.base Namespace Reference
Classes
class FilterExpression
class InvalidTemplateLibrary
class Lexer
class Library
class Node
class NodeList
class Origin
class Parser
class StringOrigin
class TagHelperNode
class Template
class TemplateDoesNotExist
class TemplateEncodingError
class TemplateSyntaxError
class TextNode
class Token
class TokenParser
class Variable
class VariableDoesNotExist
class VariableNode
Functions
def compile_string (template_string, origin)
def resolve_variable (path, context)
def render_value_in_context (value, context)
def token_kwargs
def parse_bits (parser, bits, params, varargs, varkw, defaults, takes_context, name)
def generic_tag_compiler (parser, token, params, varargs, varkw, defaults, name, takes_context, node_class)
def is_library_missing (name)
def import_library (taglib_module)
def get_templatetags_modules ()
def get_library (library_name)
def add_to_builtins (module)
Variables
int TOKEN_TEXT = 0
int TOKEN_VAR = 1
int TOKEN_BLOCK = 2
int TOKEN_COMMENT = 3
dictionary TOKEN_MAPPING
string FILTER_SEPARATOR = '|'
string FILTER_ARGUMENT_SEPARATOR = ':'
string VARIABLE_ATTRIBUTE_SEPARATOR = '.'
string BLOCK_TAG_START = '{%'
string BLOCK_TAG_END = '%}'
string VARIABLE_TAG_START = '{{'
string VARIABLE_TAG_END = '}}'
string COMMENT_TAG_START = '{#'
string COMMENT_TAG_END = '#}'
string TRANSLATOR_COMMENT_MARK = 'Translators'
string SINGLE_BRACE_START = '{'
string SINGLE_BRACE_END = '}'
tuple ALLOWED_VARIABLE_CHARS
string UNKNOWN_SOURCE = '<unknown source>'
tuple tag_re
dictionary libraries = {}
list builtins = []
invalid_var_format_string = None
string constant_string = r""
string filter_raw_string = r""
tuple filter_re = re.compile(filter_raw_string, re.UNICODE | re.VERBOSE)
tuple kwarg_re = re.compile(r"(?:(\w+)=)?(.+)")
list templatetags_modules = []
Function Documentation
def django.template.base.add_to_builtins (module)
Definition at line 1330 of file base.py.
References django.template.base.import_library().
Referenced by django.template.loader.select_template().
def django.template.base.compile_string (template_string, origin)
Definition at line 144 of file base.py.
def django.template.base.generic_tag_compiler (parser, token, params, varargs, varkw, defaults, name, takes_context, node_class)
Returns a template.Node subclass.
Definition at line 1019 of file base.py.
References django.template.base.parse_bits().
Referenced by django.template.base.parse_bits().
def django.template.base.get_library (library_name)
Load the template library module with the given name.
If library is not already loaded loop over all templatetags modules
to locate it.
{% load somelib %} and {% load someotherlib %} loops twice.
Subsequent loads eg. {% load somelib %} in the same process will grab
the cached module from libraries.
Definition at line 1299 of file base.py.
References django.template.base.get_templatetags_modules(), django.template.base.import_library(), and django.template.defaultfilters.join().
Referenced by django.template.defaulttags.load().
def django.template.base.get_templatetags_modules ()
Return the list of all available template tag modules.
Caches the result for faster access.
Definition at line 1277 of file base.py.
References django.utils.importlib.import_module().
Referenced by django.template.base.get_library().
def django.template.base.import_library (taglib_module)
Load a template tag library module.
Verifies that the library contains a 'register' attribute, and
returns that attribute as the representation of the library
Definition at line 1249 of file base.py.
References django.utils.importlib.import_module(), and django.template.base.is_library_missing().
Referenced by django.template.base.add_to_builtins(), and django.template.base.get_library().
def django.template.base.is_library_missing (name)
Check if library that failed to load cannot be found under any
templatetags directory or does exist but fails to import.
Non-existing condition is checked recursively for each subpackage in cases
like <appdir>/templatetags/subpackage/package/module.py.
Definition at line 1233 of file base.py.
References django.utils.importlib.import_module(), and django.utils.module_loading.module_has_submodule().
Referenced by django.template.base.import_library().
def django.template.base.parse_bits (parser, bits, params, varargs, varkw, defaults, takes_context, name)
Parses bits for template tag helpers (simple_tag, include_tag and
assignment_tag), in particular by detecting syntax errors and by
extracting positional and keyword arguments.
Definition at line 952 of file base.py.
References django.template.base.generic_tag_compiler(), django.template.defaultfilters.join(), and django.template.base.token_kwargs().
Referenced by django.template.base.generic_tag_compiler(), and django.template.base.token_kwargs().
def django.template.base.render_value_in_context (value, context)
Converts any value to a string to become part of a rendered template. This
means escaping, if required, and conversion to a unicode object. If value
is a string, it is expected to have already been translated.
Definition at line 867 of file base.py.
References django.utils.html.escape, django.utils.encoding.force_text(), django.templatetags.l10n.localize(), and django.utils.timezone.template_localtime().
Referenced by django.template.defaulttags.CycleNode.render(), django.templatetags.i18n.TranslateNode.render(), django.template.defaulttags.FirstOfNode.render(), django.templatetags.i18n.BlockTranslateNode.render(), and django.template.base.VariableNode.render().
def django.template.base.resolve_variable (path, context)
Returns the resolved variable, which may contain attribute syntax, within
the given context.
Deprecated; use the Variable class instead.
Definition at line 659 of file base.py.
References django.core.urlresolvers.resolve().
def django.template.base.token_kwargs (bits, parser, support_legacy = False)
A utility method for parsing token keyword arguments.
:param bits: A list containing remainder of the token (split by spaces)
    that is to be checked for arguments. Valid arguments will be removed
    from this list.
:param support_legacy: If set to true ``True``, the legacy format
    ``1 as foo`` will be accepted. Otherwise, only the standard ``foo=1``
    format is allowed.
:returns: A dictionary of the arguments retrieved from the ``bits`` token
    list.
There is no requirement for all remaining token ``bits`` to be keyword
arguments, so the dictionary will be returned as soon as an invalid
argument format is reached.
Definition at line 902 of file base.py.
References django.template.base.parse_bits().
Referenced by django.templatetags.i18n.do_block_translate(), django.template.loader_tags.do_include(), django.template.defaulttags.do_with(), and django.template.base.parse_bits().
Variable Documentation
tuple django.template.base.ALLOWED_VARIABLE_CHARS
Initial value:
 = ('abcdefghijklmnopqrstuvwxyz'
                          'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.')
Definition at line 51 of file base.py.
string django.template.base.BLOCK_TAG_END = '%}'
Definition at line 42 of file base.py.
string django.template.base.BLOCK_TAG_START = '{%'
Definition at line 41 of file base.py.
list django.template.base.builtins = []
Definition at line 68 of file base.py.
string django.template.base.COMMENT_TAG_END = '#}'
Definition at line 46 of file base.py.
string django.template.base.COMMENT_TAG_START = '{#'
Definition at line 45 of file base.py.
tuple django.template.base.constant_string = r""
Definition at line 487 of file base.py.
string django.template.base.FILTER_ARGUMENT_SEPARATOR = ':'
Definition at line 39 of file base.py.
string django.template.base.filter_raw_string = r""
Definition at line 500 of file base.py.
tuple django.template.base.filter_re = re.compile(filter_raw_string, re.UNICODE | re.VERBOSE)
Definition at line 519 of file base.py.
string django.template.base.FILTER_SEPARATOR = '|'
Definition at line 38 of file base.py.
django.template.base.invalid_var_format_string = None
Definition at line 72 of file base.py.
tuple django.template.base.kwarg_re = re.compile(r"(?:(\w+)=)?(.+)")
Definition at line 900 of file base.py.
dictionary django.template.base.libraries = {}
Definition at line 66 of file base.py.
string django.template.base.SINGLE_BRACE_END = '}'
Definition at line 49 of file base.py.
string django.template.base.SINGLE_BRACE_START = '{'
Definition at line 48 of file base.py.
tuple django.template.base.tag_re
Initial value:
 = (re.compile('(%s.*?%s|%s.*?%s|%s.*?%s)' %
           (re.escape(BLOCK_TAG_START), re.escape(BLOCK_TAG_END),
            re.escape(VARIABLE_TAG_START), re.escape(VARIABLE_TAG_END),
            re.escape(COMMENT_TAG_START), re.escape(COMMENT_TAG_END))))
Definition at line 60 of file base.py.
list django.template.base.templatetags_modules = []
Definition at line 1275 of file base.py.
int django.template.base.TOKEN_BLOCK = 2
Definition at line 28 of file base.py.
int django.template.base.TOKEN_COMMENT = 3
Definition at line 29 of file base.py.
dictionary django.template.base.TOKEN_MAPPING
Initial value:
 = {
     TOKEN_TEXT: 'Text',
     TOKEN_VAR: 'Var',
     TOKEN_BLOCK: 'Block',
     TOKEN_COMMENT: 'Comment',
 }
Definition at line 30 of file base.py.
int django.template.base.TOKEN_TEXT = 0
Definition at line 26 of file base.py.
int django.template.base.TOKEN_VAR = 1
Definition at line 27 of file base.py.
string django.template.base.TRANSLATOR_COMMENT_MARK = 'Translators'
Definition at line 47 of file base.py.
string django.template.base.UNKNOWN_SOURCE = '<unknown source>'
Definition at line 56 of file base.py.
string django.template.base.VARIABLE_ATTRIBUTE_SEPARATOR = '.'
Definition at line 40 of file base.py.
string django.template.base.VARIABLE_TAG_END = '}}'
Definition at line 44 of file base.py.
string django.template.base.VARIABLE_TAG_START = '{{'
Definition at line 43 of file base.py.