Django: django.core.signing Namespace Reference
django.core.signing Namespace Reference
Classes
class BadSignature
class JSONSerializer
class SignatureExpired
class Signer
class TimestampSigner
Functions
def b64_encode (s)
def b64_decode (s)
def base64_hmac (salt, value, key)
def get_cookie_signer
def dumps
def loads
Detailed Description
Functions for creating and restoring url-safe signed JSON objects.
The format used looks like this:
>>> signing.dumps("hello")
'ImhlbGxvIg:1QaUZC:YIye-ze3TTx7gtSv422nZA4sgmk'
There are two components here, separated by a ':'. The first component is a
URLsafe base64 encoded JSON of the object passed to dumps(). The second
component is a base64 encoded hmac/SHA1 hash of "$first_component:$secret"
signing.loads(s) checks the signature and returns the deserialised object.
If the signature fails, a BadSignature exception is raised.
>>> signing.loads("ImhlbGxvIg:1QaUZC:YIye-ze3TTx7gtSv422nZA4sgmk")
u'hello'
>>> signing.loads("ImhlbGxvIg:1QaUZC:YIye-ze3TTx7gtSv422nZA4sgmk-modified")
...
BadSignature: Signature failed: ImhlbGxvIg:1QaUZC:YIye-ze3TTx7gtSv422nZA4sgmk-modified
You can optionally compress the JSON prior to base64 encoding it to save
space, using the compress=True argument. This checks if compression actually
helps and only applies compression if the result is a shorter string:
>>> signing.dumps(range(1, 20), compress=True)
'.eJwFwcERACAIwLCF-rCiILN47r-GyZVJsNgkxaFxoDgxcOHGxMKD_T7vhAml:1QaUaL:BA0thEZrp4FQVXIXuOvYJtLJSrQ'
The fact that the string is compressed is signalled by the prefixed '.' at the
start of the base64 JSON.
There are 65 url-safe characters: the 64 used by url-safe base64 and the ':'.
These functions make use of all of them.
Function Documentation
def django.core.signing.b64_decode (s)
Definition at line 68 of file signing.py.
Referenced by django.core.signing.loads().
def django.core.signing.b64_encode (s)
Definition at line 64 of file signing.py.
Referenced by django.core.signing.base64_hmac(), and django.core.signing.dumps().
def django.core.signing.base64_hmac (salt, value, key)
Definition at line 73 of file signing.py.
References django.core.signing.b64_encode(), and django.utils.crypto.salted_hmac().
Referenced by django.core.signing.Signer.signature().
def django.core.signing.dumps (obj, key = None, salt = 'django.core.signing', serializer = JSONSerializer, compress = False)
Returns URL-safe, sha1 signed base64 compressed JSON string. If key is
None, settings.SECRET_KEY is used instead.
If compress is True (not the default) checks if compressing using zlib can
save some space. Prepends a '.' to signify compression. This is included
in the signature, to protect against zip bombs.
Salt can be used to namespace the hash, so that a signed string is
only valid for a given namespace. Leaving this at the default
value or re-using a salt value across different parts of your
application without good cause is a security risk.
The serializer is expected to return a bytestring.
Definition at line 94 of file signing.py.
References django.core.signing.b64_encode().
Referenced by django.contrib.sessions.backends.base.SessionBase.encode().
def django.core.signing.get_cookie_signer (salt = 'django.core.signing.get_cookie_signer')
Definition at line 77 of file signing.py.
References django.utils.module_loading.import_by_path().
def django.core.signing.loads (s, key = None, salt = 'django.core.signing', serializer = JSONSerializer, max_age = None)
Reverse of dumps(), raises BadSignature if signature fails.
The serializer is expected to accept a bytestring.
Definition at line 127 of file signing.py.
References django.core.signing.b64_decode(), and django.utils.encoding.force_bytes().
Referenced by django.contrib.sessions.backends.base.SessionBase.decode().