Django: django.core.servers.basehttp Namespace Reference
django.core.servers.basehttp Namespace Reference
Classes
class ServerHandler
class WSGIRequestHandler
class WSGIServer
Functions
def get_internal_wsgi_application ()
def run
Variables
tuple __all__ = ('WSGIServer', 'WSGIRequestHandler', 'MAX_SOCKET_CHUNK_SIZE')
int MAX_SOCKET_CHUNK_SIZE = 32
Detailed Description
HTTP server that implements the Python WSGI protocol (PEP 333, rev 1.21).
Based on wsgiref.simple_server which is part of the standard library since 2.5.
This is a simple server for use in testing or debugging Django apps. It hasn't
been reviewed for security issues. DON'T USE IT FOR PRODUCTION USE!
Function Documentation
def django.core.servers.basehttp.get_internal_wsgi_application ()
Loads and returns the WSGI application as configured by the user in
``settings.WSGI_APPLICATION``. With the default ``startproject`` layout,
this will be the ``application`` object in ``projectname/wsgi.py``.
This function, and the ``WSGI_APPLICATION`` setting itself, are only useful
for Django's internal servers (runserver, runfcgi); external WSGI servers
should just be configured to point to the correct application object
directly.
If settings.WSGI_APPLICATION is not set (is ``None``), we just return
whatever ``django.core.wsgi.get_wsgi_application`` returns.
Definition at line 35 of file basehttp.py.
References django.core.wsgi.get_wsgi_application(), and django.utils.module_loading.import_by_path().
Referenced by django.core.management.commands.runserver.Command.get_handler(), and django.core.servers.fastcgi.runfastcgi().
def django.core.servers.basehttp.run (addr, port, wsgi_handler, ipv6 = False, threading = False)
Definition at line 172 of file basehttp.py.
Variable Documentation
tuple django.core.servers.basehttp.__all__ = ('WSGIServer', 'WSGIRequestHandler', 'MAX_SOCKET_CHUNK_SIZE')
Definition at line 26 of file basehttp.py.
int django.core.servers.basehttp.MAX_SOCKET_CHUNK_SIZE = 32
Definition at line 32 of file basehttp.py.