Django: django.test.signals Namespace Reference
django.test.signals Namespace Reference
Functions
def update_connections_time_zone (kwargs)
def clear_context_processors_cache (kwargs)
def clear_template_loaders_cache (kwargs)
def clear_serializers_cache (kwargs)
def language_changed (kwargs)
def file_storage_changed (kwargs)
Variables
tuple template_rendered = Signal(providing_args=["template", "context"])
tuple setting_changed = Signal(providing_args=["setting", "value"])
Function Documentation
def django.test.signals.clear_context_processors_cache (kwargs)
Definition at line 49 of file signals.py.
References django.dispatch.dispatcher.receiver().
def django.test.signals.clear_serializers_cache (kwargs)
Definition at line 63 of file signals.py.
References django.dispatch.dispatcher.receiver().
def django.test.signals.clear_template_loaders_cache (kwargs)
Definition at line 56 of file signals.py.
References django.dispatch.dispatcher.receiver().
def django.test.signals.file_storage_changed (kwargs)
Definition at line 78 of file signals.py.
def django.test.signals.language_changed (kwargs)
Definition at line 70 of file signals.py.
References django.dispatch.dispatcher.receiver().
def django.test.signals.update_connections_time_zone (kwargs)
Definition at line 19 of file signals.py.
References django.dispatch.dispatcher.receiver().
Variable Documentation
tuple django.test.signals.setting_changed = Signal(providing_args=["setting", "value"])
Definition at line 12 of file signals.py.
tuple django.test.signals.template_rendered = Signal(providing_args=["template", "context"])
Definition at line 10 of file signals.py.