Django: django.contrib.admin.validation.InlineValidator Class Reference
django.contrib.admin.validation.InlineValidator Class Reference
Public Member Functions
def validate_fk_name (self, cls, model)
def validate_extra (self, cls, model)
def validate_max_num (self, cls, model)
def validate_formset (self, cls, model)
Public Member Functions inherited from django.contrib.admin.validation.BaseValidator
def __init__ (self)
def validate (self, cls, model)
def check_field_spec (self, cls, model, flds, label)
def validate_raw_id_fields (self, cls, model)
def validate_fields (self, cls, model)
def validate_fieldsets (self, cls, model)
def validate_exclude (self, cls, model)
def validate_form (self, cls, model)
def validate_filter_vertical (self, cls, model)
def validate_filter_horizontal (self, cls, model)
def validate_radio_fields (self, cls, model)
def validate_prepopulated_fields (self, cls, model)
def validate_ordering (self, cls, model)
def validate_readonly_fields (self, cls, model)
Detailed Description
Definition at line 376 of file validation.py.
Member Function Documentation
def django.contrib.admin.validation.InlineValidator.validate_extra (self, cls, model)
Definition at line 385 of file validation.py.
References django.contrib.admin.validation.check_type().
def django.contrib.admin.validation.InlineValidator.validate_fk_name (self, cls, model)
Definition at line 377 of file validation.py.
References django.contrib.admin.validation.get_field().
def django.contrib.admin.validation.InlineValidator.validate_formset (self, cls, model)
Definition at line 393 of file validation.py.
def django.contrib.admin.validation.InlineValidator.validate_max_num (self, cls, model)
Definition at line 389 of file validation.py.
References django.contrib.admin.validation.check_type().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/admin/validation.py