Django: django.utils.dateformat Namespace Reference
django.utils.dateformat Namespace Reference
Classes
class DateFormat
class Formatter
class TimeFormat
Functions
def format (value, format_string)
def time_format (value, format_string)
Variables
tuple re_formatchars = re.compile(r'(?<!\\)([aAbBcdDeEfFgGhHiIjlLmMnNoOPrsStTUuwWyYzZ])')
tuple re_escaped = re.compile(r'\\(.)')
Detailed Description
PHP date() style date formatting
See http://www.php.net/date for format strings
Usage:
>>> import datetime
>>> d = datetime.datetime.now()
>>> df = DateFormat(d)
>>> print(df.format('jS F Y H:i'))
7th October 2003 11:39
>>>
Function Documentation
def django.utils.dateformat.format (value, format_string)
Definition at line 309 of file dateformat.py.
Referenced by django.template.defaultfilters.date(), django.db.backends.util.format_number(), django.contrib.admin.templatetags.admin_list.result_headers(), and django.contrib.gis.geos.tests.test_geos.GEOSTest.test_polygons_from_bbox().
def django.utils.dateformat.time_format (value, format_string)
Definition at line 314 of file dateformat.py.
Referenced by django.template.defaultfilters.time().
Variable Documentation
tuple django.utils.dateformat.re_escaped = re.compile(r'\\(.)')
Definition at line 28 of file dateformat.py.
tuple django.utils.dateformat.re_formatchars = re.compile(r'(?<!\\)([aAbBcdDeEfFgGhHiIjlLmMnNoOPrsStTUuwWyYzZ])')
Definition at line 27 of file dateformat.py.