Django: django.core.management.commands.startproject.Command Class Reference
django.core.management.commands.startproject.Command Class Reference
Public Member Functions
def handle (self, project_name=None, target=None, args, options)
Public Member Functions inherited from django.core.management.templates.TemplateCommand
def handle (self, app_or_project, name, target=None, options)
def handle_template (self, template, subdir)
def validate_name (self, name, app_or_project)
def download (self, url)
def splitext (self, the_path)
def extract (self, filename)
def is_url (self, template)
def make_writeable (self, filename)
Public Member Functions inherited from django.core.management.base.BaseCommand
def __init__ (self)
def get_version (self)
def usage (self, subcommand)
def create_parser (self, prog_name, subcommand)
def print_help (self, prog_name, subcommand)
def run_from_argv (self, argv)
def execute (self, args, options)
def validate
def handle (self, args, options)
Static Public Attributes
tuple help
Static Public Attributes inherited from django.core.management.templates.TemplateCommand
string args = "[name] [optional destination directory]"
tuple option_list
requires_model_validation = False
can_import_settings = False
list url_schemes = ['http', 'https', 'ftp']
leave_locale_alone = True
Static Public Attributes inherited from django.core.management.base.BaseCommand
tuple option_list
string help = ''
string args = ''
can_import_settings = True
requires_model_validation = True
output_transaction = False
leave_locale_alone = False
Additional Inherited Members
Public Attributes inherited from django.core.management.templates.TemplateCommand
app_or_project
paths_to_remove
verbosity
Public Attributes inherited from django.core.management.base.BaseCommand
style
stdout
stderr
Detailed Description
Definition at line 7 of file startproject.py.
Member Function Documentation
def django.core.management.commands.startproject.Command.handle (self, project_name = None, target = None, args, options)
Definition at line 12 of file startproject.py.
References django.utils.crypto.get_random_string(), django.utils.importlib.import_module(), and django.core.management.templates.TemplateCommand.validate_name().
Member Data Documentation
tuple django.core.management.commands.startproject.Command.help static
Initial value:
 = ("Creates a Django project directory structure for the given "
             "project name in the current directory or optionally in the "
             "given directory.")
Definition at line 8 of file startproject.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/core/management/commands/startproject.py