Django: django.test.client.FakePayload Class Reference
django.test.client.FakePayload Class Reference
Public Member Functions
def __init__
def __len__ (self)
def read
def write (self, content)
Public Attributes
read_started
Detailed Description
A wrapper around BytesIO that restricts what can be read since data from
the network can't be seeked and cannot be read outside of its content
length. This makes sure that views can't do anything under the test client
that wouldn't work in Real Life.
Definition at line 36 of file client.py.
Constructor & Destructor Documentation
def django.test.client.FakePayload.__init__ (self, content = None)
Definition at line 43 of file client.py.
References django.test.client.FakePayload.__content, django.test.client.FakePayload.__len, and django.utils.six.BytesIO.
Member Function Documentation
def django.test.client.FakePayload.__len__ (self)
Definition at line 50 of file client.py.
References django.test.client.FakePayload.__len.
def django.test.client.FakePayload.read (self, num_bytes = None)
Definition at line 53 of file client.py.
References django.test.client.FakePayload.__len, and django.test.client.FakePayload.read_started.
def django.test.client.FakePayload.write (self, content)
Definition at line 64 of file client.py.
References django.test.client.FakePayload.__len, django.utils.encoding.force_bytes(), and django.test.client.FakePayload.read_started.
Referenced by django.utils.unittest.runner._WritelnDecorator.writeln(), and django.utils.feedgenerator.SyndicationFeed.writeString().
Member Data Documentation
django.test.client.FakePayload.read_started
Definition at line 46 of file client.py.
Referenced by django.test.client.FakePayload.read(), and django.test.client.FakePayload.write().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/test/client.py