Django: django.contrib.gis.gdal.tests.test_geom.OGRGeomTest Class Reference
django.contrib.gis.gdal.tests.test_geom.OGRGeomTest Class Reference
Public Member Functions
def test00a_geomtype (self)
def test00b_geomtype_25d (self)
def test01a_wkt (self)
def test01a_ewkt (self)
def test01b_gml (self)
def test01c_hex (self)
def test01d_wkb (self)
def test01e_json (self)
def test02_points (self)
def test03_multipoints (self)
def test04_linestring (self)
def test05_multilinestring (self)
def test06_linearring (self)
def test07a_polygons (self)
def test07b_closepolygons (self)
def test08_multipolygons (self)
def test09a_srs (self)
def test09b_srs_transform (self)
def test09c_transform_dim (self)
def test10_difference (self)
def test11_intersection (self)
def test12_symdifference (self)
def test13_union (self)
def test14_add (self)
def test15_extent (self)
def test16_25D (self)
def test17_pickle (self)
def test18_ogrgeometry_transform_workaround (self)
def test19_equivalence_regression (self)
Public Member Functions inherited from django.contrib.gis.geometry.test_data.TestDataMixin
def geometries (self)
Detailed Description
Definition at line 21 of file test_geom.py.
Member Function Documentation
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test00a_geomtype (self)
Definition at line 24 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertRaises(), and django.utils.unittest.case.TestCase.fail().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test00b_geomtype_25d (self)
Definition at line 63 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test01a_ewkt (self)
Definition at line 76 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test01a_wkt (self)
Definition at line 70 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test01b_gml (self)
Definition at line 87 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test01c_hex (self)
Definition at line 98 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test01d_wkb (self)
Definition at line 107 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.template.defaultfilters.upper().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test01e_json (self)
Definition at line 117 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test02_points (self)
Definition at line 127 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test03_multipoints (self)
Definition at line 140 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test04_linestring (self)
Definition at line 156 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test05_multilinestring (self)
Definition at line 176 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test06_linearring (self)
Definition at line 193 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test07a_polygons (self)
Definition at line 205 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertAlmostEqual(), and django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test07b_closepolygons (self)
Definition at line 240 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test08_multipolygons (self)
Definition at line 252 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test09a_srs (self)
Definition at line 268 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test09b_srs_transform (self)
Definition at line 319 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertAlmostEqual(), django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertNotEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test09c_transform_dim (self)
Definition at line 343 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertAlmostEqual(), and django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test10_difference (self)
Definition at line 355 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test11_intersection (self)
Definition at line 367 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test12_symdifference (self)
Definition at line 380 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test13_union (self)
Definition at line 392 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test14_add (self)
Definition at line 404 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test15_extent (self)
Definition at line 425 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test16_25D (self)
Definition at line 438 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test17_pickle (self)
Definition at line 449 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test18_ogrgeometry_transform_workaround (self)
Definition at line 457 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_geom.OGRGeomTest.test19_equivalence_regression (self)
Definition at line 482 of file test_geom.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertNotEqual().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/gdal/tests/test_geom.py