Django: django.db.utils.ConnectionRouter Class Reference
django.db.utils.ConnectionRouter Class Reference
Public Member Functions
def __init__
def routers (self)
def allow_relation (self, obj1, obj2, hints)
def allow_syncdb (self, db, model)
Static Public Attributes
tuple db_for_read = _router_func('db_for_read')
tuple db_for_write = _router_func('db_for_write')
Detailed Description
Definition at line 216 of file utils.py.
Constructor & Destructor Documentation
def django.db.utils.ConnectionRouter.__init__ (self, routers = None)
If routers is not specified, will default to settings.DATABASE_ROUTERS.
Definition at line 217 of file utils.py.
References django.db.utils.ConnectionRouter._routers.
Member Function Documentation
def django.db.utils.ConnectionRouter.allow_relation (self, obj1, obj2, hints)
Definition at line 258 of file utils.py.
References django.db.utils.ConnectionRouter.routers().
def django.db.utils.ConnectionRouter.allow_syncdb (self, db, model)
Definition at line 271 of file utils.py.
References django.db.utils.ConnectionRouter.routers().
def django.db.utils.ConnectionRouter.routers (self)
Definition at line 224 of file utils.py.
References django.db.utils.ConnectionRouter._routers, django.utils.module_loading.import_by_path(), and django.db.utils.ConnectionRouter.routers().
Referenced by django.db.utils.ConnectionRouter.allow_relation(), django.db.utils.ConnectionRouter.allow_syncdb(), and django.db.utils.ConnectionRouter.routers().
Member Data Documentation
tuple django.db.utils.ConnectionRouter.db_for_read = _router_func('db_for_read') static
Definition at line 255 of file utils.py.
Referenced by django.contrib.gis.tests.layermap.tests.OtherRouter.db_for_write().
tuple django.db.utils.ConnectionRouter.db_for_write = _router_func('db_for_write') static
Definition at line 256 of file utils.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/db/utils.py