Django: django.utils.ipv6 Namespace Reference
django.utils.ipv6 Namespace Reference
Functions
def clean_ipv6_address
def is_valid_ipv6_address (ip_str)
Function Documentation
def django.utils.ipv6.clean_ipv6_address (ip_str, unpack_ipv4 = False, error_message = _("This is not a valid IPv6 address."))
Cleans a IPv6 address string.
Validity is checked by calling is_valid_ipv6_address() - if an
invalid address is passed, ValidationError is raised.
Replaces the longest continious zero-sequence with "::" and
removes leading zeroes and makes sure all hextets are lowercase.
Args:
    ip_str: A valid IPv6 address.
    unpack_ipv4: if an IPv4-mapped address is found,
    return the plain IPv4 address (default=False).
    error_message: A error message for in the ValidationError.
Returns:
    A compressed IPv6 address, or the same value
Definition at line 9 of file ipv6.py.
References django.utils.ipv6.is_valid_ipv6_address(), and django.template.defaultfilters.join().
Referenced by django.db.models.fields.GenericIPAddressField.get_prep_value(), django.forms.fields.GenericIPAddressField.to_python(), and django.db.models.fields.GenericIPAddressField.to_python().
def django.utils.ipv6.is_valid_ipv6_address (ip_str)
Ensure we have a valid IPv6 address.
Args:
    ip_str: A string, the IPv6 address.
Returns:
    A boolean, True if this is a valid IPv6 address.
Definition at line 144 of file ipv6.py.
References django.template.defaultfilters.join(), django.template.defaultfilters.lower(), and django.core.validators.validate_ipv4_address.
Referenced by django.utils.ipv6.clean_ipv6_address(), and django.core.validators.validate_ipv6_address().