Django: django.contrib.formtools.tests.tests.TestFormPreview Class Reference
django.contrib.formtools.tests.tests.TestFormPreview Class Reference
Public Member Functions
def get_context (self, request, form)
def get_initial (self, request)
def done (self, request, cleaned_data)
Public Member Functions inherited from django.contrib.formtools.preview.FormPreview
def __init__ (self, form)
def __call__ (self, request, args, kwargs)
def unused_name (self, name)
def preview_get (self, request)
def preview_post (self, request)
def post_post (self, request)
def get_auto_id (self)
def get_initial (self, request)
def get_context (self, request, form)
def parse_params (self, args, kwargs)
def process_preview (self, request, form, context)
def security_hash (self, request, form)
def failed_hash (self, request)
def done (self, request, cleaned_data)
Additional Inherited Members
Public Attributes inherited from django.contrib.formtools.preview.FormPreview
state
Static Public Attributes inherited from django.contrib.formtools.preview.FormPreview
string preview_template = 'formtools/preview.html'
string form_template = 'formtools/form.html'
Detailed Description
Definition at line 20 of file tests.py.
Member Function Documentation
def django.contrib.formtools.tests.tests.TestFormPreview.done (self, request, cleaned_data)
Definition at line 29 of file tests.py.
References django.utils._os.upath().
Referenced by django.contrib.formtools.wizard.views.WizardView.render_done().
def django.contrib.formtools.tests.tests.TestFormPreview.get_context (self, request, form)
Definition at line 21 of file tests.py.
def django.contrib.formtools.tests.tests.TestFormPreview.get_initial (self, request)
Definition at line 26 of file tests.py.
Referenced by django.views.generic.edit.FormMixin.get_form_kwargs().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/formtools/tests/tests.py