Django: django.core.mail.backends.base.BaseEmailBackend Class Reference
django.core.mail.backends.base.BaseEmailBackend Class Reference
Public Member Functions
def __init__ (self, fail_silently=False, kwargs)
def open (self)
def close (self)
def send_messages (self, email_messages)
Public Attributes
fail_silently
Detailed Description
Base class for email backend implementations.
Subclasses must at least overwrite send_messages().
Definition at line 3 of file base.py.
Constructor & Destructor Documentation
def django.core.mail.backends.base.BaseEmailBackend.__init__ (self, fail_silently = False, kwargs)
Definition at line 9 of file base.py.
Member Function Documentation
def django.core.mail.backends.base.BaseEmailBackend.close (self)
Close a network connection.
Definition at line 30 of file base.py.
Referenced by django.utils.archive.Archive.__exit__(), django.core.mail.backends.filebased.EmailBackend.close(), django.db.backends.BaseDatabaseWrapper.close_if_unusable_or_obsolete(), django.core.servers.basehttp.ServerHandler.finish_response(), django.core.mail.backends.console.EmailBackend.send_messages(), django.core.mail.backends.smtp.EmailBackend.send_messages(), and django.db.backends.BaseDatabaseWrapper.temporary_connection().
def django.core.mail.backends.base.BaseEmailBackend.open (self)
Open a network connection.
This method can be overwritten by backend implementations to
open a network connection.
It's up to the backend implementation to track the status of
a network connection if it's needed by the backend.
This method can be called by applications to force a single
network connection to be used when sending mails. See the
send_messages() method of the SMTP backend for a reference
implementation.
The default implementation does nothing.
Definition at line 12 of file base.py.
Referenced by django.contrib.staticfiles.storage.CachedFilesMixin.hashed_name(), django.core.mail.backends.filebased.EmailBackend.open(), django.core.mail.backends.console.EmailBackend.send_messages(), and django.core.mail.backends.smtp.EmailBackend.send_messages().
def django.core.mail.backends.base.BaseEmailBackend.send_messages (self, email_messages)
Sends one or more EmailMessage objects and returns the number of email
messages sent.
Definition at line 34 of file base.py.
Member Data Documentation
django.core.mail.backends.base.BaseEmailBackend.fail_silently
Definition at line 10 of file base.py.
Referenced by django.core.mail.backends.smtp.EmailBackend.close(), django.core.mail.backends.smtp.EmailBackend.open(), django.core.mail.backends.console.EmailBackend.send_messages(), and django.core.mail.backends.smtp.EmailBackend.send_messages().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/core/mail/backends/base.py