Django: django.contrib.auth.tests.test_forms.PasswordResetFormTest Class Reference
django.contrib.auth.tests.test_forms.PasswordResetFormTest Class Reference
Public Member Functions
def create_dummy_user (self)
def test_invalid_email (self)
def test_nonexistant_email (self)
def test_cleaned_data (self)
def test_custom_email_subject (self)
def test_preserve_username_case (self)
def test_inactive_user (self)
def test_unusable_password (self)
Static Public Attributes
list fixtures = ['authtestdata.json']
Detailed Description
Definition at line 336 of file test_forms.py.
Member Function Documentation
def django.contrib.auth.tests.test_forms.PasswordResetFormTest.create_dummy_user (self)
Create a user and return a tuple (user_object, username, email).
Definition at line 340 of file test_forms.py.
Referenced by django.contrib.auth.tests.test_forms.PasswordResetFormTest.test_cleaned_data(), and django.contrib.auth.tests.test_forms.PasswordResetFormTest.test_inactive_user().
def django.contrib.auth.tests.test_forms.PasswordResetFormTest.test_cleaned_data (self)
Definition at line 365 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertTrue(), and django.contrib.auth.tests.test_forms.PasswordResetFormTest.create_dummy_user().
def django.contrib.auth.tests.test_forms.PasswordResetFormTest.test_custom_email_subject (self)
Definition at line 374 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.auth.tests.test_forms.PasswordResetFormTest.test_inactive_user (self)
Test that inactive user cannot receive password reset email.
Definition at line 395 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertTrue(), and django.contrib.auth.tests.test_forms.PasswordResetFormTest.create_dummy_user().
def django.contrib.auth.tests.test_forms.PasswordResetFormTest.test_invalid_email (self)
Definition at line 349 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertFalse().
def django.contrib.auth.tests.test_forms.PasswordResetFormTest.test_nonexistant_email (self)
Test nonexistant email address. This should not fail because it would
expose information about registered users.
Definition at line 355 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.auth.tests.test_forms.PasswordResetFormTest.test_preserve_username_case (self)
Preserve the case of the user name (before the @ in the email address)
when creating a user (#5605).
Definition at line 385 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.auth.tests.test_forms.PasswordResetFormTest.test_unusable_password (self)
Definition at line 407 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertTrue().
Member Data Documentation
list django.contrib.auth.tests.test_forms.PasswordResetFormTest.fixtures = ['authtestdata.json'] static
Definition at line 338 of file test_forms.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_forms.py