Django: django.template.defaulttags Namespace Reference
django.template.defaulttags Namespace Reference
Classes
class AutoEscapeControlNode
class CommentNode
class CsrfTokenNode
class CycleNode
class DebugNode
class FilterNode
class FirstOfNode
class ForNode
class IfChangedNode
class IfEqualNode
class IfNode
class LoadNode
class NowNode
class RegroupNode
class SpacelessNode
class SsiNode
class TemplateIfParser
class TemplateLiteral
class TemplateTagNode
class URLNode
class VerbatimNode
class WidthRatioNode
class WithNode
Functions
def include_is_allowed (filepath)
def autoescape (parser, token)
def comment (parser, token)
def cycle
def csrf_token (parser, token)
def debug (parser, token)
def do_filter (parser, token)
def firstof
def do_for (parser, token)
def do_ifequal (parser, token, negate)
def ifequal (parser, token)
def ifnotequal (parser, token)
def do_if (parser, token)
def ifchanged (parser, token)
def ssi (parser, token)
def load (parser, token)
def now (parser, token)
def regroup (parser, token)
def spaceless (parser, token)
def templatetag (parser, token)
def url (parser, token)
def verbatim (parser, token)
def widthratio (parser, token)
def do_with (parser, token)
Variables
tuple register = Library()
Detailed Description
Default tags used by the template system, available to all templates.
Function Documentation
def django.template.defaulttags.autoescape (parser, token)
Force autoescape behavior for this block.
Definition at line 511 of file defaulttags.py.
def django.template.defaulttags.comment (parser, token)
Ignores everything between ``{% comment %}`` and ``{% endcomment %}``.
Definition at line 527 of file defaulttags.py.
def django.template.defaulttags.csrf_token (parser, token)
Definition at line 631 of file defaulttags.py.
def django.template.defaulttags.cycle (parser, token, escape = False)
Cycles among the given strings each time this tag is encountered.
Within a loop, cycles among the given strings each time through
the loop::
    {% for o in some_list %}
        <tr class="{% cycle 'row1' 'row2' %}">
            ...
        </tr>
    {% endfor %}
Outside of a loop, give the values a unique name the first time you call
it, then use that name each sucessive time through::
        <tr class="{% cycle 'row1' 'row2' 'row3' as rowcolors %}">...</tr>
        <tr class="{% cycle rowcolors %}">...</tr>
        <tr class="{% cycle rowcolors %}">...</tr>
You can use any number of values, separated by spaces. Commas can also
be used to separate values; if a comma is used, the cycle values are
interpreted as literal strings.
The optional flag "silent" can be used to prevent the cycle declaration
from returning any value::
    {% for o in some_list %}
        {% cycle 'row1' 'row2' as rowcolors silent %}
        <tr class="{{ rowcolors }}">{% include "subtemplate.html " %}</tr>
    {% endfor %}
Definition at line 535 of file defaulttags.py.
def django.template.defaulttags.debug (parser, token)
Outputs a whole load of debugging information, including the current
context and imported modules.
Sample usage::
    <pre>
        {% debug %}
    </pre>
Definition at line 635 of file defaulttags.py.
def django.template.defaulttags.do_filter (parser, token)
Filters the contents of the block through variable filters.
Filters can also be piped through each other, and they can have
arguments -- just like in variable syntax.
Sample usage::
    {% filter force_escape|lower %}
        This text will be HTML-escaped, and will appear in lowercase.
    {% endfilter %}
Note that the ``escape`` and ``safe`` filters are not acceptable arguments.
Instead, use the ``autoescape`` tag to manage autoescaping for blocks of
template code.
Definition at line 649 of file defaulttags.py.
def django.template.defaulttags.do_for (parser, token)
Loops over each item in an array.
For example, to display a list of athletes given ``athlete_list``::
    <ul>
    {% for athlete in athlete_list %}
        <li>{{ athlete.name }}</li>
    {% endfor %}
    </ul>
You can loop over a list in reverse by using
``{% for obj in list reversed %}``.
You can also unpack multiple values from a two-dimensional array::
    {% for key,value in dict.items %}
        {{ key }}: {{ value }}
    {% endfor %}
The ``for`` tag can take an optional ``{% empty %}`` clause that will
be displayed if the given array is empty or could not be found::
    <ul>
      {% for athlete in athlete_list %}
        <li>{{ athlete.name }}</li>
      {% empty %}
        <li>Sorry, no athletes in this list.</li>
      {% endfor %}
    <ul>
The above is equivalent to -- but shorter, cleaner, and possibly faster
than -- the following::
    <ul>
      {% if althete_list %}
        {% for athlete in athlete_list %}
          <li>{{ athlete.name }}</li>
        {% endfor %}
      {% else %}
        <li>Sorry, no athletes in this list.</li>
      {% endif %}
    </ul>
The for loop sets a number of variables available within the loop:
    ==========================  ================================================
    Variable                    Description
    ==========================  ================================================
    ``forloop.counter``         The current iteration of the loop (1-indexed)
    ``forloop.counter0``        The current iteration of the loop (0-indexed)
    ``forloop.revcounter``      The number of iterations from the end of the
                                loop (1-indexed)
    ``forloop.revcounter0``     The number of iterations from the end of the
                                loop (0-indexed)
    ``forloop.first``           True if this is the first time through the loop
    ``forloop.last``            True if this is the last time through the loop
    ``forloop.parentloop``      For nested loops, this is the loop "above" the
                                current one
    ==========================  ================================================
Definition at line 725 of file defaulttags.py.
References django.template.defaultfilters.join().
def django.template.defaulttags.do_if (parser, token)
The ``{% if %}`` tag evaluates a variable, and if that variable is "true"
(i.e., exists, is not empty, and is not a false boolean value), the
contents of the block are output:
::
    {% if athlete_list %}
        Number of athletes: {{ athlete_list|count }}
    {% elif athlete_in_locker_room_list %}
        Athletes should be out of the locker room soon!
    {% else %}
        No athletes.
    {% endif %}
In the above, if ``athlete_list`` is not empty, the number of athletes will
be displayed by the ``{{ athlete_list|count }}`` variable.
As you can see, the ``if`` tag may take one or several `` {% elif %}``
clauses, as well as an ``{% else %}`` clause that will be displayed if all
previous conditions fail. These clauses are optional.
``if`` tags may use ``or``, ``and`` or ``not`` to test a number of
variables or to negate a given variable::
    {% if not athlete_list %}
        There are no athletes.
    {% endif %}
    {% if athlete_list or coach_list %}
        There are some athletes or some coaches.
    {% endif %}
    {% if athlete_list and coach_list %}
        Both atheletes and coaches are available.
    {% endif %}
    {% if not athlete_list or coach_list %}
        There are no athletes, or there are some coaches.
    {% endif %}
    {% if athlete_list and not coach_list %}
        There are some athletes and absolutely no coaches.
    {% endif %}
Comparison operators are also available, and the use of filters is also
allowed, for example::
    {% if articles|length >= 5 %}...{% endif %}
Arguments and operators _must_ have a space between them, so
``{% if 1>2 %}`` is not a valid if tag.
All supported operators are: ``or``, ``and``, ``in``, ``not in``
``==`` (or ``=``), ``!=``, ``>``, ``>=``, ``<`` and ``<=``.
Operator precedence follows Python.
Definition at line 880 of file defaulttags.py.
def django.template.defaulttags.do_ifequal (parser, token, negate)
Definition at line 815 of file defaulttags.py.
Referenced by django.template.defaulttags.ifequal(), and django.template.defaulttags.ifnotequal().
def django.template.defaulttags.do_with (parser, token)
Adds one or more values to the context (inside of this block) for caching
and easy access.
For example::
    {% with total=person.some_sql_method %}
        {{ total }} object{{ total|pluralize }}
    {% endwith %}
Multiple values can be added to the context::
    {% with foo=1 bar=2 %}
        ...
    {% endwith %}
The legacy format of ``{% with person.some_sql_method as total %}`` is
still accepted.
Definition at line 1378 of file defaulttags.py.
References django.template.base.token_kwargs().
def django.template.defaulttags.firstof (parser, token, escape = False)
Outputs the first variable passed that is not False, without escaping.
Outputs nothing if all the passed variables are False.
Sample usage::
    {% firstof var1 var2 var3 %}
This is equivalent to::
    {% if var1 %}
        {{ var1|safe }}
    {% elif var2 %}
        {{ var2|safe }}
    {% elif var3 %}
        {{ var3|safe }}
    {% endif %}
but obviously much cleaner!
You can also use a literal string as a fallback value in case all
passed variables are False::
    {% firstof var1 var2 var3 "fallback value" %}
If you want to escape the output, use a filter tag::
    {% filter force_escape %}
        {% firstof var1 var2 var3 "fallback value" %}
    {% endfilter %}
Definition at line 678 of file defaulttags.py.
def django.template.defaulttags.ifchanged (parser, token)
Checks if a value has changed from the last iteration of a loop.
The ``{% ifchanged %}`` block tag is used within a loop. It has two
possible uses.
1. Checks its own rendered contents against its previous state and only
   displays the content if it has changed. For example, this displays a
   list of days, only displaying the month if it changes::
        <h1>Archive for {{ year }}</h1>
        {% for date in days %}
            {% ifchanged %}<h3>{{ date|date:"F" }}</h3>{% endifchanged %}
            <a href="{{ date|date:"M/d"|lower }}/">{{ date|date:"j" }}</a>
        {% endfor %}
2. If given one or more variables, check whether any variable has changed.
   For example, the following shows the date every time it changes, while
   showing the hour if either the hour or the date has changed::
        {% for date in days %}
            {% ifchanged date.date %} {{ date.date }} {% endifchanged %}
            {% ifchanged date.hour date.date %}
                {{ date.hour }}
            {% endifchanged %}
        {% endfor %}
Definition at line 967 of file defaulttags.py.
def django.template.defaulttags.ifequal (parser, token)
Outputs the contents of the block if the two arguments equal each other.
Examples::
    {% ifequal user.id comment.user_id %}
        ...
    {% endifequal %}
    {% ifnotequal user.id comment.user_id %}
        ...
    {% else %}
        ...
    {% endifnotequal %}
Definition at line 832 of file defaulttags.py.
References django.template.defaulttags.do_ifequal().
def django.template.defaulttags.ifnotequal (parser, token)
Outputs the contents of the block if the two arguments are not equal.
See ifequal.
Definition at line 851 of file defaulttags.py.
References django.template.defaulttags.do_ifequal().
def django.template.defaulttags.include_is_allowed (filepath)
Definition at line 335 of file defaulttags.py.
Referenced by django.template.defaulttags.SsiNode.render().
def django.template.defaulttags.load (parser, token)
Loads a custom template tag set.
For example, to load the template tags in
``django/templatetags/news/photos.py``::
    {% load news.photos %}
Can also be used to load an individual tag/filter from
a library::
    {% load byline from news %}
Definition at line 1038 of file defaulttags.py.
References django.template.base.get_library().
def django.template.defaulttags.now (parser, token)
Displays the date, formatted according to the given string.
Uses the same format as PHP's ``date()`` function; see http://php.net/date
for all the possible values.
Sample usage::
    It is {% now "jS F Y H:i" %}
Definition at line 1088 of file defaulttags.py.
def django.template.defaulttags.regroup (parser, token)
Regroups a list of alike objects by a common attribute.
This complex tag is best illustrated by use of an example:  say that
``people`` is a list of ``Person`` objects that have ``first_name``,
``last_name``, and ``gender`` attributes, and you'd like to display a list
that looks like:
    * Male:
        * George Bush
        * Bill Clinton
    * Female:
        * Margaret Thatcher
        * Colendeeza Rice
    * Unknown:
        * Pat Smith
The following snippet of template code would accomplish this dubious task::
    {% regroup people by gender as grouped %}
    <ul>
    {% for group in grouped %}
        <li>{{ group.grouper }}
        <ul>
            {% for item in group.list %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
    </ul>
As you can see, ``{% regroup %}`` populates a variable with a list of
objects with ``grouper`` and ``list`` attributes.  ``grouper`` contains the
item that was grouped by; ``list`` contains the list of objects that share
that ``grouper``.  In this case, ``grouper`` would be ``Male``, ``Female``
and ``Unknown``, and ``list`` is the list of people with those genders.
Note that ``{% regroup %}`` does not work when the list to be grouped is not
sorted by the key you are grouping by!  This means that if your list of
people was not sorted by gender, you'd need to make sure it is sorted
before using it, i.e.::
    {% regroup people|dictsort:"gender" by gender as grouped %}
Definition at line 1106 of file defaulttags.py.
def django.template.defaulttags.spaceless (parser, token)
Removes whitespace between HTML tags, including tab and newline characters.
Example usage::
    {% spaceless %}
        <p>
            <a href="foo/">Foo</a>
        </p>
    {% endspaceless %}
This example would return this HTML::
    <p><a href="foo/">Foo</a></p>
Only space between *tags* is normalized -- not space between tags and text.
In this example, the space around ``Hello`` won't be stripped::
    {% spaceless %}
        <strong>
            Hello
        </strong>
    {% endspaceless %}
Definition at line 1174 of file defaulttags.py.
def django.template.defaulttags.ssi (parser, token)
Outputs the contents of a given file into the page.
Like a simple "include" tag, the ``ssi`` tag includes the contents
of another file -- which must be specified using an absolute path --
in the current page::
    {% ssi "/home/html/ljworld.com/includes/right_generic.html" %}
If the optional "parsed" parameter is given, the contents of the included
file are evaluated as template code, with the current context::
    {% ssi "/home/html/ljworld.com/includes/right_generic.html" parsed %}
Definition at line 1008 of file defaulttags.py.
def django.template.defaulttags.templatetag (parser, token)
Outputs one of the bits used to compose template tags.
Since the template system has no concept of "escaping", to display one of
the bits used in template tags, you must use the ``{% templatetag %}`` tag.
The argument tells which template bit to output:
    ==================  =======
    Argument            Outputs
    ==================  =======
    ``openblock``       ``{%``
    ``closeblock``      ``%}``
    ``openvariable``    ``{{``
    ``closevariable``   ``}}``
    ``openbrace``       ``{``
    ``closebrace``      ``}``
    ``opencomment``     ``{#``
    ``closecomment``    ``#}``
    ==================  =======
Definition at line 1204 of file defaulttags.py.
def django.template.defaulttags.url (parser, token)
Returns an absolute URL matching given view with its parameters.
This is a way to define links that aren't tied to a particular URL
configuration::
    {% url "path.to.some_view" arg1 arg2 %}
    or
    {% url "path.to.some_view" name1=value1 name2=value2 %}
The first argument is a path to a view. It can be an absolute Python path
or just ``app_name.view_name`` without the project name if the view is
located inside the project.
Other arguments are space-separated values that will be filled in place of
positional and keyword arguments in the URL. Don't mix positional and
keyword arguments.
All arguments for the URL should be present.
For example if you have a view ``app_name.client`` taking client's id and
the corresponding line in a URLconf looks like this::
    ('^client/(\d+)/$', 'app_name.client')
and this app's URLconf is included into the project's URLconf under some
path::
    ('^clients/', include('project_name.app_name.urls'))
then in a template you can create a link for a certain client like this::
    {% url "app_name.client" client.id %}
The URL will look like ``/clients/client/123/``.
The first argument can also be a named URL instead of the Python path to
the view callable. For example if the URLconf entry looks like this::
    url('^client/(\d+)/$', name='client-detail-view')
then in the template you can use::
    {% url "client-detail-view" client.id %}
There is even another possible value type for the first argument. It can be
the name of a template variable that will be evaluated to obtain the view
name or the URL name, e.g.::
    {% with view_path="app_name.client" %}
    {% url view_path client.id %}
    {% endwith %}
    or,
    {% with url_name="client-detail-view" %}
    {% url url_name client.id %}
    {% endwith %}
Definition at line 1238 of file defaulttags.py.
def django.template.defaulttags.verbatim (parser, token)
Stops the template engine from rendering the contents of this block tag.
Usage::
    {% verbatim %}
        {% don't process this %}
    {% endverbatim %}
You can also designate a specific closing tag block (allowing the
unrendered use of ``{% endverbatim %}``)::
    {% verbatim myblock %}
        ...
    {% endverbatim myblock %}
Definition at line 1333 of file defaulttags.py.
def django.template.defaulttags.widthratio (parser, token)
For creating bar charts and such, this tag calculates the ratio of a given
value to a maximum value, and then applies that ratio to a constant.
For example::
    <img src='bar.gif' height='10' width='{% widthratio this_value max_value max_width %}' />
If ``this_value`` is 175, ``max_value`` is 200, and ``max_width`` is 100,
the image in the above example will be 88 pixels wide
(because 175/200 = .875; .875 * 100 = 87.5 which is rounded up to 88).
Definition at line 1355 of file defaulttags.py.
Variable Documentation
tuple django.template.defaulttags.register = Library()
Definition at line 26 of file defaulttags.py.