Django: django.middleware.clickjacking.XFrameOptionsMiddleware Class Reference
django.middleware.clickjacking.XFrameOptionsMiddleware Class Reference
Public Member Functions
def process_response (self, request, response)
def get_xframe_options_value (self, request, response)
Detailed Description
Middleware that sets the X-Frame-Options HTTP header in HTTP responses.
Does not set the header if it's already set or if the response contains
a xframe_options_exempt value set to True.
By default, sets the X-Frame-Options header to 'SAMEORIGIN', meaning the
response can only be loaded on a frame within the same site. To prevent the
response from being loaded in a frame in any site, set X_FRAME_OPTIONS in
your project's Django settings to 'DENY'.
Note: older browsers will quietly ignore this header, thus other
clickjacking protection techniques should be used if protection in those
browsers is required.
http://en.wikipedia.org/wiki/Clickjacking#Server_and_client
Definition at line 10 of file clickjacking.py.
Member Function Documentation
def django.middleware.clickjacking.XFrameOptionsMiddleware.get_xframe_options_value (self, request, response)
Gets the value to set for the X_FRAME_OPTIONS header.
By default this uses the value from the X_FRAME_OPTIONS Django
settings. If not found in settings, defaults to 'SAMEORIGIN'.
This method can be overridden if needed, allowing it to vary based on
the request or response.
Definition at line 41 of file clickjacking.py.
References django.template.defaultfilters.upper().
Referenced by django.middleware.clickjacking.XFrameOptionsMiddleware.process_response().
def django.middleware.clickjacking.XFrameOptionsMiddleware.process_response (self, request, response)
Definition at line 28 of file clickjacking.py.
References django.middleware.clickjacking.XFrameOptionsMiddleware.get_xframe_options_value().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/middleware/clickjacking.py