Django: django.contrib.redirects.models.Redirect.Meta Class Reference
django.contrib.redirects.models.Redirect.Meta Class Reference
Static Public Attributes
tuple verbose_name = _('redirect')
tuple verbose_name_plural = _('redirects')
string db_table = 'django_redirect'
tuple unique_together = (('site', 'old_path'),)
tuple ordering = ('old_path',)
Detailed Description
Definition at line 14 of file models.py.
Member Data Documentation
string django.contrib.redirects.models.Redirect.Meta.db_table = 'django_redirect' static
Definition at line 17 of file models.py.
Referenced by django.db.models.fields.related.ManyToManyField.get_choices_default(), and django.db.models.options.Options.setup_proxy().
tuple django.contrib.redirects.models.Redirect.Meta.ordering = ('old_path',) static
Definition at line 19 of file models.py.
Referenced by django.db.models.options.Options.module_name().
tuple django.contrib.redirects.models.Redirect.Meta.unique_together = (('site', 'old_path'),) static
Definition at line 18 of file models.py.
tuple django.contrib.redirects.models.Redirect.Meta.verbose_name = _('redirect') static
Definition at line 15 of file models.py.
Referenced by django.db.models.fields.Field.formfield(), django.db.models.fields.NullBooleanField.formfield(), and django.db.models.options.Options.verbose_name_raw().
tuple django.contrib.redirects.models.Redirect.Meta.verbose_name_plural = _('redirects') static
Definition at line 16 of file models.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/redirects/models.py