Django: django.utils.feedgenerator Namespace Reference
django.utils.feedgenerator Namespace Reference
Classes
class Atom1Feed
class Enclosure
class Rss201rev2Feed
class RssFeed
class RssUserland091Feed
class SyndicationFeed
Functions
def rfc2822_date (date)
def rfc3339_date (date)
def get_tag_uri (url, date)
Variables
DefaultFeed = Rss201rev2Feed
Detailed Description
Syndication feed generation library -- used for generating RSS, etc.
Sample usage:
>>> from django.utils import feedgenerator
>>> feed = feedgenerator.Rss201rev2Feed(
...     title="Poynter E-Media Tidbits",
...     link="http://www.poynter.org/column.asp?id=31",
...     description="A group Weblog by the sharpest minds in online media/journalism/publishing.",
...     language="en",
...)
>>> feed.add_item(
...     title="Hello",
...     link="http://www.holovaty.com/test/",
...     description="Testing."
...)
>>> with open('test.rss', 'w') as fp:
...     feed.write(fp, 'utf-8')
For definitions of the different versions of RSS, see:
http://web.archive.org/web/20110718035220/http://diveintomark.org/archives/2004/02/04/incompatible-rss
Function Documentation
def django.utils.feedgenerator.get_tag_uri (url, date)
Creates a TagURI.
See http://web.archive.org/web/20110514113830/http://diveintomark.org/archives/2004/05/28/howto-atom-id
Definition at line 70 of file feedgenerator.py.
References django.utils.datetime_safe.strftime().
Referenced by django.utils.feedgenerator.Atom1Feed.add_item_elements().
def django.utils.feedgenerator.rfc2822_date (date)
Definition at line 35 of file feedgenerator.py.
References django.utils.timezone.is_aware().
Referenced by django.utils.feedgenerator.Rss201rev2Feed.add_item_elements(), and django.utils.feedgenerator.RssFeed.add_root_elements().
def django.utils.feedgenerator.rfc3339_date (date)
Definition at line 56 of file feedgenerator.py.
References django.utils.timezone.is_aware().
Referenced by django.utils.feedgenerator.Atom1Feed.add_item_elements(), and django.utils.feedgenerator.Atom1Feed.add_root_elements().
Variable Documentation
django.utils.feedgenerator.DefaultFeed = Rss201rev2Feed
Definition at line 391 of file feedgenerator.py.