Django: django.contrib.sessions.middleware.SessionMiddleware Class Reference
django.contrib.sessions.middleware.SessionMiddleware Class Reference
Public Member Functions
def process_request (self, request)
def process_response (self, request, response)
Detailed Description
Definition at line 8 of file middleware.py.
Member Function Documentation
def django.contrib.sessions.middleware.SessionMiddleware.process_request (self, request)
Definition at line 9 of file middleware.py.
References django.utils.importlib.import_module().
Referenced by django.test.testcases.StoppableWSGIServer.handle_request().
def django.contrib.sessions.middleware.SessionMiddleware.process_response (self, request, response)
If request.session was modified, or if the configuration is to save the
session every time, save the changes and set a session cookie.
Definition at line 14 of file middleware.py.
References django.utils.cache.patch_vary_headers().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/sessions/middleware.py