Django: django.contrib.auth.tests.test_forms.UserCreationFormTest Class Reference
django.contrib.auth.tests.test_forms.UserCreationFormTest Class Reference
Public Member Functions
def test_user_already_exists (self)
def test_invalid_data (self)
def test_password_verification (self)
def test_both_passwords (self)
def test_success (self)
Static Public Attributes
list fixtures = ['authtestdata.json']
Detailed Description
Definition at line 24 of file test_forms.py.
Member Function Documentation
def django.contrib.auth.tests.test_forms.UserCreationFormTest.test_both_passwords (self)
Definition at line 62 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertFalse(), and django.utils.encoding.force_text().
def django.contrib.auth.tests.test_forms.UserCreationFormTest.test_invalid_data (self)
Definition at line 39 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertFalse(), and django.utils.encoding.force_text().
def django.contrib.auth.tests.test_forms.UserCreationFormTest.test_password_verification (self)
Definition at line 50 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertFalse(), and django.utils.encoding.force_text().
def django.contrib.auth.tests.test_forms.UserCreationFormTest.test_success (self)
Definition at line 77 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.auth.tests.test_forms.UserCreationFormTest.test_user_already_exists (self)
Definition at line 28 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertFalse(), and django.utils.encoding.force_text().
Member Data Documentation
list django.contrib.auth.tests.test_forms.UserCreationFormTest.fixtures = ['authtestdata.json'] static
Definition at line 26 of file test_forms.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_forms.py