Django: django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase Class Reference
django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase Class Reference
Public Member Functions
def setUp (self)
def tearDown (self)
def test_actual_implementation (self)
def test_simple (self)
def test_existing (self)
def test_i18n (self)
Public Attributes
old_get_system_username
Detailed Description
Definition at line 22 of file test_management.py.
Member Function Documentation
def django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase.setUp (self)
Definition at line 24 of file test_management.py.
Referenced by django.utils.unittest.case.TestCase.debug(), django.test._doctest.DocTestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase.tearDown (self)
Definition at line 27 of file test_management.py.
References django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase.old_get_system_username.
Referenced by django.utils.unittest.case.TestCase.debug(), django.test._doctest.DocTestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase.test_actual_implementation (self)
Definition at line 30 of file test_management.py.
References django.utils.unittest.case.TestCase.assertIsInstance().
def django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase.test_existing (self)
Definition at line 37 of file test_management.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase.test_i18n (self)
Definition at line 44 of file test_management.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase.test_simple (self)
Definition at line 33 of file test_management.py.
References django.utils.unittest.case.TestCase.assertEqual().
Member Data Documentation
django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase.old_get_system_username
Definition at line 25 of file test_management.py.
Referenced by django.contrib.auth.tests.test_management.GetDefaultUsernameTestCase.tearDown().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_management.py