Django: django.contrib.flatpages.tests.test_templatetags.FlatpageTemplateTagTests Class Reference
django.contrib.flatpages.tests.test_templatetags.FlatpageTemplateTagTests Class Reference
Public Member Functions
def test_get_flatpages_tag (self)
def test_get_flatpages_tag_for_anon_user (self)
def test_get_flatpages_tag_for_user (self)
def test_get_flatpages_with_prefix (self)
def test_get_flatpages_with_prefix_for_anon_user (self)
def test_get_flatpages_with_prefix_for_user (self)
def test_get_flatpages_with_variable_prefix (self)
def test_parsing_errors (self)
Static Public Attributes
list fixtures = ['sample_flatpages']
string urls = 'django.contrib.flatpages.tests.urls'
Detailed Description
Definition at line 23 of file test_templatetags.py.
Member Function Documentation
def django.contrib.flatpages.tests.test_templatetags.FlatpageTemplateTagTests.test_get_flatpages_tag (self)
Definition at line 27 of file test_templatetags.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.shortcuts.render().
def django.contrib.flatpages.tests.test_templatetags.FlatpageTemplateTagTests.test_get_flatpages_tag_for_anon_user (self)
Definition at line 38 of file test_templatetags.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.shortcuts.render().
def django.contrib.flatpages.tests.test_templatetags.FlatpageTemplateTagTests.test_get_flatpages_tag_for_user (self)
Definition at line 52 of file test_templatetags.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.shortcuts.render().
def django.contrib.flatpages.tests.test_templatetags.FlatpageTemplateTagTests.test_get_flatpages_with_prefix (self)
Definition at line 66 of file test_templatetags.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.shortcuts.render().
def django.contrib.flatpages.tests.test_templatetags.FlatpageTemplateTagTests.test_get_flatpages_with_prefix_for_anon_user (self)
Definition at line 77 of file test_templatetags.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.shortcuts.render().
def django.contrib.flatpages.tests.test_templatetags.FlatpageTemplateTagTests.test_get_flatpages_with_prefix_for_user (self)
Definition at line 91 of file test_templatetags.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.shortcuts.render().
def django.contrib.flatpages.tests.test_templatetags.FlatpageTemplateTagTests.test_get_flatpages_with_variable_prefix (self)
Definition at line 105 of file test_templatetags.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.shortcuts.render().
def django.contrib.flatpages.tests.test_templatetags.FlatpageTemplateTagTests.test_parsing_errors (self)
Definition at line 118 of file test_templatetags.py.
References django.utils.unittest.case.TestCase.assertRaises(), and django.shortcuts.render().
Member Data Documentation
list django.contrib.flatpages.tests.test_templatetags.FlatpageTemplateTagTests.fixtures = ['sample_flatpages'] static
Definition at line 24 of file test_templatetags.py.
string django.contrib.flatpages.tests.test_templatetags.FlatpageTemplateTagTests.urls = 'django.contrib.flatpages.tests.urls' static
Definition at line 25 of file test_templatetags.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/flatpages/tests/test_templatetags.py