Django: django.contrib.gis.geoip.prototypes Namespace Reference
django.contrib.gis.geoip.prototypes Namespace Reference
Classes
class geoip_char_p
class GeoIPRecord
GeoIP C Structure definitions ####.
class GeoIPTag
Functions
def check_record (result, func, cargs)
def record_output (func)
def check_string (result, func, cargs)
def string_output (func)
Variables
list geoip_char_fields = [name for name, ctype in GeoIPRecord._fields_ if ctype is c_char_p]
string GEOIP_DEFAULT_ENCODING = 'iso-8859-1'
dictionary geoip_encodings
tuple RECTYPE = POINTER(GeoIPRecord)
tuple DBTYPE = POINTER(GeoIPTag)
GeoIP_lib_version = lgeoip.GeoIP_lib_version
ctypes function prototypes ####
GeoIPRecord_delete = lgeoip.GeoIPRecord_delete
tuple GeoIP_record_by_addr = record_output(lgeoip.GeoIP_record_by_addr)
tuple GeoIP_record_by_name = record_output(lgeoip.GeoIP_record_by_name)
GeoIP_open = lgeoip.GeoIP_open
GeoIP_delete = lgeoip.GeoIP_delete
GeoIP_database_info = lgeoip.GeoIP_database_info
tuple GeoIP_country_code_by_addr = string_output(lgeoip.GeoIP_country_code_by_addr)
tuple GeoIP_country_code_by_name = string_output(lgeoip.GeoIP_country_code_by_name)
tuple GeoIP_country_name_by_addr = string_output(lgeoip.GeoIP_country_name_by_addr)
tuple GeoIP_country_name_by_name = string_output(lgeoip.GeoIP_country_name_by_name)
Function Documentation
def django.contrib.gis.geoip.prototypes.check_record (result, func, cargs)
Definition at line 51 of file prototypes.py.
References django.contrib.gis.geoip.prototypes.GeoIPRecord_delete.
def django.contrib.gis.geoip.prototypes.check_string (result, func, cargs)
Definition at line 90 of file prototypes.py.
def django.contrib.gis.geoip.prototypes.record_output (func)
Definition at line 70 of file prototypes.py.
def django.contrib.gis.geoip.prototypes.string_output (func)
Definition at line 103 of file prototypes.py.
Variable Documentation
tuple django.contrib.gis.geoip.prototypes.DBTYPE = POINTER(GeoIPTag)
Definition at line 33 of file prototypes.py.
list django.contrib.gis.geoip.prototypes.geoip_char_fields = [name for name, ctype in GeoIPRecord._fields_ if ctype is c_char_p]
Definition at line 24 of file prototypes.py.
tuple django.contrib.gis.geoip.prototypes.GeoIP_country_code_by_addr = string_output(lgeoip.GeoIP_country_code_by_addr)
Definition at line 112 of file prototypes.py.
Referenced by django.contrib.gis.geoip.base.GeoIP.country_code().
tuple django.contrib.gis.geoip.prototypes.GeoIP_country_code_by_name = string_output(lgeoip.GeoIP_country_code_by_name)
Definition at line 113 of file prototypes.py.
Referenced by django.contrib.gis.geoip.base.GeoIP.country_code().
tuple django.contrib.gis.geoip.prototypes.GeoIP_country_name_by_addr = string_output(lgeoip.GeoIP_country_name_by_addr)
Definition at line 114 of file prototypes.py.
Referenced by django.contrib.gis.geoip.base.GeoIP.country_name().
tuple django.contrib.gis.geoip.prototypes.GeoIP_country_name_by_name = string_output(lgeoip.GeoIP_country_name_by_name)
Definition at line 115 of file prototypes.py.
Referenced by django.contrib.gis.geoip.base.GeoIP.country_name().
django.contrib.gis.geoip.prototypes.GeoIP_database_info = lgeoip.GeoIP_database_info
Definition at line 98 of file prototypes.py.
Referenced by django.contrib.gis.geoip.base.GeoIP.__init__(), django.contrib.gis.geoip.base.GeoIP.city_info(), and django.contrib.gis.geoip.base.GeoIP.country_info().
string django.contrib.gis.geoip.prototypes.GEOIP_DEFAULT_ENCODING = 'iso-8859-1'
Definition at line 25 of file prototypes.py.
django.contrib.gis.geoip.prototypes.GeoIP_delete = lgeoip.GeoIP_delete
Definition at line 82 of file prototypes.py.
Referenced by django.contrib.gis.geoip.base.GeoIP.__del__().
dictionary django.contrib.gis.geoip.prototypes.geoip_encodings
Initial value:
 = { 0: 'iso-8859-1',
                     1: 'utf8',
                     }
Definition at line 26 of file prototypes.py.
django.contrib.gis.geoip.prototypes.GeoIP_lib_version = lgeoip.GeoIP_lib_version
ctypes function prototypes ####
Definition at line 39 of file prototypes.py.
Referenced by django.contrib.gis.geoip.base.GeoIP.info().
django.contrib.gis.geoip.prototypes.GeoIP_open = lgeoip.GeoIP_open
Definition at line 80 of file prototypes.py.
Referenced by django.contrib.gis.geoip.base.GeoIP.__init__().
tuple django.contrib.gis.geoip.prototypes.GeoIP_record_by_addr = record_output(lgeoip.GeoIP_record_by_addr)
Definition at line 75 of file prototypes.py.
Referenced by django.contrib.gis.geoip.base.GeoIP.city().
tuple django.contrib.gis.geoip.prototypes.GeoIP_record_by_name = record_output(lgeoip.GeoIP_record_by_name)
Definition at line 76 of file prototypes.py.
Referenced by django.contrib.gis.geoip.base.GeoIP.city().
django.contrib.gis.geoip.prototypes.GeoIPRecord_delete = lgeoip.GeoIPRecord_delete
Definition at line 46 of file prototypes.py.
Referenced by django.contrib.gis.geoip.prototypes.check_record().
tuple django.contrib.gis.geoip.prototypes.RECTYPE = POINTER(GeoIPRecord)
Definition at line 32 of file prototypes.py.