Django: django.contrib.formtools.tests.wizard.test_loadstorage.TestLoadStorage Class Reference
django.contrib.formtools.tests.wizard.test_loadstorage.TestLoadStorage Class Reference
Public Member Functions
def test_load_storage (self)
def test_missing_storage (self)
Detailed Description
Definition at line 7 of file test_loadstorage.py.
Member Function Documentation
def django.contrib.formtools.tests.wizard.test_loadstorage.TestLoadStorage.test_load_storage (self)
Definition at line 8 of file test_loadstorage.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.formtools.wizard.storage.get_storage().
def django.contrib.formtools.tests.wizard.test_loadstorage.TestLoadStorage.test_missing_storage (self)
Definition at line 13 of file test_loadstorage.py.
References django.utils.unittest.case.TestCase.assertRaises().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/formtools/tests/wizard/test_loadstorage.py