Django: django.http.request Namespace Reference
django.http.request Namespace Reference
Classes
class HttpRequest
class QueryDict
class UnreadablePostError
Functions
def build_request_repr
def bytes_to_text (s, encoding)
def split_domain_port (host)
def validate_host (host, allowed_hosts)
Variables
tuple RAISE_ERROR = object()
tuple absolute_http_url_re = re.compile(r"^https?://", re.I)
tuple host_validation_re = re.compile(r"^([a-z0-9.-]+|\[[a-f0-9]*:[a-f0-9:]+\])(:\d+)?$")
Function Documentation
def django.http.request.build_request_repr (request, path_override = None, GET_override = None, POST_override = None, COOKIES_override = None, META_override = None)
Builds and returns the request's representation string. The request's
attributes may be overridden by pre-processed values.
Definition at line 415 of file request.py.
References django.utils.encoding.force_str.
Referenced by django.http.request.HttpRequest.__repr__(), django.views.debug.ExceptionReporterFilter.get_request_repr(), and django.http.request.QueryDict.urlencode().
def django.http.request.bytes_to_text (s, encoding)
Converts basestring objects to unicode, using the given encoding. Illegally
encoded input characters are replaced with Unicode "unknown" codepoint
(\ufffd).
Returns any non-basestring objects without change.
Definition at line 462 of file request.py.
Referenced by django.http.request.QueryDict.__setitem__(), django.http.request.QueryDict.appendlist(), django.http.request.QueryDict.setdefault(), and django.http.request.QueryDict.setlist().
def django.http.request.split_domain_port (host)
Return a (domain, port) tuple from a given host.
Returned domain is lower-cased. If the host is invalid, the domain will be
empty.
Definition at line 476 of file request.py.
Referenced by django.http.request.HttpRequest.get_host().
def django.http.request.validate_host (host, allowed_hosts)
Validate the given host for this site.
Check that the host looks valid and matches a host or host pattern in the
given list of ``allowed_hosts``. Any pattern beginning with a period
matches a domain and all its subdomains (e.g. ``.example.com`` matches
``example.com`` and any subdomain), ``*`` matches anything, and anything
else must match exactly.
Note: This function assumes that the given host is lower-cased and has
already had the port, if any, stripped off.
Return ``True`` for a valid host, ``False`` otherwise.
Definition at line 497 of file request.py.
Referenced by django.http.request.HttpRequest.get_host().
Variable Documentation
tuple django.http.request.absolute_http_url_re = re.compile(r"^https?://", re.I)
Definition at line 22 of file request.py.
tuple django.http.request.host_validation_re = re.compile(r"^([a-z0-9.-]+|\[[a-f0-9]*:[a-f0-9:]+\])(:\d+)?$")
Definition at line 23 of file request.py.
tuple django.http.request.RAISE_ERROR = object()
Definition at line 21 of file request.py.