Django: django.utils.cache Namespace Reference
django.utils.cache Namespace Reference
Functions
def patch_cache_control (response, kwargs)
def get_max_age (response)
def patch_response_headers
def add_never_cache_headers (response)
def patch_vary_headers (response, newheaders)
def has_vary_header (response, header_query)
def get_cache_key
def learn_cache_key
Variables
tuple cc_delim_re = re.compile(r'\s*,\s*')
Detailed Description
This module contains helper functions for controlling caching. It does so by
managing the "Vary" header of responses. It includes functions to patch the
header of response objects directly and decorators that change functions to do
that header-patching themselves.
For information on the Vary header, see:
    http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.44
Essentially, the "Vary" HTTP header defines which headers a cache should take
into account when building its cache key. Requests with the same path but
different header content for headers named in "Vary" need to get different
cache keys to prevent delivery of wrong content.
An example: i18n middleware would need to distinguish caches by the
"Accept-language" header.
Function Documentation
def django.utils.cache.add_never_cache_headers (response)
Adds headers to a response to indicate that a page should never be cached.
Definition at line 127 of file cache.py.
References django.utils.cache.patch_response_headers().
Referenced by django.views.decorators.cache.never_cache().
def django.utils.cache.get_cache_key (request, key_prefix = None, method = 'GET', cache = None)
Returns a cache key based on the request path and query. It can be used
in the request phase because it pulls the list of headers to take into
account from the global path registry and uses those to build a cache key
to check against.
If there is no headerlist stored, the page needs to be rebuilt, so this
function returns None.
Definition at line 197 of file cache.py.
References django.core.cache.get_cache().
Referenced by django.middleware.cache.FetchFromCacheMiddleware.process_request().
def django.utils.cache.get_max_age (response)
Returns the max-age from the response Cache-Control header as an integer
(or ``None`` if it wasn't found or wasn't an integer.
Definition at line 82 of file cache.py.
Referenced by django.middleware.cache.UpdateCacheMiddleware.process_response().
def django.utils.cache.has_vary_header (response, header_query)
Checks to see if the response has a given header name in its Vary header.
Definition at line 152 of file cache.py.
References django.utils.encoding.force_bytes(), django.utils.encoding.force_text(), django.utils.timezone.get_current_timezone_name(), django.utils.translation.trans_null.get_language, and django.utils.encoding.iri_to_uri().
Referenced by django.middleware.cache.UpdateCacheMiddleware.process_response().
def django.utils.cache.learn_cache_key (request, response, cache_timeout = None, key_prefix = None, cache = None)
Learns what headers to take into account for some request path from the
response object. It stores those headers in a global path registry so that
later access to that path will know what headers to take into account
without building the response object itself. The headers are named in the
Vary header of the response, but we want to prevent response generation.
The list of headers to use for cache key generation is stored in the same
cache as the pages themselves. If the cache ages some data out of the
cache, this just means that we have to build the response once to get at
the Vary header and so at the list of headers to use for the cache key.
Definition at line 218 of file cache.py.
References django.core.cache.get_cache(), and django.template.defaultfilters.lower().
Referenced by django.middleware.cache.UpdateCacheMiddleware.process_response().
def django.utils.cache.patch_cache_control (response, kwargs)
This function patches the Cache-Control header by adding all
keyword arguments to it. The transformation is as follows:
* All keyword parameter names are turned to lowercase, and underscores
  are converted to hyphens.
* If the value of a parameter is True (exactly True, not just a
  true value), only the parameter name is added to the header.
* All other parameters are added with their value, after applying
  str() to it.
Definition at line 34 of file cache.py.
References django.template.defaultfilters.join(), and django.template.defaultfilters.lower().
Referenced by django.views.decorators.cache.cache_control(), and django.utils.cache.patch_response_headers().
def django.utils.cache.patch_response_headers (response, cache_timeout = None)
Adds some useful headers to the given HttpResponse object:
    ETag, Last-Modified, Expires and Cache-Control
Each header is only added if it isn't already set.
cache_timeout is in seconds. The CACHE_MIDDLEWARE_SECONDS setting is used
by default.
Definition at line 102 of file cache.py.
References django.utils.six.callable, and django.utils.cache.patch_cache_control().
Referenced by django.utils.cache.add_never_cache_headers(), and django.middleware.cache.UpdateCacheMiddleware.process_response().
def django.utils.cache.patch_vary_headers (response, newheaders)
Adds (or updates) the "Vary" header in the given HttpResponse object.
newheaders is a list of header names that should be in "Vary". Existing
headers in "Vary" aren't removed.
Definition at line 133 of file cache.py.
References django.template.defaultfilters.join().
Referenced by django.contrib.sessions.middleware.SessionMiddleware.process_response(), django.middleware.gzip.GZipMiddleware.process_response(), django.middleware.locale.LocaleMiddleware.process_response(), django.middleware.csrf.CsrfViewMiddleware.process_response(), django.views.decorators.vary.vary_on_cookie(), and django.views.decorators.vary.vary_on_headers().
Variable Documentation
tuple django.utils.cache.cc_delim_re = re.compile(r'\s*,\s*')
Definition at line 32 of file cache.py.