Django: django.contrib.gis.gdal.field.OFTTime Class Reference
django.contrib.gis.gdal.field.OFTTime Class Reference
Public Member Functions
def value (self)
Public Member Functions inherited from django.contrib.gis.gdal.field.Field
def __init__ (self, feat, index)
Python 'magic' routines ####.
def __str__ (self)
def as_double (self)
Field Methods ####.
def as_int (self)
def as_string (self)
def as_datetime (self)
def name (self)
Field Properties ####.
def precision (self)
def type (self)
def type_name (self)
def value (self)
def width (self)
Additional Inherited Members
Public Attributes inherited from django.contrib.gis.gdal.field.Field
ptr
precision
Static Public Attributes inherited from django.contrib.gis.gdal.base.GDALBase
ptr_type = c_void_p
Properties inherited from django.contrib.gis.gdal.base.GDALBase
ptr = property(_get_ptr, _set_ptr)
Detailed Description
Definition at line 164 of file field.py.
Member Function Documentation
def django.contrib.gis.gdal.field.OFTTime.value (self)
Definition at line 166 of file field.py.
References django.contrib.gis.gdal.field.Field.as_datetime(), and django.template.defaultfilters.time().
Referenced by django.forms.forms.BoundField.__iter__(), and django.forms.forms.BoundField.as_widget().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/gdal/field.py