Django: django.contrib.gis.tests.test_geoforms.CustomGeometryWidgetTest Class Reference
django.contrib.gis.tests.test_geoforms.CustomGeometryWidgetTest Class Reference
Public Member Functions
def test_custom_serialization_widget (self)
Detailed Description
Definition at line 271 of file test_geoforms.py.
Member Function Documentation
def django.contrib.gis.tests.test_geoforms.CustomGeometryWidgetTest.test_custom_serialization_widget (self)
Definition at line 273 of file test_geoforms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertIn(), django.utils.unittest.case.TestCase.assertTrue(), django.core.serializers.deserialize(), django.utils.html.escape, and django.core.serializers.serialize().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/tests/test_geoforms.py