Django: django.contrib.auth.management.commands.createsuperuser.Command Class Reference
django.contrib.auth.management.commands.createsuperuser.Command Class Reference
Public Member Functions
def __init__ (self, args, kwargs)
def handle (self, args, options)
Public Member Functions inherited from django.core.management.base.BaseCommand
def __init__ (self)
def get_version (self)
def usage (self, subcommand)
def create_parser (self, prog_name, subcommand)
def print_help (self, prog_name, subcommand)
def run_from_argv (self, argv)
def execute (self, args, options)
def validate
def handle (self, args, options)
Public Attributes
UserModel
username_field
Public Attributes inherited from django.core.management.base.BaseCommand
style
stdout
stderr
Static Public Attributes
option_list = BaseCommand.option_list
string help = 'Used to create a superuser.'
Static Public Attributes inherited from django.core.management.base.BaseCommand
tuple option_list
string help = ''
string args = ''
can_import_settings = True
requires_model_validation = True
output_transaction = False
leave_locale_alone = False
Detailed Description
Definition at line 20 of file createsuperuser.py.
Constructor & Destructor Documentation
def django.contrib.auth.management.commands.createsuperuser.Command.__init__ (self, args, kwargs)
Definition at line 22 of file createsuperuser.py.
Member Function Documentation
def django.contrib.auth.management.commands.createsuperuser.Command.handle (self, args, options)
Definition at line 49 of file createsuperuser.py.
References django.utils.text.capfirst, django.contrib.auth.management.create_superuser(), django.utils.encoding.force_str, django.contrib.auth.management.get_default_username(), and django.template.defaultfilters.join().
Member Data Documentation
string django.contrib.auth.management.commands.createsuperuser.Command.help = 'Used to create a superuser.' static
Definition at line 47 of file createsuperuser.py.
Referenced by django.core.management.base.BaseCommand.usage().
django.contrib.auth.management.commands.createsuperuser.Command.option_list = BaseCommand.option_list static
Definition at line 46 of file createsuperuser.py.
Referenced by django.core.management.commands.test.Command.create_parser(), and django.core.management.base.BaseCommand.create_parser().
django.contrib.auth.management.commands.createsuperuser.Command.UserModel
Definition at line 26 of file createsuperuser.py.
django.contrib.auth.management.commands.createsuperuser.Command.username_field
Definition at line 27 of file createsuperuser.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py