Django: django.forms.formsets Namespace Reference
django.forms.formsets Namespace Reference
Classes
class BaseFormSet
class ManagementForm
Functions
def formset_factory
def all_valid (formsets)
Variables
tuple __all__ = ('BaseFormSet', 'all_valid')
string TOTAL_FORM_COUNT = 'TOTAL_FORMS'
string INITIAL_FORM_COUNT = 'INITIAL_FORMS'
string MAX_NUM_FORM_COUNT = 'MAX_NUM_FORMS'
string ORDERING_FIELD_NAME = 'ORDER'
string DELETION_FIELD_NAME = 'DELETE'
int DEFAULT_MAX_NUM = 1000
Function Documentation
def django.forms.formsets.all_valid (formsets)
Returns true if every formset in formsets is valid.
Definition at line 411 of file formsets.py.
Referenced by django.contrib.admin.options.ModelAdmin.add_view(), and django.contrib.admin.options.ModelAdmin.change_view().
def django.forms.formsets.formset_factory (form, formset = BaseFormSet, extra = 1, can_order = False, can_delete = False, max_num = None, validate_max = False)
Return a FormSet for the given form class.
Definition at line 397 of file formsets.py.
Referenced by django.forms.formsets.BaseFormSet.as_ul(), and django.forms.models.modelformset_factory().
Variable Documentation
tuple django.forms.formsets.__all__ = ('BaseFormSet', 'all_valid')
Definition at line 16 of file formsets.py.
int django.forms.formsets.DEFAULT_MAX_NUM = 1000
Definition at line 26 of file formsets.py.
string django.forms.formsets.DELETION_FIELD_NAME = 'DELETE'
Definition at line 23 of file formsets.py.
string django.forms.formsets.INITIAL_FORM_COUNT = 'INITIAL_FORMS'
Definition at line 20 of file formsets.py.
string django.forms.formsets.MAX_NUM_FORM_COUNT = 'MAX_NUM_FORMS'
Definition at line 21 of file formsets.py.
string django.forms.formsets.ORDERING_FIELD_NAME = 'ORDER'
Definition at line 22 of file formsets.py.
string django.forms.formsets.TOTAL_FORM_COUNT = 'TOTAL_FORMS'
Definition at line 19 of file formsets.py.