Django: django.contrib.auth.tests.test_handlers.ModWsgiHandlerTestCase Class Reference
django.contrib.auth.tests.test_handlers.ModWsgiHandlerTestCase Class Reference
Public Member Functions
def test_check_password (self)
def test_check_password_custom_user (self)
def test_groups_for_user (self)
Static Public Attributes
list available_apps
Detailed Description
Tests for the mod_wsgi authentication handler
Definition at line 13 of file test_handlers.py.
Member Function Documentation
def django.contrib.auth.tests.test_handlers.ModWsgiHandlerTestCase.test_check_password (self)
Verify that check_password returns the correct values as per
http://code.google.com/p/modwsgi/wiki/AccessControlMechanisms#Apache_Authentication_Provider
Definition at line 24 of file test_handlers.py.
References django.utils.unittest.case.TestCase.assertFalse(), django.utils.unittest.case.TestCase.assertTrue(), and django.contrib.auth.handlers.modwsgi.check_password().
def django.contrib.auth.tests.test_handlers.ModWsgiHandlerTestCase.test_check_password_custom_user (self)
Verify that check_password returns the correct values as per
http://code.google.com/p/modwsgi/wiki/AccessControlMechanisms#Apache_Authentication_Provider
with custom user installed
Definition at line 45 of file test_handlers.py.
References django.utils.unittest.case.TestCase.assertFalse(), django.utils.unittest.case.TestCase.assertTrue(), and django.contrib.auth.handlers.modwsgi.check_password().
def django.contrib.auth.tests.test_handlers.ModWsgiHandlerTestCase.test_groups_for_user (self)
Check that groups_for_user returns correct values as per
http://code.google.com/p/modwsgi/wiki/AccessControlMechanisms#Apache_Group_Authorisation
Definition at line 65 of file test_handlers.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.auth.handlers.modwsgi.groups_for_user().
Member Data Documentation
list django.contrib.auth.tests.test_handlers.ModWsgiHandlerTestCase.available_apps static
Initial value:
 = [
         'django.contrib.auth',
         'django.contrib.contenttypes',
     ]
Definition at line 18 of file test_handlers.py.
Referenced by django.db.models.loading.AppCache.get_app(), django.db.models.loading.AppCache.get_apps(), django.db.models.loading.AppCache.get_model(), django.db.models.loading.AppCache.get_models(), and django.db.models.loading.AppCache.unset_available_apps().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_handlers.py