Django: django.http.multipartparser.LazyStream Class Reference
django.http.multipartparser.LazyStream Class Reference
Public Member Functions
def __init__
def tell (self)
def read
def __next__ (self)
def close (self)
def __iter__ (self)
def unget (self, bytes)
Public Attributes
length
position
Detailed Description
The LazyStream wrapper allows one to get and "unget" bytes from a stream.
Given a producer object (an iterator that yields bytestrings), the
LazyStream object will support iteration, reading, and keeping a "look-back"
variable in case you need to "unget" some bytes.
Definition at line 268 of file multipartparser.py.
Constructor & Destructor Documentation
def django.http.multipartparser.LazyStream.__init__ (self, producer, length = None)
Every LazyStream must have a producer when instantiated.
A producer is an iterable that returns a string each time it
is called.
Definition at line 276 of file multipartparser.py.
References django.http.multipartparser.LazyStream._empty, django.http.multipartparser.LazyStream._leftover, and django.http.multipartparser.LazyStream._producer.
Member Function Documentation
def django.http.multipartparser.LazyStream.__iter__ (self)
Definition at line 344 of file multipartparser.py.
def django.http.multipartparser.LazyStream.__next__ (self)
Used when the exact number of bytes to read is unimportant.
This procedure just returns whatever is chunk is conveniently returned
from the iterator instead. Useful to avoid unnecessary bookkeeping if
performance is an issue.
Definition at line 318 of file multipartparser.py.
References django.http.multipartparser.LazyStream._leftover, django.http.multipartparser.LazyStream._producer, django.http.multipartparser.LazyStream._unget_history, django.utils.six.next, and django.http.multipartparser.LazyStream.position.
def django.http.multipartparser.LazyStream.close (self)
Used to invalidate/disable this lazy stream.
Replaces the producer with an empty list. Any leftover bytes that have
already been read will still be reported upon read() and/or next().
Definition at line 335 of file multipartparser.py.
References django.http.multipartparser.LazyStream._producer.
Referenced by django.utils.archive.Archive.__exit__(), and django.core.servers.basehttp.ServerHandler.finish_response().
def django.http.multipartparser.LazyStream.read (self, size = None)
Definition at line 294 of file multipartparser.py.
References django.http.multipartparser.LazyStream._remaining, django.template.defaultfilters.join(), django.utils.six.next, and django.http.multipartparser.LazyStream.unget().
Referenced by django.http.request.HttpRequest.body().
def django.http.multipartparser.LazyStream.tell (self)
Definition at line 291 of file multipartparser.py.
References django.http.multipartparser.LazyStream.position.
def django.http.multipartparser.LazyStream.unget (self, bytes)
Places bytes back onto the front of the lazy stream.
Future calls to read() will return those bytes first. The
stream position and thus tell() will be rewound.
Definition at line 347 of file multipartparser.py.
References django.http.multipartparser.LazyStream._leftover, django.http.multipartparser.LazyStream._unget_history, django.http.multipartparser.LazyStream._update_unget_history(), django.template.defaultfilters.join(), and django.http.multipartparser.LazyStream.position.
Referenced by django.http.multipartparser.LazyStream.read().
Member Data Documentation
django.http.multipartparser.LazyStream.length
Definition at line 286 of file multipartparser.py.
django.http.multipartparser.LazyStream.position
Definition at line 287 of file multipartparser.py.
Referenced by django.http.multipartparser.LazyStream.__next__(), django.http.multipartparser.LazyStream.tell(), and django.http.multipartparser.LazyStream.unget().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/http/multipartparser.py