Django: django.contrib.contenttypes.tests.ContentTypesTests Class Reference
django.contrib.contenttypes.tests.ContentTypesTests Class Reference
Public Member Functions
def setUp (self)
def tearDown (self)
def test_lookup_cache (self)
def test_get_for_models_empty_cache (self)
def test_get_for_models_partial_cache (self)
def test_get_for_models_full_cache (self)
def test_get_for_concrete_model (self)
def test_get_for_concrete_models (self)
def test_shortcut_view (self)
def test_shortcut_view_without_get_absolute_url (self)
def test_shortcut_view_with_broken_get_absolute_url (self)
def test_missing_model (self)
Public Attributes
old_Site_meta_installed
Detailed Description
Definition at line 50 of file tests.py.
Member Function Documentation
def django.contrib.contenttypes.tests.ContentTypesTests.setUp (self)
Definition at line 52 of file tests.py.
Referenced by django.utils.unittest.case.TestCase.debug(), django.test._doctest.DocTestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.contrib.contenttypes.tests.ContentTypesTests.tearDown (self)
Definition at line 56 of file tests.py.
References django.contrib.contenttypes.tests.ContentTypesTests.old_Site_meta_installed.
Referenced by django.utils.unittest.case.TestCase.debug(), django.test._doctest.DocTestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.contrib.contenttypes.tests.ContentTypesTests.test_get_for_concrete_model (self)
Make sure the `for_concrete_model` kwarg correctly works
with concrete, proxy and deferred models
Definition at line 126 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertNotEqual().
def django.contrib.contenttypes.tests.ContentTypesTests.test_get_for_concrete_models (self)
Make sure the `for_concrete_models` kwarg correctly works
with concrete, proxy and deferred models.
Definition at line 164 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.contenttypes.tests.ContentTypesTests.test_get_for_models_empty_cache (self)
Definition at line 96 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.test.testcases.TransactionTestCase.assertNumQueries().
def django.contrib.contenttypes.tests.ContentTypesTests.test_get_for_models_full_cache (self)
Definition at line 115 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.test.testcases.TransactionTestCase.assertNumQueries().
def django.contrib.contenttypes.tests.ContentTypesTests.test_get_for_models_partial_cache (self)
Definition at line 105 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.test.testcases.TransactionTestCase.assertNumQueries().
def django.contrib.contenttypes.tests.ContentTypesTests.test_lookup_cache (self)
Make sure that the content type cache (see ContentTypeManager)
works correctly. Lookups for a particular content type -- by model, ID
or natural key -- should hit the database only on the first lookup.
Definition at line 60 of file tests.py.
References django.test.testcases.TransactionTestCase.assertNumQueries().
def django.contrib.contenttypes.tests.ContentTypesTests.test_missing_model (self)
Ensures that displaying content types in admin (or anywhere) doesn't
break on leftover content type records in the DB for which no model
is defined anymore.
Definition at line 265 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertIsNone().
def django.contrib.contenttypes.tests.ContentTypesTests.test_shortcut_view (self)
Check that the shortcut view (used for the admin "view on site"
functionality) returns a complete URL regardless of whether the sites
framework is installed
Definition at line 208 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.contrib.sites.models.get_current_site(), and django.contrib.contenttypes.views.shortcut().
def django.contrib.contenttypes.tests.ContentTypesTests.test_shortcut_view_with_broken_get_absolute_url (self)
Check that the shortcut view does not catch an AttributeError raised
by the model's get_absolute_url method.
Refs #8997.
Definition at line 249 of file tests.py.
References django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.contenttypes.tests.ContentTypesTests.test_shortcut_view_without_get_absolute_url (self)
Check that the shortcut view (used for the admin "view on site"
functionality) returns 404 when get_absolute_url is not defined.
Definition at line 233 of file tests.py.
References django.utils.unittest.case.TestCase.assertRaises().
Member Data Documentation
django.contrib.contenttypes.tests.ContentTypesTests.old_Site_meta_installed
Definition at line 53 of file tests.py.
Referenced by django.contrib.sites.tests.SitesFrameworkTests.tearDown(), django.contrib.gis.tests.geoapp.test_feeds.GeoFeedTest.tearDown(), django.contrib.gis.tests.geoapp.test_sitemaps.GeoSitemapTest.tearDown(), django.contrib.sitemaps.tests.base.SitemapTestsBase.tearDown(), and django.contrib.contenttypes.tests.ContentTypesTests.tearDown().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/contenttypes/tests.py