Django: django.contrib.gis.tests.test_measure Namespace Reference
django.contrib.gis.tests.test_measure Namespace Reference
Classes
class AreaTest
class DistanceTest
Functions
def suite ()
def run
Detailed Description
Distance and Area objects to allow for sensible and convienient calculation
and conversions. Here are some tests.
Function Documentation
def django.contrib.gis.tests.test_measure.run (verbosity = 2)
Definition at line 286 of file test_measure.py.
References django.contrib.gis.tests.test_measure.suite().
Referenced by django.test.runner.DiscoverRunner.run_suite(), and django.core.servers.fastcgi.runfastcgi().
def django.contrib.gis.tests.test_measure.suite ()
Definition at line 280 of file test_measure.py.
Referenced by django.contrib.gis.tests.test_measure.run().