Django: django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest Class Reference
django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest Class Reference
Public Member Functions
def test02_select_related (self)
def test03_transform_related (self)
def test04a_related_extent_aggregate (self)
def test04b_related_union_aggregate (self)
def test05_select_related_fk_to_subclass (self)
def test06_f_expressions (self)
def test07_values (self)
def test08_defer_only (self)
def test09_pk_relations (self)
def test10_combine (self)
def test11_geoquery_pickle (self)
def test12a_count (self)
def test12b_count (self)
def test13c_count (self)
def test13_select_related_null_fk (self)
def test14_collect (self)
def test15_invalid_select_related (self)
def test16_annotated_date_queryset (self)
Detailed Description
Definition at line 17 of file tests.py.
Member Function Documentation
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test02_select_related (self)
Definition at line 19 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test03_transform_related (self)
Definition at line 40 of file tests.py.
References django.utils.unittest.case.TestCase.assertAlmostEqual(), and django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test04a_related_extent_aggregate (self)
Definition at line 65 of file tests.py.
References django.utils.unittest.case.TestCase.assertAlmostEqual().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test04b_related_union_aggregate (self)
Definition at line 84 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test05_select_related_fk_to_subclass (self)
Definition at line 118 of file tests.py.
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test06_f_expressions (self)
Definition at line 123 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test07_values (self)
Definition at line 171 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test08_defer_only (self)
Definition at line 188 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test09_pk_relations (self)
Definition at line 195 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test10_combine (self)
Definition at line 210 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test11_geoquery_pickle (self)
Definition at line 222 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test12a_count (self)
Definition at line 235 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test12b_count (self)
Definition at line 244 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test13_select_related_null_fk (self)
Definition at line 269 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test13c_count (self)
Definition at line 260 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test14_collect (self)
Definition at line 279 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test15_invalid_select_related (self)
Definition at line 296 of file tests.py.
def django.contrib.gis.tests.relatedapp.tests.RelatedGeoModelTest.test16_annotated_date_queryset (self)
Definition at line 304 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/tests/relatedapp/tests.py