Django: django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests Class Reference
django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests Class Reference
Public Member Functions
def test_view_flatpage (self)
def test_view_non_existent_flatpage (self)
def test_view_authenticated_flatpage (self)
def test_fallback_flatpage (self)
def test_fallback_non_existent_flatpage (self)
def test_fallback_authenticated_flatpage (self)
def test_fallback_flatpage_special_chars (self)
Static Public Attributes
list fixtures = ['sample_flatpages', 'example_site']
string urls = 'django.contrib.flatpages.tests.urls'
APPEND_SLASH = True,
string LOGIN_URL = '/accounts/login/'
tuple MIDDLEWARE_CLASSES
tuple TEMPLATE_DIRS
int SITE_ID = 1
Detailed Description
Definition at line 25 of file test_middleware.py.
Member Function Documentation
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.test_fallback_authenticated_flatpage (self)
Definition at line 63 of file test_middleware.py.
References django.test.testcases.SimpleTestCase.assertContains(), django.utils.unittest.case.TestCase.assertEqual(), and django.test.testcases.SimpleTestCase.assertRedirects().
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.test_fallback_flatpage (self)
Definition at line 51 of file test_middleware.py.
References django.test.testcases.SimpleTestCase.assertContains(), and django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.test_fallback_flatpage_special_chars (self)
Definition at line 73 of file test_middleware.py.
References django.test.testcases.SimpleTestCase.assertContains(), and django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.test_fallback_non_existent_flatpage (self)
Definition at line 57 of file test_middleware.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.test_view_authenticated_flatpage (self)
Definition at line 41 of file test_middleware.py.
References django.test.testcases.SimpleTestCase.assertContains(), django.utils.unittest.case.TestCase.assertEqual(), and django.test.testcases.SimpleTestCase.assertRedirects().
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.test_view_flatpage (self)
Definition at line 29 of file test_middleware.py.
References django.test.testcases.SimpleTestCase.assertContains(), and django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.test_view_non_existent_flatpage (self)
Definition at line 35 of file test_middleware.py.
References django.utils.unittest.case.TestCase.assertEqual().
Member Data Documentation
django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.APPEND_SLASH = True, static
Definition at line 90 of file test_middleware.py.
list django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.fixtures = ['sample_flatpages', 'example_site'] static
Definition at line 26 of file test_middleware.py.
string django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.LOGIN_URL = '/accounts/login/' static
Definition at line 91 of file test_middleware.py.
tuple django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.MIDDLEWARE_CLASSES static
Initial value:
 = (
         'django.middleware.common.CommonMiddleware',
         'django.contrib.sessions.middleware.SessionMiddleware',
         'django.middleware.csrf.CsrfViewMiddleware',
         'django.contrib.auth.middleware.AuthenticationMiddleware',
         'django.contrib.messages.middleware.MessageMiddleware',
         'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
     )
Definition at line 92 of file test_middleware.py.
int django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.SITE_ID = 1 static
Definition at line 103 of file test_middleware.py.
tuple django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.TEMPLATE_DIRS static
Initial value:
 = (
         os.path.join(os.path.dirname(__file__), 'templates'),
     )
Definition at line 100 of file test_middleware.py.
string django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareTests.urls = 'django.contrib.flatpages.tests.urls' static
Definition at line 27 of file test_middleware.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/flatpages/tests/test_middleware.py