Django: django.contrib.auth.tests.test_context_processors.PermWrapperTests.EQLimiterObject Class Reference
django.contrib.auth.tests.test_context_processors.PermWrapperTests.EQLimiterObject Class Reference
Public Member Functions
def __init__ (self)
def __eq__ (self, other)
Public Attributes
eq_calls
Detailed Description
This object makes sure __eq__ will not be called endlessly.
Definition at line 31 of file test_context_processors.py.
Constructor & Destructor Documentation
def django.contrib.auth.tests.test_context_processors.PermWrapperTests.EQLimiterObject.__init__ (self)
Definition at line 35 of file test_context_processors.py.
Member Function Documentation
def django.contrib.auth.tests.test_context_processors.PermWrapperTests.EQLimiterObject.__eq__ (self, other)
Definition at line 38 of file test_context_processors.py.
References django.contrib.auth.tests.test_context_processors.PermWrapperTests.EQLimiterObject.eq_calls.
Referenced by django.db.models.fields.files.FieldFile.__ne__(), django.test.html.Element.__ne__(), and django.db.models.base.Model.__ne__().
Member Data Documentation
django.contrib.auth.tests.test_context_processors.PermWrapperTests.EQLimiterObject.eq_calls
Definition at line 36 of file test_context_processors.py.
Referenced by django.contrib.auth.tests.test_context_processors.PermWrapperTests.EQLimiterObject.__eq__().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_context_processors.py