Django: django.utils.formats Namespace Reference
django.utils.formats Namespace Reference
Functions
def reset_format_cache ()
def iter_format_modules (lang)
def get_format_modules
def get_format
def date_format
def time_format
def number_format
def localize
def localize_input
def sanitize_separators (value)
Variables
dictionary _format_cache = {}
dictionary _format_modules_cache = {}
dictionary ISO_INPUT_FORMATS
tuple get_format_lazy = lazy(get_format, six.text_type, list, tuple)
Function Documentation
def django.utils.formats.date_format (value, format = None, use_l10n = None)
Formats a datetime.date or datetime.datetime object using a
localizable format
If use_l10n is provided and is not None, that will force the value to
be localized (or not), overriding the value of settings.USE_L10N.
Definition at line 111 of file formats.py.
References django.utils.formats.get_format().
Referenced by django.utils.formats.localize().
def django.utils.formats.get_format (format_type, lang = None, use_l10n = None)
For a specific format type, returns the format for the current
language (locale), defaults to the format in the settings.
format_type is the name of the format, e.g. 'DATE_FORMAT'
If use_l10n is provided and is not None, that will force the value to
be localized (or not), overriding the value of settings.USE_L10N.
Definition at line 72 of file formats.py.
References django.utils.encoding.force_str, django.utils.formats.get_format_modules(), and django.utils.translation.trans_null.get_language.
Referenced by django.utils.formats.date_format(), django.views.i18n.get_formats(), django.utils.formats.localize_input(), django.utils.formats.number_format(), django.forms.extras.widgets.SelectDateWidget.render(), django.utils.formats.sanitize_separators(), django.utils.formats.time_format(), and django.forms.extras.widgets.SelectDateWidget.value_from_datadict().
def django.utils.formats.get_format_modules (lang = None, reverse = False)
Returns a list of the format modules found
Definition at line 61 of file formats.py.
References django.utils.translation.trans_null.get_language, and django.utils.formats.iter_format_modules().
Referenced by django.utils.formats.get_format(), and django.views.i18n.get_formats().
def django.utils.formats.iter_format_modules (lang)
Does the heavy lifting of finding format modules.
Definition at line 41 of file formats.py.
References django.utils.translation.trans_null.check_for_language, django.utils.importlib.import_module(), and django.utils.translation.to_locale().
Referenced by django.utils.formats.get_format_modules().
def django.utils.formats.localize (value, use_l10n = None)
Checks if value is a localizable type (date, number...) and returns it
formatted as a string using current locale format.
If use_l10n is provided and is not None, that will force the value to
be localized (or not), overriding the value of settings.USE_L10N.
Definition at line 150 of file formats.py.
References django.utils.formats.date_format(), django.utils.safestring.mark_safe(), django.utils.formats.number_format(), and django.utils.formats.time_format().
def django.utils.formats.localize_input (value, default = None)
Checks if an input value is a localizable type and returns it
formatted with the appropriate formatting string of the current locale.
Definition at line 171 of file formats.py.
References django.utils.encoding.force_str, django.utils.formats.get_format(), and django.utils.formats.number_format().
def django.utils.formats.number_format (value, decimal_pos = None, use_l10n = None, force_grouping = False)
Formats a numeric value using localization settings
If use_l10n is provided and is not None, that will force the value to
be localized (or not), overriding the value of settings.USE_L10N.
Definition at line 130 of file formats.py.
References django.utils.formats.get_format(), and django.utils.translation.trans_null.get_language.
Referenced by django.contrib.humanize.templatetags.humanize.intcomma(), django.utils.formats.localize(), and django.utils.formats.localize_input().
def django.utils.formats.reset_format_cache ()
Clear any cached formats.
This method is provided primarily for testing purposes,
so that the effects of cached formats can be removed.
Definition at line 31 of file formats.py.
def django.utils.formats.sanitize_separators (value)
Sanitizes a value according to the current decimal and
thousand separator setting. Used with form field input.
Definition at line 191 of file formats.py.
References django.utils.formats.get_format(), and django.template.defaultfilters.join().
def django.utils.formats.time_format (value, format = None, use_l10n = None)
Formats a datetime.time object using a localizable format
If use_l10n is provided and is not None, that will force the value to
be localized (or not), overriding the value of settings.USE_L10N.
Definition at line 121 of file formats.py.
References django.utils.formats.get_format().
Referenced by django.utils.formats.localize().
Variable Documentation
dictionary django.utils.formats._format_cache = {}
Definition at line 17 of file formats.py.
dictionary django.utils.formats._format_modules_cache = {}
Definition at line 18 of file formats.py.
tuple django.utils.formats.get_format_lazy = lazy(get_format, six.text_type, list, tuple)
Definition at line 109 of file formats.py.
dictionary django.utils.formats.ISO_INPUT_FORMATS
Initial value:
 = {
     'DATE_INPUT_FORMATS': ('%Y-%m-%d',),
     'TIME_INPUT_FORMATS': ('%H:%M:%S', '%H:%M:%S.%f', '%H:%M'),
     'DATETIME_INPUT_FORMATS': (
         '%Y-%m-%d %H:%M:%S',
         '%Y-%m-%d %H:%M:%S.%f',
         '%Y-%m-%d %H:%M',
         '%Y-%m-%d'
     ),
 }
Definition at line 20 of file formats.py.