Django: django.contrib.auth.tests.test_auth_backends.CountingMD5PasswordHasher Class Reference
django.contrib.auth.tests.test_auth_backends.CountingMD5PasswordHasher Class Reference
Public Member Functions
def encode (self, args, kwargs)
Public Member Functions inherited from django.contrib.auth.hashers.MD5PasswordHasher
def encode (self, password, salt)
def verify (self, password, encoded)
def safe_summary (self, encoded)
Public Member Functions inherited from django.contrib.auth.hashers.BasePasswordHasher
def salt (self)
def verify (self, password, encoded)
def encode (self, password, salt)
def safe_summary (self, encoded)
def must_update (self, encoded)
Static Public Attributes
int calls = 0
Static Public Attributes inherited from django.contrib.auth.hashers.MD5PasswordHasher
string algorithm = "md5"
Static Public Attributes inherited from django.contrib.auth.hashers.BasePasswordHasher
algorithm = None
library = None
Detailed Description
Hasher that counts how many times it computes a hash.
Definition at line 18 of file test_auth_backends.py.
Member Function Documentation
def django.contrib.auth.tests.test_auth_backends.CountingMD5PasswordHasher.encode (self, args, kwargs)
Definition at line 23 of file test_auth_backends.py.
Referenced by django.contrib.sessions.models.SessionManager.save(), django.contrib.sessions.backends.db.SessionStore.save(), and django.contrib.sessions.backends.file.SessionStore.save().
Member Data Documentation
int django.contrib.auth.tests.test_auth_backends.CountingMD5PasswordHasher.calls = 0 static
Definition at line 21 of file test_auth_backends.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_auth_backends.py