Django: django.core.context_processors Namespace Reference
django.core.context_processors Namespace Reference
Functions
def csrf (request)
def debug (request)
def i18n (request)
def tz (request)
def static (request)
def media (request)
def request (request)
Detailed Description
A set of request processors that return dictionaries to be merged into a
template context. Each function takes the request object as its only parameter
and returns a dictionary to add to the context.
These are referenced from the setting TEMPLATE_CONTEXT_PROCESSORS and used by
RequestContext.
Function Documentation
def django.core.context_processors.csrf (request)
Context processor that provides a CSRF token, or the string 'NOTPROVIDED' if
it has not been provided by either a view decorator or the middleware
Definition at line 18 of file context_processors.py.
References django.middleware.csrf.get_token(), django.utils.functional.lazy(), and django.utils.encoding.smart_text().
def django.core.context_processors.debug (request)
Definition at line 36 of file context_processors.py.
def django.core.context_processors.i18n (request)
Definition at line 45 of file context_processors.py.
def django.core.context_processors.media (request)
Adds media-related context variables to the context.
Definition at line 67 of file context_processors.py.
def django.core.context_processors.request (request)
Definition at line 74 of file context_processors.py.
def django.core.context_processors.static (request)
Adds static-related context variables to the context.
Definition at line 60 of file context_processors.py.
def django.core.context_processors.tz (request)
Definition at line 55 of file context_processors.py.