Django: django.utils.safestring.SafeBytes Class Reference
django.utils.safestring.SafeBytes Class Reference
Public Member Functions
def __add__ (self, rhs)
Static Public Attributes
tuple decode = curry(_proxy_method, method=bytes.decode)
Detailed Description
A bytes subclass that has been specifically marked as "safe" (requires no
further escaping) for HTML output purposes.
Definition at line 35 of file safestring.py.
Member Function Documentation
def django.utils.safestring.SafeBytes.__add__ (self, rhs)
Concatenating a safe byte string with another safe byte string or safe
unicode string is safe. Otherwise, the result is no longer safe.
Definition at line 40 of file safestring.py.
Member Data Documentation
tuple django.utils.safestring.SafeBytes.decode = curry(_proxy_method, method=bytes.decode) static
Definition at line 65 of file safestring.py.
Referenced by django.contrib.sessions.backends.db.SessionStore.load(), django.contrib.sessions.backends.cached_db.SessionStore.load(), and django.contrib.sessions.backends.file.SessionStore.load().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/utils/safestring.py