Django: django.template.debug.DebugParser Class Reference
django.template.debug.DebugParser Class Reference
Public Member Functions
def __init__ (self, lexer)
def enter_command (self, command, token)
def exit_command (self)
def error (self, token, msg)
def source_error (self, source, msg)
def create_nodelist (self)
def create_variable_node (self, contents)
def extend_nodelist (self, nodelist, node, token)
def unclosed_block_tag (self, parse_until)
def compile_filter_error (self, token, e)
def compile_function_error (self, token, e)
Public Member Functions inherited from django.template.base.Parser
def __init__ (self, tokens)
def parse
def skip_past (self, endtag)
def create_variable_node (self, filter_expression)
def create_nodelist (self)
def extend_nodelist (self, nodelist, node, token)
def enter_command (self, command, token)
def exit_command (self)
def error (self, token, msg)
def empty_variable (self, token)
def empty_block_tag (self, token)
def invalid_block_tag
def unclosed_block_tag (self, parse_until)
def compile_filter_error (self, token, e)
def compile_function_error (self, token, e)
def next_token (self)
def prepend_token (self, token)
def delete_first_token (self)
def add_library (self, lib)
def compile_filter (self, token)
def find_filter (self, filter_name)
Public Attributes
command_stack
Public Attributes inherited from django.template.base.Parser
tokens
tags
filters
Detailed Description
Definition at line 33 of file debug.py.
Constructor & Destructor Documentation
def django.template.debug.DebugParser.__init__ (self, lexer)
Definition at line 34 of file debug.py.
Member Function Documentation
def django.template.debug.DebugParser.compile_filter_error (self, token, e)
Definition at line 67 of file debug.py.
def django.template.debug.DebugParser.compile_function_error (self, token, e)
Definition at line 71 of file debug.py.
def django.template.debug.DebugParser.create_nodelist (self)
Definition at line 52 of file debug.py.
def django.template.debug.DebugParser.create_variable_node (self, contents)
Definition at line 55 of file debug.py.
def django.template.debug.DebugParser.enter_command (self, command, token)
Definition at line 38 of file debug.py.
def django.template.debug.DebugParser.error (self, token, msg)
Definition at line 44 of file debug.py.
References django.template.debug.DebugParser.source_error().
Referenced by django.test.html.Parser.handle_endtag(), and django.utils.html_parser.HTMLParser.parse_endtag().
def django.template.debug.DebugParser.exit_command (self)
Definition at line 41 of file debug.py.
def django.template.debug.DebugParser.extend_nodelist (self, nodelist, node, token)
Definition at line 58 of file debug.py.
def django.template.debug.DebugParser.source_error (self, source, msg)
Definition at line 47 of file debug.py.
Referenced by django.template.debug.DebugParser.error(), and django.template.debug.DebugParser.unclosed_block_tag().
def django.template.debug.DebugParser.unclosed_block_tag (self, parse_until)
Definition at line 62 of file debug.py.
References django.template.defaultfilters.join(), and django.template.debug.DebugParser.source_error().
Member Data Documentation
django.template.debug.DebugParser.command_stack
Definition at line 36 of file debug.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/template/debug.py