Django: django.contrib.auth.backends.ModelBackend Class Reference
django.contrib.auth.backends.ModelBackend Class Reference
Public Member Functions
def authenticate (self, username=None, password=None, kwargs)
def get_group_permissions
def get_all_permissions
def has_perm
def has_module_perms (self, user_obj, app_label)
def get_user (self, user_id)
Detailed Description
Authenticates against settings.AUTH_USER_MODEL.
Definition at line 6 of file backends.py.
Member Function Documentation
def django.contrib.auth.backends.ModelBackend.authenticate (self, username = None, password = None, kwargs)
Definition at line 11 of file backends.py.
References django.contrib.auth.get_user_model().
def django.contrib.auth.backends.ModelBackend.get_all_permissions (self, user_obj, obj = None)
Definition at line 42 of file backends.py.
References django.contrib.auth.backends.ModelBackend.get_group_permissions().
Referenced by django.contrib.auth.backends.ModelBackend.has_module_perms(), and django.contrib.auth.backends.ModelBackend.has_perm().
def django.contrib.auth.backends.ModelBackend.get_group_permissions (self, user_obj, obj = None)
Returns a set of permission strings that this user has through his/her
groups.
Definition at line 24 of file backends.py.
References django.contrib.auth.get_user_model().
Referenced by django.contrib.auth.backends.ModelBackend.get_all_permissions().
def django.contrib.auth.backends.ModelBackend.get_user (self, user_id)
Definition at line 66 of file backends.py.
References django.contrib.auth.get_user_model().
def django.contrib.auth.backends.ModelBackend.has_module_perms (self, user_obj, app_label)
Returns True if user_obj has any permissions in the given app_label.
Definition at line 55 of file backends.py.
References django.contrib.auth.backends.ModelBackend.get_all_permissions().
def django.contrib.auth.backends.ModelBackend.has_perm (self, user_obj, perm, obj = None)
Definition at line 50 of file backends.py.
References django.contrib.auth.backends.ModelBackend.get_all_permissions().
Referenced by django.contrib.auth.models.PermissionsMixin.has_perms(), and django.contrib.auth.models.AnonymousUser.has_perms().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/backends.py