Django: django.contrib.auth.admin.UserAdmin Class Reference
django.contrib.auth.admin.UserAdmin Class Reference
Public Member Functions
def get_fieldsets
def get_form (self, request, obj=None, kwargs)
def get_urls (self)
def lookup_allowed (self, lookup, value)
def add_view
def user_change_password
def response_add
Public Member Functions inherited from django.contrib.admin.options.ModelAdmin
def __init__ (self, model, admin_site)
def get_inline_instances
def get_urls (self)
def urls (self)
def media (self)
def get_model_perms (self, request)
def get_fieldsets
def get_form (self, request, obj=None, kwargs)
def get_changelist (self, request, kwargs)
def get_object (self, request, object_id)
def get_changelist_form (self, request, kwargs)
def get_changelist_formset (self, request, kwargs)
def get_formsets
def get_paginator
def log_addition (self, request, object)
def log_change (self, request, object, message)
def log_deletion (self, request, object, object_repr)
def action_checkbox (self, obj)
def get_actions (self, request)
def get_action_choices
def get_action (self, action)
def get_list_display (self, request)
def get_list_display_links (self, request, list_display)
def get_list_filter (self, request)
def get_search_results (self, request, queryset, search_term)
def get_preserved_filters (self, request)
def construct_change_message (self, request, form, formsets)
def message_user
def save_form (self, request, form, change)
def save_model (self, request, obj, form, change)
def delete_model (self, request, obj)
def save_formset (self, request, form, formset, change)
def save_related (self, request, form, formsets, change)
def render_change_form
def response_add
def response_change (self, request, obj)
def response_post_save_add (self, request, obj)
def response_post_save_change (self, request, obj)
def response_action (self, request, queryset)
def add_view
def change_view
def changelist_view
def delete_view
def history_view
Public Member Functions inherited from django.contrib.admin.options.BaseModelAdmin
def validate (cls, model)
def __init__ (self)
def formfield_for_dbfield (self, db_field, kwargs)
def formfield_for_choice_field (self, db_field, request=None, kwargs)
def get_field_queryset (self, db, db_field, request)
def formfield_for_foreignkey (self, db_field, request=None, kwargs)
def formfield_for_manytomany (self, db_field, request=None, kwargs)
def get_ordering (self, request)
def get_readonly_fields
def get_prepopulated_fields
def get_queryset (self, request)
def lookup_allowed (self, lookup, value)
def to_field_allowed (self, request, to_field)
def has_add_permission (self, request)
def has_change_permission
def has_delete_permission
Public Member Functions inherited from django.forms.widgets.MediaDefiningClass
def __new__ (cls, name, bases, attrs)
Public Member Functions inherited from django.utils.deprecation.RenameMethodsBase
def __new__ (cls, name, bases, attrs)
Static Public Attributes
string add_form_template = 'admin/auth/user/add_form.html'
change_user_password_template = None
tuple fieldsets
tuple add_fieldsets
form = UserChangeForm
add_form = UserCreationForm
change_password_form = AdminPasswordChangeForm
tuple list_display = ('username', 'email', 'first_name', 'last_name', 'is_staff')
tuple list_filter = ('is_staff', 'is_superuser', 'is_active', 'groups')
tuple search_fields = ('username', 'first_name', 'last_name', 'email')
tuple ordering = ('username',)
tuple filter_horizontal = ('groups', 'user_permissions',)
Static Public Attributes inherited from django.contrib.admin.options.ModelAdmin
tuple list_display = ('__str__',)
tuple list_display_links = ()
tuple list_filter = ()
list_select_related = False
int list_per_page = 100
int list_max_show_all = 200
tuple list_editable = ()
tuple search_fields = ()
date_hierarchy = None
save_as = False
save_on_top = False
paginator = Paginator
preserve_filters = True
list inlines = []
add_form_template = None
change_form_template = None
change_list_template = None
delete_confirmation_template = None
delete_selected_confirmation_template = None
object_history_template = None
list actions = []
action_form = helpers.ActionForm
actions_on_top = True
actions_on_bottom = False
actions_selection_counter = True
validator_class = validation.ModelAdminValidator
Static Public Attributes inherited from django.contrib.admin.options.BaseModelAdmin
tuple raw_id_fields = ()
fields = None
exclude = None
fieldsets = None
form = forms.ModelForm
tuple filter_vertical = ()
tuple filter_horizontal = ()
dictionary radio_fields = {}
dictionary prepopulated_fields = {}
dictionary formfield_overrides = {}
tuple readonly_fields = ()
ordering = None
validator_class = validation.BaseValidator
Static Public Attributes inherited from django.contrib.admin.options.RenameBaseModelAdminMethods
tuple renamed_methods
Static Public Attributes inherited from django.utils.deprecation.RenameMethodsBase
tuple renamed_methods = ()
Additional Inherited Members
Public Attributes inherited from django.contrib.admin.options.ModelAdmin
model
opts
admin_site
Public Attributes inherited from django.contrib.admin.options.BaseModelAdmin
formfield_overrides
Properties inherited from django.contrib.admin.options.ModelAdmin
urls = property(urls)
Properties inherited from django.contrib.admin.options.BaseModelAdmin
declared_fieldsets = property(_declared_fieldsets)
Detailed Description
Definition at line 38 of file admin.py.
Member Function Documentation
def django.contrib.auth.admin.UserAdmin.add_view (self, request, form_url = '', extra_context = None)
Definition at line 97 of file admin.py.
References django.contrib.admin.options.BaseModelAdmin.has_add_permission(), and django.contrib.admin.options.BaseModelAdmin.has_change_permission().
def django.contrib.auth.admin.UserAdmin.get_fieldsets (self, request, obj = None)
Definition at line 63 of file admin.py.
References django.contrib.auth.admin.UserAdmin.add_fieldsets.
def django.contrib.auth.admin.UserAdmin.get_form (self, request, obj = None, kwargs)
Use special form during user creation
Definition at line 68 of file admin.py.
References django.contrib.auth.admin.UserAdmin.add_fieldsets, and django.contrib.auth.admin.UserAdmin.add_form.
Referenced by django.views.generic.edit.ProcessFormView.get(), django.contrib.formtools.wizard.views.WizardView.get(), django.contrib.formtools.wizard.views.NamedUrlWizardView.get(), django.contrib.formtools.wizard.views.WizardView.get_all_cleaned_data(), django.contrib.formtools.wizard.views.WizardView.get_cleaned_data_for_step(), django.views.generic.edit.ProcessFormView.post(), django.contrib.formtools.wizard.views.WizardView.post(), django.contrib.comments.templatetags.comments.CommentFormNode.render(), django.contrib.comments.templatetags.comments.RenderCommentFormNode.render(), django.contrib.formtools.wizard.views.WizardView.render(), django.contrib.formtools.wizard.views.WizardView.render_done(), django.contrib.formtools.wizard.views.WizardView.render_goto_step(), and django.contrib.formtools.wizard.views.WizardView.render_next_step().
def django.contrib.auth.admin.UserAdmin.get_urls (self)
Definition at line 81 of file admin.py.
References django.conf.urls.patterns(), and django.contrib.auth.admin.UserAdmin.user_change_password().
def django.contrib.auth.admin.UserAdmin.lookup_allowed (self, lookup, value)
Definition at line 88 of file admin.py.
def django.contrib.auth.admin.UserAdmin.response_add (self, request, obj, post_url_continue = None)
Determines the HttpResponse for the add_view stage. It mostly defers to
its superclass implementation but is customized because the User model
has a slightly different workflow.
Definition at line 166 of file admin.py.
def django.contrib.auth.admin.UserAdmin.user_change_password (self, request, id, form_url = '')
Definition at line 126 of file admin.py.
References django.contrib.auth.admin.UserAdmin.change_password_form, django.contrib.auth.admin.UserAdmin.change_user_password_template, django.contrib.admin.options.ModelAdmin.construct_change_message(), django.utils.html.escape, django.shortcuts.get_object_or_404(), django.contrib.admin.options.BaseModelAdmin.get_queryset(), django.contrib.admin.options.BaseModelAdmin.has_change_permission(), django.contrib.admin.options.ModelAdmin.log_change(), and django.utils.translation.trans_real.ugettext.
Referenced by django.contrib.auth.admin.UserAdmin.get_urls().
Member Data Documentation
tuple django.contrib.auth.admin.UserAdmin.add_fieldsets static
Initial value:
 = (
         (None, {
             'classes': ('wide',),
             'fields': ('username', 'password1', 'password2')}
         ),
     )
Definition at line 48 of file admin.py.
Referenced by django.contrib.auth.admin.UserAdmin.get_fieldsets(), and django.contrib.auth.admin.UserAdmin.get_form().
django.contrib.auth.admin.UserAdmin.add_form = UserCreationForm static
Definition at line 55 of file admin.py.
Referenced by django.contrib.auth.admin.UserAdmin.get_form().
string django.contrib.auth.admin.UserAdmin.add_form_template = 'admin/auth/user/add_form.html' static
Definition at line 39 of file admin.py.
django.contrib.auth.admin.UserAdmin.change_password_form = AdminPasswordChangeForm static
Definition at line 56 of file admin.py.
Referenced by django.contrib.auth.admin.UserAdmin.user_change_password().
django.contrib.auth.admin.UserAdmin.change_user_password_template = None static
Definition at line 40 of file admin.py.
Referenced by django.contrib.auth.admin.UserAdmin.user_change_password().
tuple django.contrib.auth.admin.UserAdmin.fieldsets static
Initial value:
 = (
         (None, {'fields': ('username', 'password')}),
         (_('Personal info'), {'fields': ('first_name', 'last_name', 'email')}),
         (_('Permissions'), {'fields': ('is_active', 'is_staff', 'is_superuser',
                                        'groups', 'user_permissions')}),
         (_('Important dates'), {'fields': ('last_login', 'date_joined')}),
     )
Definition at line 41 of file admin.py.
tuple django.contrib.auth.admin.UserAdmin.filter_horizontal = ('groups', 'user_permissions',) static
Definition at line 61 of file admin.py.
django.contrib.auth.admin.UserAdmin.form = UserChangeForm static
Definition at line 54 of file admin.py.
Referenced by django.contrib.admin.helpers.AdminForm.__iter__(), django.contrib.admin.helpers.InlineAdminForm.__iter__(), django.forms.forms.BoundField.css_classes(), django.contrib.admin.helpers.InlineAdminForm.deletion_field(), django.forms.formsets.BaseFormSet.empty_form(), django.contrib.admin.helpers.AdminForm.first_field(), django.contrib.admin.helpers.InlineAdminForm.fk_field(), django.forms.formsets.BaseFormSet.forms(), django.contrib.admin.helpers.InlineAdminForm.ordering_field(), django.contrib.admin.helpers.InlineAdminForm.pk_field(), django.contrib.formtools.preview.FormPreview.post_post(), django.contrib.formtools.preview.FormPreview.preview_get(), and django.contrib.formtools.preview.FormPreview.preview_post().
tuple django.contrib.auth.admin.UserAdmin.list_display = ('username', 'email', 'first_name', 'last_name', 'is_staff') static
Definition at line 57 of file admin.py.
tuple django.contrib.auth.admin.UserAdmin.list_filter = ('is_staff', 'is_superuser', 'is_active', 'groups') static
Definition at line 58 of file admin.py.
Referenced by django.contrib.admin.options.BaseModelAdmin.lookup_allowed().
tuple django.contrib.auth.admin.UserAdmin.ordering = ('username',) static
Definition at line 60 of file admin.py.
Referenced by django.db.models.options.Options.module_name().
tuple django.contrib.auth.admin.UserAdmin.search_fields = ('username', 'first_name', 'last_name', 'email') static
Definition at line 59 of file admin.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/admin.py