Django: django.views.generic.dates.BaseMonthArchiveView Class Reference
django.views.generic.dates.BaseMonthArchiveView Class Reference
Public Member Functions
def get_dated_items (self)
Public Member Functions inherited from django.views.generic.dates.YearMixin
def get_year_format (self)
def get_year (self)
def get_next_year (self, date)
def get_previous_year (self, date)
Public Member Functions inherited from django.views.generic.dates.MonthMixin
def get_month_format (self)
def get_month (self)
def get_next_month (self, date)
def get_previous_month (self, date)
Public Member Functions inherited from django.views.generic.dates.BaseDateListView
def get (self, request, args, kwargs)
def get_dated_items (self)
def get_dated_queryset (self, ordering=None, lookup)
def get_date_list_period (self)
def get_date_list
Public Member Functions inherited from django.views.generic.list.MultipleObjectMixin
def get_queryset (self)
def paginate_queryset (self, queryset, page_size)
def get_paginate_by (self, queryset)
def get_paginator (self, queryset, per_page, orphans=0, allow_empty_first_page=True, kwargs)
def get_paginate_orphans (self)
def get_allow_empty (self)
def get_context_object_name (self, object_list)
def get_context_data (self, kwargs)
Public Member Functions inherited from django.views.generic.base.ContextMixin
def get_context_data (self, kwargs)
Public Member Functions inherited from django.views.generic.dates.DateMixin
def get_date_field (self)
def get_allow_future (self)
def uses_datetime_field (self)
Public Member Functions inherited from django.views.generic.base.View
def __init__ (self, kwargs)
def as_view (cls, initkwargs)
def dispatch (self, request, args, kwargs)
def http_method_not_allowed (self, request, args, kwargs)
def options (self, request, args, kwargs)
Static Public Attributes
string date_list_period = 'day'
Static Public Attributes inherited from django.views.generic.dates.YearMixin
string year_format = '%Y'
year = None
Static Public Attributes inherited from django.views.generic.dates.MonthMixin
string month_format = '%b'
month = None
Static Public Attributes inherited from django.views.generic.dates.BaseDateListView
allow_empty = False
string date_list_period = 'year'
Static Public Attributes inherited from django.views.generic.list.MultipleObjectMixin
allow_empty = True
queryset = None
model = None
paginate_by = None
int paginate_orphans = 0
context_object_name = None
paginator_class = Paginator
string page_kwarg = 'page'
Static Public Attributes inherited from django.views.generic.dates.DateMixin
date_field = None
allow_future = False
Static Public Attributes inherited from django.views.generic.base.View
list http_method_names = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace']
Additional Inherited Members
Public Attributes inherited from django.views.generic.base.View
head
request
args
kwargs
Detailed Description
List of objects published in a given month.
Definition at line 482 of file dates.py.
Member Function Documentation
def django.views.generic.dates.BaseMonthArchiveView.get_dated_items (self)
Return (date_list, items, extra_context) for this request.
Definition at line 488 of file dates.py.
References django.views.generic.dates.MonthMixin._get_next_month(), django.views.generic.dates.DateMixin._make_date_lookup_arg(), django.views.generic.dates.DateMixin.get_date_field(), django.views.generic.dates.BaseDateListView.get_date_list(), django.views.generic.dates.BaseDateListView.get_dated_queryset(), django.views.generic.dates.MonthMixin.get_month(), django.views.generic.dates.MonthMixin.get_month_format(), django.views.generic.dates.MonthMixin.get_next_month(), django.views.generic.dates.MonthMixin.get_previous_month(), django.views.generic.dates.YearMixin.get_year(), and django.views.generic.dates.YearMixin.get_year_format().
Member Data Documentation
string django.views.generic.dates.BaseMonthArchiveView.date_list_period = 'day' static
Definition at line 486 of file dates.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/views/generic/dates.py