Django: django.utils.archive.BaseArchive Class Reference
django.utils.archive.BaseArchive Class Reference
Public Member Functions
def split_leading_dir (self, path)
def has_leading_dir (self, paths)
def extract (self)
def list (self)
Detailed Description
Base Archive class.  Implementations should inherit this class.
Definition at line 97 of file archive.py.
Member Function Documentation
def django.utils.archive.BaseArchive.extract (self)
Definition at line 128 of file archive.py.
def django.utils.archive.BaseArchive.has_leading_dir (self, paths)
Returns true if all the paths have the same leading path name
(i.e., everything is in one subdirectory in an archive)
Definition at line 112 of file archive.py.
References django.utils.archive.BaseArchive.split_leading_dir().
Referenced by django.utils.archive.TarArchive.extract(), and django.utils.archive.ZipArchive.extract().
def django.utils.archive.BaseArchive.list (self)
Definition at line 131 of file archive.py.
def django.utils.archive.BaseArchive.split_leading_dir (self, path)
Definition at line 101 of file archive.py.
Referenced by django.utils.archive.TarArchive.extract(), django.utils.archive.ZipArchive.extract(), and django.utils.archive.BaseArchive.has_leading_dir().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/utils/archive.py