Django: django.db.backends.mysql.creation.DatabaseCreation Class Reference
django.db.backends.mysql.creation.DatabaseCreation Class Reference
Public Member Functions
def sql_table_creation_suffix (self)
def sql_for_inline_foreign_key_references (self, model, field, known_models, style)
def sql_destroy_indexes_for_fields (self, model, fields, style)
Public Member Functions inherited from django.db.backends.creation.BaseDatabaseCreation
def __init__ (self, connection)
def sql_create_model
def sql_for_inline_foreign_key_references (self, model, field, known_models, style)
def sql_for_pending_references (self, model, style, pending_references)
def sql_indexes_for_model (self, model, style)
def sql_indexes_for_field (self, model, f, style)
def sql_indexes_for_fields (self, model, fields, style)
def sql_destroy_model (self, model, references_to_delete, style)
def sql_remove_table_constraints (self, model, references_to_delete, style)
def sql_destroy_indexes_for_model (self, model, style)
def sql_destroy_indexes_for_field (self, model, f, style)
def sql_destroy_indexes_for_fields (self, model, fields, style)
def create_test_db
def destroy_test_db
def set_autocommit (self)
def sql_table_creation_suffix (self)
def test_db_signature (self)
Static Public Attributes
dictionary data_types
Static Public Attributes inherited from django.db.backends.creation.BaseDatabaseCreation
dictionary data_types = {}
Additional Inherited Members
Public Attributes inherited from django.db.backends.creation.BaseDatabaseCreation
connection
Detailed Description
Definition at line 3 of file creation.py.
Member Function Documentation
def django.db.backends.mysql.creation.DatabaseCreation.sql_destroy_indexes_for_fields (self, model, fields, style)
Definition at line 46 of file creation.py.
References django.db.backends.creation.BaseDatabaseCreation._digest(), and django.db.backends.util.truncate_name().
def django.db.backends.mysql.creation.DatabaseCreation.sql_for_inline_foreign_key_references (self, model, field, known_models, style)
Definition at line 42 of file creation.py.
def django.db.backends.mysql.creation.DatabaseCreation.sql_table_creation_suffix (self)
Definition at line 34 of file creation.py.
References django.template.defaultfilters.join().
Member Data Documentation
dictionary django.db.backends.mysql.creation.DatabaseCreation.data_types static
Initial value:
 = {
         'AutoField':         'integer AUTO_INCREMENT',
         'BinaryField':       'longblob',
         'BooleanField':      'bool',
         'CharField':         'varchar(%(max_length)s)',
         'CommaSeparatedIntegerField': 'varchar(%(max_length)s)',
         'DateField':         'date',
         'DateTimeField':     'datetime',
         'DecimalField':      'numeric(%(max_digits)s, %(decimal_places)s)',
         'FileField':         'varchar(%(max_length)s)',
         'FilePathField':     'varchar(%(max_length)s)',
         'FloatField':        'double precision',
         'IntegerField':      'integer',
         'BigIntegerField':   'bigint',
         'IPAddressField':    'char(15)',
         'GenericIPAddressField': 'char(39)',
         'NullBooleanField':  'bool',
         'OneToOneField':     'integer',
         'PositiveIntegerField': 'integer UNSIGNED',
         'PositiveSmallIntegerField': 'smallint UNSIGNED',
         'SlugField':         'varchar(%(max_length)s)',
         'SmallIntegerField': 'smallint',
         'TextField':         'longtext',
         'TimeField':         'time',
     }
Definition at line 8 of file creation.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/db/backends/mysql/creation.py