Django: django.dispatch.dispatcher Namespace Reference
django.dispatch.dispatcher Namespace Reference
Classes
class Signal
Functions
def receiver (signal, kwargs)
Variables
tuple WEAKREF_TYPES = (weakref.ReferenceType, saferef.BoundMethodWeakref)
tuple NONE_ID = _make_id(None)
tuple NO_RECEIVERS = object()
Function Documentation
def django.dispatch.dispatcher.receiver (signal, kwargs)
A decorator for connecting receivers to signals. Used by passing in the
signal (or list of signals) and keyword arguments to connect::
    @receiver(post_save, sender=MyModel)
    def signal_receiver(sender, **kwargs):
        ...
    @receiver([post_save, post_delete], sender=MyModel)
    def signals_receiver(sender, **kwargs):
        ...
Definition at line 285 of file dispatcher.py.
Referenced by django.test.signals.clear_context_processors_cache(), django.test.signals.clear_serializers_cache(), django.test.signals.clear_template_loaders_cache(), django.test.signals.language_changed(), django.dispatch.dispatcher.Signal.send(), django.dispatch.dispatcher.Signal.send_robust(), and django.test.signals.update_connections_time_zone().
Variable Documentation
tuple django.dispatch.dispatcher.NO_RECEIVERS = object()
Definition at line 18 of file dispatcher.py.
tuple django.dispatch.dispatcher.NONE_ID = _make_id(None)
Definition at line 15 of file dispatcher.py.
tuple django.dispatch.dispatcher.WEAKREF_TYPES = (weakref.ReferenceType, saferef.BoundMethodWeakref)
Definition at line 8 of file dispatcher.py.