Django: django.contrib.messages.tests.base.override_settings_tags Class Reference
django.contrib.messages.tests.base.override_settings_tags Class Reference
Public Member Functions
def enable (self)
def disable (self)
Public Member Functions inherited from django.test.utils.override_settings
def __init__ (self, kwargs)
def __enter__ (self)
def __exit__ (self, exc_type, exc_value, traceback)
def __call__ (self, test_func)
def enable (self)
def disable (self)
Public Attributes
old_level_tags
Public Attributes inherited from django.test.utils.override_settings
options
wrapped
Detailed Description
Definition at line 32 of file base.py.
Member Function Documentation
def django.contrib.messages.tests.base.override_settings_tags.disable (self)
Definition at line 40 of file base.py.
References django.contrib.messages.tests.base.override_settings_tags.old_level_tags.
Referenced by django.test.utils.override_settings.__call__(), and django.test.utils.override_settings.__exit__().
def django.contrib.messages.tests.base.override_settings_tags.enable (self)
Definition at line 33 of file base.py.
Referenced by django.test.utils.override_settings.__call__(), and django.test.utils.override_settings.__enter__().
Member Data Documentation
django.contrib.messages.tests.base.override_settings_tags.old_level_tags
Definition at line 38 of file base.py.
Referenced by django.contrib.messages.tests.base.override_settings_tags.disable().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/messages/tests/base.py