Django: django.contrib.gis.db.backends.mysql.compiler.GeoSQLCompiler Class Reference
django.contrib.gis.db.backends.mysql.compiler.GeoSQLCompiler Class Reference
Public Member Functions
def resolve_columns
Detailed Description
Definition at line 6 of file compiler.py.
Member Function Documentation
def django.contrib.gis.db.backends.mysql.compiler.GeoSQLCompiler.resolve_columns (self, row, fields = ())
Integrate the cases handled both by the base GeoSQLCompiler and the
main MySQL compiler (converting 0/1 to True/False for boolean fields).
Refs #15169.
Definition at line 7 of file compiler.py.
Referenced by django.contrib.gis.db.models.sql.compiler.SQLDateCompiler.results_iter(), django.contrib.gis.db.models.sql.compiler.SQLDateTimeCompiler.results_iter(), django.db.models.sql.compiler.SQLCompiler.results_iter(), django.db.models.sql.compiler.SQLDateCompiler.results_iter(), and django.db.models.sql.compiler.SQLDateTimeCompiler.results_iter().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/db/backends/mysql/compiler.py