Django: django.contrib.admin.tests.AdminSeleniumWebDriverTestCase Class Reference
django.contrib.admin.tests.AdminSeleniumWebDriverTestCase Class Reference
Public Member Functions
def setUpClass (cls)
def wait_until
def wait_loaded_tag
def wait_page_loaded (self)
def admin_login
def get_css_value (self, selector, attribute)
def get_select_option (self, selector, value)
def assertSelectOptions (self, selector, values)
def has_css_class (self, selector, klass)
Static Public Attributes
list available_apps
string webdriver_class = 'selenium.webdriver.firefox.webdriver.WebDriver'
Detailed Description
Definition at line 9 of file tests.py.
Member Function Documentation
def django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.admin_login (self, username, password, login_url = '/admin/')
Helper function to log into the admin.
Definition at line 72 of file tests.py.
References django.test.testcases.LiveServerTestCase.live_server_url(), and django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.wait_page_loaded().
def django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.assertSelectOptions (self, selector, values)
Asserts that the <SELECT> widget identified by `selector` has the
options with the given `values`.
Definition at line 107 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.get_css_value (self, selector, attribute)
Helper function that returns the value for the CSS attribute of an
DOM element specified by the given selector. Uses the jQuery that ships
with Django.
Definition at line 86 of file tests.py.
def django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.get_select_option (self, selector, value)
Returns the <OPTION> with the value `value` inside the <SELECT> widget
identified by the CSS selector `selector`.
Definition at line 95 of file tests.py.
def django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.has_css_class (self, selector, klass)
Returns True if the element identified by `selector` has the CSS class
`klass`.
Definition at line 118 of file tests.py.
References find.
def django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.setUpClass (cls)
Definition at line 21 of file tests.py.
References django.utils.module_loading.import_by_path().
def django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.wait_loaded_tag (self, tag_name, timeout = 10)
Helper function that blocks until the element with the given tag name
is found on the page.
Definition at line 48 of file tests.py.
References django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.wait_until().
Referenced by django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.wait_page_loaded().
def django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.wait_page_loaded (self)
Block until page has started to load.
Definition at line 58 of file tests.py.
References django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.wait_loaded_tag().
Referenced by django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.admin_login().
def django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.wait_until (self, callback, timeout = 10)
Helper function that blocks the execution of the tests until the
specified callback returns a value that is not falsy. This function can
be called, for example, after clicking a link or submitting a form.
See the other public methods that call this function for more details.
Definition at line 38 of file tests.py.
Referenced by django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.wait_loaded_tag().
Member Data Documentation
list django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.available_apps static
Initial value:
 = [
         'django.contrib.admin',
         'django.contrib.auth',
         'django.contrib.contenttypes',
         'django.contrib.sessions',
         'django.contrib.sites',
     ]
Definition at line 11 of file tests.py.
Referenced by django.db.models.loading.AppCache.get_app(), django.db.models.loading.AppCache.get_apps(), django.db.models.loading.AppCache.get_model(), django.db.models.loading.AppCache.get_models(), and django.db.models.loading.AppCache.unset_available_apps().
string django.contrib.admin.tests.AdminSeleniumWebDriverTestCase.webdriver_class = 'selenium.webdriver.firefox.webdriver.WebDriver' static
Definition at line 18 of file tests.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/admin/tests.py