Django: django.contrib.admin.helpers Namespace Reference
django.contrib.admin.helpers Namespace Reference
Classes
class ActionForm
class AdminErrorList
class AdminField
class AdminForm
class AdminReadonlyField
class Fieldline
class Fieldset
class InlineAdminForm
class InlineAdminFormSet
class InlineFieldset
Functions
def normalize_fieldsets (fieldsets)
def normalize_dictionary (data_dict)
Variables
string ACTION_CHECKBOX_NAME = '_selected_action'
tuple checkbox = forms.CheckboxInput({'class': 'action-select'}, lambda value: False)
Function Documentation
def django.contrib.admin.helpers.normalize_dictionary (data_dict)
Converts all the keys in "data_dict" to strings. The keys must be
convertible using str().
Definition at line 347 of file helpers.py.
Referenced by django.contrib.admin.helpers.normalize_fieldsets().
def django.contrib.admin.helpers.normalize_fieldsets (fieldsets)
Make sure the keys in fieldset dictionaries are strings. Returns the
normalized data.
Definition at line 337 of file helpers.py.
References django.contrib.admin.helpers.normalize_dictionary().
Variable Documentation
string django.contrib.admin.helpers.ACTION_CHECKBOX_NAME = '_selected_action'
Definition at line 20 of file helpers.py.
tuple django.contrib.admin.helpers.checkbox = forms.CheckboxInput({'class': 'action-select'}, lambda value: False)
Definition at line 27 of file helpers.py.
Referenced by yt().