Django: django.views.i18n Namespace Reference
django.views.i18n Namespace Reference
Functions
def set_language (request)
def get_formats ()
def render_javascript_catalog
def get_javascript_catalog (locale, domain, packages)
def null_javascript_catalog
def javascript_catalog
Variables
string js_catalog_template = r""
Function Documentation
def django.views.i18n.get_formats ()
Returns all formats strings required for i18n to work
Definition at line 43 of file i18n.py.
References django.utils.formats.get_format(), django.utils.formats.get_format_modules(), and django.utils.encoding.smart_text().
Referenced by django.views.i18n.render_javascript_catalog().
def django.views.i18n.get_javascript_catalog (locale, domain, packages)
Definition at line 187 of file i18n.py.
References django.utils.translation.to_locale(), and django.utils._os.upath().
Referenced by django.views.i18n.javascript_catalog().
def django.views.i18n.javascript_catalog (request, domain = 'djangojs', packages = None)
Returns the selected language catalog as a javascript library.
Receives the list of packages to check for translations in the
packages parameter either from an infodict or as a +-delimited
string from the request. Default is 'django.conf'.
Additionally you can override the gettext domain for this view,
but usually you don't want to do that, as JavaScript messages
go to the djangojs domain. But this might be needed if you
deliver your JavaScript source from Django templates.
Definition at line 280 of file i18n.py.
References django.utils.translation.trans_null.check_for_language, django.views.i18n.get_javascript_catalog(), django.utils.translation.trans_null.get_language, django.views.i18n.render_javascript_catalog(), and django.utils.translation.to_locale().
Referenced by django.contrib.admin.sites.AdminSite.i18n_javascript().
def django.views.i18n.null_javascript_catalog (request, domain = None, packages = None)
Returns "identity" versions of the JavaScript i18n functions -- i.e.,
versions that don't actually do anything.
Definition at line 272 of file i18n.py.
References django.views.i18n.render_javascript_catalog().
def django.views.i18n.render_javascript_catalog (catalog = None, plural = None)
Definition at line 173 of file i18n.py.
References django.views.i18n.get_formats().
Referenced by django.views.i18n.javascript_catalog(), and django.views.i18n.null_javascript_catalog().
def django.views.i18n.set_language (request)
Redirect to a given url while setting the chosen language in the
session or cookie. The url and the language code need to be
specified in the request parameters.
Since this view changes how the user will see the rest of the site, it must
only be accessed as a POST request. If called as a GET request, it will
redirect to the page in the request (the 'next' parameter) without changing
any state.
Definition at line 16 of file i18n.py.
References django.utils.translation.trans_null.check_for_language.
Variable Documentation
string django.views.i18n.js_catalog_template = r""
Definition at line 67 of file i18n.py.