Django: django.contrib.auth.hashers.CryptPasswordHasher Class Reference
django.contrib.auth.hashers.CryptPasswordHasher Class Reference
Public Member Functions
def salt (self)
def encode (self, password, salt)
def verify (self, password, encoded)
def safe_summary (self, encoded)
Public Member Functions inherited from django.contrib.auth.hashers.BasePasswordHasher
def salt (self)
def verify (self, password, encoded)
def encode (self, password, salt)
def safe_summary (self, encoded)
def must_update (self, encoded)
Static Public Attributes
string algorithm = "crypt"
string library = "crypt"
Static Public Attributes inherited from django.contrib.auth.hashers.BasePasswordHasher
algorithm = None
library = None
Detailed Description
Password hashing using UNIX crypt (not recommended)
The crypt module is not supported on all platforms.
Definition at line 482 of file hashers.py.
Member Function Documentation
def django.contrib.auth.hashers.CryptPasswordHasher.encode (self, password, salt)
Definition at line 494 of file hashers.py.
References django.contrib.auth.hashers.BasePasswordHasher._load_library(), django.contrib.auth.hashers.BasePasswordHasher.algorithm, and django.utils.encoding.force_str.
Referenced by django.contrib.sessions.models.SessionManager.save(), django.contrib.sessions.backends.db.SessionStore.save(), and django.contrib.sessions.backends.file.SessionStore.save().
def django.contrib.auth.hashers.CryptPasswordHasher.safe_summary (self, encoded)
Definition at line 507 of file hashers.py.
References django.contrib.auth.hashers.BasePasswordHasher.algorithm, and django.contrib.auth.hashers.mask_hash().
def django.contrib.auth.hashers.CryptPasswordHasher.salt (self)
Definition at line 491 of file hashers.py.
References django.utils.crypto.get_random_string().
def django.contrib.auth.hashers.CryptPasswordHasher.verify (self, password, encoded)
Definition at line 501 of file hashers.py.
References django.contrib.auth.hashers.BasePasswordHasher._load_library(), django.contrib.auth.hashers.BasePasswordHasher.algorithm, django.utils.crypto.constant_time_compare(), and django.utils.encoding.force_str.
Member Data Documentation
string django.contrib.auth.hashers.CryptPasswordHasher.algorithm = "crypt" static
Definition at line 488 of file hashers.py.
string django.contrib.auth.hashers.CryptPasswordHasher.library = "crypt" static
Definition at line 489 of file hashers.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/hashers.py