Django: django Namespace Reference
django Namespace Reference
Namespaces
conf
contrib
core
db
dispatch
forms
http
middleware
shortcuts
template
templatetags
test
utils
::2to3_fixes::fix_unicode
views
Functions
def get_version (args, kwargs)
Variables
tuple VERSION = (1, 6, 10, 'final', 0)
Function Documentation
def django.get_version (args, kwargs)
Definition at line 3 of file __init__.py.
Referenced by django.core.management.ManagementUtility.execute(), django.views.debug.ExceptionReporter.get_traceback_data(), django.core.management.base.BaseCommand.get_version(), and django.db.backends.postgresql_psycopg2.base.DatabaseWrapper.pg_version().
Variable Documentation
tuple django.VERSION = (1, 6, 10, 'final', 0)
Definition at line 1 of file __init__.py.