Django: django.utils.unittest.loader Namespace Reference
django.utils.unittest.loader Namespace Reference
Classes
class TestLoader
Functions
def getTestCaseNames
def makeSuite
def findTestCases
Variables
__unittest = True
tuple VALID_MODULE_NAME = re.compile(r'[_a-z]\w*\.py$', re.IGNORECASE)
tuple defaultTestLoader = TestLoader()
obj
Detailed Description
Loading unittests.
Function Documentation
def django.utils.unittest.loader.findTestCases (module, prefix = 'test', sortUsing = cmp, suiteClass = suite.TestSuite)
Definition at line 321 of file loader.py.
Referenced by django.utils.unittest.loader.makeSuite().
def django.utils.unittest.loader.getTestCaseNames (testCaseClass, prefix, sortUsing = cmp)
Definition at line 313 of file loader.py.
References django.utils.unittest.loader.makeSuite().
def django.utils.unittest.loader.makeSuite (testCaseClass, prefix = 'test', sortUsing = cmp, suiteClass = suite.TestSuite)
Definition at line 317 of file loader.py.
References django.utils.unittest.loader.findTestCases().
Referenced by django.utils.unittest.loader.getTestCaseNames().
Variable Documentation
django.utils.unittest.loader.__unittest = True
Definition at line 19 of file loader.py.
tuple django.utils.unittest.loader.defaultTestLoader = TestLoader()
Definition at line 302 of file loader.py.
django.utils.unittest.loader.obj
Definition at line 26 of file loader.py.
Referenced by addEvent(), buildParams(), findPosX(), findPosY(), django.utils.unittest.loader.TestLoader.loadTestsFromName(), quickElement(), and removeEvent().
tuple django.utils.unittest.loader.VALID_MODULE_NAME = re.compile(r'[_a-z]\w*\.py$', re.IGNORECASE)
Definition at line 35 of file loader.py.