Django: django.template.context.RenderContext Class Reference
django.template.context.RenderContext Class Reference
Public Member Functions
def __iter__ (self)
def has_key (self, key)
def get
Public Member Functions inherited from django.template.context.BaseContext
def __init__
def __copy__ (self)
def __repr__ (self)
def __iter__ (self)
def push (self)
def pop (self)
def __setitem__ (self, key, value)
def __getitem__ (self, key)
def __delitem__ (self, key)
def has_key (self, key)
def __contains__ (self, key)
def get
def new
Additional Inherited Members
Public Attributes inherited from django.template.context.BaseContext
dicts
Detailed Description
A stack container for storing Template state.
RenderContext simplifies the implementation of template Nodes by providing a
safe place to store state between invocations of a node's `render` method.
The RenderContext also provides scoping rules that are more sensible for
'template local' variables. The render context stack is pushed before each
template is rendered, creating a fresh scope with nothing in it. Name
resolution fails if a variable is not found at the top of the RequestContext
stack. Thus, variables are local to a specific template and don't affect the
rendering of other templates as they would if they were stored in the normal
template context.
Definition at line 109 of file context.py.
Member Function Documentation
def django.template.context.RenderContext.__iter__ (self)
Definition at line 124 of file context.py.
References django.template.context.BaseContext.dicts.
def django.template.context.RenderContext.get (self, key, otherwise = None)
Definition at line 131 of file context.py.
References django.template.context.BaseContext.dicts.
Referenced by django.views.generic.base.RedirectView.delete(), django.contrib.contenttypes.models.ContentTypeManager.get_by_natural_key(), django.contrib.auth.models.PermissionManager.get_by_natural_key(), django.contrib.auth.models.GroupManager.get_by_natural_key(), django.contrib.auth.models.BaseUserManager.get_by_natural_key(), django.contrib.sites.models.SiteManager.get_current(), django.contrib.contenttypes.models.ContentTypeManager.get_for_id(), django.views.generic.base.RedirectView.head(), django.views.generic.base.RedirectView.options(), django.views.generic.base.RedirectView.patch(), django.views.generic.base.RedirectView.post(), and django.views.generic.base.RedirectView.put().
def django.template.context.RenderContext.has_key (self, key)
Definition at line 128 of file context.py.
References django.template.context.BaseContext.dicts.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/template/context.py