Django: django.contrib.comments.feeds.LatestCommentFeed Class Reference
django.contrib.comments.feeds.LatestCommentFeed Class Reference
Public Member Functions
def __call__ (self, request, args, kwargs)
def title (self)
def link (self)
def description (self)
def items (self)
def item_pubdate (self, item)
Public Member Functions inherited from django.contrib.syndication.views.Feed
def __call__ (self, request, args, kwargs)
def item_title (self, item)
def item_description (self, item)
def item_link (self, item)
def feed_extra_kwargs (self, obj)
def item_extra_kwargs (self, item)
def get_object (self, request, args, kwargs)
def get_context_data (self, kwargs)
def get_feed (self, obj, request)
Public Attributes
site
Additional Inherited Members
Static Public Attributes inherited from django.contrib.syndication.views.Feed
feed_type = feedgenerator.DefaultFeed
title_template = None
description_template = None
Detailed Description
Feed of latest comments on the current site.
Definition at line 6 of file feeds.py.
Member Function Documentation
def django.contrib.comments.feeds.LatestCommentFeed.__call__ (self, request, args, kwargs)
Definition at line 9 of file feeds.py.
def django.contrib.comments.feeds.LatestCommentFeed.description (self)
Definition at line 19 of file feeds.py.
def django.contrib.comments.feeds.LatestCommentFeed.item_pubdate (self, item)
Definition at line 30 of file feeds.py.
def django.contrib.comments.feeds.LatestCommentFeed.items (self)
Definition at line 22 of file feeds.py.
Referenced by django.forms.util.ErrorDict.as_text(), django.forms.util.ErrorDict.as_ul(), and django.contrib.sitemaps.Sitemap.location().
def django.contrib.comments.feeds.LatestCommentFeed.link (self)
Definition at line 16 of file feeds.py.
def django.contrib.comments.feeds.LatestCommentFeed.title (self)
Definition at line 13 of file feeds.py.
Member Data Documentation
django.contrib.comments.feeds.LatestCommentFeed.site
Definition at line 10 of file feeds.py.
Referenced by django.contrib.redirects.tests.RedirectTests.test_model(), django.contrib.redirects.tests.RedirectTests.test_redirect(), django.contrib.redirects.tests.RedirectTests.test_redirect_with_append_slash(), django.contrib.redirects.tests.RedirectTests.test_redirect_with_append_slash_and_query_string(), and django.contrib.redirects.tests.RedirectTests.test_response_gone().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/comments/feeds.py