Django: django.contrib.sessions.tests.SessionMiddlewareTests Class Reference
django.contrib.sessions.tests.SessionMiddlewareTests Class Reference
Public Member Functions
def test_secure_session_cookie (self)
def test_httponly_session_cookie (self)
def test_no_httponly_session_cookie (self)
def test_session_save_on_500 (self)
Detailed Description
Definition at line 502 of file tests.py.
Member Function Documentation
def django.contrib.sessions.tests.SessionMiddlewareTests.test_httponly_session_cookie (self)
Definition at line 520 of file tests.py.
References django.utils.unittest.case.TestCase.assertIn(), and django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.sessions.tests.SessionMiddlewareTests.test_no_httponly_session_cookie (self)
Definition at line 537 of file tests.py.
References django.utils.unittest.case.TestCase.assertFalse(), and django.utils.unittest.case.TestCase.assertNotIn().
def django.contrib.sessions.tests.SessionMiddlewareTests.test_secure_session_cookie (self)
Definition at line 505 of file tests.py.
References django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.sessions.tests.SessionMiddlewareTests.test_session_save_on_500 (self)
Definition at line 553 of file tests.py.
References django.utils.unittest.case.TestCase.assertNotIn().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/sessions/tests.py