Django: django.contrib.admin.sites Namespace Reference
django.contrib.admin.sites Namespace Reference
Classes
class AdminSite
class AlreadyRegistered
class NotRegistered
Variables
string LOGIN_FORM_KEY = 'this_is_the_login_form'
tuple site = AdminSite()
Variable Documentation
string django.contrib.admin.sites.LOGIN_FORM_KEY = 'this_is_the_login_form'
Definition at line 18 of file sites.py.
tuple django.contrib.admin.sites.site = AdminSite()
Definition at line 452 of file sites.py.
Referenced by django.contrib.gis.sitemaps.views.index(), django.contrib.sitemaps.views.index(), django.contrib.gis.sitemaps.views.sitemap(), and django.contrib.sitemaps.views.sitemap().