Django: django.contrib.contenttypes.views Namespace Reference
django.contrib.contenttypes.views Namespace Reference
Functions
def shortcut (request, content_type_id, object_id)
Function Documentation
def django.contrib.contenttypes.views.shortcut (request, content_type_id, object_id)
Redirect to an object's page based on a content-type ID and an object ID.
Definition at line 9 of file views.py.
References django.db.models.base.get_absolute_url(), and django.contrib.sites.models.get_current_site().
Referenced by django.contrib.contenttypes.tests.ContentTypesTests.test_shortcut_view().