Django: django.db.backends.sqlite3.introspection.DatabaseIntrospection Class Reference
django.db.backends.sqlite3.introspection.DatabaseIntrospection Class Reference
Public Member Functions
def get_table_list (self, cursor)
def get_table_description (self, cursor, table_name)
def get_relations (self, cursor, table_name)
def get_key_columns (self, cursor, table_name)
def get_indexes (self, cursor, table_name)
def get_primary_key_column (self, cursor, table_name)
Public Member Functions inherited from django.db.backends.BaseDatabaseIntrospection
def __init__ (self, connection)
def get_field_type (self, data_type, description)
def table_name_converter (self, name)
def table_names
def get_table_list (self, cursor)
def django_table_names
def installed_models (self, tables)
def sequence_list (self)
def get_key_columns (self, cursor, table_name)
def get_primary_key_column (self, cursor, table_name)
def get_indexes (self, cursor, table_name)
Static Public Attributes
tuple data_types_reverse = FlexibleFieldLookupDict()
Static Public Attributes inherited from django.db.backends.BaseDatabaseIntrospection
dictionary data_types_reverse = {}
Additional Inherited Members
Public Attributes inherited from django.db.backends.BaseDatabaseIntrospection
connection
Detailed Description
Definition at line 49 of file introspection.py.
Member Function Documentation
def django.db.backends.sqlite3.introspection.DatabaseIntrospection.get_indexes (self, cursor, table_name)
Definition at line 143 of file introspection.py.
References django.db.backends.sqlite3.introspection.DatabaseIntrospection._table_info().
def django.db.backends.sqlite3.introspection.DatabaseIntrospection.get_key_columns (self, cursor, table_name)
Returns a list of (column_name, referenced_table_name, referenced_column_name) for all
key columns in given table.
Definition at line 114 of file introspection.py.
def django.db.backends.sqlite3.introspection.DatabaseIntrospection.get_primary_key_column (self, cursor, table_name)
Get the column name of the primary key for the given table.
Definition at line 162 of file introspection.py.
References django.db.backends.sqlite3.introspection.get_field_size().
def django.db.backends.sqlite3.introspection.DatabaseIntrospection.get_relations (self, cursor, table_name)
Returns a dictionary of {field_index: (field_index_other_table, other_table)}
representing all relationships to the given table. Indexes are 0-based.
Definition at line 67 of file introspection.py.
def django.db.backends.sqlite3.introspection.DatabaseIntrospection.get_table_description (self, cursor, table_name)
Definition at line 62 of file introspection.py.
References django.db.backends.sqlite3.introspection.DatabaseIntrospection._table_info(), and django.db.backends.FieldInfo.
def django.db.backends.sqlite3.introspection.DatabaseIntrospection.get_table_list (self, cursor)
Definition at line 52 of file introspection.py.
Member Data Documentation
tuple django.db.backends.sqlite3.introspection.DatabaseIntrospection.data_types_reverse = FlexibleFieldLookupDict() static
Definition at line 50 of file introspection.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/db/backends/sqlite3/introspection.py