Django: django.contrib.auth.tests.test_management.CustomUserModelValidationTestCase Class Reference
django.contrib.auth.tests.test_management.CustomUserModelValidationTestCase Class Reference
Public Member Functions
def test_required_fields_is_list (self)
def test_username_not_in_required_fields (self)
def test_username_non_unique (self)
Detailed Description
Definition at line 188 of file test_management.py.
Member Function Documentation
def django.contrib.auth.tests.test_management.CustomUserModelValidationTestCase.test_required_fields_is_list (self)
Definition at line 190 of file test_management.py.
References django.utils.unittest.case.TestCase.assertIn(), django.db.models.loading.get_app, django.core.management.validation.get_validation_errors(), and django.utils.six.StringIO.
def django.contrib.auth.tests.test_management.CustomUserModelValidationTestCase.test_username_non_unique (self)
Definition at line 204 of file test_management.py.
References django.utils.unittest.case.TestCase.assertIn(), django.db.models.loading.get_app, django.core.management.validation.get_validation_errors(), and django.utils.six.StringIO.
def django.contrib.auth.tests.test_management.CustomUserModelValidationTestCase.test_username_not_in_required_fields (self)
Definition at line 197 of file test_management.py.
References django.utils.unittest.case.TestCase.assertIn(), django.db.models.loading.get_app, django.core.management.validation.get_validation_errors(), and django.utils.six.StringIO.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_management.py