Django: django.contrib.auth.context_processors.PermLookupDict Class Reference
django.contrib.auth.context_processors.PermLookupDict Class Reference
Public Member Functions
def __init__ (self, user, app_label)
def __repr__ (self)
def __getitem__ (self, perm_name)
def __iter__ (self)
def __bool__ (self)
def __nonzero__ (self)
Public Attributes
app_label
Detailed Description
Definition at line 4 of file context_processors.py.
Constructor & Destructor Documentation
def django.contrib.auth.context_processors.PermLookupDict.__init__ (self, user, app_label)
Definition at line 5 of file context_processors.py.
Member Function Documentation
def django.contrib.auth.context_processors.PermLookupDict.__bool__ (self)
Definition at line 19 of file context_processors.py.
References django.contrib.auth.context_processors.PermLookupDict.app_label.
Referenced by django.contrib.auth.context_processors.PermLookupDict.__nonzero__().
def django.contrib.auth.context_processors.PermLookupDict.__getitem__ (self, perm_name)
Definition at line 11 of file context_processors.py.
References django.contrib.auth.context_processors.PermLookupDict.app_label.
def django.contrib.auth.context_processors.PermLookupDict.__iter__ (self)
Definition at line 14 of file context_processors.py.
Referenced by django.forms.forms.BoundField.__getitem__(), and django.forms.forms.BoundField.__len__().
def django.contrib.auth.context_processors.PermLookupDict.__nonzero__ (self)
Definition at line 22 of file context_processors.py.
References django.contrib.auth.context_processors.PermLookupDict.__bool__().
def django.contrib.auth.context_processors.PermLookupDict.__repr__ (self)
Definition at line 8 of file context_processors.py.
Member Data Documentation
django.contrib.auth.context_processors.PermLookupDict.app_label
Definition at line 6 of file context_processors.py.
Referenced by django.contrib.auth.context_processors.PermLookupDict.__bool__(), django.contrib.auth.context_processors.PermLookupDict.__getitem__(), django.db.models.options.Options.__str__(), django.contrib.contenttypes.models.ContentType.model_class(), and django.contrib.contenttypes.models.ContentType.natural_key().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/context_processors.py