Django: django.contrib.messages.api Namespace Reference
django.contrib.messages.api Namespace Reference
Classes
class MessageFailure
Functions
def add_message
def get_messages (request)
def get_level (request)
def set_level (request, level)
def debug
def info
def success
def warning
def error
Variables
tuple __all__
Function Documentation
def django.contrib.messages.api.add_message (request, level, message, extra_tags = '', fail_silently = False)
Attempts to add a message to the request using the 'messages' app.
Definition at line 15 of file api.py.
Referenced by django.contrib.messages.api.debug(), django.contrib.messages.api.error(), django.contrib.messages.api.info(), django.contrib.messages.api.success(), and django.contrib.messages.api.warning().
def django.contrib.messages.api.debug (request, message, extra_tags = '', fail_silently = False)
Adds a message with the ``DEBUG`` level.
Definition at line 65 of file api.py.
References django.contrib.messages.api.add_message().
def django.contrib.messages.api.error (request, message, extra_tags = '', fail_silently = False)
Adds a message with the ``ERROR`` level.
Definition at line 97 of file api.py.
References django.contrib.messages.api.add_message().
def django.contrib.messages.api.get_level (request)
Returns the minimum level of messages to be recorded.
The default level is the ``MESSAGE_LEVEL`` setting. If this is not found,
the ``INFO`` level is used.
Definition at line 37 of file api.py.
References django.contrib.messages.storage.default_storage.
Referenced by django.contrib.messages.tests.base.BaseTests.test_default_level(), django.contrib.messages.tests.base.BaseTests.test_high_level(), django.contrib.messages.tests.base.BaseTests.test_low_level(), and django.contrib.messages.tests.base.BaseTests.test_settings_level().
def django.contrib.messages.api.get_messages (request)
Returns the message storage on the request if it exists, otherwise returns
an empty list.
Definition at line 26 of file api.py.
Referenced by django.contrib.messages.context_processors.messages().
def django.contrib.messages.api.info (request, message, extra_tags = '', fail_silently = False)
Adds a message with the ``INFO`` level.
Definition at line 73 of file api.py.
References django.contrib.messages.api.add_message().
def django.contrib.messages.api.set_level (request, level)
Sets the minimum level of messages to be recorded, returning ``True`` if
the level was recorded successfully.
If set to ``None``, the default level will be used (see the ``get_level``
method).
Definition at line 51 of file api.py.
Referenced by django.contrib.messages.tests.base.BaseTests.test_high_level(), and django.contrib.messages.tests.base.BaseTests.test_low_level().
def django.contrib.messages.api.success (request, message, extra_tags = '', fail_silently = False)
Adds a message with the ``SUCCESS`` level.
Definition at line 81 of file api.py.
References django.contrib.messages.api.add_message().
def django.contrib.messages.api.warning (request, message, extra_tags = '', fail_silently = False)
Adds a message with the ``WARNING`` level.
Definition at line 89 of file api.py.
References django.contrib.messages.api.add_message().
Variable Documentation
tuple django.contrib.messages.api.__all__
Initial value:
 = (
     'add_message', 'get_messages',
     'get_level', 'set_level',
     'debug', 'info', 'success', 'warning', 'error',
 )
Definition at line 4 of file api.py.