Django: django.views.decorators.vary Namespace Reference
django.views.decorators.vary Namespace Reference
Functions
def vary_on_headers (headers)
def vary_on_cookie (func)
Function Documentation
def django.views.decorators.vary.vary_on_cookie (func)
A view decorator that adds "Cookie" to the Vary header of a response. This
indicates that a page's contents depends on cookies. Usage:
    @vary_on_cookie
    def index(request):
        ...
Definition at line 25 of file vary.py.
References django.utils.decorators.available_attrs(), django.utils.cache.patch_vary_headers(), and django.utils.six.wraps.
def django.views.decorators.vary.vary_on_headers (headers)
A view decorator that adds the specified headers to the Vary header of the
response. Usage:
   @vary_on_headers('Cookie', 'Accept-language')
   def index(request):
       ...
Note that the header names are not case-sensitive.
Definition at line 5 of file vary.py.
References django.utils.decorators.available_attrs(), django.utils.cache.patch_vary_headers(), and django.utils.six.wraps.