Django: django.core.serializers.xml_serializer.DefusedExpatParser Class Reference
django.core.serializers.xml_serializer.DefusedExpatParser Class Reference
Public Member Functions
def __init__ (self, args, kwargs)
def start_doctype_decl (self, name, sysid, pubid, has_internal_subset)
def entity_decl (self, name, is_parameter_entity, value, base, sysid, pubid, notation_name)
def unparsed_entity_decl (self, name, base, sysid, pubid, notation_name)
def external_entity_ref_handler (self, context, base, sysid, pubid)
def reset (self)
Detailed Description
An expat parser hardened against XML bomb attacks.
Forbids DTDs, external entity references
Definition at line 310 of file xml_serializer.py.
Constructor & Destructor Documentation
def django.core.serializers.xml_serializer.DefusedExpatParser.__init__ (self, args, kwargs)
Definition at line 317 of file xml_serializer.py.
Member Function Documentation
def django.core.serializers.xml_serializer.DefusedExpatParser.entity_decl (self, name, is_parameter_entity, value, base, sysid, pubid, notation_name)
Definition at line 326 of file xml_serializer.py.
Referenced by django.core.serializers.xml_serializer.DefusedExpatParser.reset(), and django.core.serializers.xml_serializer.DefusedExpatParser.start_doctype_decl().
def django.core.serializers.xml_serializer.DefusedExpatParser.external_entity_ref_handler (self, context, base, sysid, pubid)
Definition at line 333 of file xml_serializer.py.
Referenced by django.core.serializers.xml_serializer.DefusedExpatParser.reset().
def django.core.serializers.xml_serializer.DefusedExpatParser.reset (self)
Definition at line 336 of file xml_serializer.py.
References django.test._doctest.DocTestFinder._parser, django.core.serializers.xml_serializer.DefusedExpatParser.entity_decl(), django.core.serializers.xml_serializer.DefusedExpatParser.external_entity_ref_handler(), django.core.serializers.xml_serializer.DefusedExpatParser.start_doctype_decl(), and django.core.serializers.xml_serializer.DefusedExpatParser.unparsed_entity_decl().
def django.core.serializers.xml_serializer.DefusedExpatParser.start_doctype_decl (self, name, sysid, pubid, has_internal_subset)
Definition at line 322 of file xml_serializer.py.
References django.core.serializers.xml_serializer.DefusedExpatParser.entity_decl().
Referenced by django.core.serializers.xml_serializer.DefusedExpatParser.reset().
def django.core.serializers.xml_serializer.DefusedExpatParser.unparsed_entity_decl (self, name, base, sysid, pubid, notation_name)
Definition at line 329 of file xml_serializer.py.
Referenced by django.core.serializers.xml_serializer.DefusedExpatParser.reset().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/core/serializers/xml_serializer.py