Django: django.contrib.gis.geos.libgeos Namespace Reference
django.contrib.gis.geos.libgeos Namespace Reference
Classes
class GEOSContextHandle_t
class GEOSCoordSeq_t
class GEOSGeom_t
GEOS Geometry C data structures, and utility functions.
class GEOSPrepGeom_t
Functions
def notice_h (fmt, lst)
def error_h (fmt, lst)
def get_pointer_arr (n)
def geos_version_info ()
Variables
tuple logger = logging.getLogger('django.contrib.gis')
lib_path = settings.GEOS_LIBRARY_PATH
lib_names = None
tuple lgeos = CDLL(lib_path)
tuple NOTICEFUNC = CFUNCTYPE(None, c_char_p, c_char_p)
tuple notice_h = NOTICEFUNC(notice_h)
tuple ERRORFUNC = CFUNCTYPE(None, c_char_p, c_char_p)
tuple error_h = ERRORFUNC(error_h)
tuple GEOM_PTR = POINTER(GEOSGeom_t)
tuple PREPGEOM_PTR = POINTER(GEOSPrepGeom_t)
tuple CS_PTR = POINTER(GEOSCoordSeq_t)
tuple CONTEXT_PTR = POINTER(GEOSContextHandle_t)
geos_version = lgeos.GEOSversion
tuple version_regex
tuple _verinfo = geos_version_info()
tuple GEOS_MAJOR_VERSION = int(_verinfo['major'])
tuple GEOS_MINOR_VERSION = int(_verinfo['minor'])
tuple GEOS_SUBMINOR_VERSION = int(_verinfo['subminor'])
tuple GEOS_VERSION = (GEOS_MAJOR_VERSION, GEOS_MINOR_VERSION, GEOS_SUBMINOR_VERSION)
tuple GEOS_PREPARE = (3, 1, 0)
Detailed Description
 This module houses the ctypes initialization procedures, as well
 as the notice and error handler function callbacks (get called
 when an error occurs in GEOS).
 This module also houses GEOS Pointer utilities, including
 get_pointer_arr(), and GEOM_PTR.
Function Documentation
def django.contrib.gis.geos.libgeos.error_h (fmt, lst)
Definition at line 74 of file libgeos.py.
References django.contrib.gis.geos.libgeos.error_h.
def django.contrib.gis.geos.libgeos.geos_version_info ()
Returns a dictionary containing the various version metadata parsed from
the GEOS version string, including the version number, whether the version
is a release candidate (and what number release candidate), and the C API
version.
Definition at line 116 of file libgeos.py.
References django.contrib.gis.geos.libgeos.geos_version.
Referenced by django.contrib.gis.geos.tests.test_geos.GEOSTest.null_srid(), django.contrib.gis.geos.tests.test_io.GEOSIOTest.test04_wkbwriter(), django.contrib.gis.geos.tests.test_geos.GEOSTest.test_valid_reason(), and django.contrib.gis.geos.tests.test_geos.GEOSTest.test_wkt().
def django.contrib.gis.geos.libgeos.get_pointer_arr (n)
Definition at line 99 of file libgeos.py.
Referenced by django.contrib.gis.geos.collections.GeometryCollection.__len__(), and django.contrib.gis.geos.polygon.Polygon.from_bbox().
def django.contrib.gis.geos.libgeos.notice_h (fmt, lst)
Definition at line 64 of file libgeos.py.
References django.contrib.gis.geos.libgeos.notice_h.
Variable Documentation
tuple django.contrib.gis.geos.libgeos._verinfo = geos_version_info()
Definition at line 131 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.CONTEXT_PTR = POINTER(GEOSContextHandle_t)
Definition at line 95 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.CS_PTR = POINTER(GEOSCoordSeq_t)
Definition at line 94 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.error_h = ERRORFUNC(error_h)
Definition at line 81 of file libgeos.py.
Referenced by django.contrib.gis.geos.libgeos.error_h().
tuple django.contrib.gis.geos.libgeos.ERRORFUNC = CFUNCTYPE(None, c_char_p, c_char_p)
Definition at line 73 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.GEOM_PTR = POINTER(GEOSGeom_t)
Definition at line 92 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.GEOS_MAJOR_VERSION = int(_verinfo['major'])
Definition at line 132 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.GEOS_MINOR_VERSION = int(_verinfo['minor'])
Definition at line 133 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.GEOS_PREPARE = (3, 1, 0)
Definition at line 137 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.GEOS_SUBMINOR_VERSION = int(_verinfo['subminor'])
Definition at line 134 of file libgeos.py.
django.contrib.gis.geos.libgeos.geos_version = lgeos.GEOSversion
Definition at line 106 of file libgeos.py.
Referenced by django.contrib.gis.geos.libgeos.geos_version_info().
tuple django.contrib.gis.geos.libgeos.GEOS_VERSION = (GEOS_MAJOR_VERSION, GEOS_MINOR_VERSION, GEOS_SUBMINOR_VERSION)
Definition at line 136 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.lgeos = CDLL(lib_path)
Definition at line 58 of file libgeos.py.
list django.contrib.gis.geos.libgeos.lib_names = None
Definition at line 30 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.lib_path = settings.GEOS_LIBRARY_PATH
Definition at line 23 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.logger = logging.getLogger('django.contrib.gis')
Definition at line 18 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.notice_h = NOTICEFUNC(notice_h)
Definition at line 71 of file libgeos.py.
Referenced by django.contrib.gis.geos.libgeos.notice_h().
tuple django.contrib.gis.geos.libgeos.NOTICEFUNC = CFUNCTYPE(None, c_char_p, c_char_p)
Definition at line 63 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.PREPGEOM_PTR = POINTER(GEOSPrepGeom_t)
Definition at line 93 of file libgeos.py.
tuple django.contrib.gis.geos.libgeos.version_regex
Initial value:
 = re.compile(
     r'^(?P<version>(?P<major>\d+)\.(?P<minor>\d+)\.(?P<subminor>\d+))'
     r'((rc(?P<release_candidate>\d+))|dev)?-CAPI-(?P<capi_version>\d+\.\d+\.\d+)( r\d+)?$'
 )
Definition at line 112 of file libgeos.py.