Django: django.test.testcases.TransactionTestCase Class Reference
django.test.testcases.TransactionTestCase Class Reference
Public Member Functions
def assertQuerysetEqual
def assertNumQueries (self, num, func=None, args, kwargs)
Public Member Functions inherited from django.test.testcases.SimpleTestCase
def __call__
def save_warnings_state (self)
def restore_warnings_state (self)
def settings (self, kwargs)
def assertRedirects
def assertContains
def assertNotContains
def assertFormError
def assertFormsetError
def assertTemplateUsed
def assertTemplateNotUsed
def assertRaisesMessage (self, expected_exception, expected_message, callable_obj=None, args, kwargs)
def assertFieldOutput
def assertHTMLEqual
def assertHTMLNotEqual
def assertInHTML
def assertJSONEqual
def assertXMLEqual
def assertXMLNotEqual
Static Public Attributes
reset_sequences = False
available_apps = None
Static Public Attributes inherited from django.test.testcases.SimpleTestCase
client_class = Client
Additional Inherited Members
Public Attributes inherited from django.test.testcases.SimpleTestCase
client
Detailed Description
Definition at line 725 of file testcases.py.
Member Function Documentation
def django.test.testcases.TransactionTestCase.assertNumQueries (self, num, func = None, args, kwargs)
Definition at line 831 of file testcases.py.
Referenced by django.contrib.sessions.tests.CacheDBSessionTests.test_exists_searches_cache_first(), django.contrib.contenttypes.tests.ContentTypesTests.test_get_for_models_empty_cache(), django.contrib.contenttypes.tests.ContentTypesTests.test_get_for_models_full_cache(), django.contrib.contenttypes.tests.ContentTypesTests.test_get_for_models_partial_cache(), and django.contrib.contenttypes.tests.ContentTypesTests.test_lookup_cache().
def django.test.testcases.TransactionTestCase.assertQuerysetEqual (self, qs, values, transform = repr, ordered = True)
Definition at line 819 of file testcases.py.
References django.utils.unittest.case.TestCase.assertEqual().
Member Data Documentation
django.test.testcases.TransactionTestCase.available_apps = None static
Definition at line 732 of file testcases.py.
django.test.testcases.TransactionTestCase.reset_sequences = False static
Definition at line 729 of file testcases.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/test/testcases.py