Django: django.test.simple Namespace Reference
django.test.simple Namespace Reference
Classes
class DjangoTestSuiteRunner
class DocTestRunner
class OutputChecker
Functions
def get_tests (app_module)
def make_doctest (module)
def build_suite (app_module)
def build_test (label)
Variables
tuple __all__ = ('DjangoTestSuiteRunner',)
string TEST_MODULE = 'tests'
tuple normalize_long_ints = lambdas:re.sub(r'(?<![\w])(\d+)L(?![\w])', '\\1', s)
tuple normalize_decimals
tuple doctestOutputChecker = OutputChecker()
Detailed Description
This module is pending deprecation as of Django 1.6 and will be removed in
version 1.8.
Function Documentation
def django.test.simple.build_suite (app_module)
Create a complete Django test suite for the provided application module.
Definition at line 128 of file simple.py.
References django.test.simple.get_tests(), and django.test.simple.make_doctest().
def django.test.simple.build_test (label)
Construct a test case with the specified label. Label should be of the
form model.TestClass or model.TestClass.test_method. Returns an
instantiated test or test suite corresponding to the label provided.
Definition at line 166 of file simple.py.
References django.db.models.loading.get_app, django.test.simple.get_tests(), django.template.defaultfilters.join(), and django.test.simple.make_doctest().
Referenced by django.test.simple.DjangoTestSuiteRunner.build_suite().
def django.test.simple.get_tests (app_module)
Definition at line 97 of file simple.py.
References django.utils.importlib.import_module(), django.template.defaultfilters.join(), and django.utils.module_loading.module_has_submodule().
Referenced by django.test.simple.build_suite(), and django.test.simple.build_test().
def django.test.simple.make_doctest (module)
Definition at line 121 of file simple.py.
Referenced by django.test.simple.build_suite(), and django.test.simple.build_test().
Variable Documentation
tuple django.test.simple.__all__ = ('DjangoTestSuiteRunner',)
Definition at line 19 of file simple.py.
tuple django.test.simple.doctestOutputChecker = OutputChecker()
Definition at line 94 of file simple.py.
tuple django.test.simple.normalize_decimals
Initial value:
 = lambdas:re.sub(r"Decimal\('(\d+(\.\d*)?)'\)",
                                 lambda m: "Decimal(\"%s\")" % m.groups()[0], s)
Definition at line 31 of file simple.py.
Referenced by django.test.simple.OutputChecker.check_output_numeric().
tuple django.test.simple.normalize_long_ints = lambdas:re.sub(r'(?<![\w])(\d+)L(?![\w])', '\\1', s)
Definition at line 30 of file simple.py.
Referenced by django.test.simple.OutputChecker.check_output_numeric().
string django.test.simple.TEST_MODULE = 'tests'
Definition at line 27 of file simple.py.