Django: django.contrib.auth.decorators Namespace Reference
django.contrib.auth.decorators Namespace Reference
Functions
def user_passes_test
def login_required
def permission_required
Function Documentation
def django.contrib.auth.decorators.login_required (function = None, redirect_field_name = REDIRECT_FIELD_NAME, login_url = None)
Decorator for views that checks that the user is logged in, redirecting
to the log-in page if necessary.
Definition at line 41 of file decorators.py.
References django.contrib.auth.decorators.user_passes_test().
def django.contrib.auth.decorators.permission_required (perm, login_url = None, raise_exception = False)
Decorator for views that checks whether a user has a particular permission
enabled, redirecting to the log-in page if neccesary.
If the raise_exception parameter is given the PermissionDenied exception
is raised.
Definition at line 56 of file decorators.py.
References django.contrib.auth.decorators.user_passes_test().
Referenced by django.contrib.comments.views.moderation.delete(), and django.contrib.comments.views.moderation.flag().
def django.contrib.auth.decorators.user_passes_test (test_func, login_url = None, redirect_field_name = REDIRECT_FIELD_NAME)
Decorator for views that checks that the user passes the given test,
redirecting to the log-in page if necessary. The test should be a callable
that takes the user object and returns True if the user passes.
Definition at line 11 of file decorators.py.
References django.utils.decorators.available_attrs(), django.utils.encoding.force_str, django.contrib.auth.views.redirect_to_login(), django.shortcuts.resolve_url(), and django.utils.six.wraps.
Referenced by django.contrib.auth.decorators.login_required(), and django.contrib.auth.decorators.permission_required().