Django: django.contrib.gis.tests.geoapp.test_regress.GeoRegressionTests Class Reference
django.contrib.gis.tests.geoapp.test_regress.GeoRegressionTests Class Reference
Public Member Functions
def test_update (self)
def test_kmz (self)
def test_extent (self)
def test_unicode_date (self)
def test_empty_count (self)
def test_defer_or_only_with_annotate (self)
def test_boolean_conversion (self)
Detailed Description
Definition at line 19 of file test_regress.py.
Member Function Documentation
def django.contrib.gis.tests.geoapp.test_regress.GeoRegressionTests.test_boolean_conversion (self)
Definition at line 79 of file test_regress.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertIsInstance().
def django.contrib.gis.tests.geoapp.test_regress.GeoRegressionTests.test_defer_or_only_with_annotate (self)
Definition at line 74 of file test_regress.py.
References django.utils.unittest.case.TestCase.assertIsInstance().
def django.contrib.gis.tests.geoapp.test_regress.GeoRegressionTests.test_empty_count (self)
Definition at line 60 of file test_regress.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.geoapp.test_regress.GeoRegressionTests.test_extent (self)
Definition at line 44 of file test_regress.py.
References django.utils.unittest.case.TestCase.assertAlmostEqual().
def django.contrib.gis.tests.geoapp.test_regress.GeoRegressionTests.test_kmz (self)
Definition at line 33 of file test_regress.py.
References django.contrib.gis.shortcuts.render_to_kmz().
def django.contrib.gis.tests.geoapp.test_regress.GeoRegressionTests.test_unicode_date (self)
Definition at line 52 of file test_regress.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.geoapp.test_regress.GeoRegressionTests.test_update (self)
Definition at line 21 of file test_regress.py.
References django.utils.unittest.case.TestCase.assertEqual().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/tests/geoapp/test_regress.py