Django: django.contrib.gis.geos.prototypes.io Namespace Reference
django.contrib.gis.geos.prototypes.io Namespace Reference
Classes
class _WKBReader
class _WKTReader
class IOBase
Base I/O Class ###.
class ThreadLocalIO
class WKBReader_st
class WKBWriter
class WKBWriter_st
class WKTReader_st
The WKB/WKT Reader/Writer structures and pointers ###.
class WKTWriter
class WKTWriter_st
Functions
def wkb_read_func (func)
def wkb_write_func (func)
def wkb_writer_get
def wkb_writer_set
def wkt_r ()
def wkt_w
def wkb_r ()
def wkb_w
def ewkb_w
Variables
tuple WKT_READ_PTR = POINTER(WKTReader_st)
tuple WKT_WRITE_PTR = POINTER(WKTWriter_st)
tuple WKB_READ_PTR = POINTER(WKBReader_st)
tuple WKB_WRITE_PTR = POINTER(WKBReader_st)
tuple wkt_reader_create = GEOSFunc('GEOSWKTReader_create')
WKTReader routines ###.
tuple wkt_reader_destroy = GEOSFunc('GEOSWKTReader_destroy')
tuple wkt_reader_read = GEOSFunc('GEOSWKTReader_read')
tuple wkt_writer_create = GEOSFunc('GEOSWKTWriter_create')
WKTWriter routines ###.
tuple wkt_writer_destroy = GEOSFunc('GEOSWKTWriter_destroy')
tuple wkt_writer_write = GEOSFunc('GEOSWKTWriter_write')
tuple wkt_writer_get_outdim = GEOSFunc('GEOSWKTWriter_getOutputDimension')
tuple wkt_writer_set_outdim = GEOSFunc('GEOSWKTWriter_setOutputDimension')
tuple wkb_reader_create = GEOSFunc('GEOSWKBReader_create')
WKBReader routines ###.
tuple wkb_reader_destroy = GEOSFunc('GEOSWKBReader_destroy')
tuple wkb_reader_read = wkb_read_func(GEOSFunc('GEOSWKBReader_read'))
tuple wkb_reader_read_hex = wkb_read_func(GEOSFunc('GEOSWKBReader_readHEX'))
tuple wkb_writer_create = GEOSFunc('GEOSWKBWriter_create')
WKBWriter routines ###.
tuple wkb_writer_destroy = GEOSFunc('GEOSWKBWriter_destroy')
tuple wkb_writer_write = wkb_write_func(GEOSFunc('GEOSWKBWriter_write'))
tuple wkb_writer_write_hex = wkb_write_func(GEOSFunc('GEOSWKBWriter_writeHEX'))
tuple wkb_writer_get_byteorder = wkb_writer_get(GEOSFunc('GEOSWKBWriter_getByteOrder'))
tuple wkb_writer_set_byteorder = wkb_writer_set(GEOSFunc('GEOSWKBWriter_setByteOrder'))
tuple wkb_writer_get_outdim = wkb_writer_get(GEOSFunc('GEOSWKBWriter_getOutputDimension'))
tuple wkb_writer_set_outdim = wkb_writer_set(GEOSFunc('GEOSWKBWriter_setOutputDimension'))
tuple wkb_writer_get_include_srid = wkb_writer_get(GEOSFunc('GEOSWKBWriter_getIncludeSRID'), restype=c_char)
tuple wkb_writer_set_include_srid = wkb_writer_set(GEOSFunc('GEOSWKBWriter_setIncludeSRID'), argtype=c_char)
tuple thread_context = ThreadLocalIO()
Function Documentation
def django.contrib.gis.geos.prototypes.io.ewkb_w (dim = 2)
Definition at line 260 of file io.py.
Referenced by django.contrib.gis.geos.geometry.GEOSGeometry.ewkb(), and django.contrib.gis.geos.geometry.GEOSGeometry.hexewkb().
def django.contrib.gis.geos.prototypes.io.wkb_r ()
Definition at line 249 of file io.py.
Referenced by django.contrib.gis.geos.geometry.GEOSGeometry.__init__(), django.contrib.gis.geos.geometry.GEOSGeometry.__setstate__(), and django.contrib.gis.geos.geometry.GEOSGeometry.transform().
def django.contrib.gis.geos.prototypes.io.wkb_read_func (func)
Definition at line 67 of file io.py.
def django.contrib.gis.geos.prototypes.io.wkb_w (dim = 2)
Definition at line 254 of file io.py.
Referenced by django.contrib.gis.geos.geometry.GEOSGeometry.hex(), and django.contrib.gis.geos.geometry.GEOSGeometry.wkb().
def django.contrib.gis.geos.prototypes.io.wkb_write_func (func)
Definition at line 89 of file io.py.
def django.contrib.gis.geos.prototypes.io.wkb_writer_get (func, restype = c_int)
Definition at line 99 of file io.py.
def django.contrib.gis.geos.prototypes.io.wkb_writer_set (func, argtype = c_int)
Definition at line 104 of file io.py.
def django.contrib.gis.geos.prototypes.io.wkt_r ()
Definition at line 238 of file io.py.
Referenced by django.contrib.gis.geos.geometry.GEOSGeometry.__init__().
def django.contrib.gis.geos.prototypes.io.wkt_w (dim = 2)
Definition at line 243 of file io.py.
Referenced by django.contrib.gis.geos.geometry.GEOSGeometry.wkt().
Variable Documentation
tuple django.contrib.gis.geos.prototypes.io.thread_context = ThreadLocalIO()
Definition at line 234 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.WKB_READ_PTR = POINTER(WKBReader_st)
Definition at line 21 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkb_reader_create = GEOSFunc('GEOSWKBReader_create')
WKBReader routines ###.
Definition at line 61 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkb_reader_destroy = GEOSFunc('GEOSWKBReader_destroy')
Definition at line 64 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkb_reader_read = wkb_read_func(GEOSFunc('GEOSWKBReader_read'))
Definition at line 78 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io._WKBReader.read().
tuple django.contrib.gis.geos.prototypes.io.wkb_reader_read_hex = wkb_read_func(GEOSFunc('GEOSWKBReader_readHEX'))
Definition at line 79 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io._WKBReader.read().
tuple django.contrib.gis.geos.prototypes.io.WKB_WRITE_PTR = POINTER(WKBReader_st)
Definition at line 22 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkb_writer_create = GEOSFunc('GEOSWKBWriter_create')
WKBWriter routines ###.
Definition at line 82 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkb_writer_destroy = GEOSFunc('GEOSWKBWriter_destroy')
Definition at line 85 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkb_writer_get_byteorder = wkb_writer_get(GEOSFunc('GEOSWKBWriter_getByteOrder'))
Definition at line 108 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKBWriter.write_hex().
tuple django.contrib.gis.geos.prototypes.io.wkb_writer_get_include_srid = wkb_writer_get(GEOSFunc('GEOSWKBWriter_getIncludeSRID'), restype=c_char)
Definition at line 112 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkb_writer_get_outdim = wkb_writer_get(GEOSFunc('GEOSWKBWriter_getOutputDimension'))
Definition at line 110 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkb_writer_set_byteorder = wkb_writer_set(GEOSFunc('GEOSWKBWriter_setByteOrder'))
Definition at line 109 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKBWriter.write_hex().
tuple django.contrib.gis.geos.prototypes.io.wkb_writer_set_include_srid = wkb_writer_set(GEOSFunc('GEOSWKBWriter_setIncludeSRID'), argtype=c_char)
Definition at line 113 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkb_writer_set_outdim = wkb_writer_set(GEOSFunc('GEOSWKBWriter_setOutputDimension'))
Definition at line 111 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkb_writer_write = wkb_write_func(GEOSFunc('GEOSWKBWriter_write'))
Definition at line 95 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKBWriter.write().
tuple django.contrib.gis.geos.prototypes.io.wkb_writer_write_hex = wkb_write_func(GEOSFunc('GEOSWKBWriter_writeHEX'))
Definition at line 96 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKBWriter.write_hex().
tuple django.contrib.gis.geos.prototypes.io.WKT_READ_PTR = POINTER(WKTReader_st)
Definition at line 19 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkt_reader_create = GEOSFunc('GEOSWKTReader_create')
WKTReader routines ###.
Definition at line 25 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkt_reader_destroy = GEOSFunc('GEOSWKTReader_destroy')
Definition at line 28 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkt_reader_read = GEOSFunc('GEOSWKTReader_read')
Definition at line 31 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io._WKTReader.read().
tuple django.contrib.gis.geos.prototypes.io.WKT_WRITE_PTR = POINTER(WKTWriter_st)
Definition at line 20 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkt_writer_create = GEOSFunc('GEOSWKTWriter_create')
WKTWriter routines ###.
Definition at line 37 of file io.py.
tuple django.contrib.gis.geos.prototypes.io.wkt_writer_destroy = GEOSFunc('GEOSWKTWriter_destroy')
Definition at line 40 of file io.py.
int django.contrib.gis.geos.prototypes.io.wkt_writer_get_outdim = GEOSFunc('GEOSWKTWriter_getOutputDimension')
Definition at line 49 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKTWriter.outdim().
django.contrib.gis.geos.prototypes.io.wkt_writer_set_outdim = GEOSFunc('GEOSWKTWriter_setOutputDimension')
Definition at line 52 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKTWriter.outdim().
tuple django.contrib.gis.geos.prototypes.io.wkt_writer_write = GEOSFunc('GEOSWKTWriter_write')
Definition at line 43 of file io.py.
Referenced by django.contrib.gis.geos.prototypes.io.WKTWriter.write().