var namespacedjango_1_1db_1_1backends_1_1postgresql__psycopg2_1_1introspection =
[
    [ "DatabaseIntrospection", "da/d0b/classdjango_1_1db_1_1backends_1_1postgresql__psycopg2_1_1introspection_1_1_database_introspection.html", "da/d0b/classdjango_1_1db_1_1backends_1_1postgresql__psycopg2_1_1introspection_1_1_database_introspection" ]
];