Django: django.contrib.auth.tests.test_auth_backends.ImproperlyConfiguredUserModelTest Class Reference
django.contrib.auth.tests.test_auth_backends.ImproperlyConfiguredUserModelTest Class Reference
Public Member Functions
def setUp (self)
def test_does_not_shadow_exception (self)
Public Attributes
user1
Detailed Description
Tests that an exception from within get_user_model is propagated and doesn't
raise an UnboundLocalError.
Regression test for ticket #21439
Definition at line 486 of file test_auth_backends.py.
Member Function Documentation
def django.contrib.auth.tests.test_auth_backends.ImproperlyConfiguredUserModelTest.setUp (self)
Definition at line 493 of file test_auth_backends.py.
Referenced by django.utils.unittest.case.TestCase.debug(), django.test._doctest.DocTestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.contrib.auth.tests.test_auth_backends.ImproperlyConfiguredUserModelTest.test_does_not_shadow_exception (self)
Definition at line 501 of file test_auth_backends.py.
References django.utils.unittest.case.TestCase.assertRaises().
Member Data Documentation
django.contrib.auth.tests.test_auth_backends.ImproperlyConfiguredUserModelTest.user1
Definition at line 494 of file test_auth_backends.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_auth_backends.py