Django: django.core.files.locks Namespace Reference
django.core.files.locks Namespace Reference
Functions
def fd (f)
def lock (file, flags)
def unlock (file)
Variables
tuple __all__ = ('LOCK_EX','LOCK_SH','LOCK_NB','lock','unlock')
system_type = None
LOCK_EX = win32con.LOCKFILE_EXCLUSIVE_LOCK
int LOCK_SH = 0
LOCK_NB = win32con.LOCKFILE_FAIL_IMMEDIATELY
tuple __overlapped = pywintypes.OVERLAPPED()
Detailed Description
Portable file locking utilities.
Based partially on example by Jonathan Feignberg <jdf@pobox.com> in the Python
Cookbook, licensed under the Python Software License.
    http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/65203
Example Usage::
    >>> from django.core.files import locks
    >>> with open('./file', 'wb') as f:
    ...     locks.lock(f, locks.LOCK_EX)
    ...     f.write('Django')
Function Documentation
def django.core.files.locks.fd (f)
Get a filedescriptor from something which could be a file or an fd.
Definition at line 42 of file locks.py.
Referenced by django.core.files.locks.lock(), and django.core.files.locks.unlock().
def django.core.files.locks.lock (file, flags)
Definition at line 47 of file locks.py.
References django.core.files.locks.fd().
Referenced by django.core.files.locks.unlock().
def django.core.files.locks.unlock (file)
Definition at line 51 of file locks.py.
References django.core.files.locks.fd(), and django.core.files.locks.lock().
Variable Documentation
tuple django.core.files.locks.__all__ = ('LOCK_EX','LOCK_SH','LOCK_NB','lock','unlock')
Definition at line 17 of file locks.py.
tuple django.core.files.locks.__overlapped = pywintypes.OVERLAPPED()
Definition at line 28 of file locks.py.
django.core.files.locks.LOCK_EX = win32con.LOCKFILE_EXCLUSIVE_LOCK
Definition at line 25 of file locks.py.
django.core.files.locks.LOCK_NB = win32con.LOCKFILE_FAIL_IMMEDIATELY
Definition at line 27 of file locks.py.
django.core.files.locks.LOCK_SH = 0
Definition at line 26 of file locks.py.
string django.core.files.locks.system_type = None
Definition at line 19 of file locks.py.