Django: django.core.checks.compatibility.django_1_6_0 Namespace Reference
django.core.checks.compatibility.django_1_6_0 Namespace Reference
Functions
def check_test_runner ()
def check_boolean_field_default_value ()
def run_checks ()
Function Documentation
def django.core.checks.compatibility.django_1_6_0.check_boolean_field_default_value ()
Checks if there are any BooleanFields without a default value, &
warns the user that the default has changed from False to Null.
Definition at line 26 of file django_1_6_0.py.
References django.template.defaultfilters.join().
Referenced by django.core.checks.compatibility.django_1_6_0.run_checks().
def django.core.checks.compatibility.django_1_6_0.check_test_runner ()
Checks if the user has *not* overridden the ``TEST_RUNNER`` setting &
warns them about the default behavior changes.
If the user has overridden that setting, we presume they know what they're
doing & avoid generating a message.
Definition at line 5 of file django_1_6_0.py.
References django.template.defaultfilters.join().
Referenced by django.core.checks.compatibility.django_1_6_0.run_checks().
def django.core.checks.compatibility.django_1_6_0.run_checks ()
Required by the ``check`` management command, this returns a list of
messages from all the relevant check functions for this version of Django.
Definition at line 52 of file django_1_6_0.py.
References django.core.checks.compatibility.django_1_6_0.check_boolean_field_default_value(), and django.core.checks.compatibility.django_1_6_0.check_test_runner().