Django: django.core.management.commands.makemessages Namespace Reference
django.core.management.commands.makemessages Namespace Reference
Classes
class Command
class TranslatableFile
Functions
def check_programs (programs)
def write_pot_file (potfile, msgs)
Variables
tuple plural_forms_re = re.compile(r'^(?P<value>"Plural-Forms.+?\\n")\s*$', re.MULTILINE | re.DOTALL)
int STATUS_OK = 0
Function Documentation
def django.core.management.commands.makemessages.check_programs (programs)
Definition at line 23 of file makemessages.py.
References django.core.management.utils.find_command().
def django.core.management.commands.makemessages.write_pot_file (potfile, msgs)
Write the :param potfile: POT file with the :param msgs: contents,
previously making sure its format is valid.
Definition at line 153 of file makemessages.py.
References django.template.defaultfilters.join().
Referenced by django.core.management.commands.makemessages.TranslatableFile.process().
Variable Documentation
tuple django.core.management.commands.makemessages.plural_forms_re = re.compile(r'^(?P<value>"Plural-Forms.+?\\n")\s*$', re.MULTILINE | re.DOTALL)
Definition at line 19 of file makemessages.py.
int django.core.management.commands.makemessages.STATUS_OK = 0
Definition at line 20 of file makemessages.py.