Django: django.contrib.gis.geos.tests.test_geos_mutation.GEOSMutationTest Class Reference
django.contrib.gis.geos.tests.test_geos_mutation.GEOSMutationTest Class Reference
Public Member Functions
def test00_GEOSIndexException (self)
def test01_PointMutations (self)
def test02_PointExceptions (self)
def test03_PointApi (self)
def test04_LineStringMutations (self)
def test05_Polygon (self)
def test06_Collection (self)
Detailed Description
Tests Pythonic Mutability of Python GEOS geometry wrappers
get/set/delitem on a slice, normal list methods
Definition at line 42 of file test_geos_mutation.py.
Member Function Documentation
def django.contrib.gis.geos.tests.test_geos_mutation.GEOSMutationTest.test00_GEOSIndexException (self)
Definition at line 48 of file test_geos_mutation.py.
References django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.geos.tests.test_geos_mutation.GEOSMutationTest.test01_PointMutations (self)
Definition at line 55 of file test_geos_mutation.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.gis.geos.factory.fromstr().
def django.contrib.gis.geos.tests.test_geos_mutation.GEOSMutationTest.test02_PointExceptions (self)
Definition at line 68 of file test_geos_mutation.py.
References django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.geos.tests.test_geos_mutation.GEOSMutationTest.test03_PointApi (self)
Definition at line 73 of file test_geos_mutation.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.gis.geos.factory.fromstr().
def django.contrib.gis.geos.tests.test_geos_mutation.GEOSMutationTest.test04_LineStringMutations (self)
Definition at line 81 of file test_geos_mutation.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.gis.geos.factory.fromstr().
def django.contrib.gis.geos.tests.test_geos_mutation.GEOSMutationTest.test05_Polygon (self)
Definition at line 99 of file test_geos_mutation.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.gis.geos.factory.fromstr().
def django.contrib.gis.geos.tests.test_geos_mutation.GEOSMutationTest.test06_Collection (self)
Definition at line 123 of file test_geos_mutation.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.gis.geos.factory.fromstr().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/geos/tests/test_geos_mutation.py