Django: django.contrib.gis.tests.geoapp.feeds.TestGeoRSS1 Class Reference
django.contrib.gis.tests.geoapp.feeds.TestGeoRSS1 Class Reference
Public Member Functions
def items (self)
def item_link (self, item)
def item_geometry (self, item)
Public Member Functions inherited from django.contrib.gis.feeds.Feed
def feed_extra_kwargs (self, obj)
def item_extra_kwargs (self, item)
Static Public Attributes
string link = '/city/'
string title = 'Test GeoDjango Cities'
Static Public Attributes inherited from django.contrib.gis.feeds.Feed
feed_type = GeoRSSFeed
Detailed Description
Definition at line 8 of file feeds.py.
Member Function Documentation
def django.contrib.gis.tests.geoapp.feeds.TestGeoRSS1.item_geometry (self, item)
Definition at line 18 of file feeds.py.
def django.contrib.gis.tests.geoapp.feeds.TestGeoRSS1.item_link (self, item)
Definition at line 15 of file feeds.py.
def django.contrib.gis.tests.geoapp.feeds.TestGeoRSS1.items (self)
Definition at line 12 of file feeds.py.
Referenced by django.forms.util.ErrorDict.as_text(), django.forms.util.ErrorDict.as_ul(), and django.contrib.sitemaps.Sitemap.location().
Member Data Documentation
string django.contrib.gis.tests.geoapp.feeds.TestGeoRSS1.link = '/city/' static
Definition at line 9 of file feeds.py.
string django.contrib.gis.tests.geoapp.feeds.TestGeoRSS1.title = 'Test GeoDjango Cities' static
Definition at line 10 of file feeds.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/tests/geoapp/feeds.py