Django: django.contrib.gis.tests.geoapp.tests.GeoLookupTest Class Reference
django.contrib.gis.tests.geoapp.tests.GeoLookupTest Class Reference
Public Member Functions
def test_disjoint_lookup (self)
def test_contains_contained_lookups (self)
def test_left_right_lookups (self)
def test_equals_lookups (self)
def test_null_geometries (self)
def test_relate_lookup (self)
Static Public Attributes
tuple test_left_right_lookups = unittest.expectedFailure(test_left_right_lookups)
Detailed Description
Definition at line 208 of file tests.py.
Member Function Documentation
def django.contrib.gis.tests.geoapp.tests.GeoLookupTest.test_contains_contained_lookups (self)
Definition at line 221 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.geoapp.tests.GeoLookupTest.test_disjoint_lookup (self)
Definition at line 211 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.geoapp.tests.GeoLookupTest.test_equals_lookups (self)
Definition at line 311 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.gis.geos.factory.fromstr().
def django.contrib.gis.tests.geoapp.tests.GeoLookupTest.test_left_right_lookups (self)
Definition at line 270 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.contrib.gis.tests.geoapp.tests.postgis_bug_version(), and django.contrib.gis.tests.geoapp.tests.GeoLookupTest.test_left_right_lookups.
def django.contrib.gis.tests.geoapp.tests.GeoLookupTest.test_null_geometries (self)
Definition at line 320 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.geoapp.tests.GeoLookupTest.test_relate_lookup (self)
Definition at line 350 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertRaises(), django.contrib.gis.geos.factory.fromstr(), and django.utils.unittest.case.skipUnless().
Member Data Documentation
tuple django.contrib.gis.tests.geoapp.tests.GeoLookupTest.test_left_right_lookups = unittest.expectedFailure(test_left_right_lookups) static
Definition at line 309 of file tests.py.
Referenced by django.contrib.gis.tests.geoapp.tests.GeoLookupTest.test_left_right_lookups().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/tests/geoapp/tests.py