Django: django.contrib.gis.gdal.error Namespace Reference
django.contrib.gis.gdal.error Namespace Reference
Classes
class GDALException
OGR & SRS Exceptions ####.
class OGRException
class OGRIndexError
class SRSException
Functions
def check_err (code)
Variables
dictionary OGRERR_DICT
int OGRERR_NONE = 0
Detailed Description
 This module houses the OGR & SRS Exception objects, and the
 check_err() routine which checks the status code returned by
 OGR methods.
Function Documentation
def django.contrib.gis.gdal.error.check_err (code)
Definition at line 33 of file error.py.
References e.
Referenced by django.contrib.gis.gdal.prototypes.errcheck.check_arg_errcode(), django.contrib.gis.gdal.prototypes.errcheck.check_const_string(), django.contrib.gis.gdal.prototypes.errcheck.check_errcode(), django.contrib.gis.gdal.prototypes.errcheck.check_geom_offset(), and django.contrib.gis.gdal.prototypes.errcheck.check_string().
Variable Documentation
dictionary django.contrib.gis.gdal.error.OGRERR_DICT
Initial value:
 = { 1 : (OGRException, 'Not enough data.'),
                 2 : (OGRException, 'Not enough memory.'),
                 3 : (OGRException, 'Unsupported geometry type.'),
                 4 : (OGRException, 'Unsupported operation.'),
                 5 : (OGRException, 'Corrupt data.'),
                 6 : (OGRException, 'OGR failure.'),
                 7 : (SRSException, 'Unsupported SRS.'),
                 8 : (OGRException, 'Invalid handle.'),
                 }
Definition at line 22 of file error.py.
int django.contrib.gis.gdal.error.OGRERR_NONE = 0
Definition at line 31 of file error.py.