Django: django.contrib.gis.tests.geogapp.tests.GeographyTest Class Reference
django.contrib.gis.tests.geogapp.tests.GeographyTest Class Reference
Public Member Functions
def test01_fixture_load (self)
def test02_distance_lookup (self)
def test03_distance_method (self)
def test04_invalid_operators_functions (self)
def test05_geography_layermapping (self)
def test06_geography_area (self)
Detailed Description
Definition at line 21 of file tests.py.
Member Function Documentation
def django.contrib.gis.tests.geogapp.tests.GeographyTest.test01_fixture_load (self)
Definition at line 23 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.geogapp.tests.GeographyTest.test02_distance_lookup (self)
Definition at line 27 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.gis.measure.D.
def django.contrib.gis.tests.geogapp.tests.GeographyTest.test03_distance_method (self)
Definition at line 41 of file tests.py.
def django.contrib.gis.tests.geogapp.tests.GeographyTest.test04_invalid_operators_functions (self)
Definition at line 47 of file tests.py.
References django.utils.unittest.case.TestCase.assertRaises(), and django.utils.unittest.case.skipUnless().
def django.contrib.gis.tests.geogapp.tests.GeographyTest.test05_geography_layermapping (self)
Definition at line 63 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils._os.upath().
def django.contrib.gis.tests.geogapp.tests.GeographyTest.test06_geography_area (self)
Definition at line 91 of file tests.py.
References django.utils.unittest.case.TestCase.assertAlmostEqual().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/tests/geogapp/tests.py