Django: django.contrib.gis.db.backends.oracle.models.SpatialRefSys Class Reference
django.contrib.gis.db.backends.oracle.models.SpatialRefSys Class Reference
Classes
class Meta
Public Member Functions
def wkt (self)
def wkt_col (cls)
Public Member Functions inherited from django.db.models.base.Model
def __init__ (self, args, kwargs)
def __repr__ (self)
def __str__ (self)
def __eq__ (self, other)
def __ne__ (self, other)
def __hash__ (self)
def __reduce__ (self)
def serializable_value (self, field_name)
def save
def save_base
def delete
def prepare_database_save (self, unused)
def clean (self)
def validate_unique
def date_error_message (self, lookup_type, field, unique_for)
def unique_error_message (self, model_class, unique_check)
def full_clean
def clean_fields
Public Member Functions inherited from django.db.models.base.ModelBase
def __new__ (cls, name, bases, attrs)
def copy_managers (cls, base_managers)
def add_to_class (cls, name, value)
Static Public Attributes
tuple cs_name = models.CharField(max_length=68)
tuple srid = models.IntegerField(primary_key=True)
tuple auth_srid = models.IntegerField()
tuple auth_name = models.CharField(max_length=256)
tuple wktext = models.CharField(max_length=2046)
tuple cs_bounds = models.PolygonField(null=True)
tuple objects = models.GeoManager()
Additional Inherited Members
Properties inherited from django.db.models.base.Model
pk = property(_get_pk_val, _set_pk_val)
Detailed Description
Definition at line 44 of file models.py.
Member Function Documentation
def django.contrib.gis.db.backends.oracle.models.SpatialRefSys.wkt (self)
Definition at line 61 of file models.py.
References django.contrib.gis.db.backends.oracle.models.SpatialRefSys.wktext.
Referenced by django.contrib.gis.gdal.geometries.OGRGeometry.__str__(), and django.contrib.gis.gdal.geometries.OGRGeometry.ewkt().
def django.contrib.gis.db.backends.oracle.models.SpatialRefSys.wkt_col (cls)
Definition at line 65 of file models.py.
Member Data Documentation
tuple django.contrib.gis.db.backends.oracle.models.SpatialRefSys.auth_name = models.CharField(max_length=256) static
Definition at line 49 of file models.py.
tuple django.contrib.gis.db.backends.oracle.models.SpatialRefSys.auth_srid = models.IntegerField() static
Definition at line 48 of file models.py.
tuple django.contrib.gis.db.backends.oracle.models.SpatialRefSys.cs_bounds = models.PolygonField(null=True) static
Definition at line 53 of file models.py.
tuple django.contrib.gis.db.backends.oracle.models.SpatialRefSys.cs_name = models.CharField(max_length=68) static
Definition at line 46 of file models.py.
tuple django.contrib.gis.db.backends.oracle.models.SpatialRefSys.objects = models.GeoManager() static
Definition at line 54 of file models.py.
Referenced by django.core.serializers.pyyaml.Serializer.end_serialization(), and django.core.serializers.python.Serializer.getvalue().
tuple django.contrib.gis.db.backends.oracle.models.SpatialRefSys.srid = models.IntegerField(primary_key=True) static
Definition at line 47 of file models.py.
Referenced by django.contrib.gis.db.backends.postgis.adapter.PostGISAdapter.__eq__(), django.contrib.gis.geos.geometry.GEOSGeometry.__getstate__(), django.contrib.gis.geos.collections.GeometryCollection.__len__(), django.contrib.gis.db.backends.spatialite.models.GeometryColumns.__str__(), django.contrib.gis.db.backends.postgis.models.GeometryColumns.__str__(), django.contrib.gis.geos.collections.MultiPolygon.cascaded_union(), django.contrib.gis.forms.fields.GeometryField.clean(), django.contrib.gis.geos.geometry.GEOSGeometry.clone(), django.contrib.gis.geos.geometry.GEOSGeometry.ewkt(), django.contrib.gis.db.models.fields.GeometryField.formfield(), django.contrib.gis.geos.polygon.Polygon.from_bbox(), django.contrib.gis.gdal.geometries.OGRGeometry.geos(), django.contrib.gis.db.models.fields.GeometryField.get_srid(), django.contrib.gis.geos.geometry.GEOSGeometry.ogr(), django.contrib.gis.geos.geometry.GEOSGeometry.srs(), django.contrib.gis.forms.fields.GeometryField.to_python(), and django.contrib.gis.geos.geometry.GEOSGeometry.transform().
tuple django.contrib.gis.db.backends.oracle.models.SpatialRefSys.wktext = models.CharField(max_length=2046) static
Definition at line 50 of file models.py.
Referenced by django.contrib.gis.db.backends.oracle.models.SpatialRefSys.wkt().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/db/backends/oracle/models.py