Django: django.middleware.csrf.CsrfViewMiddleware Class Reference
django.middleware.csrf.CsrfViewMiddleware Class Reference
Public Member Functions
def process_view (self, request, callback, callback_args, callback_kwargs)
def process_response (self, request, response)
Detailed Description
Middleware that requires a present and correct csrfmiddlewaretoken
for POST requests that have a CSRF cookie, and sets an outgoing
CSRF cookie.
This middleware should be used in conjunction with the csrf_token template
tag.
Definition at line 76 of file csrf.py.
Member Function Documentation
def django.middleware.csrf.CsrfViewMiddleware.process_response (self, request, response)
Definition at line 182 of file csrf.py.
References django.utils.cache.patch_vary_headers().
def django.middleware.csrf.CsrfViewMiddleware.process_view (self, request, callback, callback_args, callback_kwargs)
Definition at line 104 of file csrf.py.
References django.middleware.csrf.CsrfViewMiddleware._accept(), django.middleware.csrf.CsrfViewMiddleware._reject(), and django.utils.crypto.constant_time_compare().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/middleware/csrf.py