Django: django.core.validators Namespace Reference
django.core.validators Namespace Reference
Classes
class BaseValidator
class EmailValidator
class MaxLengthValidator
class MaxValueValidator
class MinLengthValidator
class MinValueValidator
class RegexValidator
class URLValidator
Functions
def validate_integer (value)
def validate_ipv6_address (value)
def validate_ipv46_address (value)
def ip_address_validators (protocol, unpack_ipv4)
Variables
tuple EMPTY_VALUES = (None, '', [], (), {})
tuple validate_email = EmailValidator()
tuple slug_re = re.compile(r'^[-a-zA-Z0-9_]+$')
tuple validate_slug = RegexValidator(slug_re, _("Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens."), 'invalid')
tuple ipv4_re = re.compile(r'^(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3}$')
tuple validate_ipv4_address = RegexValidator(ipv4_re, _('Enter a valid IPv4 address.'), 'invalid')
dictionary ip_address_validator_map
tuple comma_separated_int_list_re = re.compile('^[\d,]+$')
tuple validate_comma_separated_integer_list = RegexValidator(comma_separated_int_list_re, _('Enter only digits separated by commas.'), 'invalid')
Function Documentation
def django.core.validators.ip_address_validators (protocol, unpack_ipv4)
Depending on the given parameters returns the appropriate validators for
the GenericIPAddressField.
This code is here, because it is exactly the same for the model and the form field.
Definition at line 156 of file validators.py.
def django.core.validators.validate_integer (value)
Definition at line 73 of file validators.py.
def django.core.validators.validate_ipv46_address (value)
Definition at line 140 of file validators.py.
References django.core.validators.validate_ipv4_address, and django.core.validators.validate_ipv6_address().
def django.core.validators.validate_ipv6_address (value)
Definition at line 135 of file validators.py.
References django.utils.ipv6.is_valid_ipv6_address().
Referenced by django.core.validators.validate_ipv46_address().
Variable Documentation
tuple django.core.validators.comma_separated_int_list_re = re.compile('^[\d,]+$')
Definition at line 172 of file validators.py.
tuple django.core.validators.EMPTY_VALUES = (None, '', [], (), {})
Definition at line 14 of file validators.py.
dictionary django.core.validators.ip_address_validator_map
Initial value:
 = {
     'both': ([validate_ipv46_address], _('Enter a valid IPv4 or IPv6 address.')),
     'ipv4': ([validate_ipv4_address], _('Enter a valid IPv4 address.')),
     'ipv6': ([validate_ipv6_address], _('Enter a valid IPv6 address.')),
 }
Definition at line 149 of file validators.py.
tuple django.core.validators.ipv4_re = re.compile(r'^(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3}$')
Definition at line 131 of file validators.py.
tuple django.core.validators.slug_re = re.compile(r'^[-a-zA-Z0-9_]+$')
Definition at line 128 of file validators.py.
tuple django.core.validators.validate_comma_separated_integer_list = RegexValidator(comma_separated_int_list_re, _('Enter only digits separated by commas.'), 'invalid')
Definition at line 173 of file validators.py.
tuple django.core.validators.validate_email = EmailValidator()
Definition at line 126 of file validators.py.
tuple django.core.validators.validate_ipv4_address = RegexValidator(ipv4_re, _('Enter a valid IPv4 address.'), 'invalid')
Definition at line 132 of file validators.py.
Referenced by django.utils.ipv6.is_valid_ipv6_address(), and django.core.validators.validate_ipv46_address().
tuple django.core.validators.validate_slug = RegexValidator(slug_re, _("Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens."), 'invalid')
Definition at line 129 of file validators.py.