Django: django.test.utils.IgnoreDeprecationWarningsMixin Class Reference
django.test.utils.IgnoreDeprecationWarningsMixin Class Reference
Public Member Functions
def setUp (self)
def tearDown (self)
Public Attributes
catch_warnings
Static Public Attributes
warning_class = DeprecationWarning
Detailed Description
Definition at line 407 of file utils.py.
Member Function Documentation
def django.test.utils.IgnoreDeprecationWarningsMixin.setUp (self)
Definition at line 411 of file utils.py.
Referenced by django.utils.unittest.case.TestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.test.utils.IgnoreDeprecationWarningsMixin.tearDown (self)
Definition at line 417 of file utils.py.
Referenced by django.utils.unittest.case.TestCase.debug(), and django.utils.unittest.case.TestCase.run().
Member Data Documentation
django.test.utils.IgnoreDeprecationWarningsMixin.catch_warnings
Definition at line 413 of file utils.py.
django.test.utils.IgnoreDeprecationWarningsMixin.warning_class = DeprecationWarning static
Definition at line 409 of file utils.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/test/utils.py