Django: django.utils.dateformat.TimeFormat Class Reference
django.utils.dateformat.TimeFormat Class Reference
Public Member Functions
def __init__ (self, t)
def a (self)
def A (self)
def B (self)
def f (self)
def g (self)
def G (self)
def h (self)
def H (self)
def i (self)
def P (self)
def s (self)
def u (self)
Public Member Functions inherited from django.utils.dateformat.Formatter
def format (self, formatstr)
Public Attributes
data
Detailed Description
Definition at line 40 of file dateformat.py.
Constructor & Destructor Documentation
def django.utils.dateformat.TimeFormat.__init__ (self, t)
Definition at line 41 of file dateformat.py.
Member Function Documentation
def django.utils.dateformat.TimeFormat.a (self)
Definition at line 44 of file dateformat.py.
Referenced by django.utils.dateformat.TimeFormat.P().
def django.utils.dateformat.TimeFormat.A (self)
Definition at line 50 of file dateformat.py.
def django.utils.dateformat.TimeFormat.B (self)
Definition at line 56 of file dateformat.py.
def django.utils.dateformat.TimeFormat.f (self)
Time, in 12-hour hours and minutes, with minutes left off if they're
zero.
Examples: '1', '1:30', '2:05', '2'
Proprietary extension.
Definition at line 60 of file dateformat.py.
References django.utils.dateformat.TimeFormat.g(), and django.utils.dateformat.TimeFormat.i().
Referenced by django.utils.dateformat.TimeFormat.P().
def django.utils.dateformat.TimeFormat.g (self)
Definition at line 71 of file dateformat.py.
Referenced by django.utils.dateformat.TimeFormat.f(), and django.utils.dateformat.TimeFormat.h().
def django.utils.dateformat.TimeFormat.G (self)
Definition at line 79 of file dateformat.py.
Referenced by django.utils.dateformat.TimeFormat.H().
def django.utils.dateformat.TimeFormat.h (self)
Definition at line 83 of file dateformat.py.
References django.utils.dateformat.TimeFormat.g().
def django.utils.dateformat.TimeFormat.H (self)
Definition at line 87 of file dateformat.py.
References django.utils.dateformat.TimeFormat.G().
def django.utils.dateformat.TimeFormat.i (self)
Definition at line 91 of file dateformat.py.
Referenced by django.utils.dateformat.TimeFormat.f().
def django.utils.dateformat.TimeFormat.P (self)
Time, in 12-hour hours, minutes and 'a.m.'/'p.m.', with minutes left off
if they're zero and the strings 'midnight' and 'noon' if appropriate.
Examples: '1 a.m.', '1:30 p.m.', 'midnight', 'noon', '12:30 p.m.'
Proprietary extension.
Definition at line 95 of file dateformat.py.
References django.utils.dateformat.TimeFormat.a(), and django.utils.dateformat.TimeFormat.f().
def django.utils.dateformat.TimeFormat.s (self)
Definition at line 108 of file dateformat.py.
def django.utils.dateformat.TimeFormat.u (self)
Definition at line 112 of file dateformat.py.
Member Data Documentation
django.utils.dateformat.TimeFormat.data
Definition at line 42 of file dateformat.py.
Referenced by django.utils.dateformat.DateFormat.e(), django.utils.dateformat.DateFormat.I(), django.utils.dateformat.DateFormat.T(), django.utils.dateformat.DateFormat.U(), django.forms.forms.BoundField.value(), and django.utils.dateformat.DateFormat.Z().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/utils/dateformat.py