Django: django.http.response.CompatibleStreamingHttpResponse Class Reference
django.http.response.CompatibleStreamingHttpResponse Class Reference
Public Member Functions
def content (self)
def content (self, content)
Public Member Functions inherited from django.http.response.StreamingHttpResponse
def __init__ (self, streaming_content=(), args, kwargs)
def content (self)
def streaming_content (self)
def streaming_content (self, value)
Public Member Functions inherited from django.http.response.HttpResponseBase
def __init__
def serialize_headers (self)
def __setitem__ (self, header, value)
def __delitem__ (self, header)
def __getitem__ (self, header)
def __getstate__ (self)
def __setstate__ (self, state)
def has_header (self, header)
def items (self)
def get
def set_cookie
def set_signed_cookie (self, key, value, salt='', kwargs)
def delete_cookie
def make_bytes (self, value)
def __iter__ (self)
def __next__ (self)
def close (self)
def write (self, content)
def flush (self)
def tell (self)
Public Attributes
streaming_content
Public Attributes inherited from django.http.response.StreamingHttpResponse
streaming_content
Public Attributes inherited from django.http.response.HttpResponseBase
cookies
status_code
Additional Inherited Members
Static Public Attributes inherited from django.http.response.StreamingHttpResponse
streaming = True
Static Public Attributes inherited from django.http.response.HttpResponseBase
int status_code = 200
reason_phrase = None
Detailed Description
This class maintains compatibility with middleware that doesn't know how
to handle the content of a streaming response by exposing a `content`
attribute that will consume and cache the content iterator when accessed.
These responses will stream only if no middleware attempts to access the
`content` attribute. Otherwise, they will behave like a regular response,
and raise a `DeprecationWarning`.
Definition at line 424 of file response.py.
Member Function Documentation
def django.http.response.CompatibleStreamingHttpResponse.content (self)
Definition at line 435 of file response.py.
References django.template.defaultfilters.join().
Referenced by django.http.response.CompatibleStreamingHttpResponse.content().
def django.http.response.CompatibleStreamingHttpResponse.content (self, content)
Definition at line 445 of file response.py.
References django.http.response.CompatibleStreamingHttpResponse.content(), and django.http.response.StreamingHttpResponse.streaming_content.
Member Data Documentation
django.http.response.CompatibleStreamingHttpResponse.streaming_content
Definition at line 441 of file response.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/http/response.py