Django: django.contrib.auth.tests.test_models.UserManagerTestCase Class Reference
django.contrib.auth.tests.test_models.UserManagerTestCase Class Reference
Public Member Functions
def test_create_user (self)
def test_create_user_email_domain_normalize_rfc3696 (self)
def test_create_user_email_domain_normalize (self)
def test_create_user_email_domain_normalize_with_whitespace (self)
def test_empty_username (self)
Detailed Description
Definition at line 85 of file test_models.py.
Member Function Documentation
def django.contrib.auth.tests.test_models.UserManagerTestCase.test_create_user (self)
Definition at line 87 of file test_models.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertFalse().
def django.contrib.auth.tests.test_models.UserManagerTestCase.test_create_user_email_domain_normalize (self)
Definition at line 100 of file test_models.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.auth.tests.test_models.UserManagerTestCase.test_create_user_email_domain_normalize_rfc3696 (self)
Definition at line 94 of file test_models.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.auth.tests.test_models.UserManagerTestCase.test_create_user_email_domain_normalize_with_whitespace (self)
Definition at line 104 of file test_models.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.auth.tests.test_models.UserManagerTestCase.test_empty_username (self)
Definition at line 108 of file test_models.py.
References django.test.testcases.SimpleTestCase.assertRaisesMessage().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_models.py