Django: django.utils.dateparse Namespace Reference
django.utils.dateparse Namespace Reference
Functions
def parse_date (value)
def parse_time (value)
def parse_datetime (value)
Variables
tuple date_re
tuple time_re
tuple datetime_re
Detailed Description
Functions to parse datetime objects.
Function Documentation
def django.utils.dateparse.parse_date (value)
Parses a string and return a datetime.date.
Raises ValueError if the input is well formatted but not a valid date.
Returns None if the input isn't well formatted.
Definition at line 30 of file dateparse.py.
Referenced by django.db.backends.sqlite3.base.DatabaseOperations.convert_values(), django.db.models.fields.DateField.to_python(), and django.db.models.fields.DateTimeField.to_python().
def django.utils.dateparse.parse_datetime (value)
Parses a string and return a datetime.datetime.
This function supports time zone offsets. When the input contains one,
the output uses an instance of FixedOffset as tzinfo.
Raises ValueError if the input is well formatted but not a valid datetime.
Returns None if the input isn't well formatted.
Definition at line 58 of file dateparse.py.
References django.template.defaultfilters.ljust().
def django.utils.dateparse.parse_time (value)
Parses a string and return a datetime.time.
This function doesn't support time zone offsets.
Raises ValueError if the input is well formatted but not a valid time.
Returns None if the input isn't well formatted, in particular if it
contains an offset.
Definition at line 41 of file dateparse.py.
References django.template.defaultfilters.ljust().
Referenced by django.db.backends.sqlite3.base.DatabaseOperations.convert_values(), and django.db.models.fields.TimeField.to_python().
Variable Documentation
tuple django.utils.dateparse.date_re
Initial value:
 = re.compile(
     r'(?P<year>\d{4})-(?P<month>\d{1,2})-(?P<day>\d{1,2})$'
 )
Definition at line 14 of file dateparse.py.
tuple django.utils.dateparse.datetime_re
Initial value:
 = re.compile(
     r'(?P<year>\d{4})-(?P<month>\d{1,2})-(?P<day>\d{1,2})'
     r'[T ](?P<hour>\d{1,2}):(?P<minute>\d{1,2})'
     r'(?::(?P<second>\d{1,2})(?:\.(?P<microsecond>\d{1,6})\d{0,6})?)?'
     r'(?P<tzinfo>Z|[+-]\d{2}:?\d{2})?$'
 )
Definition at line 23 of file dateparse.py.
tuple django.utils.dateparse.time_re
Initial value:
 = re.compile(
     r'(?P<hour>\d{1,2}):(?P<minute>\d{1,2})'
     r'(?::(?P<second>\d{1,2})(?:\.(?P<microsecond>\d{1,6})\d{0,6})?)?'
 )
Definition at line 18 of file dateparse.py.