Django: django.core.management.commands.shell.Command Class Reference
django.core.management.commands.shell.Command Class Reference
Public Member Functions
def ipython (self)
def bpython (self)
def run_shell
def handle_noargs (self, options)
Public Member Functions inherited from django.core.management.base.NoArgsCommand
def handle (self, args, options)
def handle_noargs (self, options)
Public Member Functions inherited from django.core.management.base.BaseCommand
def __init__ (self)
def get_version (self)
def usage (self, subcommand)
def create_parser (self, prog_name, subcommand)
def print_help (self, prog_name, subcommand)
def run_from_argv (self, argv)
def execute (self, args, options)
def validate
def handle (self, args, options)
Static Public Attributes
list shells = ['ipython', 'bpython']
tuple option_list
string help = "Runs a Python interactive interpreter. Tries to use IPython or bpython, if one of them is available."
requires_model_validation = False
Static Public Attributes inherited from django.core.management.base.NoArgsCommand
string args = ''
Static Public Attributes inherited from django.core.management.base.BaseCommand
tuple option_list
string help = ''
string args = ''
can_import_settings = True
requires_model_validation = True
output_transaction = False
leave_locale_alone = False
Additional Inherited Members
Public Attributes inherited from django.core.management.base.BaseCommand
style
stdout
stderr
Detailed Description
Definition at line 6 of file shell.py.
Member Function Documentation
def django.core.management.commands.shell.Command.bpython (self)
Definition at line 52 of file shell.py.
def django.core.management.commands.shell.Command.handle_noargs (self, options)
Definition at line 66 of file shell.py.
References django.db.models.loading.get_models, and django.core.management.commands.shell.Command.run_shell().
def django.core.management.commands.shell.Command.ipython (self)
Start any version of IPython
Definition at line 40 of file shell.py.
References django.core.management.commands.shell.Command._ipython(), django.core.management.commands.shell.Command._ipython_pre_011(), and django.core.management.commands.shell.Command._ipython_pre_100().
def django.core.management.commands.shell.Command.run_shell (self, shell = None)
Definition at line 56 of file shell.py.
References django.core.management.commands.shell.Command.shells.
Referenced by django.core.management.commands.shell.Command.handle_noargs().
Member Data Documentation
string django.core.management.commands.shell.Command.help = "Runs a Python interactive interpreter. Tries to use IPython or bpython, if one of them is available." static
Definition at line 19 of file shell.py.
tuple django.core.management.commands.shell.Command.option_list static
Initial value:
 = NoArgsCommand.option_list+(
         make_option('--plain', action='store_true', dest='plain',
             help='Tells Django to use plain Python, not IPython or bpython.'),
         make_option('--no-startup', action='store_true', dest='no_startup',
             help='When using plain Python, ignore the PYTHONSTARTUP environment variable and ~/.pythonrc.py script.'),
         make_option('-i', '--interface', action='store', type='choice', choices=shells,
                     dest='interface',
             help='Specify an interactive interpreter interface. Available options: "ipython" and "bpython"'),
     )
Definition at line 9 of file shell.py.
django.core.management.commands.shell.Command.requires_model_validation = False static
Definition at line 20 of file shell.py.
list django.core.management.commands.shell.Command.shells = ['ipython', 'bpython'] static
Definition at line 7 of file shell.py.
Referenced by django.core.management.commands.shell.Command.run_shell().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/core/management/commands/shell.py