Django: django.contrib.humanize.templatetags.humanize Namespace Reference
django.contrib.humanize.templatetags.humanize Namespace Reference
Functions
def ordinal (value)
def intcomma
def intword (value)
def apnumber (value)
def naturalday
def naturaltime (value)
Variables
tuple register = template.Library()
tuple intword_converters
Function Documentation
def django.contrib.humanize.templatetags.humanize.apnumber (value)
For numbers 1-9, returns the number spelled out. Otherwise, returns the
number. This follows Associated Press style.
Definition at line 136 of file humanize.py.
def django.contrib.humanize.templatetags.humanize.intcomma (value, use_l10n = True)
Converts an integer to a string containing commas every three digits.
For example, 3000 becomes '3,000' and 45000 becomes '45,000'.
Definition at line 34 of file humanize.py.
References django.utils.encoding.force_text(), and django.utils.formats.number_format().
def django.contrib.humanize.templatetags.humanize.intword (value)
Converts a large integer to a friendly text representation. Works best
for numbers over 1 million. For example, 1000000 becomes '1.0 million',
1200000 becomes '1.2 million' and '1200000000' becomes '1.2 billion'.
Definition at line 103 of file humanize.py.
def django.contrib.humanize.templatetags.humanize.naturalday (value, arg = None)
For date values that are tomorrow, today or yesterday compared to
present day returns representing string. Otherwise, returns a string
formatted according to settings.DATE_FORMAT.
Definition at line 152 of file humanize.py.
References django.template.defaultfilters.date().
def django.contrib.humanize.templatetags.humanize.naturaltime (value)
For date and time values shows how many seconds, minutes or hours ago
compared to current timestamp returns representing string.
Definition at line 180 of file humanize.py.
References django.utils.timezone.is_aware(), django.utils.translation.pgettext(), and django.utils.translation.trans_real.ungettext.
def django.contrib.humanize.templatetags.humanize.ordinal (value)
Converts an integer to its ordinal as a string. 1 is '1st', 2 is '2nd',
3 is '3rd', etc. Works for any integer.
Definition at line 19 of file humanize.py.
Variable Documentation
tuple django.contrib.humanize.templatetags.humanize.intword_converters
Definition at line 55 of file humanize.py.
tuple django.contrib.humanize.templatetags.humanize.register = template.Library()
Definition at line 16 of file humanize.py.