Django: django.core.servers.fastcgi Namespace Reference
django.core.servers.fastcgi Namespace Reference
Functions
def fastcgi_help
def runfastcgi (argset=[], kwargs)
Variables
string __version__ = "0.1"
list __all__ = ["runfastcgi"]
dictionary FASTCGI_OPTIONS
string FASTCGI_HELP = r""
Detailed Description
FastCGI (or SCGI, or AJP1.3 ...) server that implements the WSGI protocol.
Uses the flup python package: http://www.saddi.com/software/flup/
This is a adaptation of the flup package to add FastCGI server support
to run Django apps from Web servers that support the FastCGI protocol.
This module can be run standalone or from the django-admin / manage.py
scripts using the "runfcgi" directive.
Run with the extra option "help" for a list of additional options you can
pass to this server.
Function Documentation
def django.core.servers.fastcgi.fastcgi_help (message = None)
Definition at line 84 of file fastcgi.py.
Referenced by django.core.servers.fastcgi.runfastcgi().
def django.core.servers.fastcgi.runfastcgi (argset = [], kwargs)
Definition at line 90 of file fastcgi.py.
References django.utils.daemonize.become_daemon(), django.core.servers.fastcgi.fastcgi_help(), django.core.servers.basehttp.get_internal_wsgi_application(), django.template.defaultfilters.lower(), and django.contrib.gis.tests.test_measure.run().
Referenced by django.core.management.commands.runfcgi.Command.handle().
Variable Documentation
list django.core.servers.fastcgi.__all__ = ["runfastcgi"]
Definition at line 20 of file fastcgi.py.
string django.core.servers.fastcgi.__version__ = "0.1"
Definition at line 19 of file fastcgi.py.
string django.core.servers.fastcgi.FASTCGI_HELP = r""
Definition at line 41 of file fastcgi.py.
dictionary django.core.servers.fastcgi.FASTCGI_OPTIONS
Initial value:
 = {
     'protocol': 'fcgi',
     'host': None,
     'port': None,
     'socket': None,
     'method': 'fork',
     'daemonize': None,
     'workdir': '/',
     'pidfile': None,
     'maxspare': 5,
     'minspare': 2,
     'maxchildren': 50,
     'maxrequests': 0,
     'debug': None,
     'outlog': None,
     'errlog': None,
     'umask': None,
 }
Definition at line 22 of file fastcgi.py.