Django: django.views.decorators.cache Namespace Reference
django.views.decorators.cache Namespace Reference
Functions
def cache_page (args, kwargs)
def cache_control (kwargs)
def never_cache (view_func)
Function Documentation
def django.views.decorators.cache.cache_control (kwargs)
Definition at line 34 of file cache.py.
References django.utils.decorators.available_attrs(), django.utils.cache.patch_cache_control(), and django.utils.six.wraps.
def django.views.decorators.cache.cache_page (args, kwargs)
Decorator for views that tries getting the page from the cache and
populates the cache if the page isn't in the cache yet.
The cache is keyed by the URL and some data from the headers.
Additionally there is the key prefix that is used to distinguish different
cache areas in a multi-site setup. You could use the
sites.get_current_site().domain, for example, as that is unique across a Django
project.
Additionally, all headers from the response's Vary header will be taken
into account on caching -- just like the middleware does.
Definition at line 7 of file cache.py.
References django.utils.six.callable, and django.utils.decorators.decorator_from_middleware_with_args().
def django.views.decorators.cache.never_cache (view_func)
Decorator that adds headers to a response so that it will
never be cached.
Definition at line 45 of file cache.py.
References django.utils.cache.add_never_cache_headers(), django.utils.decorators.available_attrs(), and django.utils.six.wraps.
Referenced by django.contrib.admin.sites.AdminSite.admin_view().