Django: django.db.models.fields.files.ImageField Class Reference
django.db.models.fields.files.ImageField Class Reference
Public Member Functions
def __init__ (self, verbose_name=None, name=None, width_field=None, height_field=None, kwargs)
def contribute_to_class (self, cls, name)
def update_dimension_fields (self, instance, force=False, args, kwargs)
def formfield (self, kwargs)
Public Member Functions inherited from django.db.models.fields.files.FileField
def __init__ (self, verbose_name=None, name=None, upload_to='', storage=None, kwargs)
def get_internal_type (self)
def get_prep_lookup (self, lookup_type, value)
def get_prep_value (self, value)
def pre_save (self, model_instance, add)
def contribute_to_class (self, cls, name)
def get_directory_name (self)
def get_filename (self, filename)
def generate_filename (self, instance, filename)
def save_form_data (self, instance, data)
def formfield (self, kwargs)
Public Member Functions inherited from django.db.models.fields.Field
def __init__
def __eq__ (self, other)
def __lt__ (self, other)
def __hash__ (self)
def __deepcopy__ (self, memodict)
def __copy__ (self)
def __reduce__ (self)
def to_python (self, value)
def run_validators (self, value)
def validate (self, value, model_instance)
def clean (self, value, model_instance)
def db_type (self, connection)
def unique (self)
def set_attributes_from_name (self, name)
def contribute_to_class
def get_attname (self)
def get_attname_column (self)
def get_cache_name (self)
def get_internal_type (self)
def pre_save (self, model_instance, add)
def get_prep_value (self, value)
def get_db_prep_value
def get_db_prep_save (self, value, connection)
def get_prep_lookup (self, lookup_type, value)
def get_db_prep_lookup
def has_default (self)
def get_default (self)
def get_validator_unique_lookup_type (self)
def get_choices
def get_choices_default (self)
def get_flatchoices
def value_to_string (self, obj)
def bind (self, fieldmapping, original, bound_field_class)
def save_form_data (self, instance, data)
def formfield (self, form_class=None, choices_form_class=None, kwargs)
def value_from_object (self, obj)
def __repr__ (self)
Public Attributes
height_field
Public Attributes inherited from django.db.models.fields.files.FileField
storage
upload_to
generate_filename
Public Attributes inherited from django.db.models.fields.Field
name
verbose_name
primary_key
null
rel
default
editable
serialize
unique_for_month
unique_for_year
help_text
db_column
db_tablespace
auto_created
db_index
creation_counter
validators
error_messages
column
model
Static Public Attributes
attr_class = ImageFieldFile
descriptor_class = ImageFileDescriptor
tuple description = _("Image")
Static Public Attributes inherited from django.db.models.fields.files.FileField
attr_class = FieldFile
descriptor_class = FileDescriptor
tuple description = _("File")
Static Public Attributes inherited from django.db.models.fields.Field
empty_strings_allowed = True
tuple empty_values = list(validators.EMPTY_VALUES)
int creation_counter = 0
int auto_creation_counter = -1
list default_validators = []
dictionary default_error_messages
Additional Inherited Members
Properties inherited from django.db.models.fields.Field
description = property(_description)
choices = property(_get_choices)
flatchoices = property(_get_flatchoices)
Detailed Description
Definition at line 321 of file files.py.
Constructor & Destructor Documentation
def django.db.models.fields.files.ImageField.__init__ (self, verbose_name = None, name = None, width_field = None, height_field = None, kwargs)
Definition at line 327 of file files.py.
Member Function Documentation
def django.db.models.fields.files.ImageField.contribute_to_class (self, cls, name)
Definition at line 331 of file files.py.
References django.db.models.fields.files.ImageField.update_dimension_fields().
def django.db.models.fields.files.ImageField.formfield (self, kwargs)
Definition at line 394 of file files.py.
def django.db.models.fields.files.ImageField.update_dimension_fields (self, instance, force = False, args, kwargs)
Updates field's width and height fields, if defined.
This method is hooked up to model's post_init signal to update
dimensions after instantiating a model instance.  However, dimensions
won't be updated if the dimensions fields are already populated.  This
avoids unnecessary recalculation when loading an object from the
database.
Dimensions can be forced to update with force=True, which is how
ImageFileDescriptor.__set__ calls this method.
Definition at line 338 of file files.py.
References django.db.models.fields.files.ImageField.height_field.
Referenced by django.db.models.fields.files.ImageField.contribute_to_class().
Member Data Documentation
django.db.models.fields.files.ImageField.attr_class = ImageFieldFile static
Definition at line 322 of file files.py.
tuple django.db.models.fields.files.ImageField.description = _("Image") static
Definition at line 324 of file files.py.
Referenced by django.utils.unittest.suite._ErrorHolder.__repr__(), and django.utils.unittest.suite._ErrorHolder.id().
django.db.models.fields.files.ImageField.descriptor_class = ImageFileDescriptor static
Definition at line 323 of file files.py.
django.db.models.fields.files.ImageField.height_field
Definition at line 328 of file files.py.
Referenced by django.db.models.fields.files.ImageField.update_dimension_fields().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/db/models/fields/files.py