Django: django.contrib.gis.db.models.proxy.GeometryProxy Class Reference
django.contrib.gis.db.models.proxy.GeometryProxy Class Reference
Public Member Functions
def __init__ (self, klass, field)
def __get__
def __set__ (self, obj, value)
Detailed Description
Definition at line 11 of file proxy.py.
Constructor & Destructor Documentation
def django.contrib.gis.db.models.proxy.GeometryProxy.__init__ (self, klass, field)
Proxy initializes on the given Geometry class (not an instance) and
the GeometryField.
Definition at line 12 of file proxy.py.
References django.contrib.gis.db.models.proxy.GeometryProxy._field, and django.contrib.gis.db.models.proxy.GeometryProxy._klass.
Member Function Documentation
def django.contrib.gis.db.models.proxy.GeometryProxy.__get__ (self, obj, type = None)
This accessor retrieves the geometry, initializing it using the geometry
class specified during initialization and the HEXEWKB value of the field.
Currently, only GEOS or OGR geometries are supported.
Definition at line 20 of file proxy.py.
References django.contrib.gis.db.models.proxy.GeometryProxy._klass.
Referenced by django.db.models.fields.related.ForeignRelatedObjectsDescriptor.__set__(), django.db.models.fields.related.ManyRelatedObjectsDescriptor.__set__(), and django.db.models.fields.related.ReverseManyRelatedObjectsDescriptor.__set__().
def django.contrib.gis.db.models.proxy.GeometryProxy.__set__ (self, obj, value)
This accessor sets the proxied geometry with the geometry class
specified during initialization.  Values of None, HEXEWKB, or WKT may
be used to set the geometry as well.
Definition at line 44 of file proxy.py.
References django.contrib.gis.db.models.proxy.GeometryProxy._klass, and django.template.defaultfilters.upper().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/db/models/proxy.py