Django: django.db.models.sql.query Namespace Reference
django.db.models.sql.query Namespace Reference
Classes
class Query
class RawQuery
Functions
def get_order_dir
def add_to_dict (data, key, value)
def is_reverse_o2o (field)
def alias_diff (refcounts_before, refcounts_after)
Variables
list __all__ = ['Query', 'RawQuery']
Detailed Description
Create SQL statements for QuerySets.
The code in here encapsulates all of the SQL construction so that QuerySets
themselves do not have to (and could be backed by things other than SQL
databases). The abstraction barrier only works one way: this module has to know
all about the internals of models in order to get the information it needs.
Function Documentation
def django.db.models.sql.query.add_to_dict (data, key, value)
A helper function to add "value" to the set of values for "key", whether or
not "key" already exists.
Definition at line 1907 of file query.py.
References django.contrib.messages.tests.urls.add().
Referenced by django.db.models.sql.query.Query.deferred_to_data().
def django.db.models.sql.query.alias_diff (refcounts_before, refcounts_after)
Given the before and after copies of refcounts works out which aliases
have been added to the after copy.
Definition at line 1924 of file query.py.
Referenced by django.db.models.sql.query.Query.add_q().
def django.db.models.sql.query.get_order_dir (field, default = 'ASC')
Returns the field name and direction for an order specification. For
example, '-foo' is returned as ('foo', 'DESC').
The 'default' param is used to indicate which way no prefix (or a '+'
prefix) should sort. The '-' prefix always sorts the opposite way.
Definition at line 1893 of file query.py.
Referenced by django.db.models.sql.compiler.SQLCompiler.find_ordering_name(), and django.db.models.sql.compiler.SQLCompiler.get_ordering().
def django.db.models.sql.query.is_reverse_o2o (field)
A little helper to check if the given field is reverse-o2o. The field is
expected to be some sort of relation field or related object.
Definition at line 1917 of file query.py.
Referenced by django.db.models.sql.query.Query.deferred_to_data().
Variable Documentation
list django.db.models.sql.query.__all__ = ['Query', 'RawQuery']
Definition at line 31 of file query.py.