Django: django.contrib.gis.gdal.prototypes.errcheck Namespace Reference
django.contrib.gis.gdal.prototypes.errcheck Namespace Reference
Functions
def arg_byref
def ptr_byref
def check_bool (result, func, cargs)
def check_const_string
String checking Routines ###.
def check_string
def check_envelope
DataSource, Layer error-checking ###.
def check_geom (result, func, cargs)
Geometry error-checking routines ###.
def check_geom_offset
def check_srs (result, func, cargs)
Spatial Reference error-checking routines ###.
def check_arg_errcode (result, func, cargs)
Other error-checking routines ###.
def check_errcode (result, func, cargs)
def check_pointer (result, func, cargs)
def check_str_arg (result, func, cargs)
Detailed Description
 This module houses the error-checking routines used by the GDAL
 ctypes prototypes.
Function Documentation
def django.contrib.gis.gdal.prototypes.errcheck.arg_byref (args, offset = -1)
Definition at line 12 of file errcheck.py.
Referenced by django.contrib.gis.gdal.prototypes.errcheck.check_arg_errcode().
def django.contrib.gis.gdal.prototypes.errcheck.check_arg_errcode (result, func, cargs)
Other error-checking routines ###.
The error code is returned in the last argument, by reference.
Check its value with `check_err` before returning the result.
Definition at line 96 of file errcheck.py.
References django.contrib.gis.gdal.prototypes.errcheck.arg_byref(), and django.contrib.gis.gdal.error.check_err().
def django.contrib.gis.gdal.prototypes.errcheck.check_bool (result, func, cargs)
Definition at line 20 of file errcheck.py.
def django.contrib.gis.gdal.prototypes.errcheck.check_const_string (result, func, cargs, offset = None)
String checking Routines ###.
Similar functionality to `check_string`, but does not free the pointer.
Definition at line 26 of file errcheck.py.
References django.contrib.gis.gdal.error.check_err(), and django.contrib.gis.gdal.prototypes.errcheck.ptr_byref().
Referenced by django.contrib.gis.gdal.prototypes.generation.const_string_output().
def django.contrib.gis.gdal.prototypes.errcheck.check_envelope (result, func, cargs, offset = -1)
DataSource, Layer error-checking ###.
Envelope checking ###
Definition at line 65 of file errcheck.py.
References django.contrib.gis.gdal.prototypes.errcheck.ptr_byref().
def django.contrib.gis.gdal.prototypes.errcheck.check_errcode (result, func, cargs)
Check the error code returned (c_int).
Definition at line 104 of file errcheck.py.
References django.contrib.gis.gdal.error.check_err().
def django.contrib.gis.gdal.prototypes.errcheck.check_geom (result, func, cargs)
Geometry error-checking routines ###.
Definition at line 71 of file errcheck.py.
Referenced by django.contrib.gis.gdal.prototypes.errcheck.check_geom_offset().
def django.contrib.gis.gdal.prototypes.errcheck.check_geom_offset (result, func, cargs, offset = -1)
Definition at line 81 of file errcheck.py.
References django.contrib.gis.gdal.error.check_err(), django.contrib.gis.gdal.prototypes.errcheck.check_geom(), and django.contrib.gis.gdal.prototypes.errcheck.ptr_byref().
Referenced by django.contrib.gis.gdal.prototypes.generation.geom_output().
def django.contrib.gis.gdal.prototypes.errcheck.check_pointer (result, func, cargs)
Definition at line 111 of file errcheck.py.
def django.contrib.gis.gdal.prototypes.errcheck.check_srs (result, func, cargs)
Spatial Reference error-checking routines ###.
Definition at line 88 of file errcheck.py.
def django.contrib.gis.gdal.prototypes.errcheck.check_str_arg (result, func, cargs)
This is for the OSRGet[Angular|Linear]Units functions, which
require that the returned string pointer not be freed.  This
returns both the double and tring values.
Definition at line 120 of file errcheck.py.
def django.contrib.gis.gdal.prototypes.errcheck.check_string (result, func, cargs, offset = -1, str_result = False)
Checks the string output returned from the given function, and frees
the string pointer allocated by OGR.  The `str_result` keyword
may be used when the result is the string pointer, otherwise
the OGR error code is assumed.  The `offset` keyword may be used
to extract the string pointer passed in by-reference at the given
slice offset in the function arguments.
Definition at line 37 of file errcheck.py.
References django.contrib.gis.gdal.error.check_err(), and django.contrib.gis.gdal.prototypes.errcheck.ptr_byref().
Referenced by django.contrib.gis.gdal.prototypes.generation.string_output().
def django.contrib.gis.gdal.prototypes.errcheck.ptr_byref (args, offset = -1)
Definition at line 16 of file errcheck.py.
Referenced by django.contrib.gis.gdal.prototypes.errcheck.check_const_string(), django.contrib.gis.gdal.prototypes.errcheck.check_envelope(), django.contrib.gis.gdal.prototypes.errcheck.check_geom_offset(), and django.contrib.gis.gdal.prototypes.errcheck.check_string().