Django: django.contrib.gis.gdal.prototypes.generation Namespace Reference
django.contrib.gis.gdal.prototypes.generation Namespace Reference
Classes
class gdal_char_p
Functions
def double_output
def geom_output
def int_output (func, argtypes)
def srs_output (func, argtypes)
def const_string_output
def string_output
def void_output
def voidptr_output (func, argtypes)
Detailed Description
 This module contains functions that generate ctypes prototypes for the
 GDAL routines.
Function Documentation
def django.contrib.gis.gdal.prototypes.generation.const_string_output (func, argtypes, offset = None, decoding = None)
Definition at line 60 of file generation.py.
References django.contrib.gis.gdal.prototypes.errcheck.check_const_string().
def django.contrib.gis.gdal.prototypes.generation.double_output (func, argtypes, errcheck = False, strarg = False)
Definition at line 14 of file generation.py.
Referenced by django.contrib.gis.gdal.prototypes.geom.pnt_func(), django.contrib.gis.gdal.prototypes.srs.srs_double(), and django.contrib.gis.gdal.prototypes.srs.units_func().
def django.contrib.gis.gdal.prototypes.generation.geom_output (func, argtypes, offset = None)
Generates a function that returns a Geometry either by reference
or directly (if the return_geom keyword is set to True).
Definition at line 22 of file generation.py.
References django.contrib.gis.gdal.prototypes.errcheck.check_geom_offset().
def django.contrib.gis.gdal.prototypes.generation.int_output (func, argtypes)
Definition at line 43 of file generation.py.
def django.contrib.gis.gdal.prototypes.generation.srs_output (func, argtypes)
Generates a ctypes prototype for the given function with
the given C arguments that returns a pointer to an OGR
Spatial Reference System.
Definition at line 49 of file generation.py.
def django.contrib.gis.gdal.prototypes.generation.string_output (func, argtypes, offset = -1, str_result = False, decoding = None)
Generates a ctypes prototype for the given function with the
given argument types that returns a string from a GDAL pointer.
The `const` flag indicates whether the allocated pointer should
be freed via the GDAL library routine VSIFree -- but only applies
only when `str_result` is True.
Definition at line 76 of file generation.py.
References django.contrib.gis.gdal.prototypes.errcheck.check_string().
def django.contrib.gis.gdal.prototypes.generation.void_output (func, argtypes, errcheck = True)
For functions that don't only return an error code that needs to
be examined.
Definition at line 104 of file generation.py.
def django.contrib.gis.gdal.prototypes.generation.voidptr_output (func, argtypes)
Definition at line 120 of file generation.py.