Django: django.utils.text.StreamingBuffer Class Reference
django.utils.text.StreamingBuffer Class Reference
Public Member Functions
def __init__ (self)
def write (self, val)
def read (self)
def flush (self)
def close (self)
Public Attributes
vals
Detailed Description
Definition at line 276 of file text.py.
Constructor & Destructor Documentation
def django.utils.text.StreamingBuffer.__init__ (self)
Definition at line 277 of file text.py.
Member Function Documentation
def django.utils.text.StreamingBuffer.close (self)
Definition at line 291 of file text.py.
Referenced by django.core.servers.basehttp.ServerHandler.finish_response().
def django.utils.text.StreamingBuffer.flush (self)
Definition at line 288 of file text.py.
def django.utils.text.StreamingBuffer.read (self)
Definition at line 283 of file text.py.
References django.template.defaultfilters.join(), and django.utils.text.StreamingBuffer.vals.
def django.utils.text.StreamingBuffer.write (self, val)
Definition at line 280 of file text.py.
Referenced by django.utils.unittest.runner._WritelnDecorator.writeln().
Member Data Documentation
django.utils.text.StreamingBuffer.vals
Definition at line 278 of file text.py.
Referenced by django.utils.text.StreamingBuffer.read().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/utils/text.py