Django: django.contrib.auth.tests.test_tokens.TokenGeneratorTest Class Reference
django.contrib.auth.tests.test_tokens.TokenGeneratorTest Class Reference
Public Member Functions
def test_make_token (self)
def test_10265 (self)
def test_timeout (self)
def test_date_length (self)
Detailed Description
Definition at line 13 of file test_tokens.py.
Member Function Documentation
def django.contrib.auth.tests.test_tokens.TokenGeneratorTest.test_10265 (self)
Ensure that the token generated for a user created in the same request
will work correctly.
Definition at line 24 of file test_tokens.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.auth.tests.test_tokens.TokenGeneratorTest.test_date_length (self)
Make sure we don't allow overly long dates, causing a potential DoS.
Definition at line 59 of file test_tokens.py.
References django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.auth.tests.test_tokens.TokenGeneratorTest.test_make_token (self)
Ensure that we can make a token and that it is valid
Definition at line 15 of file test_tokens.py.
References django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.auth.tests.test_tokens.TokenGeneratorTest.test_timeout (self)
Ensure we can use the token after n days, but no greater.
Definition at line 37 of file test_tokens.py.
References django.contrib.auth.tests.test_tokens.TokenGeneratorTest._today_val, django.utils.unittest.case.TestCase.assertFalse(), and django.utils.unittest.case.TestCase.assertTrue().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_tokens.py