Django: django.utils.translation.trans_real Namespace Reference
django.utils.translation.trans_real Namespace Reference
Classes
class DjangoTranslation
Functions
def to_locale
def to_language (locale)
def translation (language)
def activate (language)
def deactivate ()
def deactivate_all ()
def get_language ()
def get_language_bidi ()
def catalog ()
def do_translate (message, translation_function)
def gettext (message)
def ugettext (message)
def pgettext (context, message)
def gettext_noop (message)
def do_ntranslate (singular, plural, number, translation_function)
def ngettext (singular, plural, number)
def ungettext (singular, plural, number)
def npgettext (context, singular, plural, number)
def all_locale_paths ()
def check_for_language (lang_code)
def get_supported_language_variant
def get_language_from_path
def get_language_from_request
def blankout (src, char)
def templatize
def parse_accept_lang_header (lang_string)
Variables
dictionary _translations = {}
tuple _active = local()
_default = None
dictionary _accepted = {}
dictionary _checked_languages = {}
string CONTEXT_SEPARATOR = "\x04"
tuple accept_language_re = re.compile(r, re.VERBOSE)
tuple language_code_prefix_re = re.compile(r'^/([\w-]+)(/|$)')
ugettext = gettext
ungettext = ngettext
tuple check_for_language = memoize(check_for_language, _checked_languages, 1)
tuple dot_re = re.compile(r'\S')
tuple context_re = re.compile(r)
tuple inline_re = re.compile(r)
tuple block_re = re.compile(r)
tuple endblock_re = re.compile(r)
tuple plural_re = re.compile(r)
tuple constant_re = re.compile(r)
tuple one_percent_re = re.compile(r)
Detailed Description
Translation helper functions.
Function Documentation
def django.utils.translation.trans_real.activate (language)
Fetches the translation object for a given tuple of application name and
language and installs it as the current translation object for the current
thread.
Definition at line 182 of file trans_real.py.
References django.utils.translation.trans_real.translation().
def django.utils.translation.trans_real.all_locale_paths ()
Returns a list of paths to user-provides languages files.
Definition at line 341 of file trans_real.py.
References django.utils._os.upath().
Referenced by django.utils.translation.trans_real.check_for_language().
def django.utils.translation.trans_real.blankout (src, char)
Changes every non-whitespace character to the given char.
Used in the templatize function.
Definition at line 473 of file trans_real.py.
Referenced by django.utils.translation.trans_real.templatize().
def django.utils.translation.trans_real.catalog ()
Returns the current active catalog for further processing.
This can be used if you need to modify the catalog or want to access the
whole message catalog instead of just translating one string.
Definition at line 230 of file trans_real.py.
References django.utils.translation.trans_real.translation().
def django.utils.translation.trans_real.check_for_language (lang_code)
Checks whether there is a global language file for the given language
code. This is used to decide whether a user-provided language is
available. This is only used for language codes from either the cookies
or session and during format localization.
Definition at line 350 of file trans_real.py.
References django.utils.translation.trans_real.all_locale_paths(), django.utils.translation.trans_real.check_for_language, and django.utils.translation.trans_real.to_locale().
def django.utils.translation.trans_real.deactivate ()
Deinstalls the currently active translation object so that further _ calls
will resolve against the default translation object, again.
Definition at line 190 of file trans_real.py.
def django.utils.translation.trans_real.deactivate_all ()
Makes the active translation object a NullTranslations() instance. This is
useful when we want delayed translations to appear as the original string
for some reason.
Definition at line 198 of file trans_real.py.
def django.utils.translation.trans_real.do_ntranslate (singular, plural, number, translation_function)
Definition at line 301 of file trans_real.py.
References django.utils.translation.trans_real.translation().
Referenced by django.utils.translation.trans_real.ngettext(), and django.utils.translation.trans_real.ungettext().
def django.utils.translation.trans_real.do_translate (message, translation_function)
Translates 'message' using the given 'translation_function' name -- which
will be either gettext or ugettext. It uses the current thread to find the
translation object to use. If no current translation is activated, the
message will be run through the default translation object.
Definition at line 246 of file trans_real.py.
References django.utils.safestring.mark_safe(), and django.utils.translation.trans_real.translation().
Referenced by django.utils.translation.trans_real.gettext(), and django.utils.translation.trans_real.ugettext().
def django.utils.translation.trans_real.get_language ()
Returns the currently selected language.
Definition at line 206 of file trans_real.py.
Referenced by django.utils.translation.trans_real.get_language_bidi().
def django.utils.translation.trans_real.get_language_bidi ()
Returns selected language's BiDi layout.
* False = left-to-right layout
* True = right-to-left layout
Definition at line 218 of file trans_real.py.
References django.utils.translation.trans_real.get_language().
def django.utils.translation.trans_real.get_language_from_path (path, supported = None, strict = False)
Returns the language-code if there is a valid language-code
found in the `path`.
If `strict` is False (the default), the function will look for an alternative
country-specific variant when the currently checked is not found.
Definition at line 390 of file trans_real.py.
References django.utils.translation.trans_real.get_supported_language_variant().
Referenced by django.utils.translation.trans_real.get_language_from_request().
def django.utils.translation.trans_real.get_language_from_request (request, check_path = False)
Analyzes the request to find what language the user wants the system to
show. Only languages listed in settings.LANGUAGES are taken into account.
If the user requests a sublanguage where we have a main language, we send
out the main language.
If check_path is True, the URL path prefix will be checked for a language
code, otherwise this is skipped for backwards compatibility.
Definition at line 410 of file trans_real.py.
References django.utils.translation.trans_real.check_for_language, django.utils.translation.trans_real.get_language_from_path(), django.utils.translation.trans_real.get_supported_language_variant(), django.utils.translation.trans_real.parse_accept_lang_header(), and django.utils.translation.trans_real.to_locale().
def django.utils.translation.trans_real.get_supported_language_variant (lang_code, supported = None, strict = False)
Returns the language-code that's listed in supported languages, possibly
selecting a more generic variant. Raises LookupError if nothing found.
If `strict` is False (the default), the function will look for an alternative
country-specific variant when the currently checked is not found.
Definition at line 363 of file trans_real.py.
References django.utils.translation.trans_real.check_for_language.
Referenced by django.utils.translation.trans_real.get_language_from_path(), and django.utils.translation.trans_real.get_language_from_request().
def django.utils.translation.trans_real.gettext (message)
Returns a string of the translation of the message.
Returns a string on Python 3 and an UTF-8-encoded bytestring on Python 2.
Definition at line 269 of file trans_real.py.
References django.utils.translation.trans_real.do_translate().
def django.utils.translation.trans_real.gettext_noop (message)
Marks strings for translation but doesn't translate them now. This can be
used to store strings in global variables that should stay in the base
language (because they might be used externally) and will be translated
later.
Definition at line 292 of file trans_real.py.
def django.utils.translation.trans_real.ngettext (singular, plural, number)
Returns a string of the translation of either the singular or plural,
based on the number.
Returns a string on Python 3 and an UTF-8-encoded bytestring on Python 2.
Definition at line 312 of file trans_real.py.
References django.utils.translation.trans_real.do_ntranslate().
def django.utils.translation.trans_real.npgettext (context, singular, plural, number)
Definition at line 331 of file trans_real.py.
References django.utils.translation.trans_real.ungettext.
def django.utils.translation.trans_real.parse_accept_lang_header (lang_string)
Parses the lang_string, which is the body of an HTTP Accept-Language
header, and returns a list of (lang, q-value), ordered by 'q' values.
Any format errors in lang_string results in an empty list being returned.
Definition at line 656 of file trans_real.py.
Referenced by django.utils.translation.trans_real.get_language_from_request().
def django.utils.translation.trans_real.pgettext (context, message)
Definition at line 283 of file trans_real.py.
References django.utils.encoding.force_text(), and django.utils.translation.trans_real.ugettext.
def django.utils.translation.trans_real.templatize (src, origin = None)
Turns a Django template into something that is understood by xgettext. It
does so by translating the Django translation tags into standard gettext
function invocations.
Definition at line 489 of file trans_real.py.
References django.utils.translation.trans_real.blankout(), django.utils.encoding.force_str, django.utils.encoding.force_text(), django.template.defaultfilters.join(), and django.utils.six.StringIO.
def django.utils.translation.trans_real.to_language (locale)
Turns a locale name (en_US) into a language name (en-us).
Definition at line 67 of file trans_real.py.
References django.template.defaultfilters.lower().
def django.utils.translation.trans_real.to_locale (language, to_lower = False)
Turns a language name (en-us) into a locale name (en_US). If 'to_lower' is
True, the last component is lower-cased (en_us).
Definition at line 50 of file trans_real.py.
References django.template.defaultfilters.lower(), and django.template.defaultfilters.upper().
Referenced by django.utils.translation.trans_real.check_for_language(), django.utils.translation.trans_real.get_language_from_request(), and django.utils.translation.trans_real.translation().
def django.utils.translation.trans_real.translation (language)
Returns a translation object.
This translation object will be constructed out of multiple GNUTranslations
objects by merging their catalogs. It will construct a object for the
requested language and add a fallback to the default language, if it's
different from the requested language.
Definition at line 101 of file trans_real.py.
References django.utils.importlib.import_module(), django.utils.translation.trans_real.to_locale(), and django.utils._os.upath().
Referenced by django.utils.translation.trans_real.activate(), django.utils.translation.trans_real.catalog(), django.utils.translation.trans_real.do_ntranslate(), and django.utils.translation.trans_real.do_translate().
def django.utils.translation.trans_real.ugettext (message)
Definition at line 280 of file trans_real.py.
References django.utils.translation.trans_real.do_translate(), and django.utils.translation.trans_real.ugettext.
def django.utils.translation.trans_real.ungettext (singular, plural, number)
Returns a unicode strings of the translation of either the singular or
plural, based on the number.
Definition at line 324 of file trans_real.py.
References django.utils.translation.trans_real.do_ntranslate(), and django.utils.translation.trans_real.ungettext.
Variable Documentation
dictionary django.utils.translation.trans_real._accepted = {}
Definition at line 33 of file trans_real.py.
tuple django.utils.translation.trans_real._active = local()
Definition at line 26 of file trans_real.py.
dictionary django.utils.translation.trans_real._checked_languages = {}
Definition at line 34 of file trans_real.py.
django.utils.translation.trans_real._default = None
Definition at line 29 of file trans_real.py.
Referenced by yt().
dictionary django.utils.translation.trans_real._translations = {}
Definition at line 25 of file trans_real.py.
tuple django.utils.translation.trans_real.accept_language_re = re.compile(r, re.VERBOSE)
Definition at line 41 of file trans_real.py.
tuple django.utils.translation.trans_real.block_re = re.compile(r)
Definition at line 482 of file trans_real.py.
tuple django.utils.translation.trans_real.check_for_language = memoize(check_for_language, _checked_languages, 1)
Definition at line 361 of file trans_real.py.
Referenced by django.utils.translation.trans_real.check_for_language(), django.utils.translation.trans_real.get_language_from_request(), and django.utils.translation.trans_real.get_supported_language_variant().
tuple django.utils.translation.trans_real.constant_re = re.compile(r)
Definition at line 485 of file trans_real.py.
tuple django.utils.translation.trans_real.context_re = re.compile(r)
Definition at line 480 of file trans_real.py.
string django.utils.translation.trans_real.CONTEXT_SEPARATOR = "\x04"
Definition at line 37 of file trans_real.py.
tuple django.utils.translation.trans_real.dot_re = re.compile(r'\S')
Definition at line 472 of file trans_real.py.
tuple django.utils.translation.trans_real.endblock_re = re.compile(r)
Definition at line 483 of file trans_real.py.
tuple django.utils.translation.trans_real.inline_re = re.compile(r)
Definition at line 481 of file trans_real.py.
tuple django.utils.translation.trans_real.language_code_prefix_re = re.compile(r'^/([\w-]+)(/|$)')
Definition at line 47 of file trans_real.py.
tuple django.utils.translation.trans_real.one_percent_re = re.compile(r)
Definition at line 486 of file trans_real.py.
tuple django.utils.translation.trans_real.plural_re = re.compile(r)
Definition at line 484 of file trans_real.py.
django.utils.translation.trans_real.ugettext = gettext
Definition at line 278 of file trans_real.py.
Referenced by django.contrib.comments.forms.CommentDetailsForm.clean_comment(), django.contrib.flatpages.forms.FlatpageForm.clean_url(), django.template.defaultfilters.filesizeformat(), django.forms.models.BaseModelFormSet.get_date_error_message(), django.forms.models.BaseModelFormSet.get_form_error(), django.forms.models.BaseModelFormSet.get_unique_error_message(), django.utils.translation.trans_real.pgettext(), django.contrib.auth.forms.ReadOnlyPasswordHashWidget.render(), django.utils.timesince.timesince(), django.utils.translation.trans_real.ugettext(), django.contrib.auth.admin.UserAdmin.user_change_password(), and django.template.defaultfilters.yesno().
django.utils.translation.trans_real.ungettext = ngettext
Definition at line 322 of file trans_real.py.
Referenced by django.contrib.admin.options.ModelAdmin.changelist_view(), django.contrib.comments.forms.CommentDetailsForm.clean_comment(), django.template.defaultfilters.filesizeformat(), django.forms.formsets.BaseFormSet.full_clean(), django.contrib.admin.util.model_ngettext(), django.contrib.humanize.templatetags.humanize.naturaltime(), django.utils.translation.trans_real.npgettext(), and django.utils.translation.trans_real.ungettext().