Django: django.contrib.admin.widgets.FilteredSelectMultiple Class Reference
django.contrib.admin.widgets.FilteredSelectMultiple Class Reference
Public Member Functions
def media (self)
def __init__
def render
Public Member Functions inherited from django.forms.widgets.SelectMultiple
def render
def value_from_datadict (self, data, files, name)
Public Member Functions inherited from django.forms.widgets.Select
def __init__
def render
def render_option (self, selected_choices, option_value, option_label)
def render_options (self, choices, selected_choices)
Public Member Functions inherited from django.forms.widgets.Widget
def __init__
def __deepcopy__ (self, memo)
def subwidgets
def render
def build_attrs (self, extra_attrs=None, kwargs)
def value_from_datadict (self, data, files, name)
def id_for_label (self, id_)
Public Member Functions inherited from django.forms.widgets.MediaDefiningClass
def __new__ (cls, name, bases, attrs)
Public Attributes
verbose_name
is_stacked
Public Attributes inherited from django.forms.widgets.Select
choices
Public Attributes inherited from django.forms.widgets.Widget
attrs
Additional Inherited Members
Static Public Attributes inherited from django.forms.widgets.SelectMultiple
allow_multiple_selected = True
Static Public Attributes inherited from django.forms.widgets.Select
allow_multiple_selected = False
Static Public Attributes inherited from django.forms.widgets.Widget
is_hidden = False
needs_multipart_form = False
is_localized = False
is_required = False
Detailed Description
A SelectMultiple with a JavaScript filter interface.
Note that the resulting JavaScript assumes that the jsi18n
catalog has been loaded in the page
Definition at line 21 of file widgets.py.
Constructor & Destructor Documentation
def django.contrib.admin.widgets.FilteredSelectMultiple.__init__ (self, verbose_name, is_stacked, attrs = None, choices = ())
Definition at line 33 of file widgets.py.
Member Function Documentation
def django.contrib.admin.widgets.FilteredSelectMultiple.media (self)
Definition at line 29 of file widgets.py.
References django.contrib.admin.templatetags.admin_static.static.
def django.contrib.admin.widgets.FilteredSelectMultiple.render (self, name, value, attrs = None, choices = ())
Definition at line 38 of file widgets.py.
References django.contrib.admin.widgets.FilteredSelectMultiple.is_stacked, django.template.defaultfilters.join(), django.utils.safestring.mark_safe(), and django.contrib.admin.templatetags.admin_static.static.
Referenced by django.forms.widgets.Media.__str__(), django.forms.widgets.ChoiceInput.__str__(), django.forms.widgets.ChoiceFieldRenderer.__str__(), django.contrib.formtools.wizard.views.WizardView.get(), django.contrib.formtools.wizard.views.NamedUrlWizardView.get(), django.contrib.gis.maps.google.gmap.GoogleMap.js(), django.contrib.formtools.wizard.views.WizardView.post(), django.templatetags.i18n.BlockTranslateNode.render(), django.contrib.formtools.wizard.views.WizardView.render_goto_step(), django.contrib.formtools.wizard.views.WizardView.render_next_step(), django.contrib.formtools.wizard.views.WizardView.render_revalidation_failure(), and django.template.loader_tags.BlockNode.super().
Member Data Documentation
django.contrib.admin.widgets.FilteredSelectMultiple.is_stacked
Definition at line 35 of file widgets.py.
Referenced by django.contrib.admin.widgets.FilteredSelectMultiple.render().
django.contrib.admin.widgets.FilteredSelectMultiple.verbose_name
Definition at line 34 of file widgets.py.
Referenced by django.db.models.fields.Field.formfield(), django.db.models.fields.NullBooleanField.formfield(), and django.db.models.options.Options.verbose_name_raw().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/admin/widgets.py