Django: django.contrib.auth.tests.test_context_processors.AuthContextProcessorTests Class Reference
django.contrib.auth.tests.test_context_processors.AuthContextProcessorTests Class Reference
Public Member Functions
def test_session_not_accessed (self)
def test_session_is_accessed (self)
def test_perms_attrs (self)
def test_perm_in_perms_attrs (self)
def test_message_attrs (self)
def test_user_attrs (self)
Static Public Attributes
string urls = 'django.contrib.auth.tests.urls'
list fixtures = ['context-processors-users.xml']
MIDDLEWARE_CLASSES = global_settings.MIDDLEWARE_CLASSES,
TEMPLATE_CONTEXT_PROCESSORS = global_settings.TEMPLATE_CONTEXT_PROCESSORS,
Detailed Description
Tests for the ``django.contrib.auth.context_processors.auth`` processor
Definition at line 73 of file test_context_processors.py.
Member Function Documentation
def django.contrib.auth.tests.test_context_processors.AuthContextProcessorTests.test_message_attrs (self)
Definition at line 128 of file test_context_processors.py.
References django.test.testcases.SimpleTestCase.assertContains().
def django.contrib.auth.tests.test_context_processors.AuthContextProcessorTests.test_perm_in_perms_attrs (self)
Definition at line 116 of file test_context_processors.py.
References django.test.testcases.SimpleTestCase.assertContains(), and django.test.testcases.SimpleTestCase.assertNotContains().
def django.contrib.auth.tests.test_context_processors.AuthContextProcessorTests.test_perms_attrs (self)
Definition at line 104 of file test_context_processors.py.
References django.test.testcases.SimpleTestCase.assertContains(), and django.test.testcases.SimpleTestCase.assertNotContains().
def django.contrib.auth.tests.test_context_processors.AuthContextProcessorTests.test_session_is_accessed (self)
Tests that the session is accessed if the auth context processor
is used and relevant attributes accessed.
Definition at line 96 of file test_context_processors.py.
References django.test.testcases.SimpleTestCase.assertContains().
def django.contrib.auth.tests.test_context_processors.AuthContextProcessorTests.test_session_not_accessed (self)
Tests that the session is not accessed simply by including
the auth context processor
Definition at line 84 of file test_context_processors.py.
References django.test.testcases.SimpleTestCase.assertContains().
def django.contrib.auth.tests.test_context_processors.AuthContextProcessorTests.test_user_attrs (self)
Test that the lazy objects returned behave just like the wrapped objects.
Definition at line 133 of file test_context_processors.py.
References django.test.testcases.SimpleTestCase.assertContains(), django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.auth.authenticate().
Member Data Documentation
list django.contrib.auth.tests.test_context_processors.AuthContextProcessorTests.fixtures = ['context-processors-users.xml'] static
Definition at line 78 of file test_context_processors.py.
django.contrib.auth.tests.test_context_processors.AuthContextProcessorTests.MIDDLEWARE_CLASSES = global_settings.MIDDLEWARE_CLASSES, static
Definition at line 81 of file test_context_processors.py.
django.contrib.auth.tests.test_context_processors.AuthContextProcessorTests.TEMPLATE_CONTEXT_PROCESSORS = global_settings.TEMPLATE_CONTEXT_PROCESSORS, static
Definition at line 82 of file test_context_processors.py.
string django.contrib.auth.tests.test_context_processors.AuthContextProcessorTests.urls = 'django.contrib.auth.tests.urls' static
Definition at line 77 of file test_context_processors.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_context_processors.py