Django: django.contrib.admin.models.LogEntry.Meta Class Reference
django.contrib.admin.models.LogEntry.Meta Class Reference
Static Public Attributes
tuple verbose_name = _('log entry')
tuple verbose_name_plural = _('log entries')
string db_table = 'django_admin_log'
tuple ordering = ('-action_time',)
Detailed Description
Definition at line 35 of file models.py.
Member Data Documentation
string django.contrib.admin.models.LogEntry.Meta.db_table = 'django_admin_log' static
Definition at line 38 of file models.py.
Referenced by django.db.models.fields.related.ManyToManyField.get_choices_default(), and django.db.models.options.Options.setup_proxy().
tuple django.contrib.admin.models.LogEntry.Meta.ordering = ('-action_time',) static
Definition at line 39 of file models.py.
Referenced by django.contrib.admin.options.BaseModelAdmin.get_ordering(), and django.db.models.options.Options.module_name().
tuple django.contrib.admin.models.LogEntry.Meta.verbose_name = _('log entry') static
Definition at line 36 of file models.py.
Referenced by django.db.models.fields.Field.formfield(), django.db.models.fields.NullBooleanField.formfield(), and django.db.models.options.Options.verbose_name_raw().
tuple django.contrib.admin.models.LogEntry.Meta.verbose_name_plural = _('log entries') static
Definition at line 37 of file models.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/admin/models.py