Django: django.middleware.csrf Namespace Reference
django.middleware.csrf Namespace Reference
Classes
class CsrfViewMiddleware
Functions
def get_token (request)
def rotate_token (request)
Variables
tuple logger = logging.getLogger('django.request')
string REASON_NO_REFERER = "Referer checking failed - no Referer."
string REASON_BAD_REFERER = "Referer checking failed - %s does not match %s."
string REASON_NO_CSRF_COOKIE = "CSRF cookie not set."
string REASON_BAD_TOKEN = "CSRF token missing or incorrect."
int CSRF_KEY_LENGTH = 32
Detailed Description
Cross Site Request Forgery Middleware.
This module provides a middleware that implements protection
against request forgeries from other sites.
Function Documentation
def django.middleware.csrf.get_token (request)
Returns the CSRF token required for a POST form. The token is an
alphanumeric value.
A side effect of calling this function is to make the csrf_protect
decorator and the CsrfViewMiddleware add a CSRF cookie and a 'Vary: Cookie'
header to the outgoing response.  For this reason, you may need to use this
function lazily, as is done by the csrf context processor.
Definition at line 40 of file csrf.py.
Referenced by django.core.context_processors.csrf(), and django.views.decorators.csrf._EnsureCsrfCookie.process_view().
def django.middleware.csrf.rotate_token (request)
Changes the CSRF token in use for a request - should be done on login
for security purposes.
Definition at line 54 of file csrf.py.
References django.utils.encoding.force_text().
Referenced by django.contrib.auth.login().
Variable Documentation
int django.middleware.csrf.CSRF_KEY_LENGTH = 32
Definition at line 27 of file csrf.py.
tuple django.middleware.csrf.logger = logging.getLogger('django.request')
Definition at line 20 of file csrf.py.
string django.middleware.csrf.REASON_BAD_REFERER = "Referer checking failed - %s does not match %s."
Definition at line 23 of file csrf.py.
string django.middleware.csrf.REASON_BAD_TOKEN = "CSRF token missing or incorrect."
Definition at line 25 of file csrf.py.
string django.middleware.csrf.REASON_NO_CSRF_COOKIE = "CSRF cookie not set."
Definition at line 24 of file csrf.py.
string django.middleware.csrf.REASON_NO_REFERER = "Referer checking failed - no Referer."
Definition at line 22 of file csrf.py.