Django: django.conf.LazySettings Class Reference
django.conf.LazySettings Class Reference
Public Member Functions
def __getattr__ (self, name)
def configure (self, default_settings=global_settings, options)
def configured (self)
Public Member Functions inherited from django.utils.functional.LazyObject
def __init__ (self)
def __setattr__ (self, name, value)
def __delattr__ (self, name)
def __getitem__ (self, key)
def __setitem__ (self, key, value)
def __delitem__ (self, key)
Detailed Description
A lazy proxy for either global Django settings or a custom settings object.
The user can manually configure settings prior to using them. Otherwise,
Django uses the settings module pointed to by DJANGO_SETTINGS_MODULE.
Definition at line 25 of file __init__.py.
Member Function Documentation
def django.conf.LazySettings.__getattr__ (self, name)
Definition at line 52 of file __init__.py.
References django.conf.LazySettings._setup(), django.conf.LazySettings._wrapped, and django.utils.module_loading.import_by_path().
def django.conf.LazySettings.configure (self, default_settings = global_settings, options)
Called to manually configure the settings. The 'default_settings'
parameter sets where to retrieve any unspecified values from (its
argument must support attribute access (__getattr__)).
Definition at line 82 of file __init__.py.
References django.conf.LazySettings._configure_logging(), and django.conf.LazySettings._wrapped.
def django.conf.LazySettings.configured (self)
Returns True if the settings have already been configured.
Definition at line 97 of file __init__.py.
References django.conf.LazySettings._wrapped.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/conf/__init__.py