Django: django.utils.jslex Namespace Reference
django.utils.jslex Namespace Reference
Classes
class JsLexer
class Lexer
class Tok
Functions
def literals
def prepare_js_for_gettext (js)
Detailed Description
JsLex: a lexer for Javascript
Function Documentation
def django.utils.jslex.literals (choices, prefix = "", suffix = "")
Create a regex from a space-separated list of literal `choices`.
If provided, `prefix` and `suffix` will be attached to each choice
individually.
Definition at line 18 of file jslex.py.
References django.template.defaultfilters.join().
def django.utils.jslex.prepare_js_for_gettext (js)
Convert the Javascript source `js` into something resembling C for
xgettext.
What actually happens is that all the regex literals are replaced with
"REGEX".
Definition at line 184 of file jslex.py.
References django.template.defaultfilters.join().
Referenced by django.core.management.commands.makemessages.TranslatableFile.process().