Django: django.contrib.gis.feeds.Feed Class Reference
django.contrib.gis.feeds.Feed Class Reference
Public Member Functions
def feed_extra_kwargs (self, obj)
def item_extra_kwargs (self, item)
Static Public Attributes
feed_type = GeoRSSFeed
Detailed Description
This is a subclass of the `Feed` from `django.contrib.syndication`.
This allows users to define a `geometry(obj)` and/or `item_geometry(item)`
methods on their own subclasses so that geo-referenced information may
placed in the feed.
Definition at line 124 of file feeds.py.
Member Function Documentation
def django.contrib.gis.feeds.Feed.feed_extra_kwargs (self, obj)
Definition at line 133 of file feeds.py.
References django.contrib.syndication.views.Feed.__get_dynamic_attr().
Referenced by django.contrib.syndication.views.Feed.get_feed().
def django.contrib.gis.feeds.Feed.item_extra_kwargs (self, item)
Definition at line 136 of file feeds.py.
References django.contrib.syndication.views.Feed.__get_dynamic_attr().
Referenced by django.contrib.syndication.views.Feed.get_feed().
Member Data Documentation
django.contrib.gis.feeds.Feed.feed_type = GeoRSSFeed static
Definition at line 131 of file feeds.py.
Referenced by django.contrib.syndication.views.Feed.get_feed().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/feeds.py