Django: django.contrib.comments.moderation.CommentModerator Class Reference
django.contrib.comments.moderation.CommentModerator Class Reference
Public Member Functions
def __init__ (self, model)
def allow (self, comment, content_object, request)
def moderate (self, comment, content_object, request)
def email (self, comment, content_object, request)
Static Public Attributes
auto_close_field = None
auto_moderate_field = None
close_after = None
email_notification = False
enable_field = None
moderate_after = None
Detailed Description
Encapsulates comment-moderation options for a given model.
This class is not designed to be used directly, since it doesn't
enable any of the available moderation options. Instead, subclass
it and override attributes to enable different options::
``auto_close_field``
    If this is set to the name of a ``DateField`` or
    ``DateTimeField`` on the model for which comments are
    being moderated, new comments for objects of that model
    will be disallowed (immediately deleted) when a certain
    number of days have passed after the date specified in
    that field. Must be used in conjunction with
    ``close_after``, which specifies the number of days past
    which comments should be disallowed. Default value is
    ``None``.
``auto_moderate_field``
    Like ``auto_close_field``, but instead of outright
    deleting new comments when the requisite number of days
    have elapsed, it will simply set the ``is_public`` field
    of new comments to ``False`` before saving them. Must be
    used in conjunction with ``moderate_after``, which
    specifies the number of days past which comments should be
    moderated. Default value is ``None``.
``close_after``
    If ``auto_close_field`` is used, this must specify the
    number of days past the value of the field specified by
    ``auto_close_field`` after which new comments for an
    object should be disallowed. Default value is ``None``.
``email_notification``
    If ``True``, any new comment on an object of this model
    which survives moderation will generate an email to site
    staff. Default value is ``False``.
``enable_field``
    If this is set to the name of a ``BooleanField`` on the
    model for which comments are being moderated, new comments
    on objects of that model will be disallowed (immediately
    deleted) whenever the value of that field is ``False`` on
    the object the comment would be attached to. Default value
    is ``None``.
``moderate_after``
    If ``auto_moderate_field`` is used, this must specify the number
    of days past the value of the field specified by
    ``auto_moderate_field`` after which new comments for an
    object should be marked non-public. Default value is
    ``None``.
Most common moderation needs can be covered by changing these
attributes, but further customization can be obtained by
subclassing and overriding the following methods. Each method will
be called with three arguments: ``comment``, which is the comment
being submitted, ``content_object``, which is the object the
comment will be attached to, and ``request``, which is the
``HttpRequest`` in which the comment is being submitted::
``allow``
    Should return ``True`` if the comment should be allowed to
    post on the content object, and ``False`` otherwise (in
    which case the comment will be immediately deleted).
``email``
    If email notification of the new comment should be sent to
    site staff or moderators, this method is responsible for
    sending the email.
``moderate``
    Should return ``True`` if the comment should be moderated
    (in which case its ``is_public`` field will be set to
    ``False`` before saving), and ``False`` otherwise (in
    which case the ``is_public`` field will not be changed).
Subclasses which want to introspect the model for which comments
are being moderated can do so through the attribute ``_model``,
which will be the model class.
Definition at line 84 of file moderation.py.
Constructor & Destructor Documentation
def django.contrib.comments.moderation.CommentModerator.__init__ (self, model)
Definition at line 174 of file moderation.py.
References django.contrib.comments.moderation.CommentModerator._model.
Member Function Documentation
def django.contrib.comments.moderation.CommentModerator.allow (self, comment, content_object, request)
Determine whether a given comment is allowed to be posted on
a given object.
Return ``True`` if the comment should be allowed, ``False
otherwise.
Definition at line 197 of file moderation.py.
References django.contrib.comments.moderation.CommentModerator._get_delta(), django.contrib.comments.moderation.CommentModerator.auto_close_field, django.contrib.comments.moderation.CommentModerator.close_after, and django.contrib.comments.moderation.CommentModerator.enable_field.
def django.contrib.comments.moderation.CommentModerator.email (self, comment, content_object, request)
Send email notification of a new comment to site staff when email
notifications have been requested.
Definition at line 231 of file moderation.py.
References django.contrib.comments.moderation.CommentModerator.email_notification, django.contrib.sites.models.get_current_site(), and django.core.mail.send_mail().
def django.contrib.comments.moderation.CommentModerator.moderate (self, comment, content_object, request)
Determine whether a given comment on a given object should be
allowed to show up immediately, or should be marked non-public
and await approval.
Return ``True`` if the comment should be moderated (marked
non-public), ``False`` otherwise.
Definition at line 215 of file moderation.py.
References django.contrib.comments.moderation.CommentModerator._get_delta(), django.contrib.comments.moderation.CommentModerator.auto_moderate_field, and django.contrib.comments.moderation.CommentModerator.moderate_after.
Member Data Documentation
django.contrib.comments.moderation.CommentModerator.auto_close_field = None static
Definition at line 167 of file moderation.py.
Referenced by django.contrib.comments.moderation.CommentModerator.allow().
django.contrib.comments.moderation.CommentModerator.auto_moderate_field = None static
Definition at line 168 of file moderation.py.
Referenced by django.contrib.comments.moderation.CommentModerator.moderate().
django.contrib.comments.moderation.CommentModerator.close_after = None static
Definition at line 169 of file moderation.py.
Referenced by django.contrib.comments.moderation.CommentModerator.allow().
django.contrib.comments.moderation.CommentModerator.email_notification = False static
Definition at line 170 of file moderation.py.
Referenced by django.contrib.comments.moderation.CommentModerator.email().
django.contrib.comments.moderation.CommentModerator.enable_field = None static
Definition at line 171 of file moderation.py.
Referenced by django.contrib.comments.moderation.CommentModerator.allow().
django.contrib.comments.moderation.CommentModerator.moderate_after = None static
Definition at line 172 of file moderation.py.
Referenced by django.contrib.comments.moderation.CommentModerator.moderate().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/comments/moderation.py