Django: django.core.urlresolvers Namespace Reference
django.core.urlresolvers Namespace Reference
Classes
class LocaleRegexProvider
class LocaleRegexURLResolver
class NoReverseMatch
class RegexURLPattern
class RegexURLResolver
class Resolver404
class ResolverMatch
Functions
def get_callable
def get_resolver (urlconf)
def get_ns_resolver (ns_pattern, resolver)
def get_mod_func (callback)
def resolve
def reverse
def clear_url_caches ()
def set_script_prefix (prefix)
def get_script_prefix ()
def clear_script_prefix ()
def set_urlconf (urlconf_name)
def get_urlconf
def is_valid_path
Variables
dictionary _resolver_cache = {}
dictionary _ns_resolver_cache = {}
dictionary _callable_cache = {}
tuple _prefixes = local()
tuple _urlconfs = local()
tuple get_callable = memoize(get_callable, _callable_cache, 1)
tuple get_resolver = memoize(get_resolver, _resolver_cache, 1)
tuple get_ns_resolver = memoize(get_ns_resolver, _ns_resolver_cache, 2)
tuple reverse_lazy = lazy(reverse, str)
Detailed Description
This module converts requested URLs to callback view functions.
RegexURLResolver is the main class here. Its resolve() method takes a URL (as
a string) and returns a tuple in this format:
    (view_function, function_args, function_kwargs)
Function Documentation
def django.core.urlresolvers.clear_script_prefix ()
Unsets the script prefix for the current thread.
Definition at line 564 of file urlresolvers.py.
Referenced by django.contrib.flatpages.tests.test_models.FlatpageModelTests.test_get_absolute_url_honors_script_prefix().
def django.core.urlresolvers.clear_url_caches ()
Definition at line 540 of file urlresolvers.py.
def django.core.urlresolvers.get_callable (lookup_view, can_fail = False)
Convert a string version of a function name to the callable object.
If the lookup_view is not an import path, it is assumed to be a URL pattern
label and the original string is returned.
If can_fail is True, lookup_view might be a URL pattern label, so errors
during the import fail and the string is returned.
Definition at line 81 of file urlresolvers.py.
def django.core.urlresolvers.get_mod_func (callback)
Definition at line 138 of file urlresolvers.py.
def django.core.urlresolvers.get_ns_resolver (ns_pattern, resolver)
Definition at line 129 of file urlresolvers.py.
References django.core.urlresolvers.get_ns_resolver.
def django.core.urlresolvers.get_resolver (urlconf)
Definition at line 122 of file urlresolvers.py.
References django.core.urlresolvers.get_resolver.
def django.core.urlresolvers.get_script_prefix ()
Returns the currently active script prefix. Useful for client code that
wishes to construct their own URLs manually (although accessing the request
instance is normally going to be a lot cleaner).
Definition at line 556 of file urlresolvers.py.
Referenced by django.contrib.admin.templatetags.admin_urls.add_preserved_filters(), django.contrib.flatpages.models.FlatPage.get_absolute_url(), and django.core.urlresolvers.reverse().
def django.core.urlresolvers.get_urlconf (default = None)
Returns the root URLconf to use for the current thread if it has been
changed from the default one.
Definition at line 584 of file urlresolvers.py.
Referenced by django.core.urlresolvers.resolve(), and django.core.urlresolvers.reverse().
def django.core.urlresolvers.is_valid_path (path, urlconf = None)
Returns True if the given path resolves against the default URL resolver,
False otherwise.
This is a convenience method to make working with "is this a match?" cases
easier, avoiding unnecessarily indented try...except blocks.
Definition at line 591 of file urlresolvers.py.
References django.core.urlresolvers.resolve().
Referenced by django.middleware.locale.LocaleMiddleware.process_response().
def django.core.urlresolvers.resolve (path, urlconf = None)
Definition at line 477 of file urlresolvers.py.
References django.core.urlresolvers.get_resolver, and django.core.urlresolvers.get_urlconf().
Referenced by django.contrib.admin.templatetags.admin_urls.add_preserved_filters(), django.core.urlresolvers.is_valid_path(), django.template.defaulttags.CycleNode.render(), and django.template.base.resolve_variable().
def django.core.urlresolvers.reverse (viewname, urlconf = None, args = None, kwargs = None, prefix = None, current_app = None)
Definition at line 482 of file urlresolvers.py.
References django.core.urlresolvers.get_ns_resolver, django.core.urlresolvers.get_resolver, django.core.urlresolvers.get_script_prefix(), django.core.urlresolvers.get_urlconf(), django.utils.encoding.iri_to_uri(), and django.template.defaultfilters.join().
def django.core.urlresolvers.set_script_prefix (prefix)
Sets the script prefix for the current thread.
Definition at line 548 of file urlresolvers.py.
Referenced by django.core.handlers.wsgi.WSGIHandler.__call__(), and django.contrib.flatpages.tests.test_models.FlatpageModelTests.test_get_absolute_url_honors_script_prefix().
def django.core.urlresolvers.set_urlconf (urlconf_name)
Sets the URLconf for the current thread (overriding the default one in
settings). Set to None to revert back to the default.
Definition at line 573 of file urlresolvers.py.
Variable Documentation
dictionary django.core.urlresolvers._callable_cache = {}
Definition at line 30 of file urlresolvers.py.
dictionary django.core.urlresolvers._ns_resolver_cache = {}
Definition at line 29 of file urlresolvers.py.
tuple django.core.urlresolvers._prefixes = local()
Definition at line 35 of file urlresolvers.py.
dictionary django.core.urlresolvers._resolver_cache = {}
Definition at line 28 of file urlresolvers.py.
tuple django.core.urlresolvers._urlconfs = local()
Definition at line 38 of file urlresolvers.py.
tuple django.core.urlresolvers.get_callable = memoize(get_callable, _callable_cache, 1)
Definition at line 120 of file urlresolvers.py.
Referenced by django.core.urlresolvers.RegexURLPattern.callback(), django.core.urlresolvers.RegexURLResolver.reverse(), and django.core.urlresolvers.RegexURLResolver.url_patterns().
tuple django.core.urlresolvers.get_ns_resolver = memoize(get_ns_resolver, _ns_resolver_cache, 2)
Definition at line 136 of file urlresolvers.py.
Referenced by django.core.urlresolvers.get_ns_resolver(), and django.core.urlresolvers.reverse().
tuple django.core.urlresolvers.get_resolver = memoize(get_resolver, _resolver_cache, 1)
Definition at line 127 of file urlresolvers.py.
Referenced by django.middleware.locale.LocaleMiddleware.__init__(), django.core.urlresolvers.get_resolver(), django.core.urlresolvers.resolve(), and django.core.urlresolvers.reverse().
tuple django.core.urlresolvers.reverse_lazy = lazy(reverse, str)
Definition at line 538 of file urlresolvers.py.