Django: django.template.loaders.cached.Loader Class Reference
django.template.loaders.cached.Loader Class Reference
Public Member Functions
def __init__ (self, loaders)
def loaders (self)
def find_template
def load_template
def reset (self)
Public Member Functions inherited from django.template.loader.BaseLoader
def __init__ (self, args, kwargs)
def __call__
def load_template
def load_template_source
def reset (self)
Public Attributes
template_cache
Static Public Attributes
is_usable = True
Static Public Attributes inherited from django.template.loader.BaseLoader
is_usable = False
Detailed Description
Definition at line 11 of file cached.py.
Constructor & Destructor Documentation
def django.template.loaders.cached.Loader.__init__ (self, loaders)
Definition at line 14 of file cached.py.
Member Function Documentation
def django.template.loaders.cached.Loader.find_template (self, name, dirs = None)
Definition at line 31 of file cached.py.
References django.template.loaders.cached.Loader.loaders(), and django.template.loader.make_origin().
Referenced by django.template.loaders.cached.Loader.load_template().
def django.template.loaders.cached.Loader.load_template (self, template_name, template_dirs = None)
Definition at line 40 of file cached.py.
References django.template.loaders.cached.Loader.find_template(), django.utils.encoding.force_bytes(), django.template.loader.get_template_from_string(), django.template.defaultfilters.join(), and django.template.loaders.cached.Loader.template_cache.
def django.template.loaders.cached.Loader.loaders (self)
Definition at line 20 of file cached.py.
References django.template.loaders.cached.Loader._cached_loaders, django.template.loaders.cached.Loader._loaders, and django.template.loader.find_template_loader().
Referenced by django.template.loaders.cached.Loader.find_template().
def django.template.loaders.cached.Loader.reset (self)
Definition at line 62 of file cached.py.
Member Data Documentation
django.template.loaders.cached.Loader.is_usable = True static
Definition at line 12 of file cached.py.
Referenced by django.db.backends.BaseDatabaseWrapper.close_if_unusable_or_obsolete().
django.template.loaders.cached.Loader.template_cache
Definition at line 15 of file cached.py.
Referenced by django.template.loaders.cached.Loader.load_template().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/template/loaders/cached.py