Django: django.contrib.gis.tests.geoapp.tests.GeoModelTest Class Reference
django.contrib.gis.tests.geoapp.tests.GeoModelTest Class Reference
Public Member Functions
def test_fixtures (self)
def test_proxy (self)
def test_lookup_insert_transform (self)
def test_createnull (self)
def test_geometryfield (self)
def test_inherited_geofields (self)
def test_raw_sql_query (self)
Detailed Description
Definition at line 31 of file tests.py.
Member Function Documentation
def django.contrib.gis.tests.geoapp.tests.GeoModelTest.test_createnull (self)
Definition at line 153 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.geoapp.tests.GeoModelTest.test_fixtures (self)
Definition at line 33 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.geoapp.tests.GeoModelTest.test_geometryfield (self)
Definition at line 159 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.geoapp.tests.GeoModelTest.test_inherited_geofields (self)
Definition at line 182 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.tests.geoapp.tests.GeoModelTest.test_lookup_insert_transform (self)
Definition at line 109 of file tests.py.
References django.utils.unittest.case.TestCase.assertAlmostEqual(), django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.gis.geos.factory.fromstr().
def django.contrib.gis.tests.geoapp.tests.GeoModelTest.test_proxy (self)
Definition at line 40 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertNotEqual(), and django.utils.unittest.case.TestCase.fail().
def django.contrib.gis.tests.geoapp.tests.GeoModelTest.test_raw_sql_query (self)
Definition at line 194 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertTrue(), and django.utils.unittest.case.skipUnless().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/tests/geoapp/tests.py