Django: django.utils.safestring.SafeText Class Reference
django.utils.safestring.SafeText Class Reference
Public Member Functions
def __add__ (self, rhs)
Static Public Attributes
tuple encode = curry(_proxy_method, method=six.text_type.encode)
Detailed Description
A unicode (Python 2) / str (Python 3) subclass that has been specifically
marked as "safe" for HTML output purposes.
Definition at line 67 of file safestring.py.
Member Function Documentation
def django.utils.safestring.SafeText.__add__ (self, rhs)
Concatenating a safe unicode string with another safe byte string or
safe unicode string is safe. Otherwise, the result is no longer safe.
Definition at line 72 of file safestring.py.
Member Data Documentation
tuple django.utils.safestring.SafeText.encode = curry(_proxy_method, method=six.text_type.encode) static
Definition at line 95 of file safestring.py.
Referenced by django.contrib.sessions.models.SessionManager.save(), django.contrib.sessions.backends.db.SessionStore.save(), django.contrib.sessions.backends.file.SessionStore.save(), django.contrib.auth.hashers.PBKDF2PasswordHasher.verify(), django.contrib.auth.hashers.SHA1PasswordHasher.verify(), django.contrib.auth.hashers.MD5PasswordHasher.verify(), django.contrib.auth.hashers.UnsaltedSHA1PasswordHasher.verify(), and django.contrib.auth.hashers.UnsaltedMD5PasswordHasher.verify().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/utils/safestring.py