Django: django.db.models.sql.constants Namespace Reference
django.db.models.sql.constants Namespace Reference
Variables
tuple QUERY_TERMS
int GET_ITERATOR_CHUNK_SIZE = 100
tuple JoinInfo
tuple SelectInfo = namedtuple('SelectInfo', 'col field')
string MULTI = 'multi'
string SINGLE = 'single'
tuple ORDER_PATTERN = re.compile(r'\?|[-+]?[.\w]+$')
dictionary ORDER_DIR
Detailed Description
Constants specific to the SQL storage portion of the ORM.
Variable Documentation
int django.db.models.sql.constants.GET_ITERATOR_CHUNK_SIZE = 100
Definition at line 20 of file constants.py.
tuple django.db.models.sql.constants.JoinInfo
Initial value:
 = namedtuple('JoinInfo',
                       'table_name rhs_alias join_type lhs_alias '
                       'join_cols nullable join_field')
Definition at line 26 of file constants.py.
Referenced by django.db.models.sql.query.Query.join().
string django.db.models.sql.constants.MULTI = 'multi'
Definition at line 34 of file constants.py.
dictionary django.db.models.sql.constants.ORDER_DIR
Initial value:
 = {
     'ASC': ('ASC', 'DESC'),
     'DESC': ('DESC', 'ASC'),
 }
Definition at line 38 of file constants.py.
tuple django.db.models.sql.constants.ORDER_PATTERN = re.compile(r'\?|[-+]?[.\w]+$')
Definition at line 37 of file constants.py.
tuple django.db.models.sql.constants.QUERY_TERMS
Initial value:
 = set([
     'exact', 'iexact', 'contains', 'icontains', 'gt', 'gte', 'lt', 'lte', 'in',
     'startswith', 'istartswith', 'endswith', 'iendswith', 'range', 'year',
     'month', 'day', 'week_day', 'hour', 'minute', 'second', 'isnull', 'search',
     'regex', 'iregex',
 ])
Definition at line 11 of file constants.py.
tuple django.db.models.sql.constants.SelectInfo = namedtuple('SelectInfo', 'col field')
Definition at line 31 of file constants.py.
Referenced by django.db.models.sql.query.Query.add_fields(), django.db.models.sql.query.Query.change_aliases(), django.db.models.sql.query.Query.combine(), django.db.models.sql.subqueries.DeleteQuery.delete_qs(), django.db.models.sql.compiler.SQLCompiler.fill_related_selections(), and django.db.models.sql.query.Query.trim_start().
string django.db.models.sql.constants.SINGLE = 'single'
Definition at line 35 of file constants.py.