Django: django.middleware.common.BrokenLinkEmailsMiddleware Class Reference
django.middleware.common.BrokenLinkEmailsMiddleware Class Reference
Public Member Functions
def process_response (self, request, response)
def is_internal_request (self, domain, referer)
def is_ignorable_request (self, request, uri, domain, referer)
Detailed Description
Definition at line 135 of file common.py.
Member Function Documentation
def django.middleware.common.BrokenLinkEmailsMiddleware.is_ignorable_request (self, request, uri, domain, referer)
Returns True if the given request *shouldn't* notify the site managers.
Definition at line 166 of file common.py.
References django.middleware.common.BrokenLinkEmailsMiddleware.is_internal_request().
Referenced by django.middleware.common.BrokenLinkEmailsMiddleware.process_response().
def django.middleware.common.BrokenLinkEmailsMiddleware.is_internal_request (self, domain, referer)
Returns True if the referring URL is the same domain as the current request.
Definition at line 159 of file common.py.
Referenced by django.middleware.common.BrokenLinkEmailsMiddleware.is_ignorable_request(), and django.middleware.common.BrokenLinkEmailsMiddleware.process_response().
def django.middleware.common.BrokenLinkEmailsMiddleware.process_response (self, request, response)
Send broken link emails for relevant 404 NOT FOUND responses.
Definition at line 137 of file common.py.
References django.utils.encoding.force_text(), django.middleware.common.BrokenLinkEmailsMiddleware.is_ignorable_request(), django.middleware.common.BrokenLinkEmailsMiddleware.is_internal_request(), and django.core.mail.mail_managers().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/middleware/common.py