Django: django.contrib.formtools.tests.tests.PreviewTests Class Reference
django.contrib.formtools.tests.tests.PreviewTests Class Reference
Public Member Functions
def setUp (self)
def test_unused_name (self)
def test_form_get (self)
def test_form_preview (self)
def test_form_submit (self)
def test_bool_submit (self)
def test_form_submit_good_hash (self)
def test_form_submit_bad_hash (self)
Public Attributes
preview
input
test_data
Static Public Attributes
string urls = 'django.contrib.formtools.tests.urls'
Detailed Description
Definition at line 37 of file tests.py.
Member Function Documentation
def django.contrib.formtools.tests.tests.PreviewTests.setUp (self)
Definition at line 40 of file tests.py.
Referenced by django.utils.unittest.case.TestCase.debug(), django.test._doctest.DocTestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.contrib.formtools.tests.tests.PreviewTests.test_bool_submit (self)
Test contrib.formtools.preview form submittal when form contains:
BooleanField(required=False)
Ticket: #6209 - When an unchecked BooleanField is previewed, the preview
form's hash would be computed with no value for ``bool1``. However, when
the preview form is rendered, the unchecked hidden BooleanField would be
rendered with the string value 'False'. So when the preview form is
resubmitted, the hash would be computed with the value 'False' for
``bool1``. We need to make sure the hashes are the same in both cases.
Definition at line 107 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.formtools.tests.tests.PreviewTests.test_data.
def django.contrib.formtools.tests.tests.PreviewTests.test_form_get (self)
Test contrib.formtools.preview form retrieval.
Use the client library to see if we can sucessfully retrieve
the form (mostly testing the setup ROOT_URLCONF
process). Verify that an additional  hidden input field
is created to manage the stage.
Definition at line 54 of file tests.py.
References django.test.testcases.SimpleTestCase.assertContains(), django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.formtools.tests.tests.PreviewTests.input.
def django.contrib.formtools.tests.tests.PreviewTests.test_form_preview (self)
Test contrib.formtools.preview form preview rendering.
Use the client library to POST to the form to see if a preview
is returned.  If we do get a form back check that the hidden
value is correctly managing the state of the form.
Definition at line 70 of file tests.py.
References django.test.testcases.SimpleTestCase.assertContains(), django.contrib.formtools.tests.tests.PreviewTests.input, and django.contrib.formtools.tests.tests.PreviewTests.test_data.
def django.contrib.formtools.tests.tests.PreviewTests.test_form_submit (self)
Test contrib.formtools.preview form submittal.
Use the client library to POST to the form with stage set to 3
to see if our forms done() method is called. Check first
without the security hash, verify failure, retry with security
hash and verify sucess.
Definition at line 87 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertNotEqual(), and django.contrib.formtools.tests.tests.PreviewTests.test_data.
def django.contrib.formtools.tests.tests.PreviewTests.test_form_submit_bad_hash (self)
Test contrib.formtools.preview form submittal does not proceed
if the hash is incorrect.
Definition at line 143 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertNotEqual(), and django.contrib.formtools.tests.tests.PreviewTests.test_data.
def django.contrib.formtools.tests.tests.PreviewTests.test_form_submit_good_hash (self)
Test contrib.formtools.preview form submittal, using a correct
hash
Definition at line 127 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertNotEqual(), and django.contrib.formtools.tests.tests.PreviewTests.test_data.
def django.contrib.formtools.tests.tests.PreviewTests.test_unused_name (self)
Verifies name mangling to get uniue field name.
Definition at line 48 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
Member Data Documentation
django.contrib.formtools.tests.tests.PreviewTests.input
Definition at line 45 of file tests.py.
Referenced by django.contrib.formtools.tests.tests.PreviewTests.test_form_get(), and django.contrib.formtools.tests.tests.PreviewTests.test_form_preview().
django.contrib.formtools.tests.tests.PreviewTests.preview
Definition at line 43 of file tests.py.
django.contrib.formtools.tests.tests.PreviewTests.test_data
Definition at line 46 of file tests.py.
Referenced by django.contrib.formtools.tests.tests.PreviewTests.test_bool_submit(), django.contrib.formtools.tests.tests.PreviewTests.test_form_preview(), django.contrib.formtools.tests.tests.PreviewTests.test_form_submit(), django.contrib.formtools.tests.tests.PreviewTests.test_form_submit_bad_hash(), and django.contrib.formtools.tests.tests.PreviewTests.test_form_submit_good_hash().
string django.contrib.formtools.tests.tests.PreviewTests.urls = 'django.contrib.formtools.tests.urls' static
Definition at line 38 of file tests.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/formtools/tests/tests.py