Django: django.db.models.query_utils Namespace Reference
django.db.models.query_utils Namespace Reference
Classes
class DeferredAttribute
class InvalidQuery
class Q
class QueryWrapper
Functions
def select_related_descend
def deferred_class_factory (model, attrs)
Detailed Description
Various data structures used in query construction.
Factored out from django.db.models.query to avoid making the main module very
large and/or so that they can be used by other modules without getting into
circular import difficulties.
Function Documentation
def django.db.models.query_utils.deferred_class_factory (model, attrs)
Returns a class object that is a copy of "model" with the specified "attrs"
being replaced with DeferredAttribute objects. The "pk_value" ties the
deferred attributes to a particular instance of the model.
Definition at line 180 of file query_utils.py.
References django.template.defaultfilters.join().
Referenced by django.db.models.query.RawQuerySet.__iter__(), django.db.models.query.get_klass_info(), and django.db.models.query.QuerySet.iterator().
def django.db.models.query_utils.select_related_descend (field, restricted, requested, load_fields, reverse = False)
Returns True if this field should be used to descend deeper for
select_related() purposes. Used by both the query construction code
(sql.query.fill_related_selections()) and the model instance creation code
(query.get_klass_info()).
Arguments:
 * field - the field to be checked
 * restricted - a boolean field, indicating if the field list has been
   manually restricted using a requested clause)
 * requested - The select_related() dictionary.
 * load_fields - the set of fields to be loaded on this model
 * reverse - boolean, True if we are checking a reverse select related
Definition at line 141 of file query_utils.py.
Referenced by django.db.models.sql.compiler.SQLCompiler.fill_related_selections(), and django.db.models.query.get_klass_info().