Django: django.db.backends.sqlite3.base.SQLiteCursorWrapper Class Reference
django.db.backends.sqlite3.base.SQLiteCursorWrapper Class Reference
Public Member Functions
def execute
def executemany (self, query, param_list)
def convert_query (self, query)
Detailed Description
Django uses "format" style placeholders, but pysqlite2 uses "qmark" style.
This fixes it -- but note that if you want to use a literal "%s" in a query,
you'll need to use "%%s".
Definition at line 442 of file base.py.
Member Function Documentation
def django.db.backends.sqlite3.base.SQLiteCursorWrapper.convert_query (self, query)
Definition at line 458 of file base.py.
References django.utils.encoding.force_text().
Referenced by django.db.backends.sqlite3.base.SQLiteCursorWrapper.execute(), and django.db.backends.sqlite3.base.SQLiteCursorWrapper.executemany().
def django.db.backends.sqlite3.base.SQLiteCursorWrapper.execute (self, query, params = None)
Definition at line 448 of file base.py.
References django.db.backends.sqlite3.base.SQLiteCursorWrapper.convert_query().
def django.db.backends.sqlite3.base.SQLiteCursorWrapper.executemany (self, query, param_list)
Definition at line 454 of file base.py.
References django.db.backends.sqlite3.base.SQLiteCursorWrapper.convert_query().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py