Django: django.contrib.auth.backends.RemoteUserBackend Class Reference
django.contrib.auth.backends.RemoteUserBackend Class Reference
Public Member Functions
def authenticate (self, remote_user)
def clean_username (self, username)
def configure_user (self, user)
Public Member Functions inherited from django.contrib.auth.backends.ModelBackend
def authenticate (self, username=None, password=None, kwargs)
def get_group_permissions
def get_all_permissions
def has_perm
def has_module_perms (self, user_obj, app_label)
def get_user (self, user_id)
Static Public Attributes
create_unknown_user = True
Detailed Description
This backend is to be used in conjunction with the ``RemoteUserMiddleware``
found in the middleware module of this package, and is used when the server
is handling authentication outside of Django.
By default, the ``authenticate`` method creates ``User`` objects for
usernames that don't already exist in the database.  Subclasses can disable
this behavior by setting the ``create_unknown_user`` attribute to
``False``.
Definition at line 74 of file backends.py.
Member Function Documentation
def django.contrib.auth.backends.RemoteUserBackend.authenticate (self, remote_user)
The username passed as ``remote_user`` is considered trusted.  This
method simply returns the ``User`` object with the given username,
creating a new ``User`` object if ``create_unknown_user`` is ``True``.
Returns None if ``create_unknown_user`` is ``False`` and a ``User``
object with the given username is not found in the database.
Definition at line 89 of file backends.py.
References django.contrib.auth.backends.RemoteUserBackend.clean_username(), django.contrib.auth.backends.RemoteUserBackend.configure_user(), django.contrib.auth.backends.RemoteUserBackend.create_unknown_user, and django.contrib.auth.get_user_model().
def django.contrib.auth.backends.RemoteUserBackend.clean_username (self, username)
Performs any cleaning on the "username" prior to using it to get or
create the user object.  Returns the cleaned username.
By default, returns the username unchanged.
Definition at line 121 of file backends.py.
Referenced by django.contrib.auth.backends.RemoteUserBackend.authenticate(), and django.contrib.auth.middleware.RemoteUserMiddleware.process_request().
def django.contrib.auth.backends.RemoteUserBackend.configure_user (self, user)
Configures a user after creation and returns the updated user.
By default, returns the user unmodified.
Definition at line 130 of file backends.py.
Referenced by django.contrib.auth.backends.RemoteUserBackend.authenticate().
Member Data Documentation
django.contrib.auth.backends.RemoteUserBackend.create_unknown_user = True static
Definition at line 87 of file backends.py.
Referenced by django.contrib.auth.backends.RemoteUserBackend.authenticate().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/backends.py