Django: django.core.management.base.AppCommand Class Reference
django.core.management.base.AppCommand Class Reference
Public Member Functions
def handle (self, app_labels, options)
def handle_app (self, app, options)
Public Member Functions inherited from django.core.management.base.BaseCommand
def __init__ (self)
def get_version (self)
def usage (self, subcommand)
def create_parser (self, prog_name, subcommand)
def print_help (self, prog_name, subcommand)
def run_from_argv (self, argv)
def execute (self, args, options)
def validate
def handle (self, args, options)
Static Public Attributes
string args = '<appname appname ...>'
Static Public Attributes inherited from django.core.management.base.BaseCommand
tuple option_list
string help = ''
string args = ''
can_import_settings = True
requires_model_validation = True
output_transaction = False
leave_locale_alone = False
Additional Inherited Members
Public Attributes inherited from django.core.management.base.BaseCommand
style
stdout
stderr
Detailed Description
A management command which takes one or more installed application
names as arguments, and does something with each of them.
Rather than implementing ``handle()``, subclasses must implement
``handle_app()``, which will be called once for each application.
Definition at line 327 of file base.py.
Member Function Documentation
def django.core.management.base.AppCommand.handle (self, app_labels, options)
Definition at line 338 of file base.py.
References django.core.management.base.AppCommand.handle_app(), and django.template.defaultfilters.join().
def django.core.management.base.AppCommand.handle_app (self, app, options)
Perform the command's actions for ``app``, which will be the
Python module corresponding to an application name given on
the command line.
Definition at line 353 of file base.py.
Referenced by django.core.management.base.AppCommand.handle().
Member Data Documentation
string django.core.management.base.AppCommand.args = '<appname appname ...>' static
Definition at line 336 of file base.py.
Referenced by django.core.urlresolvers.ResolverMatch.__getitem__(), django.core.urlresolvers.ResolverMatch.__repr__(), django.template.base.TagHelperNode.get_resolved_arguments(), and django.template.defaulttags.URLNode.render().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/core/management/base.py