Django: django.test._doctest Namespace Reference
django.test._doctest Namespace Reference
Classes
class _OutputRedirectingPdb
class _SpoofOut
class _TestClass
class DebugRunner
class DocFileCase
class DocTest
class DocTestCase
class DocTestFailure
class DocTestFinder
class DocTestParser
class DocTestRunner
class Example
class OutputChecker
class Tester
class UnexpectedException
Functions
def patch_isclass (isclass)
def register_optionflag (name)
def testmod
def testfile
def run_docstring_examples
def set_unittest_reportflags (flags)
def DocTestSuite (module=None, globs=None, extraglobs=None, test_finder=None, test_class=DocTestCase, options)
def DocFileTest (path, module_relative=True, package=None, globs=None, parser=DocTestParser(), encoding=None, options)
def DocFileSuite (paths, kw)
def script_from_examples (s)
def testsource (module, name)
def debug_src
def debug_script
def debug
Variables
string __docformat__ = 'reStructuredText en'
list __all__
dictionary OPTIONFLAGS_BY_NAME = {}
tuple DONT_ACCEPT_TRUE_FOR_1 = register_optionflag('DONT_ACCEPT_TRUE_FOR_1')
tuple DONT_ACCEPT_BLANKLINE = register_optionflag('DONT_ACCEPT_BLANKLINE')
tuple NORMALIZE_WHITESPACE = register_optionflag('NORMALIZE_WHITESPACE')
tuple ELLIPSIS = register_optionflag('ELLIPSIS')
tuple SKIP = register_optionflag('SKIP')
tuple IGNORE_EXCEPTION_DETAIL = register_optionflag('IGNORE_EXCEPTION_DETAIL')
tuple COMPARISON_FLAGS
tuple REPORT_UDIFF = register_optionflag('REPORT_UDIFF')
tuple REPORT_CDIFF = register_optionflag('REPORT_CDIFF')
tuple REPORT_NDIFF = register_optionflag('REPORT_NDIFF')
tuple REPORT_ONLY_FIRST_FAILURE = register_optionflag('REPORT_ONLY_FIRST_FAILURE')
tuple REPORTING_FLAGS
string BLANKLINE_MARKER = '<BLANKLINE>'
string ELLIPSIS_MARKER = '...'
master = None
int _unittest_reportflags = 0
dictionary __test__
Function Documentation
def django.test._doctest.debug (module, name, pm = False)
Debug a single doctest docstring.
Provide the module (or dotted name of the module) containing the
test to be debugged and the name (within the module) of the object
with the docstring with tests to be debugged.
Definition at line 2642 of file _doctest.py.
References django.test._doctest.debug_script(), and django.test._doctest.testsource().
def django.test._doctest.debug_script (src, pm = False, globs = None)
Definition at line 2611 of file _doctest.py.
Referenced by django.test._doctest.debug(), and django.test._doctest.debug_src().
def django.test._doctest.debug_src (src, pm = False, globs = None)
Debug a single doctest docstring, in argument `src`'
Definition at line 2606 of file _doctest.py.
References django.test._doctest.debug_script(), and django.test._doctest.script_from_examples().
def django.test._doctest.DocFileSuite (paths, kw)
A unittest suite for one or more doctest files.
The path to each doctest file is given as a string; the
interpretation of that string depends on the keyword argument
"module_relative".
A number of options may be provided as keyword arguments:
module_relative
  If "module_relative" is True, then the given file paths are
  interpreted as os-independent module-relative paths.  By
  default, these paths are relative to the calling module's
  directory; but if the "package" argument is specified, then
  they are relative to that package.  To ensure os-independence,
  "filename" should use "/" characters to separate path
  segments, and may not be an absolute path (i.e., it may not
  begin with "/").
  If "module_relative" is False, then the given file paths are
  interpreted as os-specific paths.  These paths may be absolute
  or relative (to the current working directory).
package
  A Python package or the name of a Python package whose directory
  should be used as the base directory for module relative paths.
  If "package" is not specified, then the calling module's
  directory is used as the base directory for module relative
  filenames.  It is an error to specify "package" if
  "module_relative" is False.
setUp
  A set-up function.  This is called before running the
  tests in each file. The setUp function will be passed a DocTest
  object.  The setUp function can access the test globals as the
  globs attribute of the test passed.
tearDown
  A tear-down function.  This is called after running the
  tests in each file.  The tearDown function will be passed a DocTest
  object.  The tearDown function can access the test globals as the
  globs attribute of the test passed.
globs
  A dictionary containing initial global variables for the tests.
optionflags
  A set of doctest option flags expressed as an integer.
parser
  A DocTestParser (or subclass) that should be used to extract
  tests from the files.
encoding
  An encoding that will be used to convert the files to unicode.
Definition at line 2437 of file _doctest.py.
References django.test._doctest.DocFileTest().
def django.test._doctest.DocFileTest (path, module_relative = True, package = None, globs = None, parser = DocTestParser(), encoding = None, options)
Definition at line 2410 of file _doctest.py.
Referenced by django.test._doctest.DocFileSuite(), and django.test._doctest.DocFileCase.format_failure().
def django.test._doctest.DocTestSuite (module = None, globs = None, extraglobs = None, test_finder = None, test_class = DocTestCase, options)
Convert doctest tests for a module to a unittest test suite.
This converts each documentation string in a module that
contains doctest tests to a unittest test case.  If any of the
tests in a doc string fail, then the test case fails.  An exception
is raised showing the name of the file containing the test and a
(sometimes approximate) line number.
The `module` argument provides the module to be tested.  The argument
can be either a module or a module name.
If no argument is given, the calling module is used.
A number of options may be provided as keyword arguments:
setUp
  A set-up function.  This is called before running the
  tests in each file. The setUp function will be passed a DocTest
  object.  The setUp function can access the test globals as the
  globs attribute of the test passed.
tearDown
  A tear-down function.  This is called after running the
  tests in each file.  The tearDown function will be passed a DocTest
  object.  The tearDown function can access the test globals as the
  globs attribute of the test passed.
globs
  A dictionary containing initial global variables for the tests.
optionflags
   A set of doctest option flags expressed as an integer.
Definition at line 2332 of file _doctest.py.
Referenced by django.test._doctest.DocTestCase.shortDescription().
def django.test._doctest.patch_isclass (isclass)
Definition at line 119 of file _doctest.py.
def django.test._doctest.register_optionflag (name)
Definition at line 147 of file _doctest.py.
def django.test._doctest.run_docstring_examples (f, globs, verbose = False, name = "NoName", compileflags = None, optionflags = 0)
Test examples in the given object's docstring (`f`), using `globs`
as globals.  Optional argument `name` is used in failure messages.
If the optional argument `verbose` is true, then generate output
even if there are no failures.
`compileflags` gives the set of flags that should be used by the
Python compiler when running the examples.  If not specified, then
it will default to the set of future-import flags that apply to
`globs`.
Optional keyword arg `optionflags` specifies options for the
testing and output.  See the documentation for `testmod` for more
information.
Definition at line 2055 of file _doctest.py.
Referenced by django.test._doctest.testfile().
def django.test._doctest.script_from_examples (s)
Debugging Support
Definition at line 2510 of file _doctest.py.
References django.template.defaultfilters.join().
Referenced by django.test._doctest.debug_src(), and django.test._doctest.testsource().
def django.test._doctest.set_unittest_reportflags (flags)
Sets the unittest option flags.
The old flag is returned so that a runner could restore the old
value if it wished to:
  >>> old = _unittest_reportflags
  >>> set_unittest_reportflags(REPORT_NDIFF |
  ...                          REPORT_ONLY_FIRST_FAILURE) == old
  True
  >>> import doctest
  >>> doctest._unittest_reportflags == (REPORT_NDIFF |
  ...                                   REPORT_ONLY_FIRST_FAILURE)
  True
Only reporting flags can be set:
  >>> set_unittest_reportflags(ELLIPSIS)
  Traceback (most recent call last):
  ...
  ValueError: ('Only reporting flags allowed', 8)
  >>> set_unittest_reportflags(old) == (REPORT_NDIFF |
  ...                                   REPORT_ONLY_FIRST_FAILURE)
  True
Definition at line 2148 of file _doctest.py.
def django.test._doctest.testfile (filename, module_relative = True, name = None, package = None, globs = None, verbose = None, report = True, optionflags = 0, extraglobs = None, raise_on_error = False, parser = DocTestParser(), encoding = None)
Test examples in the given file.  Return (#failures, #tests).
Optional keyword arg "module_relative" specifies how filenames
should be interpreted:
  - If "module_relative" is True (the default), then "filename"
     specifies a module-relative path.  By default, this path is
     relative to the calling module's directory; but if the
     "package" argument is specified, then it is relative to that
     package.  To ensure os-independence, "filename" should use
     "/" characters to separate path segments, and should not
     be an absolute path (i.e., it may not begin with "/").
  - If "module_relative" is False, then "filename" specifies an
    os-specific path.  The path may be absolute or relative (to
    the current working directory).
Optional keyword arg "name" gives the name of the test; by default
use the file's basename.
Optional keyword argument "package" is a Python package or the
name of a Python package whose directory should be used as the
base directory for a module relative filename.  If no package is
specified, then the calling module's directory is used as the base
directory for module relative filenames.  It is an error to
specify "package" if "module_relative" is False.
Optional keyword arg "globs" gives a dict to be used as the globals
when executing examples; by default, use {}.  A copy of this dict
is actually used for each docstring, so that each docstring's
examples start with a clean slate.
Optional keyword arg "extraglobs" gives a dictionary that should be
merged into the globals that are used to execute examples.  By
default, no extra globals are used.
Optional keyword arg "verbose" prints lots of stuff if true, prints
only failures if false; by default, it's true iff "-v" is in sys.argv.
Optional keyword arg "report" prints a summary at the end when true,
else prints nothing at the end.  In verbose mode, the summary is
detailed, else very brief (in fact, empty if all tests passed).
Optional keyword arg "optionflags" or's together module constants,
and defaults to 0.  Possible values (see the docs for details):
    DONT_ACCEPT_TRUE_FOR_1
    DONT_ACCEPT_BLANKLINE
    NORMALIZE_WHITESPACE
    ELLIPSIS
    SKIP
    IGNORE_EXCEPTION_DETAIL
    REPORT_UDIFF
    REPORT_CDIFF
    REPORT_NDIFF
    REPORT_ONLY_FIRST_FAILURE
Optional keyword arg "raise_on_error" raises an exception on the
first unexpected exception or failure. This allows failures to be
post-mortem debugged.
Optional keyword arg "parser" specifies a DocTestParser (or
subclass) that should be used to extract tests from the files.
Optional keyword arg "encoding" specifies an encoding that should
be used to convert the file to unicode.
Advanced tomfoolery:  testmod runs methods of a local instance of
class doctest.Tester, then merges the results into (or creates)
global Tester instance doctest.master.  Methods of doctest.master
can be called directly too, if you want to do something unusual.
Passing report=0 to testmod is especially useful then, to delay
displaying a summary.  Invoke doctest.master.summarize(verbose)
when you're done fiddling.
Definition at line 1934 of file _doctest.py.
References django.test._doctest.run_docstring_examples().
Referenced by django.test._doctest.testmod().
def django.test._doctest.testmod (m = None, name = None, globs = None, verbose = None, report = True, optionflags = 0, extraglobs = None, raise_on_error = False, exclude_empty = False)
m=None, name=None, globs=None, verbose=None, report=True,
   optionflags=0, extraglobs=None, raise_on_error=False,
   exclude_empty=False
Test examples in docstrings in functions and classes reachable
from module m (or the current module if m is not supplied), starting
with m.__doc__.
Also test examples reachable from dict m.__test__ if it exists and is
not None.  m.__test__ maps names to functions, classes and strings;
function and class docstrings are tested even if the name is private;
strings are tested directly, as if they were docstrings.
Return (#failures, #tests).
See doctest.__doc__ for an overview.
Optional keyword arg "name" gives the name of the module; by default
use m.__name__.
Optional keyword arg "globs" gives a dict to be used as the globals
when executing examples; by default, use m.__dict__.  A copy of this
dict is actually used for each docstring, so that each docstring's
examples start with a clean slate.
Optional keyword arg "extraglobs" gives a dictionary that should be
merged into the globals that are used to execute examples.  By
default, no extra globals are used.  This is new in 2.4.
Optional keyword arg "verbose" prints lots of stuff if true, prints
only failures if false; by default, it's true iff "-v" is in sys.argv.
Optional keyword arg "report" prints a summary at the end when true,
else prints nothing at the end.  In verbose mode, the summary is
detailed, else very brief (in fact, empty if all tests passed).
Optional keyword arg "optionflags" or's together module constants,
and defaults to 0.  This is new in 2.3.  Possible values (see the
docs for details):
    DONT_ACCEPT_TRUE_FOR_1
    DONT_ACCEPT_BLANKLINE
    NORMALIZE_WHITESPACE
    ELLIPSIS
    SKIP
    IGNORE_EXCEPTION_DETAIL
    REPORT_UDIFF
    REPORT_CDIFF
    REPORT_NDIFF
    REPORT_ONLY_FIRST_FAILURE
Optional keyword arg "raise_on_error" raises an exception on the
first unexpected exception or failure. This allows failures to be
post-mortem debugged.
Advanced tomfoolery:  testmod runs methods of a local instance of
class doctest.Tester, then merges the results into (or creates)
global Tester instance doctest.master.  Methods of doctest.master
can be called directly too, if you want to do something unusual.
Passing report=0 to testmod is especially useful then, to delay
displaying a summary.  Invoke doctest.master.summarize(verbose)
when you're done fiddling.
Definition at line 1829 of file _doctest.py.
References django.test._doctest.testfile().
def django.test._doctest.testsource (module, name)
Extract the test sources from a doctest docstring as a script.
Provide the module (or dotted name of the module) containing the
test to be debugged and the name (within the module) of the object
with the doc string with tests to be debugged.
Definition at line 2590 of file _doctest.py.
References find, and django.test._doctest.script_from_examples().
Referenced by django.test._doctest.debug().
Variable Documentation
list django.test._doctest.__all__
Definition at line 62 of file _doctest.py.
string django.test._doctest.__docformat__ = 'reStructuredText en'
Definition at line 60 of file _doctest.py.
dictionary django.test._doctest.__test__
Initial value:
 = {"_TestClass": _TestClass,
             "string": r,
             "bool-int equivalence": r,
             "blank lines": r,
             "ellipsis": r,
             "whitespace normalization": r,
            }
Definition at line 2700 of file _doctest.py.
int django.test._doctest._unittest_reportflags = 0
Unittest Support
Definition at line 2146 of file _doctest.py.
string django.test._doctest.BLANKLINE_MARKER = '<BLANKLINE>'
Definition at line 176 of file _doctest.py.
tuple django.test._doctest.COMPARISON_FLAGS
Initial value:
 = (DONT_ACCEPT_TRUE_FOR_1 |
                     DONT_ACCEPT_BLANKLINE |
                     NORMALIZE_WHITESPACE |
                     ELLIPSIS |
                     SKIP |
                     IGNORE_EXCEPTION_DETAIL)
Definition at line 158 of file _doctest.py.
tuple django.test._doctest.DONT_ACCEPT_BLANKLINE = register_optionflag('DONT_ACCEPT_BLANKLINE')
Definition at line 152 of file _doctest.py.
tuple django.test._doctest.DONT_ACCEPT_TRUE_FOR_1 = register_optionflag('DONT_ACCEPT_TRUE_FOR_1')
Definition at line 151 of file _doctest.py.
tuple django.test._doctest.ELLIPSIS = register_optionflag('ELLIPSIS')
Definition at line 154 of file _doctest.py.
string django.test._doctest.ELLIPSIS_MARKER = '...'
Definition at line 177 of file _doctest.py.
tuple django.test._doctest.IGNORE_EXCEPTION_DETAIL = register_optionflag('IGNORE_EXCEPTION_DETAIL')
Definition at line 156 of file _doctest.py.
django.test._doctest.master = None
Test Functions
These should be backwards compatible.
Definition at line 1825 of file _doctest.py.
tuple django.test._doctest.NORMALIZE_WHITESPACE = register_optionflag('NORMALIZE_WHITESPACE')
Definition at line 153 of file _doctest.py.
dictionary django.test._doctest.OPTIONFLAGS_BY_NAME = {}
Definition at line 146 of file _doctest.py.
tuple django.test._doctest.REPORT_CDIFF = register_optionflag('REPORT_CDIFF')
Definition at line 166 of file _doctest.py.
tuple django.test._doctest.REPORT_NDIFF = register_optionflag('REPORT_NDIFF')
Definition at line 167 of file _doctest.py.
tuple django.test._doctest.REPORT_ONLY_FIRST_FAILURE = register_optionflag('REPORT_ONLY_FIRST_FAILURE')
Definition at line 168 of file _doctest.py.
tuple django.test._doctest.REPORT_UDIFF = register_optionflag('REPORT_UDIFF')
Definition at line 165 of file _doctest.py.
tuple django.test._doctest.REPORTING_FLAGS
Initial value:
 = (REPORT_UDIFF |
                    REPORT_CDIFF |
                    REPORT_NDIFF |
                    REPORT_ONLY_FIRST_FAILURE)
Definition at line 170 of file _doctest.py.
tuple django.test._doctest.SKIP = register_optionflag('SKIP')
Definition at line 155 of file _doctest.py.