Django: django.contrib.comments.views.moderation Namespace Reference
django.contrib.comments.views.moderation Namespace Reference
Functions
def flag
def delete
def approve
def perform_flag (request, comment)
def perform_delete (request, comment)
def perform_approve (request, comment)
Variables
tuple flag_done
tuple delete_done
tuple approve_done
Function Documentation
def django.contrib.comments.views.moderation.approve (request, comment_id, next = None)
Approve a comment (that is, mark it as public and non-removed). Confirmation
on GET, action on POST. Requires the "can moderate comments" permission.
Templates: :template:`comments/approve.html`,
Context:
    comment
        the `comments.comment` object for approval
Definition at line 69 of file moderation.py.
References django.shortcuts.get_object_or_404(), django.contrib.comments.views.utils.next_redirect(), django.contrib.comments.views.moderation.perform_approve(), and django.shortcuts.render_to_response().
def django.contrib.comments.views.moderation.delete (request, comment_id, next = None)
Deletes a comment. Confirmation on GET, action on POST. Requires the "can
moderate comments" permission.
Templates: :template:`comments/delete.html`,
Context:
    comment
        the flagged `comments.comment` object
Definition at line 41 of file moderation.py.
References django.shortcuts.get_object_or_404(), django.contrib.comments.views.utils.next_redirect(), django.contrib.comments.views.moderation.perform_delete(), django.contrib.auth.decorators.permission_required(), and django.shortcuts.render_to_response().
Referenced by django.contrib.sites.tests.SitesFrameworkTests.test_delete_all_sites_clears_cache(), django.contrib.gis.tests.layermap.tests.LayerMapTest.test_layermap_strict(), django.contrib.sitemaps.tests.test_http.HTTPSitemapTests.test_sitemap_get_urls_no_site_1(), and django.contrib.gis.tests.layermap.tests.LayerMapTest.test_test_fid_range_step().
def django.contrib.comments.views.moderation.flag (request, comment_id, next = None)
Flags a comment. Confirmation on GET, action on POST.
Templates: :template:`comments/flag.html`,
Context:
    comment
        the flagged `comments.comment` object
Definition at line 15 of file moderation.py.
References django.shortcuts.get_object_or_404(), django.contrib.comments.views.utils.next_redirect(), django.contrib.comments.views.moderation.perform_flag(), django.contrib.auth.decorators.permission_required(), and django.shortcuts.render_to_response().
def django.contrib.comments.views.moderation.perform_approve (request, comment)
Definition at line 133 of file moderation.py.
Referenced by django.contrib.comments.views.moderation.approve().
def django.contrib.comments.views.moderation.perform_delete (request, comment)
Definition at line 116 of file moderation.py.
Referenced by django.contrib.comments.views.moderation.delete().
def django.contrib.comments.views.moderation.perform_flag (request, comment)
Actually perform the flagging of a comment from a request.
Definition at line 99 of file moderation.py.
Referenced by django.contrib.comments.views.moderation.flag().
Variable Documentation
tuple django.contrib.comments.views.moderation.approve_done
Initial value:
 = confirmation_view(
     template = "comments/approved.html",
     doc = 'Displays a "comment was approved" success page.'
 )
Definition at line 162 of file moderation.py.
tuple django.contrib.comments.views.moderation.delete_done
Initial value:
 = confirmation_view(
     template = "comments/deleted.html",
     doc = 'Displays a "comment was deleted" success page.'
 )
Definition at line 158 of file moderation.py.
tuple django.contrib.comments.views.moderation.flag_done
Initial value:
 = confirmation_view(
     template = "comments/flagged.html",
     doc = 'Displays a "comment was flagged" success page.'
 )
Definition at line 154 of file moderation.py.