Django: django.contrib.formtools.tests.wizard.wizardtests.forms.ContactWizard Class Reference
django.contrib.formtools.tests.wizard.wizardtests.forms.ContactWizard Class Reference
Public Member Functions
def done (self, form_list, kwargs)
def get_context_data (self, form, kwargs)
Public Member Functions inherited from django.contrib.formtools.wizard.views.WizardView
def __repr__ (self)
def as_view (cls, args, kwargs)
def get_initkwargs (cls, form_list=None, initial_dict=None, instance_dict=None, condition_dict=None, args, kwargs)
def get_prefix (self, args, kwargs)
def get_form_list (self)
def dispatch (self, request, args, kwargs)
def get (self, request, args, kwargs)
def post (self, args, kwargs)
def render_next_step (self, form, kwargs)
def render_goto_step (self, goto_step, kwargs)
def render_done (self, form, kwargs)
def get_form_prefix
def get_form_initial (self, step)
def get_form_instance (self, step)
def get_form_kwargs
def get_form
def process_step (self, form)
def process_step_files (self, form)
def render_revalidation_failure (self, step, form, kwargs)
def get_form_step_data (self, form)
def get_form_step_files (self, form)
def get_all_cleaned_data (self)
def get_cleaned_data_for_step (self, step)
def get_next_step
def get_prev_step
def get_step_index
def get_context_data (self, form, kwargs)
def render (self, form=None, kwargs)
def done (self, form_list, kwargs)
Static Public Attributes
file_storage = temp_storage
Static Public Attributes inherited from django.contrib.formtools.wizard.views.WizardView
storage_name = None
form_list = None
initial_dict = None
instance_dict = None
condition_dict = None
string template_name = 'formtools/wizard/wizard_form.html'
Additional Inherited Members
Public Attributes inherited from django.contrib.formtools.wizard.views.WizardView
prefix
storage
steps
Detailed Description
Definition at line 34 of file forms.py.
Member Function Documentation
def django.contrib.formtools.tests.wizard.wizardtests.forms.ContactWizard.done (self, form_list, kwargs)
Definition at line 37 of file forms.py.
References django.contrib.formtools.wizard.views.WizardView.get_all_cleaned_data(), django.contrib.formtools.wizard.views.WizardView.get_cleaned_data_for_step(), and django.contrib.formtools.wizard.views.WizardView.render().
Referenced by django.contrib.formtools.wizard.views.WizardView.render_done().
def django.contrib.formtools.tests.wizard.wizardtests.forms.ContactWizard.get_context_data (self, form, kwargs)
Definition at line 49 of file forms.py.
Referenced by django.views.generic.edit.FormMixin.form_invalid(), django.views.generic.base.TemplateView.get(), django.views.generic.edit.ProcessFormView.get(), django.views.generic.dates.BaseDateListView.get(), django.contrib.syndication.views.Feed.get_feed(), and django.contrib.formtools.wizard.views.WizardView.render().
Member Data Documentation
django.contrib.formtools.tests.wizard.wizardtests.forms.ContactWizard.file_storage = temp_storage static
Definition at line 35 of file forms.py.
Referenced by django.contrib.formtools.wizard.storage.base.BaseStorage.get_step_files(), and django.contrib.formtools.wizard.storage.base.BaseStorage.set_step_files().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/formtools/tests/wizard/wizardtests/forms.py