Django: django.utils.itercompat Namespace Reference
django.utils.itercompat Namespace Reference
Functions
def is_iterable (x)
def is_iterator (x)
def product (args, kwds)
Detailed Description
Providing iterator functions that are not in all version of Python we support.
Where possible, we try to use the system-native version and only fall back to
these implementations if necessary.
Function Documentation
def django.utils.itercompat.is_iterable (x)
Definition at line 13 of file itercompat.py.
Referenced by django.test.client.encode_multipart(), django.core.management.validation.get_validation_errors(), and django.template.base.Library.inclusion_tag().
def django.utils.itercompat.is_iterator (x)
An implementation independent way of checking for iterators
Python 2.6 has a different implementation of collections.Iterator which
accepts anything with a `next` method. 2.7+ requires and `__iter__` method
as well.
Definition at line 22 of file itercompat.py.
Referenced by django.db.models.fields.Field.bind().
def django.utils.itercompat.product (args, kwds)
Definition at line 33 of file itercompat.py.
Referenced by django.core.management.commands.loaddata.Command.load_label().