Django: django.views.static Namespace Reference
django.views.static Namespace Reference
Functions
def serve
def directory_index (path, fullpath)
def was_modified_since
Variables
int STREAM_CHUNK_SIZE = 4096
string DEFAULT_DIRECTORY_INDEX_TEMPLATE
tuple template_translatable = ugettext_noop("Index of %(directory)s")
Detailed Description
Views and functions for serving static files. These are only to be used
during development, and SHOULD NOT be used in a production setting.
Function Documentation
def django.views.static.directory_index (path, fullpath)
Definition at line 102 of file static.py.
Referenced by django.views.static.serve().
def django.views.static.serve (request, path, document_root = None, show_indexes = False)
Serve static files below a given point in the directory structure.
To use, put a URL pattern such as::
    (r'^(?P<path>.*)$', 'django.views.static.serve', {'document_root' : '/path/to/my/files/'})
in your URLconf. You must provide the ``document_root`` param. You may
also set ``show_indexes`` to ``True`` if you'd like to serve a basic index
of the directory.  This index view will use the template hardcoded below,
but if you'd like to override it, you can create a template called
``static/directory_index.html``.
Definition at line 23 of file static.py.
References django.views.static.directory_index(), django.contrib.admin.util.unquote(), and django.views.static.was_modified_since().
def django.views.static.was_modified_since (header = None, mtime = 0, size = 0)
Was something modified since the user last downloaded it?
header
  This is the value of the If-Modified-Since header.  If this is None,
  I'll just return True.
mtime
  This is the modification time of the item we're talking about.
size
  This is the size of the item we're talking about.
Definition at line 120 of file static.py.
Referenced by django.views.static.serve().
Variable Documentation
string django.views.static.DEFAULT_DIRECTORY_INDEX_TEMPLATE
Initial value:
 = """
 {% load i18n %}
 <!DOCTYPE html>
 <html lang="en">
   <head>
     <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
     <meta http-equiv="Content-Language" content="en-us" />
     <meta name="robots" content="NONE,NOARCHIVE" />
     <title>{% blocktrans %}Index of {{ directory }}{% endblocktrans %}</title>
   </head>
   <body>
     <h1>{% blocktrans %}Index of {{ directory }}{% endblocktrans %}</h1>
     <ul>
       {% ifnotequal directory "/" %}
       <li><a href="../">../</a></li>
       {% endifnotequal %}
       {% for f in file_list %}
       <li><a href="{{ f|urlencode }}">{{ f }}</a></li>
       {% endfor %}
     </ul>
   </body>
 </html>
 """
Definition at line 77 of file static.py.
int django.views.static.STREAM_CHUNK_SIZE = 4096
Definition at line 20 of file static.py.
tuple django.views.static.template_translatable = ugettext_noop("Index of %(directory)s")
Definition at line 100 of file static.py.