Django: django.contrib.gis.gdal.tests.test_ds.DataSourceTest Class Reference
django.contrib.gis.gdal.tests.test_ds.DataSourceTest Class Reference
Public Member Functions
def test01_valid_shp (self)
def test02_invalid_shp (self)
def test03a_layers (self)
def test03b_layer_slice (self)
def test03c_layer_references (self)
def test04_features (self)
def test05_geometries (self)
def test06_spatial_filter (self)
def test07_integer_overflow (self)
Detailed Description
Definition at line 36 of file test_ds.py.
Member Function Documentation
def django.contrib.gis.gdal.tests.test_ds.DataSourceTest.test01_valid_shp (self)
Definition at line 38 of file test_ds.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.fail().
def django.contrib.gis.gdal.tests.test_ds.DataSourceTest.test02_invalid_shp (self)
Definition at line 62 of file test_ds.py.
References django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.gdal.tests.test_ds.DataSourceTest.test03a_layers (self)
Definition at line 67 of file test_ds.py.
References django.utils.unittest.case.TestCase.assertAlmostEqual(), django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.gdal.tests.test_ds.DataSourceTest.test03b_layer_slice (self)
Definition at line 118 of file test_ds.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_ds.DataSourceTest.test03c_layer_references (self)
Ensure OGR objects keep references to the objects they belong to.
Definition at line 133 of file test_ds.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.gis.gdal.prototypes.ds.get_layer.
def django.contrib.gis.gdal.tests.test_ds.DataSourceTest.test04_features (self)
Definition at line 155 of file test_ds.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_ds.DataSourceTest.test05_geometries (self)
Definition at line 179 of file test_ds.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_ds.DataSourceTest.test06_spatial_filter (self)
Definition at line 201 of file test_ds.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertRaises(), and django.contrib.gis.geometry.test_data.get_ds_file().
def django.contrib.gis.gdal.tests.test_ds.DataSourceTest.test07_integer_overflow (self)
Definition at line 236 of file test_ds.py.
References django.utils.unittest.case.TestCase.assertEqual().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/gdal/tests/test_ds.py