Django: django.core.management.ManagementUtility Class Reference
django.core.management.ManagementUtility Class Reference
Public Member Functions
def __init__
def main_help_text
def fetch_command (self, subcommand)
def autocomplete (self)
def execute (self)
Public Attributes
argv
prog_name
Detailed Description
Encapsulates the logic of the django-admin.py and manage.py utilities.
A ManagementUtility has a number of commands, which can be manipulated
by editing the self.commands dictionary.
Definition at line 215 of file __init__.py.
Constructor & Destructor Documentation
def django.core.management.ManagementUtility.__init__ (self, argv = None)
Definition at line 222 of file __init__.py.
Member Function Documentation
def django.core.management.ManagementUtility.autocomplete (self)
Output completion suggestions for BASH.
The output of this function is passed to BASH's `COMREPLY` variable and
treated as completion suggestions. `COMREPLY` expects a space
separated string as the result.
The `COMP_WORDS` and `COMP_CWORD` BASH environment variables are used
to get information about the cli input. Please refer to the BASH
man-page for more information about this variables.
Subcommand options are saved as pairs. A pair consists of
the long option string (e.g. '--exclude') and a boolean
value indicating if the option requires arguments. When printing to
stdout, a equal sign is appended to options which require arguments.
Note: If debugging this function, it is recommended to write the debug
output in a separate file. Otherwise the debug output will be treated
and formatted as potential completion suggestions.
Definition at line 275 of file __init__.py.
References django.core.management.ManagementUtility.fetch_command(), django.core.management.get_commands(), and django.template.defaultfilters.join().
Referenced by django.core.management.ManagementUtility.execute().
def django.core.management.ManagementUtility.execute (self)
Given the command-line arguments, this figures out which subcommand is
being run, creates a parser appropriate to that command, and runs it.
Definition at line 350 of file __init__.py.
References django.core.management.ManagementUtility.argv, django.core.management.ManagementUtility.autocomplete(), django.core.management.ManagementUtility.fetch_command(), django.get_version(), django.core.management.base.handle_default_options(), django.core.management.ManagementUtility.main_help_text(), and django.core.management.ManagementUtility.prog_name.
Referenced by django.core.management.base.BaseCommand.run_from_argv().
def django.core.management.ManagementUtility.fetch_command (self, subcommand)
Tries to fetch the given subcommand, printing a message with the
appropriate command called from the command line (usually
"django-admin.py" or "manage.py") if it can't be found.
Definition at line 254 of file __init__.py.
References django.core.management.get_commands(), django.core.management.load_command_class(), and django.core.management.ManagementUtility.prog_name.
Referenced by django.core.management.ManagementUtility.autocomplete(), and django.core.management.ManagementUtility.execute().
def django.core.management.ManagementUtility.main_help_text (self, commands_only = False)
Returns the script's main help text, as a string.
Definition at line 226 of file __init__.py.
References django.core.management.color.color_style(), django.core.management.get_commands(), django.template.defaultfilters.join(), and django.core.management.ManagementUtility.prog_name.
Referenced by django.core.management.ManagementUtility.execute().
Member Data Documentation
django.core.management.ManagementUtility.argv
Definition at line 223 of file __init__.py.
Referenced by django.core.management.ManagementUtility.execute().
django.core.management.ManagementUtility.prog_name
Definition at line 224 of file __init__.py.
Referenced by django.core.management.ManagementUtility.execute(), django.core.management.ManagementUtility.fetch_command(), and django.core.management.ManagementUtility.main_help_text().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/core/management/__init__.py