Django: django.views.generic.base.ContextMixin Class Reference
django.views.generic.base.ContextMixin Class Reference
Public Member Functions
def get_context_data (self, kwargs)
Detailed Description
A default context mixin that passes the keyword arguments received by
get_context_data as the template context.
Definition at line 16 of file base.py.
Member Function Documentation
def django.views.generic.base.ContextMixin.get_context_data (self, kwargs)
Definition at line 22 of file base.py.
Referenced by django.views.generic.edit.FormMixin.form_invalid(), django.views.generic.base.TemplateView.get(), django.views.generic.edit.ProcessFormView.get(), and django.views.generic.dates.BaseDateListView.get().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/views/generic/base.py