Django: django.template.base.Node Class Reference
django.template.base.Node Class Reference
Public Member Functions
def render (self, context)
def __iter__ (self)
def get_nodes_by_type (self, nodetype)
Static Public Attributes
must_be_first = False
tuple child_nodelists = ('nodelist',)
Detailed Description
Definition at line 802 of file base.py.
Member Function Documentation
def django.template.base.Node.__iter__ (self)
Definition at line 814 of file base.py.
def django.template.base.Node.get_nodes_by_type (self, nodetype)
Return a list of all nodes (within this node and its nodelist)
of the given type
Definition at line 817 of file base.py.
References django.template.base.Node.child_nodelists.
def django.template.base.Node.render (self, context)
Return the node rendered as a string.
Definition at line 808 of file base.py.
Referenced by django.templatetags.i18n.BlockTranslateNode.render(), and django.template.loader_tags.BlockNode.super().
Member Data Documentation
tuple django.template.base.Node.child_nodelists = ('nodelist',) static
Definition at line 806 of file base.py.
Referenced by django.template.base.Node.get_nodes_by_type().
django.template.base.Node.must_be_first = False static
Definition at line 805 of file base.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/template/base.py