Django: django.utils.datetime_safe Namespace Reference
django.utils.datetime_safe Namespace Reference
Classes
class date
class datetime
Functions
def new_date (d)
def new_datetime (d)
def strftime (dt, fmt)
Variables
tuple _illegal_formatting = re.compile(r"((^|[^%])(%%)*%[sy])")
Function Documentation
def django.utils.datetime_safe.new_date (d)
Definition at line 31 of file datetime_safe.py.
def django.utils.datetime_safe.new_datetime (d)
Generate a safe datetime from a datetime.date or datetime.datetime object.
Definition at line 35 of file datetime_safe.py.
def django.utils.datetime_safe.strftime (dt, fmt)
Definition at line 60 of file datetime_safe.py.
Referenced by django.db.models.fields.files.FileField.get_directory_name(), django.utils.feedgenerator.get_tag_uri(), django.core.management.commands.runserver.Command.inner_run(), and django.core.mail.backends.filebased.EmailBackend.write_message().
Variable Documentation
tuple django.utils.datetime_safe._illegal_formatting = re.compile(r"((^|[^%])(%%)*%[sy])")
Definition at line 46 of file datetime_safe.py.