Django: django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareAppendSlashTests Class Reference
django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareAppendSlashTests Class Reference
Public Member Functions
def test_redirect_view_flatpage (self)
def test_redirect_view_non_existent_flatpage (self)
def test_redirect_fallback_flatpage (self)
def test_redirect_fallback_non_existent_flatpage (self)
def test_redirect_fallback_flatpage_special_chars (self)
def test_redirect_fallback_flatpage_root (self)
Static Public Attributes
list fixtures = ['sample_flatpages', 'example_site']
string urls = 'django.contrib.flatpages.tests.urls'
Detailed Description
Definition at line 105 of file test_middleware.py.
Member Function Documentation
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareAppendSlashTests.test_redirect_fallback_flatpage (self)
Definition at line 119 of file test_middleware.py.
References django.test.testcases.SimpleTestCase.assertRedirects().
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareAppendSlashTests.test_redirect_fallback_flatpage_root (self)
Definition at line 143 of file test_middleware.py.
References django.test.testcases.SimpleTestCase.assertContains(), and django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareAppendSlashTests.test_redirect_fallback_flatpage_special_chars (self)
Definition at line 129 of file test_middleware.py.
References django.test.testcases.SimpleTestCase.assertRedirects().
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareAppendSlashTests.test_redirect_fallback_non_existent_flatpage (self)
Definition at line 124 of file test_middleware.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareAppendSlashTests.test_redirect_view_flatpage (self)
Definition at line 109 of file test_middleware.py.
References django.test.testcases.SimpleTestCase.assertRedirects().
def django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareAppendSlashTests.test_redirect_view_non_existent_flatpage (self)
Definition at line 114 of file test_middleware.py.
References django.utils.unittest.case.TestCase.assertEqual().
Member Data Documentation
list django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareAppendSlashTests.fixtures = ['sample_flatpages', 'example_site'] static
Definition at line 106 of file test_middleware.py.
string django.contrib.flatpages.tests.test_middleware.FlatpageMiddlewareAppendSlashTests.urls = 'django.contrib.flatpages.tests.urls' static
Definition at line 107 of file test_middleware.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/flatpages/tests/test_middleware.py