Django: django.test._doctest.DocFileCase Class Reference
django.test._doctest.DocFileCase Class Reference
Public Member Functions
def id (self)
def __repr__ (self)
def format_failure (self, err)
Public Member Functions inherited from django.test._doctest.DocTestCase
def __init__
def setUp (self)
def tearDown (self)
def runTest (self)
def format_failure (self, err)
def debug (self)
def id (self)
def __repr__ (self)
def shortDescription (self)
Detailed Description
Definition at line 2394 of file _doctest.py.
Member Function Documentation
def django.test._doctest.DocFileCase.__repr__ (self)
Definition at line 2399 of file _doctest.py.
def django.test._doctest.DocFileCase.format_failure (self, err)
Definition at line 2403 of file _doctest.py.
References django.test._doctest.DocFileTest().
def django.test._doctest.DocFileCase.id (self)
Definition at line 2396 of file _doctest.py.
References django.template.defaultfilters.join().
Referenced by django.utils.unittest.suite._ErrorHolder.__str__(), django.contrib.sitemaps.tests.base.TestModel.get_absolute_url(), and django.contrib.auth.models.AbstractUser.get_profile().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/test/_doctest.py