Django: django.contrib.auth.tests.urls Namespace Reference
django.contrib.auth.tests.urls Namespace Reference
Classes
class CustomRequestAuthenticationForm
Functions
def remote_user_auth_view (request)
def auth_processor_no_attr_access (request)
def auth_processor_attr_access (request)
def auth_processor_user (request)
def auth_processor_perms (request)
def auth_processor_perm_in_perms (request)
def auth_processor_messages (request)
def userpage (request)
def custom_request_auth_login (request)
Variables
tuple urlpatterns
Function Documentation
def django.contrib.auth.tests.urls.auth_processor_attr_access (request)
Definition at line 32 of file urls.py.
References django.shortcuts.render_to_response().
def django.contrib.auth.tests.urls.auth_processor_messages (request)
Definition at line 50 of file urls.py.
References django.contrib.gis.geos.prototypes.topology.info, and django.shortcuts.render_to_response().
def django.contrib.auth.tests.urls.auth_processor_no_attr_access (request)
Definition at line 25 of file urls.py.
References django.shortcuts.render_to_response().
def django.contrib.auth.tests.urls.auth_processor_perm_in_perms (request)
Definition at line 46 of file urls.py.
References django.shortcuts.render_to_response().
def django.contrib.auth.tests.urls.auth_processor_perms (request)
Definition at line 42 of file urls.py.
References django.shortcuts.render_to_response().
def django.contrib.auth.tests.urls.auth_processor_user (request)
Definition at line 38 of file urls.py.
References django.shortcuts.render_to_response().
def django.contrib.auth.tests.urls.custom_request_auth_login (request)
Definition at line 58 of file urls.py.
def django.contrib.auth.tests.urls.remote_user_auth_view (request)
Definition at line 19 of file urls.py.
def django.contrib.auth.tests.urls.userpage (request)
Definition at line 55 of file urls.py.
Variable Documentation
tuple django.contrib.auth.tests.urls.urlpatterns
Initial value:
 = urlpatterns+patterns('',
     (r'^logout/custom_query/$', 'django.contrib.auth.views.logout', dict(redirect_field_name='follow')),
     (r'^logout/next_page/$', 'django.contrib.auth.views.logout', dict(next_page='/somewhere/')),
     (r'^logout/next_page/named/$', 'django.contrib.auth.views.logout', dict(next_page='password_reset')),
     (r'^remote_user/$', remote_user_auth_view),
     (r'^password_reset_from_email/$', 'django.contrib.auth.views.password_reset', dict(from_email='staffmember@example.com')),
     (r'^password_reset/custom_redirect/$', 'django.contrib.auth.views.password_reset', dict(post_reset_redirect='/custom/')),
     (r'^password_reset/custom_redirect/named/$', 'django.contrib.auth.views.password_reset', dict(post_reset_redirect='password_reset')),
     (r'^reset/custom/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         'django.contrib.auth.views.password_reset_confirm',
         dict(post_reset_redirect='/custom/')),
     (r'^reset/custom/named/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         'django.contrib.auth.views.password_reset_confirm',
         dict(post_reset_redirect='password_reset')),
     (r'^password_change/custom/$', 'django.contrib.auth.views.password_change', dict(post_change_redirect='/custom/')),
     (r'^password_change/custom/named/$', 'django.contrib.auth.views.password_change', dict(post_change_redirect='password_reset')),
     (r'^admin_password_reset/$', 'django.contrib.auth.views.password_reset', dict(is_admin_site=True)),
     (r'^login_required/$', login_required(password_reset)),
     (r'^login_required_login_url/$', login_required(password_reset, login_url='/somewhere/')),
     (r'^auth_processor_no_attr_access/$', auth_processor_no_attr_access),
     (r'^auth_processor_attr_access/$', auth_processor_attr_access),
     (r'^auth_processor_user/$', auth_processor_user),
     (r'^auth_processor_perms/$', auth_processor_perms),
     (r'^auth_processor_perm_in_perms/$', auth_processor_perm_in_perms),
     (r'^auth_processor_messages/$', auth_processor_messages),
     (r'^custom_request_auth_login/$', custom_request_auth_login),
     url(r'^userpage/(.+)/$', userpage, name="userpage"),
 )
Definition at line 62 of file urls.py.