Django: django.test.simple.OutputChecker Class Reference
django.test.simple.OutputChecker Class Reference
Public Member Functions
def check_output (self, want, got, optionflags)
def check_output_default (self, want, got, optionflags)
def check_output_numeric (self, want, got, optionflags)
def check_output_xml (self, want, got, optionsflags)
def check_output_json (self, want, got, optionsflags)
Detailed Description
Definition at line 35 of file simple.py.
Member Function Documentation
def django.test.simple.OutputChecker.check_output (self, want, got, optionflags)
The entry method for doctest output checking. Defers to a sequence of
child checkers
Definition at line 36 of file simple.py.
References django.test.simple.OutputChecker.check_output_default(), django.test.simple.OutputChecker.check_output_json(), django.test.simple.OutputChecker.check_output_numeric(), and django.test.simple.OutputChecker.check_output_xml().
def django.test.simple.OutputChecker.check_output_default (self, want, got, optionflags)
The default comparator provided by doctest - not perfect, but good for
most purposes
Definition at line 50 of file simple.py.
Referenced by django.test.simple.OutputChecker.check_output().
def django.test.simple.OutputChecker.check_output_json (self, want, got, optionsflags)
Tries to compare want and got as if they were JSON-encoded data
Definition at line 75 of file simple.py.
References django.test.utils.strip_quotes().
Referenced by django.test.simple.OutputChecker.check_output().
def django.test.simple.OutputChecker.check_output_numeric (self, want, got, optionflags)
Doctest does an exact string comparison of output, which means that
some numerically equivalent values aren't equal. This check normalizes
 * long integers (22L) so that they equal normal integers. (22)
 * Decimals so that they are comparable, regardless of the change
   made to __repr__ in Python 2.6.
Definition at line 57 of file simple.py.
References django.test.simple.normalize_decimals, and django.test.simple.normalize_long_ints.
Referenced by django.test.simple.OutputChecker.check_output().
def django.test.simple.OutputChecker.check_output_xml (self, want, got, optionsflags)
Definition at line 69 of file simple.py.
References django.test.utils.compare_xml().
Referenced by django.test.simple.OutputChecker.check_output().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/test/simple.py