Django: django.contrib.auth.tests.test_models.IsActiveTestCase Class Reference
django.contrib.auth.tests.test_models.IsActiveTestCase Class Reference
Public Member Functions
def test_builtin_user_isactive (self)
def test_is_active_field_default (self)
Detailed Description
Tests the behavior of the guaranteed is_active attribute
Definition at line 114 of file test_models.py.
Member Function Documentation
def django.contrib.auth.tests.test_models.IsActiveTestCase.test_builtin_user_isactive (self)
Definition at line 120 of file test_models.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertFalse().
def django.contrib.auth.tests.test_models.IsActiveTestCase.test_is_active_field_default (self)
tests that the default value for is_active is provided
Definition at line 131 of file test_models.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.auth.get_user_model().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_models.py