Django: django.contrib.webdesign.templatetags.webdesign.LoremNode Class Reference
django.contrib.webdesign.templatetags.webdesign.LoremNode Class Reference
Public Member Functions
def __init__ (self, count, method, common)
def render (self, context)
Public Attributes
common
method
Detailed Description
Definition at line 8 of file webdesign.py.
Constructor & Destructor Documentation
def django.contrib.webdesign.templatetags.webdesign.LoremNode.__init__ (self, count, method, common)
Definition at line 9 of file webdesign.py.
Member Function Documentation
def django.contrib.webdesign.templatetags.webdesign.LoremNode.render (self, context)
Definition at line 12 of file webdesign.py.
Referenced by django.forms.widgets.Media.__str__(), django.forms.widgets.ChoiceInput.__str__(), django.forms.widgets.ChoiceFieldRenderer.__str__(), django.templatetags.i18n.BlockTranslateNode.render(), and django.template.loader_tags.BlockNode.super().
Member Data Documentation
django.contrib.webdesign.templatetags.webdesign.LoremNode.common
Definition at line 10 of file webdesign.py.
django.contrib.webdesign.templatetags.webdesign.LoremNode.method
Definition at line 17 of file webdesign.py.
Referenced by django.http.request.HttpRequest.body().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/webdesign/templatetags/webdesign.py