Django: django.core.management.LaxOptionParser Class Reference
django.core.management.LaxOptionParser Class Reference
Public Member Functions
def error (self, msg)
def print_help (self)
def print_lax_help (self)
Detailed Description
An option parser that doesn't raise any errors on unknown options.
This is needed because the --settings and --pythonpath options affect
the commands (and thus the options) that are available to the user.
Definition at line 161 of file __init__.py.
Member Function Documentation
def django.core.management.LaxOptionParser.error (self, msg)
Definition at line 168 of file __init__.py.
Referenced by django.template.base.Parser.empty_block_tag(), django.template.base.Parser.empty_variable(), django.test.html.Parser.handle_endtag(), django.template.base.Parser.invalid_block_tag(), django.utils.html_parser.HTMLParser.parse_endtag(), and django.template.base.Parser.unclosed_block_tag().
def django.core.management.LaxOptionParser.print_help (self)
Output nothing.
The lax options are included in the normal option parser, so under
normal usage, we don't need to print the lax options.
Definition at line 171 of file __init__.py.
def django.core.management.LaxOptionParser.print_lax_help (self)
Output the basic options available to every command.
This just redirects to the default print_help() behavior.
Definition at line 179 of file __init__.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/core/management/__init__.py