Django: django.http.multipartparser Namespace Reference
django.http.multipartparser Namespace Reference
Classes
class BoundaryIter
class ChunkIter
class InputStreamExhausted
class InterBoundaryIter
class LazyStream
class MultiPartParser
class MultiPartParserError
class Parser
Functions
def exhaust (stream_or_iterable)
def parse_boundary_stream (stream, max_header_size)
def parse_header (line)
Variables
tuple __all__ = ('MultiPartParser', 'MultiPartParserError', 'InputStreamExhausted')
string RAW = "raw"
string FILE = "file"
string FIELD = "field"
Detailed Description
Multi-part parsing for file uploads.
Exposes one class, ``MultiPartParser``, which feeds chunks of uploaded data to
file upload handlers for processing.
Function Documentation
def django.http.multipartparser.exhaust (stream_or_iterable)
Completely exhausts an iterator or stream.
Raise a MultiPartParserError if the argument is not a stream or an iterable.
Definition at line 515 of file multipartparser.py.
Referenced by django.http.multipartparser.MultiPartParser.parse().
def django.http.multipartparser.parse_boundary_stream (stream, max_header_size)
Parses one and exactly one stream that encapsulates a boundary.
Definition at line 533 of file multipartparser.py.
References django.http.multipartparser.parse_header().
Referenced by django.http.multipartparser.Parser.__iter__().
def django.http.multipartparser.parse_header (line)
Parse the header into a key-value.
    Input (line): bytes, output: unicode for key/name, bytes for value which
    will be decoded later
Definition at line 602 of file multipartparser.py.
References django.template.defaultfilters.lower().
Referenced by django.http.multipartparser.MultiPartParser.__init__(), and django.http.multipartparser.parse_boundary_stream().
Variable Documentation
tuple django.http.multipartparser.__all__ = ('MultiPartParser', 'MultiPartParserError', 'InputStreamExhausted')
Definition at line 21 of file multipartparser.py.
string django.http.multipartparser.FIELD = "field"
Definition at line 34 of file multipartparser.py.
string django.http.multipartparser.FILE = "file"
Definition at line 33 of file multipartparser.py.
string django.http.multipartparser.RAW = "raw"
Definition at line 32 of file multipartparser.py.