Django: django.contrib.gis.tests.layermap.tests.LayerMapRouterTest Class Reference
django.contrib.gis.tests.layermap.tests.LayerMapRouterTest Class Reference
Public Member Functions
def setUp (self)
def tearDown (self)
def test_layermapping_default_db (self)
Public Attributes
old_routers
Detailed Description
Definition at line 319 of file tests.py.
Member Function Documentation
def django.contrib.gis.tests.layermap.tests.LayerMapRouterTest.setUp (self)
Definition at line 321 of file tests.py.
Referenced by django.utils.unittest.case.TestCase.debug(), django.test._doctest.DocTestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.contrib.gis.tests.layermap.tests.LayerMapRouterTest.tearDown (self)
Definition at line 325 of file tests.py.
References django.contrib.gis.tests.layermap.tests.LayerMapRouterTest.old_routers.
Referenced by django.utils.unittest.case.TestCase.debug(), django.test._doctest.DocTestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.contrib.gis.tests.layermap.tests.LayerMapRouterTest.test_layermapping_default_db (self)
Definition at line 329 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
Member Data Documentation
django.contrib.gis.tests.layermap.tests.LayerMapRouterTest.old_routers
Definition at line 322 of file tests.py.
Referenced by django.contrib.gis.tests.layermap.tests.LayerMapRouterTest.tearDown().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/tests/layermap/tests.py