Django: django.contrib.auth.tests.test_views.LoginTest Class Reference
django.contrib.auth.tests.test_views.LoginTest Class Reference
Public Member Functions
def test_current_site_in_context_after_login (self)
def test_security_check
def test_login_form_contains_request (self)
def test_login_csrf_rotate
Public Member Functions inherited from django.contrib.auth.tests.test_views.AuthViewsTestCase
def login
def logout (self)
def assertFormError (self, response, error)
def assertURLEqual
Additional Inherited Members
Static Public Attributes inherited from django.contrib.auth.tests.test_views.AuthViewsTestCase
list fixtures = ['authtestdata.json']
string urls = 'django.contrib.auth.tests.urls'
Detailed Description
Definition at line 428 of file test_views.py.
Member Function Documentation
def django.contrib.auth.tests.test_views.LoginTest.test_current_site_in_context_after_login (self)
Definition at line 430 of file test_views.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertIsInstance(), django.utils.unittest.case.TestCase.assertTrue(), and django.db.models.fields.related.reverse.
def django.contrib.auth.tests.test_views.LoginTest.test_login_csrf_rotate (self, password = 'password')
Makes sure that a login rotates the currently-used CSRF token.
Definition at line 498 of file test_views.py.
References django.utils.unittest.case.TestCase.assertNotEqual().
def django.contrib.auth.tests.test_views.LoginTest.test_login_form_contains_request (self)
Definition at line 489 of file test_views.py.
def django.contrib.auth.tests.test_views.LoginTest.test_security_check (self, password = 'password')
Definition at line 442 of file test_views.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertFalse(), django.utils.unittest.case.TestCase.assertTrue(), and django.db.models.fields.related.reverse.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_views.py