Django: django.contrib.comments.views.utils Namespace Reference
django.contrib.comments.views.utils Namespace Reference
Functions
def next_redirect (request, fallback, get_kwargs)
def confirmation_view
Detailed Description
A few bits of helper functions for comment views.
Function Documentation
def django.contrib.comments.views.utils.confirmation_view (template, doc = "Display a confirmation view.")
Confirmation view generator for the "comment was
posted/flagged/deleted/approved" views.
Definition at line 41 of file utils.py.
References django.shortcuts.render_to_response().
def django.contrib.comments.views.utils.next_redirect (request, fallback, get_kwargs)
Handle the "where should I go next?" part of comment views.
The next value could be a
``?next=...`` GET arg or the URL of a given view (``fallback``). See
the view modules for examples.
Returns an ``HttpResponseRedirect``.
Definition at line 15 of file utils.py.
References django.shortcuts.resolve_url(), and django.template.defaultfilters.urlencode().
Referenced by django.contrib.comments.views.moderation.approve(), django.contrib.comments.views.moderation.delete(), django.contrib.comments.views.moderation.flag(), and django.contrib.comments.views.comments.post_comment().