Django: django.utils.timezone Namespace Reference
django.utils.timezone Namespace Reference
Classes
class LocalTimezone
class override
class ReferenceLocalTimezone
class UTC
Functions
def get_default_timezone ()
def get_default_timezone_name ()
def get_current_timezone ()
def get_current_timezone_name ()
def activate (timezone)
def deactivate ()
def template_localtime
def localtime
def now ()
def is_aware (value)
def is_naive (value)
def make_aware (value, timezone)
def make_naive (value, timezone)
Variables
pytz = None
list __all__
tuple ZERO = timedelta(0)
tuple utc = pytz.utcifpytzelseUTC()
_localtime = None
tuple _active = local()
Detailed Description
Timezone-related classes and functions.
This module uses pytz when it's available and fallbacks when it isn't.
Function Documentation
def django.utils.timezone.activate (timezone)
Sets the time zone for the current thread.
The ``timezone`` argument must be an instance of a tzinfo subclass or a
time zone name. If it is a time zone name, pytz is required.
Definition at line 180 of file timezone.py.
Referenced by django.utils.timezone.override.__enter__().
def django.utils.timezone.deactivate ()
Unsets the time zone for the current thread.
Django will then use the time zone defined by settings.TIME_ZONE.
Definition at line 194 of file timezone.py.
Referenced by django.utils.timezone.override.__enter__(), and django.utils.timezone.override.__exit__().
def django.utils.timezone.get_current_timezone ()
Returns the currently active time zone as a tzinfo instance.
Definition at line 152 of file timezone.py.
References django.utils.timezone.get_default_timezone().
Referenced by django.utils.timezone.get_current_timezone_name(), and django.utils.timezone.localtime().
def django.utils.timezone.get_current_timezone_name ()
Returns the name of the currently active time zone.
Definition at line 158 of file timezone.py.
References django.utils.timezone.get_current_timezone().
Referenced by django.utils.cache.has_vary_header().
def django.utils.timezone.get_default_timezone ()
Returns the default time zone as a tzinfo instance.
This is the time zone defined by settings.TIME_ZONE.
See also :func:`get_current_timezone`.
Definition at line 126 of file timezone.py.
Referenced by django.utils.timezone.get_current_timezone(), and django.utils.timezone.get_default_timezone_name().
def django.utils.timezone.get_default_timezone_name ()
Returns the name of the default time zone.
Definition at line 144 of file timezone.py.
References django.utils.timezone.get_default_timezone().
def django.utils.timezone.is_aware (value)
Determines if a given datetime.datetime is aware.
The logic is described in Python's docs:
http://docs.python.org/library/datetime.html#datetime.tzinfo
Definition at line 280 of file timezone.py.
Referenced by django.core.serializers.json.DjangoJSONEncoder.default(), django.contrib.humanize.templatetags.humanize.naturaltime(), django.utils.feedgenerator.rfc2822_date(), django.utils.feedgenerator.rfc3339_date(), django.utils.timesince.timesince(), and django.utils.dateformat.DateFormat.U().
def django.utils.timezone.is_naive (value)
Determines if a given datetime.datetime is naive.
The logic is described in Python's docs:
http://docs.python.org/library/datetime.html#datetime.tzinfo
Definition at line 289 of file timezone.py.
Referenced by django.contrib.syndication.views.Feed.get_feed(), and django.utils.timezone.template_localtime().
def django.utils.timezone.localtime (value, timezone = None)
Converts an aware datetime.datetime to local time.
Local time is defined by the current time zone, unless another time zone
is specified.
Definition at line 252 of file timezone.py.
References django.utils.timezone.get_current_timezone().
Referenced by django.utils.timezone.template_localtime().
def django.utils.timezone.make_aware (value, timezone)
Makes a naive datetime.datetime in a given time zone aware.
Definition at line 298 of file timezone.py.
def django.utils.timezone.make_naive (value, timezone)
Makes an aware datetime.datetime naive in a given time zone.
Definition at line 309 of file timezone.py.
def django.utils.timezone.now ()
Returns an aware or naive datetime.datetime, depending on settings.USE_TZ.
Definition at line 267 of file timezone.py.
def django.utils.timezone.template_localtime (value, use_tz = None)
Checks if value is a datetime and converts it to local time if necessary.
If use_tz is provided and is not None, that will force the value to
be converted (or not), overriding the value of settings.USE_TZ.
This function is designed for use by the template engine.
Definition at line 234 of file timezone.py.
References django.utils.timezone.is_naive(), and django.utils.timezone.localtime().
Referenced by django.template.debug.DebugVariableNode.render(), django.template.base.render_value_in_context(), and django.template.base.FilterExpression.resolve().
Variable Documentation
list django.utils.timezone.__all__
Initial value:
 = [
     'utc',
     'get_default_timezone', 'get_default_timezone_name',
     'get_current_timezone', 'get_current_timezone_name',
     'activate', 'deactivate', 'override',
     'localtime', 'now',
     'is_aware', 'is_naive', 'make_aware', 'make_naive',
 ]
Definition at line 20 of file timezone.py.
tuple django.utils.timezone._active = local()
Definition at line 150 of file timezone.py.
django.utils.timezone._localtime = None
Definition at line 124 of file timezone.py.
django.utils.timezone.pytz = None
Definition at line 15 of file timezone.py.
tuple django.utils.timezone.utc = pytz.utcifpytzelseUTC()
Definition at line 119 of file timezone.py.
tuple django.utils.timezone.ZERO = timedelta(0)
Definition at line 32 of file timezone.py.