Django: django.contrib.gis.db.models.sql.query.GeoQuery Class Reference
django.contrib.gis.db.models.sql.query.GeoQuery Class Reference
Public Member Functions
def __init__
Methods overridden from the base Query class ####.
def clone (self, args, kwargs)
def convert_values (self, value, field, connection)
def get_aggregation (self, using)
def resolve_aggregate (self, value, aggregate, connection)
Public Attributes
custom_select
transformed_srid
extra_select_fields
Static Public Attributes
query_terms = ALL_TERMS
aggregates_module = gis_aggregates
string compiler = 'GeoSQLCompiler'
Detailed Description
A single spatial SQL query.
Definition at line 24 of file query.py.
Constructor & Destructor Documentation
def django.contrib.gis.db.models.sql.query.GeoQuery.__init__ (self, model, where = GeoWhereNode)
Methods overridden from the base Query class ####.
Definition at line 35 of file query.py.
Member Function Documentation
def django.contrib.gis.db.models.sql.query.GeoQuery.clone (self, args, kwargs)
Definition at line 44 of file query.py.
References django.contrib.gis.db.models.sql.query.GeoQuery.transformed_srid.
Referenced by django.contrib.gis.geos.geometry.GEOSGeometry.__copy__(), django.contrib.gis.geos.geometry.GEOSGeometry.__deepcopy__(), django.db.models.sql.query.Query.__deepcopy__(), django.db.models.sql.query.Query.get_aggregation(), django.db.models.sql.query.Query.get_count(), django.db.models.sql.query.Query.has_results(), django.contrib.gis.gdal.geometries.OGRGeometry.transform(), and django.contrib.gis.geos.geometry.GEOSGeometry.transform().
def django.contrib.gis.db.models.sql.query.GeoQuery.convert_values (self, value, field, connection)
Using the same routines that Oracle does we can convert our
extra selection objects into Geometry and Distance objects.
TODO: Make converted objects 'lazy' for less overhead.
Definition at line 53 of file query.py.
References django.contrib.gis.geometry.backend.Geometry.
Referenced by django.db.models.sql.query.Query.resolve_aggregate().
def django.contrib.gis.db.models.sql.query.GeoQuery.get_aggregation (self, using)
Definition at line 79 of file query.py.
References django.contrib.gis.db.models.sql.query.GeoQuery.extra_select_fields.
def django.contrib.gis.db.models.sql.query.GeoQuery.resolve_aggregate (self, value, aggregate, connection)
Overridden from GeoQuery's normalize to handle the conversion of
GeoAggregate objects.
Definition at line 89 of file query.py.
Referenced by django.db.models.sql.query.Query.get_aggregation().
Member Data Documentation
django.contrib.gis.db.models.sql.query.GeoQuery.aggregates_module = gis_aggregates static
Definition at line 30 of file query.py.
string django.contrib.gis.db.models.sql.query.GeoQuery.compiler = 'GeoSQLCompiler' static
Definition at line 32 of file query.py.
Referenced by django.db.models.sql.query.Query.get_compiler().
django.contrib.gis.db.models.sql.query.GeoQuery.custom_select
Definition at line 40 of file query.py.
django.contrib.gis.db.models.sql.query.GeoQuery.extra_select_fields
Definition at line 42 of file query.py.
Referenced by django.contrib.gis.db.models.sql.query.GeoQuery.get_aggregation().
django.contrib.gis.db.models.sql.query.GeoQuery.query_terms = ALL_TERMS static
Definition at line 29 of file query.py.
Referenced by django.db.models.sql.query.Query.build_filter().
django.contrib.gis.db.models.sql.query.GeoQuery.transformed_srid
Definition at line 41 of file query.py.
Referenced by django.contrib.gis.db.models.sql.query.GeoQuery.clone().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/db/models/sql/query.py