Django: django.core.cache Namespace Reference
django.core.cache Namespace Reference
Namespaces
backends
utils
Functions
def parse_backend_uri (backend_uri)
def parse_backend_conf (backend, kwargs)
def get_cache (backend, kwargs)
Variables
list __all__
dictionary BACKENDS
string DEFAULT_CACHE_ALIAS = 'default'
tuple cache = get_cache(DEFAULT_CACHE_ALIAS)
Detailed Description
Caching framework.
This package defines set of cache backends that all conform to a simple API.
In a nutshell, a cache is a set of values -- which can be any object that
may be pickled -- identified by string keys.  For the complete API, see
the abstract BaseCache class in django.core.cache.backends.base.
Client code should not access a cache backend directly; instead it should
either use the "cache" variable made available here, or it should use the
get_cache() function made available here. get_cache() takes a backend URI
(e.g. "memcached://127.0.0.1:11211/") and returns an instance of a backend
cache class.
See docs/topics/cache.txt for information on the public API.
Function Documentation
def django.core.cache.get_cache (backend, kwargs)
Function to load a cache backend dynamically. This is flexible by design
to allow different use cases:
To load a backend with the old URI-based notation::
    cache = get_cache('locmem://')
To load a backend that is pre-defined in the settings::
    cache = get_cache('default')
To load a backend with its dotted import path,
including arbitrary options::
    cache = get_cache('django.core.cache.backends.memcached.MemcachedCache', **{
        'LOCATION': '127.0.0.1:11211', 'TIMEOUT': 30,
    })
Definition at line 95 of file __init__.py.
References django.utils.module_loading.import_by_path(), django.core.cache.parse_backend_conf(), and django.core.cache.parse_backend_uri().
Referenced by django.contrib.sessions.backends.cache.SessionStore.__init__(), django.contrib.gis.db.backends.spatialite.creation.SpatiaLiteCreation.create_test_db(), django.db.backends.creation.BaseDatabaseCreation.create_test_db(), django.utils.cache.get_cache_key(), django.utils.cache.learn_cache_key(), and django.contrib.sessions.tests.CacheSessionTests.test_default_cache().
def django.core.cache.parse_backend_conf (backend, kwargs)
Helper function to parse the backend configuration
that doesn't use the URI notation.
Definition at line 72 of file __init__.py.
References django.utils.module_loading.import_by_path().
Referenced by django.core.cache.get_cache().
def django.core.cache.parse_backend_uri (backend_uri)
Converts the "backend_uri" into a cache scheme ('db', 'memcached', etc), a
host and any extra params that are required for the backend. Returns a
(scheme, host, params) tuple.
Definition at line 45 of file __init__.py.
Referenced by django.core.cache.get_cache().
Variable Documentation
list django.core.cache.__all__
Initial value:
 = [
     'get_cache', 'cache', 'DEFAULT_CACHE_ALIAS'
 ]
Definition at line 28 of file __init__.py.
dictionary django.core.cache.BACKENDS
Initial value:
 = {
     'memcached': 'memcached',
     'locmem': 'locmem',
     'file': 'filebased',
     'db': 'db',
     'dummy': 'dummy',
 }
Definition at line 35 of file __init__.py.
tuple django.core.cache.cache = get_cache(DEFAULT_CACHE_ALIAS)
Definition at line 138 of file __init__.py.
string django.core.cache.DEFAULT_CACHE_ALIAS = 'default'
Definition at line 43 of file __init__.py.