Django: django.contrib.contenttypes.management Namespace Reference
django.contrib.contenttypes.management Namespace Reference
Functions
def update_contenttypes (app, created_models, verbosity=2, db=DEFAULT_DB_ALIAS, kwargs)
def update_all_contenttypes (verbosity=2, kwargs)
Function Documentation
def django.contrib.contenttypes.management.update_all_contenttypes (verbosity = 2, kwargs)
Definition at line 87 of file management.py.
References django.db.models.loading.get_apps, and django.contrib.contenttypes.management.update_contenttypes().
def django.contrib.contenttypes.management.update_contenttypes (app, created_models, verbosity = 2, db = DEFAULT_DB_ALIAS, kwargs)
Creates content types for models in the given app, removing any model
entries that no longer have a matching model class.
Definition at line 9 of file management.py.
References django.db.models.loading.get_model, django.db.models.loading.get_models, django.template.defaultfilters.join(), and django.utils.encoding.smart_text().
Referenced by django.contrib.contenttypes.management.update_all_contenttypes().