Django: django.contrib.auth.tests.test_forms.AuthenticationFormTest Class Reference
django.contrib.auth.tests.test_forms.AuthenticationFormTest Class Reference
Public Member Functions
def test_invalid_username (self)
def test_inactive_user (self)
def test_inactive_user_i18n (self)
def test_success (self)
def test_username_field_label (self)
def test_username_field_label_not_set (self)
def test_username_field_label_empty_string (self)
Static Public Attributes
list fixtures = ['authtestdata.json']
Detailed Description
Definition at line 92 of file test_forms.py.
Member Function Documentation
def django.contrib.auth.tests.test_forms.AuthenticationFormTest.test_inactive_user (self)
Definition at line 110 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertFalse(), and django.utils.encoding.force_text().
def django.contrib.auth.tests.test_forms.AuthenticationFormTest.test_inactive_user_i18n (self)
Definition at line 121 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertFalse(), django.utils.encoding.force_text(), and django.test.testcases.SimpleTestCase.settings().
def django.contrib.auth.tests.test_forms.AuthenticationFormTest.test_invalid_username (self)
Definition at line 96 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertFalse(), and django.utils.encoding.force_text().
def django.contrib.auth.tests.test_forms.AuthenticationFormTest.test_success (self)
Definition at line 134 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.auth.tests.test_forms.AuthenticationFormTest.test_username_field_label (self)
Definition at line 144 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.auth.tests.test_forms.AuthenticationFormTest.test_username_field_label_empty_string (self)
Definition at line 162 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.auth.tests.test_forms.AuthenticationFormTest.test_username_field_label_not_set (self)
Definition at line 152 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.text.capfirst, and django.contrib.auth.get_user_model().
Member Data Documentation
list django.contrib.auth.tests.test_forms.AuthenticationFormTest.fixtures = ['authtestdata.json'] static
Definition at line 94 of file test_forms.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_forms.py