Django: django.views.debug.ExceptionReporterFilter Class Reference
django.views.debug.ExceptionReporterFilter Class Reference
Public Member Functions
def get_request_repr (self, request)
def get_post_parameters (self, request)
def get_traceback_frame_variables (self, request, tb_frame)
Detailed Description
Base for all exception reporter filter classes. All overridable hooks
contain lenient default behaviors.
Definition at line 86 of file debug.py.
Member Function Documentation
def django.views.debug.ExceptionReporterFilter.get_post_parameters (self, request)
Definition at line 98 of file debug.py.
Referenced by django.views.debug.ExceptionReporterFilter.get_request_repr().
def django.views.debug.ExceptionReporterFilter.get_request_repr (self, request)
Definition at line 92 of file debug.py.
References django.http.request.build_request_repr(), and django.views.debug.ExceptionReporterFilter.get_post_parameters().
Referenced by django.views.debug.SafeExceptionReporterFilter.cleanse_special_types().
def django.views.debug.ExceptionReporterFilter.get_traceback_frame_variables (self, request, tb_frame)
Definition at line 104 of file debug.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/views/debug.py