Django: django.contrib.flatpages.tests.test_views.FlatpageViewAppendSlashTests Class Reference
django.contrib.flatpages.tests.test_views.FlatpageViewAppendSlashTests Class Reference
Public Member Functions
def test_redirect_view_flatpage (self)
def test_redirect_view_non_existent_flatpage (self)
def test_redirect_fallback_flatpage (self)
def test_redirect_fallback_non_existent_flatpage (self)
def test_redirect_view_flatpage_special_chars (self)
Static Public Attributes
list fixtures = ['sample_flatpages', 'example_site']
string urls = 'django.contrib.flatpages.tests.urls'
Detailed Description
Definition at line 93 of file test_views.py.
Member Function Documentation
def django.contrib.flatpages.tests.test_views.FlatpageViewAppendSlashTests.test_redirect_fallback_flatpage (self)
Definition at line 107 of file test_views.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_views.FlatpageViewAppendSlashTests.test_redirect_fallback_non_existent_flatpage (self)
Definition at line 112 of file test_views.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.flatpages.tests.test_views.FlatpageViewAppendSlashTests.test_redirect_view_flatpage (self)
Definition at line 97 of file test_views.py.
References django.test.testcases.SimpleTestCase.assertRedirects().
def django.contrib.flatpages.tests.test_views.FlatpageViewAppendSlashTests.test_redirect_view_flatpage_special_chars (self)
Definition at line 117 of file test_views.py.
References django.test.testcases.SimpleTestCase.assertRedirects().
def django.contrib.flatpages.tests.test_views.FlatpageViewAppendSlashTests.test_redirect_view_non_existent_flatpage (self)
Definition at line 102 of file test_views.py.
References django.utils.unittest.case.TestCase.assertEqual().
Member Data Documentation
list django.contrib.flatpages.tests.test_views.FlatpageViewAppendSlashTests.fixtures = ['sample_flatpages', 'example_site'] static
Definition at line 94 of file test_views.py.
string django.contrib.flatpages.tests.test_views.FlatpageViewAppendSlashTests.urls = 'django.contrib.flatpages.tests.urls' static
Definition at line 95 of file test_views.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/flatpages/tests/test_views.py