Django: django.core.files.base.ContentFile Class Reference
django.core.files.base.ContentFile Class Reference
Public Member Functions
def __init__
def __str__ (self)
def __bool__ (self)
def __nonzero__ (self)
def open
def close (self)
Public Member Functions inherited from django.core.files.base.File
def __init__
def __str__ (self)
def __repr__ (self)
def __bool__ (self)
def __nonzero__ (self)
def __len__ (self)
def chunks
def multiple_chunks
def __iter__ (self)
def __enter__ (self)
def __exit__ (self, exc_type, exc_value, tb)
def open
def close (self)
Public Member Functions inherited from django.core.files.utils.FileProxyMixin
def __iter__ (self)
Public Attributes
size
Public Attributes inherited from django.core.files.base.File
file
name
mode
Additional Inherited Members
Static Public Attributes inherited from django.core.files.base.File
int DEFAULT_CHUNK_SIZE = 64
Properties inherited from django.core.files.base.File
size = property(_get_size, _set_size)
closed = property(_get_closed)
Properties inherited from django.core.files.utils.FileProxyMixin
encoding = property(lambda self: self.file.encoding)
fileno = property(lambda self: self.file.fileno)
flush = property(lambda self: self.file.flush)
isatty = property(lambda self: self.file.isatty)
newlines = property(lambda self: self.file.newlines)
read = property(lambda self: self.file.read)
readinto = property(lambda self: self.file.readinto)
readline = property(lambda self: self.file.readline)
readlines = property(lambda self: self.file.readlines)
seek = property(lambda self: self.file.seek)
softspace = property(lambda self: self.file.softspace)
tell = property(lambda self: self.file.tell)
truncate = property(lambda self: self.file.truncate)
write = property(lambda self: self.file.write)
writelines = property(lambda self: self.file.writelines)
xreadlines = property(lambda self: self.file.xreadlines)
Detailed Description
A File-like object that takes just raw content, rather than an actual file.
Definition at line 132 of file base.py.
Constructor & Destructor Documentation
def django.core.files.base.ContentFile.__init__ (self, content, name = None)
Definition at line 136 of file base.py.
References django.utils.encoding.force_bytes().
Member Function Documentation
def django.core.files.base.ContentFile.__bool__ (self)
Definition at line 148 of file base.py.
Referenced by django.core.files.base.ContentFile.__nonzero__().
def django.core.files.base.ContentFile.__nonzero__ (self)
Definition at line 151 of file base.py.
References django.core.files.base.ContentFile.__bool__().
def django.core.files.base.ContentFile.__str__ (self)
Definition at line 145 of file base.py.
def django.core.files.base.ContentFile.close (self)
Definition at line 157 of file base.py.
Referenced by django.core.files.temp.TemporaryFile.__del__(), django.utils.archive.Archive.__exit__(), django.db.backends.BaseDatabaseWrapper.close_if_unusable_or_obsolete(), django.core.servers.basehttp.ServerHandler.finish_response(), django.core.mail.backends.console.EmailBackend.send_messages(), django.core.mail.backends.smtp.EmailBackend.send_messages(), and django.db.backends.BaseDatabaseWrapper.temporary_connection().
def django.core.files.base.ContentFile.open (self, mode = None)
Definition at line 154 of file base.py.
References django.core.files.utils.FileProxyMixin.seek.
Referenced by django.contrib.staticfiles.storage.CachedFilesMixin.hashed_name(), django.core.mail.backends.console.EmailBackend.send_messages(), and django.core.mail.backends.smtp.EmailBackend.send_messages().
Member Data Documentation
django.core.files.base.ContentFile.size
Definition at line 143 of file base.py.
Referenced by django.contrib.gis.geos.coordseq.GEOSCoordSeq.__iter__(), django.contrib.gis.geos.coordseq.GEOSCoordSeq.__len__(), django.contrib.gis.geos.coordseq.GEOSCoordSeq.__setitem__(), and django.contrib.gis.geos.coordseq.GEOSCoordSeq.tuple().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/core/files/base.py