Django: django.utils.autoreload Namespace Reference
django.utils.autoreload Namespace Reference
Functions
def code_changed ()
def check_errors (fn)
def ensure_echo_on ()
def reloader_thread ()
def restart_with_reloader ()
def python_reloader (main_func, args, kwargs)
def jython_reloader (main_func, args, kwargs)
def main
Variables
termios = None
RUN_RELOADER = True
dictionary _mtimes = {}
tuple _win = (sys.platform == "win32")
list _error_files = []
Function Documentation
def django.utils.autoreload.check_errors (fn)
Definition at line 90 of file autoreload.py.
References fn.
Referenced by django.utils.autoreload.main().
def django.utils.autoreload.code_changed ()
Definition at line 57 of file autoreload.py.
Referenced by django.utils.autoreload.jython_reloader(), and django.utils.autoreload.reloader_thread().
def django.utils.autoreload.ensure_echo_on ()
Definition at line 111 of file autoreload.py.
Referenced by django.utils.autoreload.reloader_thread().
def django.utils.autoreload.jython_reloader (main_func, args, kwargs)
Definition at line 161 of file autoreload.py.
References django.utils.autoreload.code_changed().
def django.utils.autoreload.main (main_func, args = None, kwargs = None)
Definition at line 170 of file autoreload.py.
References django.utils.autoreload.check_errors().
def django.utils.autoreload.python_reloader (main_func, args, kwargs)
Definition at line 144 of file autoreload.py.
References django.utils.autoreload.reloader_thread(), and django.utils.autoreload.restart_with_reloader().
def django.utils.autoreload.reloader_thread ()
Definition at line 126 of file autoreload.py.
References django.utils.autoreload.code_changed(), and django.utils.autoreload.ensure_echo_on().
Referenced by django.utils.autoreload.python_reloader().
def django.utils.autoreload.restart_with_reloader ()
Definition at line 133 of file autoreload.py.
Referenced by django.utils.autoreload.python_reloader().
Variable Documentation
list django.utils.autoreload._error_files = []
Definition at line 55 of file autoreload.py.
dictionary django.utils.autoreload._mtimes = {}
Definition at line 52 of file autoreload.py.
tuple django.utils.autoreload._win = (sys.platform == "win32")
Definition at line 53 of file autoreload.py.
django.utils.autoreload.RUN_RELOADER = True
Definition at line 50 of file autoreload.py.
django.utils.autoreload.termios = None
Definition at line 48 of file autoreload.py.