Django: django.contrib.auth.tests.test_forms.SetPasswordFormTest Class Reference
django.contrib.auth.tests.test_forms.SetPasswordFormTest Class Reference
Public Member Functions
def test_password_verification (self)
def test_success (self)
Static Public Attributes
list fixtures = ['authtestdata.json']
Detailed Description
Definition at line 173 of file test_forms.py.
Member Function Documentation
def django.contrib.auth.tests.test_forms.SetPasswordFormTest.test_password_verification (self)
Definition at line 177 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertEqual(), django.utils.unittest.case.TestCase.assertFalse(), and django.utils.encoding.force_text().
def django.contrib.auth.tests.test_forms.SetPasswordFormTest.test_success (self)
Definition at line 189 of file test_forms.py.
References django.utils.unittest.case.TestCase.assertTrue().
Member Data Documentation
list django.contrib.auth.tests.test_forms.SetPasswordFormTest.fixtures = ['authtestdata.json'] static
Definition at line 175 of file test_forms.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/auth/tests/test_forms.py