Django: django.contrib.webdesign.lorem_ipsum Namespace Reference
django.contrib.webdesign.lorem_ipsum Namespace Reference
Functions
def sentence ()
def paragraph ()
def paragraphs
def words
Variables
string COMMON_P = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
tuple WORDS
tuple COMMON_WORDS
Detailed Description
Utility functions for generating "lorem ipsum" Latin text.
Function Documentation
def django.contrib.webdesign.lorem_ipsum.paragraph ()
Returns a randomly generated paragraph of lorem ipsum text.
The paragraph consists of between 1 and 4 sentences, inclusive.
Definition at line 59 of file lorem_ipsum.py.
References django.template.defaultfilters.join(), and django.contrib.webdesign.lorem_ipsum.sentence().
Referenced by django.contrib.webdesign.lorem_ipsum.paragraphs().
def django.contrib.webdesign.lorem_ipsum.paragraphs (count, common = True)
Returns a list of paragraphs as returned by paragraph().
If `common` is True, then the first paragraph will be the standard
'lorem ipsum' paragraph. Otherwise, the first paragraph will be random
Latin text. Either way, subsequent paragraphs will be random Latin text.
Definition at line 67 of file lorem_ipsum.py.
References django.contrib.webdesign.lorem_ipsum.paragraph().
Referenced by django.contrib.webdesign.tests.WebdesignTest.test_paragraphs().
def django.contrib.webdesign.lorem_ipsum.sentence ()
Returns a randomly generated sentence of lorem ipsum text.
The first word is capitalized, and the sentence ends in either a period or
question mark. Commas are added at random.
Definition at line 45 of file lorem_ipsum.py.
References django.template.defaultfilters.join(), and django.template.defaultfilters.upper().
Referenced by django.contrib.webdesign.lorem_ipsum.paragraph().
def django.contrib.webdesign.lorem_ipsum.words (count, common = True)
Returns a string of `count` lorem ipsum words separated by a single space.
If `common` is True, then the first 19 words will be the standard
'lorem ipsum' words. Otherwise, all words will be selected randomly.
Definition at line 83 of file lorem_ipsum.py.
References django.template.defaultfilters.join().
Referenced by django.contrib.admin.widgets.ForeignKeyRawIdWidget.label_for_value(), django.contrib.webdesign.tests.WebdesignTest.test_words(), django.template.defaultfilters.truncatewords(), and django.template.defaultfilters.truncatewords_html().
Variable Documentation
string django.contrib.webdesign.lorem_ipsum.COMMON_P = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
Definition at line 9 of file lorem_ipsum.py.
tuple django.contrib.webdesign.lorem_ipsum.COMMON_WORDS
Initial value:
 = ('lorem', 'ipsum', 'dolor', 'sit', 'amet', 'consectetur',
         'adipisicing', 'elit', 'sed', 'do', 'eiusmod', 'tempor', 'incididunt',
         'ut', 'labore', 'et', 'dolore', 'magna', 'aliqua')
Definition at line 41 of file lorem_ipsum.py.
tuple django.contrib.webdesign.lorem_ipsum.WORDS
Initial value:
 = ('exercitationem', 'perferendis', 'perspiciatis', 'laborum', 'eveniet',
         'sunt', 'iure', 'nam', 'nobis', 'eum', 'cum', 'officiis', 'excepturi',
         'odio', 'consectetur', 'quasi', 'aut', 'quisquam', 'vel', 'eligendi',
         'itaque', 'non', 'odit', 'tempore', 'quaerat', 'dignissimos',
         'facilis', 'neque', 'nihil', 'expedita', 'vitae', 'vero', 'ipsum',
         'nisi', 'animi', 'cumque', 'pariatur', 'velit', 'modi', 'natus',
         'iusto', 'eaque', 'sequi', 'illo', 'sed', 'ex', 'et', 'voluptatibus',
         'tempora', 'veritatis', 'ratione', 'assumenda', 'incidunt', 'nostrum',
         'placeat', 'aliquid', 'fuga', 'provident', 'praesentium', 'rem',
         'necessitatibus', 'suscipit', 'adipisci', 'quidem', 'possimus',
         'voluptas', 'debitis', 'sint', 'accusantium', 'unde', 'sapiente',
         'voluptate', 'qui', 'aspernatur', 'laudantium', 'soluta', 'amet',
         'quo', 'aliquam', 'saepe', 'culpa', 'libero', 'ipsa', 'dicta',
         'reiciendis', 'nesciunt', 'doloribus', 'autem', 'impedit', 'minima',
         'maiores', 'repudiandae', 'ipsam', 'obcaecati', 'ullam', 'enim',
         'totam', 'delectus', 'ducimus', 'quis', 'voluptates', 'dolores',
         'molestiae', 'harum', 'dolorem', 'quia', 'voluptatem', 'molestias',
         'magni', 'distinctio', 'omnis', 'illum', 'dolorum', 'voluptatum', 'ea',
         'quas', 'quam', 'corporis', 'quae', 'blanditiis', 'atque', 'deserunt',
         'laboriosam', 'earum', 'consequuntur', 'hic', 'cupiditate',
         'quibusdam', 'accusamus', 'ut', 'rerum', 'error', 'minus', 'eius',
         'ab', 'ad', 'nemo', 'fugit', 'officia', 'at', 'in', 'id', 'quos',
         'reprehenderit', 'numquam', 'iste', 'fugiat', 'sit', 'inventore',
         'beatae', 'repellendus', 'magnam', 'recusandae', 'quod', 'explicabo',
         'doloremque', 'aperiam', 'consequatur', 'asperiores', 'commodi',
         'optio', 'dolor', 'labore', 'temporibus', 'repellat', 'veniam',
         'architecto', 'est', 'esse', 'mollitia', 'nulla', 'a', 'similique',
         'eos', 'alias', 'dolore', 'tenetur', 'deleniti', 'porro', 'facere',
         'maxime', 'corrupti')
Definition at line 11 of file lorem_ipsum.py.