Django: django.test.client Namespace Reference
django.test.client Namespace Reference
Classes
class Client
class ClientHandler
class FakePayload
class RequestFactory
Functions
def closing_iterator_wrapper (iterable, close)
def store_rendered_templates (store, signal, sender, template, context, kwargs)
def encode_multipart (boundary, data)
def encode_file (boundary, key, file)
Variables
tuple __all__ = ('Client', 'RequestFactory', 'encode_file', 'encode_multipart')
string BOUNDARY = 'BoUnDaRyStRiNg'
string MULTIPART_CONTENT = 'multipart/form-data; boundary=%s'
tuple CONTENT_TYPE_RE = re.compile('.*; charset=([\w\d-]+);?')
Function Documentation
def django.test.client.closing_iterator_wrapper (iterable, close)
Definition at line 72 of file client.py.
Referenced by django.test.client.ClientHandler.__call__().
def django.test.client.encode_file (boundary, key, file)
Definition at line 177 of file client.py.
References django.utils.encoding.force_bytes().
Referenced by django.test.client.encode_multipart().
def django.test.client.encode_multipart (boundary, data)
Encodes multipart POST data from a dictionary of form values.
The key will be used as the form data name; the value will be transmitted
as content. If the value is a file, the contents of the file will be sent
as an application/octet-stream; otherwise, str(value) will be sent.
Definition at line 132 of file client.py.
References django.utils.six.callable, django.test.client.encode_file(), django.utils.encoding.force_bytes(), django.utils.itercompat.is_iterable(), and django.template.defaultfilters.join().
Referenced by django.test.client.RequestFactory.request().
def django.test.client.store_rendered_templates (store, signal, sender, template, context, kwargs)
Stores templates and contexts that are rendered.
The context is copied so that it is an accurate representation at the time
of rendering.
Definition at line 122 of file client.py.
Variable Documentation
tuple django.test.client.__all__ = ('Client', 'RequestFactory', 'encode_file', 'encode_multipart')
Definition at line 29 of file client.py.
string django.test.client.BOUNDARY = 'BoUnDaRyStRiNg'
Definition at line 32 of file client.py.
tuple django.test.client.CONTENT_TYPE_RE = re.compile('.*; charset=([\w\d-]+);?')
Definition at line 34 of file client.py.
string django.test.client.MULTIPART_CONTENT = 'multipart/form-data; boundary=%s'
Definition at line 33 of file client.py.