Django: dj16/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js File Reference
RelatedObjectLookups.js File Reference
Functions
function html_unescape (text)
function id_to_windowname (text)
function windowname_to_id (text)
function showRelatedObjectLookupPopup (triggeringLink)
function dismissRelatedLookupPopup (win, chosenId)
function showAddAnotherPopup (triggeringLink)
function dismissAddAnotherPopup (win, newId, newRepr)
Function Documentation
function dismissAddAnotherPopup (win, newId, newRepr)
Definition at line 69 of file RelatedObjectLookups.js.
References html_unescape(), o, and windowname_to_id().
function dismissRelatedLookupPopup (win, chosenId)
Definition at line 44 of file RelatedObjectLookups.js.
References windowname_to_id().
function html_unescape (text)
Definition at line 4 of file RelatedObjectLookups.js.
References gt, lt(), and text.
Referenced by dismissAddAnotherPopup().
function id_to_windowname (text)
Definition at line 18 of file RelatedObjectLookups.js.
References text.
Referenced by showAddAnotherPopup(), and showRelatedObjectLookupPopup().
function showAddAnotherPopup (triggeringLink)
Definition at line 55 of file RelatedObjectLookups.js.
References id_to_windowname(), and window.
function showRelatedObjectLookupPopup (triggeringLink)
Definition at line 30 of file RelatedObjectLookups.js.
References id_to_windowname(), and window.
function windowname_to_id (text)
Definition at line 24 of file RelatedObjectLookups.js.
References text.
Referenced by dismissAddAnotherPopup(), and dismissRelatedLookupPopup().