Django: django.contrib.comments.models.CommentFlag Class Reference
django.contrib.comments.models.CommentFlag Class Reference
Classes
class Meta
Public Member Functions
def __str__ (self)
def save (self, args, kwargs)
Public Attributes
flag_date
Static Public Attributes
tuple user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('user'), related_name="comment_flags")
tuple comment = models.ForeignKey(Comment, verbose_name=_('comment'), related_name="flags")
tuple flag = models.CharField(_('flag'), max_length=30, db_index=True)
tuple flag_date = models.DateTimeField(_('date'), default=None)
string SUGGEST_REMOVAL = "removal suggestion"
string MODERATOR_DELETION = "moderator deletion"
string MODERATOR_APPROVAL = "moderator approval"
Detailed Description
Records a flag on a comment. This is intentionally flexible; right now, a
flag could be:
    * A "removal suggestion" -- where a user suggests a comment for (potential) removal.
    * A "moderator deletion" -- used when a moderator deletes a comment.
You can (ab)use this model to add other flags, if needed. However, by
design users are only allowed to flag a comment with a given flag once;
if you want rating look elsewhere.
Definition at line 164 of file models.py.
Member Function Documentation
def django.contrib.comments.models.CommentFlag.__str__ (self)
Definition at line 193 of file models.py.
References django.contrib.comments.models.CommentFlag.flag.
def django.contrib.comments.models.CommentFlag.save (self, args, kwargs)
Definition at line 197 of file models.py.
References django.contrib.comments.models.CommentFlag.flag_date.
Referenced by django.contrib.auth.models.AbstractBaseUser.check_password(), django.contrib.sessions.backends.cache.SessionStore.create(), django.contrib.sessions.backends.db.SessionStore.create(), django.contrib.sessions.backends.file.SessionStore.create(), and django.contrib.sessions.backends.signed_cookies.SessionStore.cycle_key().
Member Data Documentation
tuple django.contrib.comments.models.CommentFlag.comment = models.ForeignKey(Comment, verbose_name=_('comment'), related_name="flags") static
Definition at line 178 of file models.py.
tuple django.contrib.comments.models.CommentFlag.flag = models.CharField(_('flag'), max_length=30, db_index=True) static
Definition at line 179 of file models.py.
Referenced by django.contrib.comments.models.CommentFlag.__str__().
tuple django.contrib.comments.models.CommentFlag.flag_date = models.DateTimeField(_('date'), default=None) static
Definition at line 180 of file models.py.
Referenced by django.contrib.comments.models.CommentFlag.save().
django.contrib.comments.models.CommentFlag.flag_date
Definition at line 199 of file models.py.
string django.contrib.comments.models.CommentFlag.MODERATOR_APPROVAL = "moderator approval" static
Definition at line 185 of file models.py.
string django.contrib.comments.models.CommentFlag.MODERATOR_DELETION = "moderator deletion" static
Definition at line 184 of file models.py.
string django.contrib.comments.models.CommentFlag.SUGGEST_REMOVAL = "removal suggestion" static
Definition at line 183 of file models.py.
tuple django.contrib.comments.models.CommentFlag.user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('user'), related_name="comment_flags") static
Definition at line 177 of file models.py.
Referenced by django.contrib.flatpages.templatetags.flatpages.FlatpageNode.render(), and django.contrib.auth.tests.test_auth_backends.BaseModelBackendTest.test_authentication_timing().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/comments/models.py