Django: django.views.generic.list.BaseListView Class Reference
django.views.generic.list.BaseListView Class Reference
Public Member Functions
def get (self, request, args, kwargs)
Public Member Functions inherited from django.views.generic.list.MultipleObjectMixin
def get_queryset (self)
def paginate_queryset (self, queryset, page_size)
def get_paginate_by (self, queryset)
def get_paginator (self, queryset, per_page, orphans=0, allow_empty_first_page=True, kwargs)
def get_paginate_orphans (self)
def get_allow_empty (self)
def get_context_object_name (self, object_list)
def get_context_data (self, kwargs)
Public Member Functions inherited from django.views.generic.base.ContextMixin
def get_context_data (self, kwargs)
Public Member Functions inherited from django.views.generic.base.View
def __init__ (self, kwargs)
def as_view (cls, initkwargs)
def dispatch (self, request, args, kwargs)
def http_method_not_allowed (self, request, args, kwargs)
def options (self, request, args, kwargs)
Public Attributes
object_list
Public Attributes inherited from django.views.generic.base.View
head
request
args
kwargs
Additional Inherited Members
Static Public Attributes inherited from django.views.generic.list.MultipleObjectMixin
allow_empty = True
queryset = None
model = None
paginate_by = None
int paginate_orphans = 0
context_object_name = None
paginator_class = Paginator
string page_kwarg = 'page'
Static Public Attributes inherited from django.views.generic.base.View
list http_method_names = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace']
Detailed Description
A base view for displaying a list of objects.
Definition at line 132 of file list.py.
Member Function Documentation
def django.views.generic.list.BaseListView.get (self, request, args, kwargs)
Definition at line 136 of file list.py.
Referenced by django.contrib.contenttypes.models.ContentTypeManager.get_by_natural_key(), django.contrib.auth.models.PermissionManager.get_by_natural_key(), django.contrib.auth.models.GroupManager.get_by_natural_key(), django.contrib.auth.models.BaseUserManager.get_by_natural_key(), django.contrib.sites.models.SiteManager.get_current(), and django.contrib.contenttypes.models.ContentTypeManager.get_for_id().
Member Data Documentation
django.views.generic.list.BaseListView.object_list
Definition at line 137 of file list.py.
Referenced by django.views.generic.dates.BaseDateListView.get(), django.views.generic.list.MultipleObjectMixin.get_context_data(), and django.views.generic.list.MultipleObjectTemplateResponseMixin.get_template_names().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/views/generic/list.py