Django: django.core.management.utils Namespace Reference
django.core.management.utils Namespace Reference
Functions
def popen_wrapper
def handle_extensions (extensions=('html',, ignored=('py',)
def find_command
Function Documentation
def django.core.management.utils.find_command (cmd, path = None, pathext = None)
Definition at line 57 of file utils.py.
Referenced by django.core.management.commands.makemessages.check_programs(), and django.core.management.commands.compilemessages.compile_messages().
def django.core.management.utils.handle_extensions (extensions = ('html',, ignored = ('py',)
Organizes multiple extensions that are separated with commas or passed by
using --extension/-e multiple times. Note that the .py extension is ignored
here because of the way non-*.py files are handled in make_messages() (they
are copied to file.ext.py files to trick xgettext to parse them as Python
files).
For example: running 'django-admin makemessages -e js,txt -e xhtml -a'
would result in an extension list: ['.js', '.txt', '.xhtml']
>>> handle_extensions(['.html', 'html,js,py,py,py,.py', 'py,.py'])
set(['.html', '.js'])
>>> handle_extensions(['.html, txt,.tpl'])
set(['.html', '.tpl', '.txt'])
Definition at line 33 of file utils.py.
def django.core.management.utils.popen_wrapper (args, os_err_exc_type = CommandError)
Friendly wrapper around Popen.
Returns stdout output, stderr output and OS status code.
Definition at line 13 of file utils.py.
References django.utils.encoding.force_text().
Referenced by django.core.management.commands.compilemessages.compile_messages(), django.core.management.commands.makemessages.TranslatableFile.process(), and django.core.management.commands.makemessages.Command.write_po_file().