Django: django.views.generic.detail.BaseDetailView Class Reference
django.views.generic.detail.BaseDetailView Class Reference
Public Member Functions
def get (self, request, args, kwargs)
Public Member Functions inherited from django.views.generic.detail.SingleObjectMixin
def get_object
def get_queryset (self)
def get_slug_field (self)
def get_context_object_name (self, obj)
def get_context_data (self, kwargs)
Public Member Functions inherited from django.views.generic.base.ContextMixin
def get_context_data (self, kwargs)
Public Member Functions inherited from django.views.generic.base.View
def __init__ (self, kwargs)
def as_view (cls, initkwargs)
def dispatch (self, request, args, kwargs)
def http_method_not_allowed (self, request, args, kwargs)
def options (self, request, args, kwargs)
Public Attributes
object
Public Attributes inherited from django.views.generic.base.View
head
request
args
kwargs
Additional Inherited Members
Static Public Attributes inherited from django.views.generic.detail.SingleObjectMixin
model = None
queryset = None
string slug_field = 'slug'
context_object_name = None
string slug_url_kwarg = 'slug'
string pk_url_kwarg = 'pk'
Static Public Attributes inherited from django.views.generic.base.View
list http_method_names = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace']
Detailed Description
A base view for displaying a single object
Definition at line 105 of file detail.py.
Member Function Documentation
def django.views.generic.detail.BaseDetailView.get (self, request, args, kwargs)
Definition at line 109 of file detail.py.
Referenced by django.contrib.contenttypes.models.ContentTypeManager.get_by_natural_key(), django.contrib.auth.models.PermissionManager.get_by_natural_key(), django.contrib.auth.models.GroupManager.get_by_natural_key(), django.contrib.auth.models.BaseUserManager.get_by_natural_key(), django.contrib.sites.models.SiteManager.get_current(), and django.contrib.contenttypes.models.ContentTypeManager.get_for_id().
Member Data Documentation
django.views.generic.detail.BaseDetailView.object
Definition at line 110 of file detail.py.
Referenced by django.views.generic.detail.SingleObjectMixin.get_context_data(), django.views.generic.edit.ModelFormMixin.get_form_class(), django.views.generic.edit.ModelFormMixin.get_form_kwargs(), django.views.generic.detail.SingleObjectTemplateResponseMixin.get_template_names(), django.views.generic.edit.BaseCreateView.post(), and django.views.generic.edit.BaseUpdateView.post().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/views/generic/detail.py