Django: django.contrib.comments.admin.CommentsAdmin Class Reference
django.contrib.comments.admin.CommentsAdmin Class Reference
Public Member Functions
def get_actions (self, request)
def flag_comments (self, request, queryset)
def approve_comments (self, request, queryset)
def remove_comments (self, request, queryset)
Public Member Functions inherited from django.contrib.admin.options.ModelAdmin
def __init__ (self, model, admin_site)
def get_inline_instances
def get_urls (self)
def urls (self)
def media (self)
def get_model_perms (self, request)
def get_fieldsets
def get_form (self, request, obj=None, kwargs)
def get_changelist (self, request, kwargs)
def get_object (self, request, object_id)
def get_changelist_form (self, request, kwargs)
def get_changelist_formset (self, request, kwargs)
def get_formsets
def get_paginator
def log_addition (self, request, object)
def log_change (self, request, object, message)
def log_deletion (self, request, object, object_repr)
def action_checkbox (self, obj)
def get_actions (self, request)
def get_action_choices
def get_action (self, action)
def get_list_display (self, request)
def get_list_display_links (self, request, list_display)
def get_list_filter (self, request)
def get_search_results (self, request, queryset, search_term)
def get_preserved_filters (self, request)
def construct_change_message (self, request, form, formsets)
def message_user
def save_form (self, request, form, change)
def save_model (self, request, obj, form, change)
def delete_model (self, request, obj)
def save_formset (self, request, form, formset, change)
def save_related (self, request, form, formsets, change)
def render_change_form
def response_add
def response_change (self, request, obj)
def response_post_save_add (self, request, obj)
def response_post_save_change (self, request, obj)
def response_action (self, request, queryset)
def add_view
def change_view
def changelist_view
def delete_view
def history_view
Public Member Functions inherited from django.contrib.admin.options.BaseModelAdmin
def validate (cls, model)
def __init__ (self)
def formfield_for_dbfield (self, db_field, kwargs)
def formfield_for_choice_field (self, db_field, request=None, kwargs)
def get_field_queryset (self, db, db_field, request)
def formfield_for_foreignkey (self, db_field, request=None, kwargs)
def formfield_for_manytomany (self, db_field, request=None, kwargs)
def get_ordering (self, request)
def get_readonly_fields
def get_prepopulated_fields
def get_queryset (self, request)
def lookup_allowed (self, lookup, value)
def to_field_allowed (self, request, to_field)
def has_add_permission (self, request)
def has_change_permission
def has_delete_permission
Public Member Functions inherited from django.forms.widgets.MediaDefiningClass
def __new__ (cls, name, bases, attrs)
Public Member Functions inherited from django.utils.deprecation.RenameMethodsBase
def __new__ (cls, name, bases, attrs)
Static Public Attributes
tuple fieldsets
tuple list_display = ('name', 'content_type', 'object_pk', 'ip_address', 'submit_date', 'is_public', 'is_removed')
tuple list_filter = ('submit_date', 'site', 'is_public', 'is_removed')
string date_hierarchy = 'submit_date'
tuple ordering = ('-submit_date',)
tuple raw_id_fields = ('user',)
tuple search_fields = ('comment', UsernameSearch(), 'user_name', 'user_email', 'user_url', 'ip_address')
list actions = ["flag_comments", "approve_comments", "remove_comments"]
Static Public Attributes inherited from django.contrib.admin.options.ModelAdmin
tuple list_display = ('__str__',)
tuple list_display_links = ()
tuple list_filter = ()
list_select_related = False
int list_per_page = 100
int list_max_show_all = 200
tuple list_editable = ()
tuple search_fields = ()
date_hierarchy = None
save_as = False
save_on_top = False
paginator = Paginator
preserve_filters = True
list inlines = []
add_form_template = None
change_form_template = None
change_list_template = None
delete_confirmation_template = None
delete_selected_confirmation_template = None
object_history_template = None
list actions = []
action_form = helpers.ActionForm
actions_on_top = True
actions_on_bottom = False
actions_selection_counter = True
validator_class = validation.ModelAdminValidator
Static Public Attributes inherited from django.contrib.admin.options.BaseModelAdmin
tuple raw_id_fields = ()
fields = None
exclude = None
fieldsets = None
form = forms.ModelForm
tuple filter_vertical = ()
tuple filter_horizontal = ()
dictionary radio_fields = {}
dictionary prepopulated_fields = {}
dictionary formfield_overrides = {}
tuple readonly_fields = ()
ordering = None
validator_class = validation.BaseValidator
Static Public Attributes inherited from django.contrib.admin.options.RenameBaseModelAdminMethods
tuple renamed_methods
Static Public Attributes inherited from django.utils.deprecation.RenameMethodsBase
tuple renamed_methods = ()
Additional Inherited Members
Public Attributes inherited from django.contrib.admin.options.ModelAdmin
model
opts
admin_site
Public Attributes inherited from django.contrib.admin.options.BaseModelAdmin
formfield_overrides
Properties inherited from django.contrib.admin.options.ModelAdmin
urls = property(urls)
Properties inherited from django.contrib.admin.options.BaseModelAdmin
declared_fieldsets = property(_declared_fieldsets)
Detailed Description
Definition at line 20 of file admin.py.
Member Function Documentation
def django.contrib.comments.admin.CommentsAdmin.approve_comments (self, request, queryset)
Definition at line 59 of file admin.py.
References django.contrib.comments.admin.CommentsAdmin._bulk_flag(), and django.utils.translation.ungettext_lazy().
def django.contrib.comments.admin.CommentsAdmin.flag_comments (self, request, queryset)
Definition at line 53 of file admin.py.
References django.contrib.comments.admin.CommentsAdmin._bulk_flag(), and django.utils.translation.ungettext_lazy().
def django.contrib.comments.admin.CommentsAdmin.get_actions (self, request)
Definition at line 41 of file admin.py.
def django.contrib.comments.admin.CommentsAdmin.remove_comments (self, request, queryset)
Definition at line 65 of file admin.py.
References django.contrib.comments.admin.CommentsAdmin._bulk_flag(), django.contrib.comments.get_model(), django.contrib.admin.options.ModelAdmin.message_user(), and django.utils.translation.ungettext_lazy().
Member Data Documentation
list django.contrib.comments.admin.CommentsAdmin.actions = ["flag_comments", "approve_comments", "remove_comments"] static
Definition at line 39 of file admin.py.
string django.contrib.comments.admin.CommentsAdmin.date_hierarchy = 'submit_date' static
Definition at line 35 of file admin.py.
Referenced by django.contrib.admin.options.BaseModelAdmin.lookup_allowed().
tuple django.contrib.comments.admin.CommentsAdmin.fieldsets static
Initial value:
 = (
         (None,
            {'fields': ('content_type', 'object_pk', 'site')}
         ),
         (_('Content'),
            {'fields': ('user', 'user_name', 'user_email', 'user_url', 'comment')}
         ),
         (_('Metadata'),
            {'fields': ('submit_date', 'ip_address', 'is_public', 'is_removed')}
         ),
      )
Definition at line 21 of file admin.py.
tuple django.contrib.comments.admin.CommentsAdmin.list_display = ('name', 'content_type', 'object_pk', 'ip_address', 'submit_date', 'is_public', 'is_removed') static
Definition at line 33 of file admin.py.
tuple django.contrib.comments.admin.CommentsAdmin.list_filter = ('submit_date', 'site', 'is_public', 'is_removed') static
Definition at line 34 of file admin.py.
Referenced by django.contrib.admin.options.BaseModelAdmin.lookup_allowed().
tuple django.contrib.comments.admin.CommentsAdmin.ordering = ('-submit_date',) static
Definition at line 36 of file admin.py.
Referenced by django.db.models.options.Options.module_name().
tuple django.contrib.comments.admin.CommentsAdmin.raw_id_fields = ('user',) static
Definition at line 37 of file admin.py.
tuple django.contrib.comments.admin.CommentsAdmin.search_fields = ('comment', UsernameSearch(), 'user_name', 'user_email', 'user_url', 'ip_address') static
Definition at line 38 of file admin.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/comments/admin.py