Django: django.contrib.gis.tests.geoadmin.tests.GeoAdminTest Class Reference
django.contrib.gis.tests.geoadmin.tests.GeoAdminTest Class Reference
Public Member Functions
def test_ensure_geographic_media (self)
def test_olmap_OSM_rendering (self)
def test_olmap_WMS_rendering (self)
def test_olwidget_has_changed (self)
def test_google_map_scripts (self)
Static Public Attributes
string urls = 'django.contrib.gis.tests.geoadmin.urls'
Detailed Description
Definition at line 19 of file tests.py.
Member Function Documentation
def django.contrib.gis.tests.geoadmin.tests.GeoAdminTest.test_ensure_geographic_media (self)
Definition at line 22 of file tests.py.
References django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.gis.tests.geoadmin.tests.GeoAdminTest.test_google_map_scripts (self)
Testing GoogleMap.scripts() output. See #20773.
Definition at line 64 of file tests.py.
References django.utils.unittest.case.TestCase.assertIn().
def django.contrib.gis.tests.geoadmin.tests.GeoAdminTest.test_olmap_OSM_rendering (self)
Definition at line 27 of file tests.py.
References django.utils.unittest.case.TestCase.assertIn(), and django.shortcuts.render().
def django.contrib.gis.tests.geoadmin.tests.GeoAdminTest.test_olmap_WMS_rendering (self)
Definition at line 35 of file tests.py.
References django.utils.unittest.case.TestCase.assertIn(), and django.shortcuts.render().
def django.contrib.gis.tests.geoadmin.tests.GeoAdminTest.test_olwidget_has_changed (self)
Check that changes are accurately noticed by OpenLayersWidget.
Definition at line 43 of file tests.py.
References django.utils.unittest.case.TestCase.assertFalse(), and django.utils.unittest.case.TestCase.assertTrue().
Member Data Documentation
string django.contrib.gis.tests.geoadmin.tests.GeoAdminTest.urls = 'django.contrib.gis.tests.geoadmin.urls' static
Definition at line 20 of file tests.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/tests/geoadmin/tests.py