Django: django.db.models.fields.BinaryField Class Reference
django.db.models.fields.BinaryField Class Reference
Public Member Functions
def __init__ (self, args, kwargs)
def get_internal_type (self)
def get_default (self)
def get_db_prep_value
def value_to_string (self, obj)
def to_python (self, value)
Public Member Functions inherited from django.db.models.fields.Field
def __init__
def __eq__ (self, other)
def __lt__ (self, other)
def __hash__ (self)
def __deepcopy__ (self, memodict)
def __copy__ (self)
def __reduce__ (self)
def to_python (self, value)
def run_validators (self, value)
def validate (self, value, model_instance)
def clean (self, value, model_instance)
def db_type (self, connection)
def unique (self)
def set_attributes_from_name (self, name)
def contribute_to_class
def get_attname (self)
def get_attname_column (self)
def get_cache_name (self)
def get_internal_type (self)
def pre_save (self, model_instance, add)
def get_prep_value (self, value)
def get_db_prep_value
def get_db_prep_save (self, value, connection)
def get_prep_lookup (self, lookup_type, value)
def get_db_prep_lookup
def has_default (self)
def get_default (self)
def get_validator_unique_lookup_type (self)
def get_choices
def get_choices_default (self)
def get_flatchoices
def value_to_string (self, obj)
def bind (self, fieldmapping, original, bound_field_class)
def save_form_data (self, instance, data)
def formfield (self, form_class=None, choices_form_class=None, kwargs)
def value_from_object (self, obj)
def __repr__ (self)
Static Public Attributes
tuple description = _("Raw binary data")
list empty_values = [None, b'']
Static Public Attributes inherited from django.db.models.fields.Field
empty_strings_allowed = True
tuple empty_values = list(validators.EMPTY_VALUES)
int creation_counter = 0
int auto_creation_counter = -1
list default_validators = []
dictionary default_error_messages
Additional Inherited Members
Public Attributes inherited from django.db.models.fields.Field
name
verbose_name
primary_key
null
rel
default
editable
serialize
unique_for_month
unique_for_year
help_text
db_column
db_tablespace
auto_created
db_index
creation_counter
validators
error_messages
column
model
Properties inherited from django.db.models.fields.Field
description = property(_description)
choices = property(_get_choices)
flatchoices = property(_get_flatchoices)
Detailed Description
Definition at line 1402 of file __init__.py.
Constructor & Destructor Documentation
def django.db.models.fields.BinaryField.__init__ (self, args, kwargs)
Definition at line 1406 of file __init__.py.
References django.forms.fields.FileField.max_length.
Member Function Documentation
def django.db.models.fields.BinaryField.get_db_prep_value (self, value, connection, prepared = False)
Definition at line 1423 of file __init__.py.
def django.db.models.fields.BinaryField.get_default (self)
Definition at line 1415 of file __init__.py.
References django.utils.six.callable, django.db.models.fields.Field.default, and django.db.models.fields.Field.has_default().
def django.db.models.fields.BinaryField.get_internal_type (self)
Definition at line 1412 of file __init__.py.
def django.db.models.fields.BinaryField.to_python (self, value)
Definition at line 1434 of file __init__.py.
References django.utils.encoding.force_bytes().
Referenced by django.forms.fields.Field.clean(), django.forms.fields.EmailField.clean(), django.forms.fields.URLField.clean(), django.forms.fields.SlugField.clean(), and django.forms.fields.Field.widget_attrs().
def django.db.models.fields.BinaryField.value_to_string (self, obj)
Binary data is serialized as base64
Definition at line 1430 of file __init__.py.
References django.db.models.fields.Field._get_val_from_obj(), and django.utils.encoding.force_bytes().
Member Data Documentation
tuple django.db.models.fields.BinaryField.description = _("Raw binary data") static
Definition at line 1403 of file __init__.py.
Referenced by django.utils.unittest.suite._ErrorHolder.__repr__(), and django.utils.unittest.suite._ErrorHolder.id().
list django.db.models.fields.BinaryField.empty_values = [None, b''] static
Definition at line 1404 of file __init__.py.
Referenced by django.forms.models.InlineForeignKeyField.clean(), django.forms.fields.SplitDateTimeField.compress(), django.forms.fields.Field.run_validators(), django.contrib.gis.forms.fields.GeometryField.to_python(), django.forms.fields.CharField.to_python(), django.forms.fields.IntegerField.to_python(), django.forms.fields.FloatField.to_python(), django.forms.fields.DecimalField.to_python(), django.forms.fields.DateField.to_python(), django.forms.fields.TimeField.to_python(), django.forms.fields.DateTimeField.to_python(), django.forms.fields.FileField.to_python(), django.forms.fields.ChoiceField.to_python(), django.forms.fields.TypedChoiceField.to_python(), django.forms.fields.TypedMultipleChoiceField.to_python(), django.forms.fields.IPAddressField.to_python(), django.forms.fields.GenericIPAddressField.to_python(), django.forms.models.ModelChoiceField.to_python(), django.forms.fields.Field.validate(), and django.forms.fields.DecimalField.validate().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/db/models/fields/__init__.py