Django: django.contrib.contenttypes.generic Namespace Reference
django.contrib.contenttypes.generic Namespace Reference
Classes
class BaseGenericInlineFormSet
class GenericForeignKey
class GenericInlineModelAdmin
class GenericRel
class GenericRelation
class GenericStackedInline
class GenericTabularInline
class RenameGenericForeignKeyMethods
class ReverseGenericRelatedObjectsDescriptor
Functions
def create_generic_related_manager (superclass)
def generic_inlineformset_factory
Variables
model
content_type
symmetrical
instance
source_col_name
target_col_name
content_type_field_name
object_id_field_name
prefetch_cache_name
pk_val
core_filters
Detailed Description
Classes allowing "generic" relations through ContentType and object-id fields.
Function Documentation
def django.contrib.contenttypes.generic.create_generic_related_manager (superclass)
Factory function for a manager that subclasses 'superclass' (which is a
Manager) and adds behavior for generic related objects.
Definition at line 295 of file generic.py.
Referenced by django.contrib.contenttypes.generic.ReverseGenericRelatedObjectsDescriptor.__get__().
def django.contrib.contenttypes.generic.generic_inlineformset_factory (model, form = ModelForm, formset = BaseGenericInlineFormSet, ct_field = "content_type", fk_field = "object_id", fields = None, exclude = None, extra = 3, can_order = False, can_delete = True, max_num = None, formfield_callback = None, validate_max = False, for_concrete_model = True)
Returns a ``GenericInlineFormSet`` for the given kwargs.
You must provide ``ct_field`` and ``fk_field`` if they are different from
the defaults ``content_type`` and ``object_id`` respectively.
Definition at line 434 of file generic.py.
References django.forms.models.modelformset_factory().
Referenced by django.contrib.contenttypes.generic.GenericInlineModelAdmin.get_formset(), and django.contrib.contenttypes.generic.BaseGenericInlineFormSet.save_new().
Variable Documentation
django.contrib.contenttypes.generic.content_type
Definition at line 309 of file generic.py.
django.contrib.contenttypes.generic.content_type_field_name
Definition at line 314 of file generic.py.
django.contrib.contenttypes.generic.core_filters
Definition at line 318 of file generic.py.
django.contrib.contenttypes.generic.instance
Definition at line 311 of file generic.py.
Referenced by django.contrib.gis.views.feed().
django.contrib.contenttypes.generic.model
Definition at line 308 of file generic.py.
django.contrib.contenttypes.generic.object_id_field_name
Definition at line 315 of file generic.py.
django.contrib.contenttypes.generic.pk_val
Definition at line 317 of file generic.py.
django.contrib.contenttypes.generic.prefetch_cache_name
Definition at line 316 of file generic.py.
django.contrib.contenttypes.generic.source_col_name
Definition at line 312 of file generic.py.
django.contrib.contenttypes.generic.symmetrical
Definition at line 310 of file generic.py.
django.contrib.contenttypes.generic.target_col_name
Definition at line 313 of file generic.py.