Django: django.forms.models Namespace Reference
django.forms.models Namespace Reference
Classes
class BaseInlineFormSet
class BaseModelForm
class BaseModelFormSet
class InlineForeignKeyField
class ModelChoiceField
class ModelChoiceIterator
class ModelForm
class ModelFormMetaclass
class ModelFormOptions
class ModelMultipleChoiceField
Functions
def construct_instance
def save_instance
def model_to_dict
def fields_for_model
def modelform_factory
def modelformset_factory
def inlineformset_factory
def modelform_defines_fields (form_class)
Variables
tuple __all__
string ALL_FIELDS = '__all__'
Detailed Description
Helper functions for creating Form classes from Django models
and database field objects.
Function Documentation
def django.forms.models.construct_instance (form, instance, fields = None, exclude = None)
Constructs and returns a model instance from the bound ``form``'s
``cleaned_data``, but does not save the returned instance to the
database.
Definition at line 33 of file models.py.
References django.forms.models.save_instance().
Referenced by django.forms.models.BaseModelForm.clean(), and django.forms.models.save_instance().
def django.forms.models.fields_for_model (model, fields = None, exclude = None, widgets = None, formfield_callback = None, localized_fields = None, labels = None, help_texts = None, error_messages = None)
Returns a ``SortedDict`` containing form fields for the given model.
``fields`` is an optional list of field names. If provided, only the named
fields will be included in the returned fields.
``exclude`` is an optional list of field names. If provided, the named
fields will be excluded from the returned fields, even if they are listed
in the ``fields`` argument.
``widgets`` is a dictionary of model field names mapped to a widget.
``localized_fields`` is a list of names of fields which should be localized.
``labels`` is a dictionary of model field names mapped to a label.
``help_texts`` is a dictionary of model field names mapped to a help text.
``error_messages`` is a dictionary of model field names mapped to a
dictionary of error messages.
``formfield_callback`` is a callable that takes a model field and returns
a form field.
Definition at line 148 of file models.py.
References django.utils.six.callable.
Referenced by django.forms.models.ModelFormMetaclass.__new__(), and django.forms.models.model_to_dict().
def django.forms.models.inlineformset_factory (parent_model, model, form = ModelForm, formset = BaseInlineFormSet, fk_name = None, fields = None, exclude = None, extra = 3, can_order = False, can_delete = True, max_num = None, formfield_callback = None, widgets = None, validate_max = False, localized_fields = None, labels = None, help_texts = None, error_messages = None)
Returns an ``InlineFormSet`` for the given kwargs.
You must provide ``fk_name`` if ``model`` has more than one ``ForeignKey``
to ``parent_model``.
Definition at line 957 of file models.py.
References django.forms.models.modelformset_factory().
Referenced by django.contrib.admin.options.InlineModelAdmin.get_formset(), and django.forms.models.BaseInlineFormSet.get_unique_error_message().
def django.forms.models.model_to_dict (instance, fields = None, exclude = None)
Returns a dict containing the data in ``instance`` suitable for passing as
a Form's ``initial`` keyword argument.
``fields`` is an optional list of field names. If provided, only the named
fields will be included in the returned dict.
``exclude`` is an optional list of field names. If provided, the named
fields will be excluded from the returned dict, even if they are listed in
the ``fields`` argument.
Definition at line 110 of file models.py.
References django.forms.models.fields_for_model().
def django.forms.models.modelform_defines_fields (form_class)
Definition at line 1248 of file models.py.
Referenced by django.contrib.admin.options.ModelAdmin.get_changelist_form(), django.contrib.admin.options.ModelAdmin.get_form(), django.contrib.contenttypes.generic.GenericInlineModelAdmin.get_formset(), and django.contrib.admin.options.InlineModelAdmin.get_formset().
def django.forms.models.modelform_factory (model, form = ModelForm, fields = None, exclude = None, formfield_callback = None, widgets = None, localized_fields = None, labels = None, help_texts = None, error_messages = None)
Returns a ModelForm containing form fields for the given model.
``fields`` is an optional list of field names. If provided, only the named
fields will be included in the returned fields. If omitted or '__all__',
all fields will be used.
``exclude`` is an optional list of field names. If provided, the named
fields will be excluded from the returned fields, even if they are listed
in the ``fields`` argument.
``widgets`` is a dictionary of model field names mapped to a widget.
``localized_fields`` is a list of names of fields which should be localized.
``formfield_callback`` is a callable that takes a model field and returns
a form field.
``labels`` is a dictionary of model field names mapped to a label.
``help_texts`` is a dictionary of model field names mapped to a help text.
``error_messages`` is a dictionary of model field names mapped to a
dictionary of error messages.
Definition at line 455 of file models.py.
Referenced by django.contrib.admin.options.ModelAdmin.get_changelist_form(), django.contrib.admin.options.ModelAdmin.get_form(), and django.forms.models.modelformset_factory().
def django.forms.models.modelformset_factory (model, form = ModelForm, formfield_callback = None, formset = BaseModelFormSet, extra = 1, can_delete = False, can_order = False, max_num = None, fields = None, exclude = None, widgets = None, validate_max = False, localized_fields = None, labels = None, help_texts = None, error_messages = None)
Returns a FormSet class for the given Django model class.
Definition at line 791 of file models.py.
References django.forms.formsets.formset_factory(), and django.forms.models.modelform_factory().
Referenced by django.forms.models.BaseModelFormSet.add_fields(), django.contrib.contenttypes.generic.generic_inlineformset_factory(), django.contrib.admin.options.ModelAdmin.get_changelist_formset(), and django.forms.models.inlineformset_factory().
def django.forms.models.save_instance (form, instance, fields = None, fail_message = 'saved', commit = True, exclude = None, construct = True)
Saves bound Form ``form``'s cleaned_data into model instance ``instance``.
If commit=True, then the changes to ``instance`` will be saved to the
database. Returns ``instance``.
If construct=False, assume ``instance`` has already been constructed and
just needs to be saved.
Definition at line 65 of file models.py.
References django.forms.models.construct_instance().
Referenced by django.forms.models.construct_instance(), django.forms.models.BaseModelForm.save(), and django.contrib.contenttypes.generic.BaseGenericInlineFormSet.save_new().
Variable Documentation
tuple django.forms.models.__all__
Initial value:
 = (
     'ModelForm', 'BaseModelForm', 'model_to_dict', 'fields_for_model',
     'save_instance', 'ModelChoiceField', 'ModelMultipleChoiceField',
     'ALL_FIELDS',
 )
Definition at line 24 of file models.py.
string django.forms.models.ALL_FIELDS = '__all__'
Definition at line 30 of file models.py.