Django: django.contrib.gis.geos.prototypes.coordseq Namespace Reference
django.contrib.gis.geos.prototypes.coordseq Namespace Reference
Functions
def check_cs_ptr (result, func, cargs)
Error-checking routines specific to coordinate sequences.
def check_cs_op (result, func, cargs)
def check_cs_get (result, func, cargs)
def cs_int (func)
Coordinate sequence prototype generation functions.
def cs_operation
def cs_output (func, argtypes)
Variables
tuple cs_clone = cs_output(GEOSFunc('GEOSCoordSeq_clone'), [CS_PTR])
Coordinate Sequence ctypes prototypes ##.
tuple create_cs = cs_output(GEOSFunc('GEOSCoordSeq_create'), [c_uint, c_uint])
tuple get_cs = cs_output(GEOSFunc('GEOSGeom_getCoordSeq'), [GEOM_PTR])
tuple cs_getordinate = cs_operation(GEOSFunc('GEOSCoordSeq_getOrdinate'), ordinate=True, get=True)
tuple cs_setordinate = cs_operation(GEOSFunc('GEOSCoordSeq_setOrdinate'), ordinate=True)
tuple cs_getx = cs_operation(GEOSFunc('GEOSCoordSeq_getX'), get=True)
tuple cs_gety = cs_operation(GEOSFunc('GEOSCoordSeq_getY'), get=True)
tuple cs_getz = cs_operation(GEOSFunc('GEOSCoordSeq_getZ'), get=True)
tuple cs_setx = cs_operation(GEOSFunc('GEOSCoordSeq_setX'))
tuple cs_sety = cs_operation(GEOSFunc('GEOSCoordSeq_setY'))
tuple cs_setz = cs_operation(GEOSFunc('GEOSCoordSeq_setZ'))
tuple cs_getsize = cs_int(GEOSFunc('GEOSCoordSeq_getSize'))
tuple cs_getdims = cs_int(GEOSFunc('GEOSCoordSeq_getDimensions'))
Function Documentation
def django.contrib.gis.geos.prototypes.coordseq.check_cs_get (result, func, cargs)
Definition at line 20 of file coordseq.py.
References django.contrib.gis.geos.prototypes.coordseq.check_cs_op(), and django.contrib.gis.geos.prototypes.errcheck.last_arg_byref().
def django.contrib.gis.geos.prototypes.coordseq.check_cs_op (result, func, cargs)
Definition at line 13 of file coordseq.py.
Referenced by django.contrib.gis.geos.prototypes.coordseq.check_cs_get().
def django.contrib.gis.geos.prototypes.coordseq.check_cs_ptr (result, func, cargs)
Error-checking routines specific to coordinate sequences.
Definition at line 7 of file coordseq.py.
def django.contrib.gis.geos.prototypes.coordseq.cs_int (func)
Coordinate sequence prototype generation functions.
Definition at line 27 of file coordseq.py.
def django.contrib.gis.geos.prototypes.coordseq.cs_operation (func, ordinate = False, get = False)
Definition at line 34 of file coordseq.py.
def django.contrib.gis.geos.prototypes.coordseq.cs_output (func, argtypes)
Definition at line 53 of file coordseq.py.
Variable Documentation
tuple django.contrib.gis.geos.prototypes.coordseq.create_cs = cs_output(GEOSFunc('GEOSCoordSeq_create'), [c_uint, c_uint])
Definition at line 64 of file coordseq.py.
tuple django.contrib.gis.geos.prototypes.coordseq.cs_clone = cs_output(GEOSFunc('GEOSCoordSeq_clone'), [CS_PTR])
Coordinate Sequence ctypes prototypes ##.
Definition at line 63 of file coordseq.py.
tuple django.contrib.gis.geos.prototypes.coordseq.cs_getdims = cs_int(GEOSFunc('GEOSCoordSeq_getDimensions'))
Definition at line 83 of file coordseq.py.
tuple django.contrib.gis.geos.prototypes.coordseq.cs_getordinate = cs_operation(GEOSFunc('GEOSCoordSeq_getOrdinate'), ordinate=True, get=True)
Definition at line 68 of file coordseq.py.
tuple django.contrib.gis.geos.prototypes.coordseq.cs_getsize = cs_int(GEOSFunc('GEOSCoordSeq_getSize'))
Definition at line 82 of file coordseq.py.
tuple django.contrib.gis.geos.prototypes.coordseq.cs_getx = cs_operation(GEOSFunc('GEOSCoordSeq_getX'), get=True)
Definition at line 72 of file coordseq.py.
tuple django.contrib.gis.geos.prototypes.coordseq.cs_gety = cs_operation(GEOSFunc('GEOSCoordSeq_getY'), get=True)
Definition at line 73 of file coordseq.py.
tuple django.contrib.gis.geos.prototypes.coordseq.cs_getz = cs_operation(GEOSFunc('GEOSCoordSeq_getZ'), get=True)
Definition at line 74 of file coordseq.py.
tuple django.contrib.gis.geos.prototypes.coordseq.cs_setordinate = cs_operation(GEOSFunc('GEOSCoordSeq_setOrdinate'), ordinate=True)
Definition at line 69 of file coordseq.py.
tuple django.contrib.gis.geos.prototypes.coordseq.cs_setx = cs_operation(GEOSFunc('GEOSCoordSeq_setX'))
Definition at line 77 of file coordseq.py.
tuple django.contrib.gis.geos.prototypes.coordseq.cs_sety = cs_operation(GEOSFunc('GEOSCoordSeq_setY'))
Definition at line 78 of file coordseq.py.
tuple django.contrib.gis.geos.prototypes.coordseq.cs_setz = cs_operation(GEOSFunc('GEOSCoordSeq_setZ'))
Definition at line 79 of file coordseq.py.
tuple django.contrib.gis.geos.prototypes.coordseq.get_cs = cs_output(GEOSFunc('GEOSGeom_getCoordSeq'), [GEOM_PTR])
Definition at line 65 of file coordseq.py.