Django: django.utils.functional Namespace Reference
django.utils.functional Namespace Reference
Classes
class cached_property
class lazy_property
class LazyObject
class Promise
class SimpleLazyObject
Functions
def curry (_curried_func, args, kwargs)
def memoize (func, cache, num_args)
def lazy (func, resultclasses)
def allow_lazy (func, resultclasses)
def new_method_proxy (func)
def partition (predicate, values)
def total_ordering (cls)
Variables
tuple empty = object()
_super = super
__args
__kw
Function Documentation
def django.utils.functional.allow_lazy (func, resultclasses)
A decorator that allows a function to be called with one or more lazy
arguments. If none of the args are lazy, the function is evaluated
immediately, otherwise a __proxy__ is returned that will evaluate the
function when needed.
Definition at line 190 of file functional.py.
References django.utils.functional.lazy(), and django.utils.six.wraps.
def django.utils.functional.curry (_curried_func, args, kwargs)
Definition at line 13 of file functional.py.
Referenced by django.db.models.base.ModelBase.add_to_class(), django.db.models.fields.DateField.contribute_to_class(), and django.test.client.Client.request().
def django.utils.functional.lazy (func, resultclasses)
Turns any callable into a lazy evaluated callable. You need to give result
classes or types -- at least one is needed so that the automatic forcing of
the lazy evaluation code is triggered. Results are not memoized; the
function is evaluated on every access.
Definition at line 62 of file functional.py.
Referenced by django.utils.functional.allow_lazy(), django.core.context_processors.csrf(), and django.utils.translation.lazy_number().
def django.utils.functional.memoize (func, cache, num_args)
Wrap a function so that results for any argument tuple are stored in
'cache'. Note that the args to the function must be usable as dictionary
keys.
Only the first num_args are considered when creating the key.
Definition at line 19 of file functional.py.
References django.utils.six.wraps.
def django.utils.functional.new_method_proxy (func)
Definition at line 210 of file functional.py.
Referenced by django.utils.functional.LazyObject.__delattr__(), django.utils.functional.LazyObject.__init__(), django.utils.functional.SimpleLazyObject.__init__(), and django.utils.functional.SimpleLazyObject.__repr__().
def django.utils.functional.partition (predicate, values)
Splits the values into two sets, based on the return value of the function
(True/False). e.g.:
    >>> partition(lambda x: x > 3, range(5))
    [0, 1, 2, 3], [4]
Definition at line 385 of file functional.py.
Referenced by django.db.models.query.QuerySet.bulk_create().
def django.utils.functional.total_ordering (cls)
Class decorator that fills in missing ordering methods
Definition at line 405 of file functional.py.
Variable Documentation
django.utils.functional.__args
Definition at line 80 of file functional.py.
django.utils.functional.__kw
Definition at line 81 of file functional.py.
django.utils.functional._super = super
Definition at line 275 of file functional.py.
Referenced by django.utils.functional.SimpleLazyObject.__init__().
tuple django.utils.functional.empty = object()
Definition at line 207 of file functional.py.
Referenced by yt().