Django: django.contrib.admindocs.tests.test_fields.TestFieldType Class Reference
django.contrib.admindocs.tests.test_fields.TestFieldType Class Reference
Public Member Functions
def setUp (self)
def test_field_name (self)
def test_builtin_fields (self)
def test_custom_fields (self)
Detailed Description
Definition at line 17 of file test_fields.py.
Member Function Documentation
def django.contrib.admindocs.tests.test_fields.TestFieldType.setUp (self)
Definition at line 18 of file test_fields.py.
Referenced by django.utils.unittest.case.TestCase.debug(), django.test._doctest.DocTestCase.debug(), and django.utils.unittest.case.TestCase.run().
def django.contrib.admindocs.tests.test_fields.TestFieldType.test_builtin_fields (self)
Definition at line 26 of file test_fields.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.admindocs.tests.test_fields.TestFieldType.test_custom_fields (self)
Definition at line 32 of file test_fields.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.admindocs.tests.test_fields.TestFieldType.test_field_name (self)
Definition at line 21 of file test_fields.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/admindocs/tests/test_fields.py