Django: django.forms.widgets Namespace Reference
django.forms.widgets Namespace Reference
Classes
class CheckboxChoiceInput
class CheckboxFieldRenderer
class CheckboxInput
class CheckboxSelectMultiple
class ChoiceFieldRenderer
class ChoiceInput
class ClearableFileInput
class DateInput
class DateTimeInput
class EmailInput
class FileInput
class HiddenInput
class Input
class Media
class MediaDefiningClass
class MultipleHiddenInput
class MultiWidget
class NullBooleanSelect
class NumberInput
class PasswordInput
class RadioChoiceInput
class RadioFieldRenderer
class RadioInput
class RadioSelect
class RendererMixin
class Select
class SelectMultiple
class SplitDateTimeWidget
class SplitHiddenDateTimeWidget
class SubWidget
class Textarea
class TextInput
class TimeInput
class URLInput
class Widget
Functions
def media_property (cls)
def boolean_check (v)
Variables
tuple __all__
tuple MEDIA_TYPES = ('css','js')
tuple FILE_INPUT_CONTRADICTION = object()
Detailed Description
HTML Widget classes
Function Documentation
def django.forms.widgets.boolean_check (v)
Definition at line 457 of file widgets.py.
def django.forms.widgets.media_property (cls)
Definition at line 106 of file widgets.py.
Referenced by django.forms.forms.DeclarativeFieldsMetaclass.__new__(), django.forms.widgets.MediaDefiningClass.__new__(), and django.forms.models.ModelFormMetaclass.__new__().
Variable Documentation
tuple django.forms.widgets.__all__
Initial value:
 = (
     'Media', 'MediaDefiningClass', 'Widget', 'TextInput',
     'EmailInput', 'URLInput', 'NumberInput', 'PasswordInput',
     'HiddenInput', 'MultipleHiddenInput', 'ClearableFileInput',
     'FileInput', 'DateInput', 'DateTimeInput', 'TimeInput', 'Textarea', 'CheckboxInput',
     'Select', 'NullBooleanSelect', 'SelectMultiple', 'RadioSelect',
     'CheckboxSelectMultiple', 'MultiWidget',
     'SplitDateTimeWidget',
 )
Definition at line 21 of file widgets.py.
tuple django.forms.widgets.FILE_INPUT_CONTRADICTION = object()
Definition at line 320 of file widgets.py.
tuple django.forms.widgets.MEDIA_TYPES = ('css','js')
Definition at line 31 of file widgets.py.