Django: django.contrib.gis.feeds.GeoRSSFeed Class Reference
django.contrib.gis.feeds.GeoRSSFeed Class Reference
Public Member Functions
def rss_attributes (self)
def add_item_elements (self, handler, item)
def add_root_elements (self, handler)
Public Member Functions inherited from django.utils.feedgenerator.Rss201rev2Feed
def add_item_elements (self, handler, item)
Public Member Functions inherited from django.utils.feedgenerator.RssFeed
def write (self, outfile, encoding)
def rss_attributes (self)
def write_items (self, handler)
def add_root_elements (self, handler)
def endChannelElement (self, handler)
Public Member Functions inherited from django.utils.feedgenerator.SyndicationFeed
def __init__ (self, title, link, description, language=None, author_email=None, author_name=None, author_link=None, subtitle=None, categories=None, feed_url=None, feed_copyright=None, feed_guid=None, ttl=None, kwargs)
def add_item (self, title, link, description, author_email=None, author_name=None, author_link=None, pubdate=None, comments=None, unique_id=None, unique_id_is_permalink=None, enclosure=None, categories=(), item_copyright=None, ttl=None, kwargs)
def num_items (self)
def root_attributes (self)
def add_root_elements (self, handler)
def item_attributes (self, item)
def add_item_elements (self, handler, item)
def write (self, outfile, encoding)
def writeString (self, encoding)
def latest_post_date (self)
Public Member Functions inherited from django.contrib.gis.feeds.GeoFeedMixin
def georss_coords (self, coords)
def add_georss_point
def add_georss_element
Additional Inherited Members
Public Attributes inherited from django.utils.feedgenerator.SyndicationFeed
feed
items
Static Public Attributes inherited from django.utils.feedgenerator.RssFeed
string mime_type = 'application/rss+xml; charset=utf-8'
Detailed Description
Definition at line 81 of file feeds.py.
Member Function Documentation
def django.contrib.gis.feeds.GeoRSSFeed.add_item_elements (self, handler, item)
Definition at line 87 of file feeds.py.
References django.contrib.gis.feeds.GeoFeedMixin.add_georss_element().
Referenced by django.utils.feedgenerator.RssFeed.write_items(), and django.utils.feedgenerator.Atom1Feed.write_items().
def django.contrib.gis.feeds.GeoRSSFeed.add_root_elements (self, handler)
Definition at line 91 of file feeds.py.
References django.contrib.gis.feeds.GeoFeedMixin.add_georss_element(), and django.utils.feedgenerator.SyndicationFeed.feed.
Referenced by django.utils.feedgenerator.RssFeed.write(), and django.utils.feedgenerator.Atom1Feed.write().
def django.contrib.gis.feeds.GeoRSSFeed.rss_attributes (self)
Definition at line 82 of file feeds.py.
Referenced by django.utils.feedgenerator.RssFeed.write().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/feeds.py