Django: django.contrib.admin.util.NestedObjects Class Reference
django.contrib.admin.util.NestedObjects Class Reference
Public Member Functions
def __init__ (self, args, kwargs)
def add_edge (self, source, target)
def collect (self, objs, source_attr=None, kwargs)
def related_objects (self, related, objs)
def nested
def can_fast_delete (self, args, kwargs)
Public Member Functions inherited from django.db.models.deletion.Collector
def __init__ (self, using)
def add
def add_field_update (self, field, value, objs)
def can_fast_delete
def collect
def related_objects (self, related, objs)
def instances_with_model (self)
def sort (self)
def delete (self)
Public Attributes
edges
protected
Public Attributes inherited from django.db.models.deletion.Collector
using
data
field_updates
fast_deletes
dependencies
Detailed Description
Definition at line 144 of file util.py.
Constructor & Destructor Documentation
def django.contrib.admin.util.NestedObjects.__init__ (self, args, kwargs)
Definition at line 145 of file util.py.
Member Function Documentation
def django.contrib.admin.util.NestedObjects.add_edge (self, source, target)
Definition at line 150 of file util.py.
Referenced by django.contrib.admin.util.NestedObjects.collect().
def django.contrib.admin.util.NestedObjects.can_fast_delete (self, args, kwargs)
We always want to load the objects into memory so that we can display
them to the user in confirm page.
Definition at line 194 of file util.py.
Referenced by django.db.models.deletion.Collector.collect().
def django.contrib.admin.util.NestedObjects.collect (self, objs, source_attr = None, kwargs)
Definition at line 153 of file util.py.
References django.contrib.admin.util.NestedObjects.add_edge().
Referenced by django.db.models.deletion.Collector.collect(), and django.contrib.staticfiles.management.commands.collectstatic.Command.handle_noargs().
def django.contrib.admin.util.NestedObjects.nested (self, format_callback = None)
Return the graph as a nested list.
Definition at line 183 of file util.py.
References django.contrib.admin.util.NestedObjects._nested().
def django.contrib.admin.util.NestedObjects.related_objects (self, related, objs)
Definition at line 164 of file util.py.
References django.contrib.admin.util.NestedObjects._nested().
Referenced by django.db.models.deletion.Collector.collect().
Member Data Documentation
django.contrib.admin.util.NestedObjects.edges
Definition at line 147 of file util.py.
django.contrib.admin.util.NestedObjects.protected
Definition at line 148 of file util.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/admin/util.py