Django: django.test.testcases Namespace Reference
django.test.testcases Namespace Reference
Classes
class _AssertNumQueriesContext
class _AssertTemplateNotUsedContext
class _AssertTemplateUsedContext
class _ImprovedEvent
class _MediaFilesHandler
class LiveServerTestCase
class LiveServerThread
class QuietWSGIRequestHandler
class SimpleTestCase
class StoppableWSGIServer
class TestCase
class TransactionTestCase
Functions
def to_list (value)
def nop (args, kwargs)
def disable_transaction_methods ()
def restore_transaction_methods ()
def assert_and_parse_html (self, html, user_msg, msg)
def connections_support_transactions ()
def skipIfDBFeature (feature)
def skipUnlessDBFeature (feature)
Variables
tuple __all__
real_commit = transaction.commit
real_rollback = transaction.rollback
real_enter_transaction_management = transaction.enter_transaction_management
real_leave_transaction_management = transaction.leave_transaction_management
real_abort = transaction.abort
_ImprovedEvent = threading.Event
Function Documentation
def django.test.testcases.assert_and_parse_html (self, html, user_msg, msg)
Definition at line 83 of file testcases.py.
References django.test.html.parse_html().
Referenced by django.test.testcases.SimpleTestCase.assertContains(), django.test.testcases.SimpleTestCase.assertHTMLEqual(), django.test.testcases.SimpleTestCase.assertHTMLNotEqual(), django.test.testcases.SimpleTestCase.assertInHTML(), and django.test.testcases.SimpleTestCase.assertNotContains().
def django.test.testcases.connections_support_transactions ()
Returns True if all connections support transactions.
Definition at line 843 of file testcases.py.
def django.test.testcases.disable_transaction_methods ()
Definition at line 68 of file testcases.py.
def django.test.testcases.nop (args, kwargs)
Definition at line 65 of file testcases.py.
def django.test.testcases.restore_transaction_methods ()
Definition at line 75 of file testcases.py.
def django.test.testcases.skipIfDBFeature (feature)
Skip a test if a database has the named feature
Definition at line 916 of file testcases.py.
def django.test.testcases.skipUnlessDBFeature (feature)
Skip a test unless a database has the named feature
Definition at line 924 of file testcases.py.
def django.test.testcases.to_list (value)
Puts value into a list if it's not already one.
Returns an empty list if value is None.
Definition at line 48 of file testcases.py.
Referenced by django.test.testcases.SimpleTestCase.assertFormError(), and django.test.testcases.SimpleTestCase.assertFormsetError().
Variable Documentation
tuple django.test.testcases.__all__
Initial value:
 = ('TestCase', 'TransactionTestCase',
            'SimpleTestCase', 'skipIfDBFeature', 'skipUnlessDBFeature')
Definition at line 44 of file testcases.py.
django.test.testcases._ImprovedEvent = threading.Event
Definition at line 944 of file testcases.py.
django.test.testcases.real_abort = transaction.abort
Definition at line 63 of file testcases.py.
django.test.testcases.real_commit = transaction.commit
Definition at line 59 of file testcases.py.
django.test.testcases.real_enter_transaction_management = transaction.enter_transaction_management
Definition at line 61 of file testcases.py.
django.test.testcases.real_leave_transaction_management = transaction.leave_transaction_management
Definition at line 62 of file testcases.py.
django.test.testcases.real_rollback = transaction.rollback
Definition at line 60 of file testcases.py.