Django: django.contrib.messages.tests.urls Namespace Reference
django.contrib.messages.tests.urls Namespace Reference
Classes
class ContactForm
class ContactFormViewWithMsg
Functions
def add (request, message_type)
def add_template_response (request, message_type)
def show (request)
def show_template_response (request)
Variables
string TEMPLATE
tuple urlpatterns
Function Documentation
def django.contrib.messages.tests.urls.add (request, message_type)
Definition at line 24 of file urls.py.
References django.db.models.fields.related.reverse.
Referenced by django.db.models.sql.query.add_to_dict(), buildParams(), django.db.models.sql.query.Query.deferred_to_columns_cb(), django.db.models.sql.query.Query.deferred_to_data(), profiling.gather_profile_stats.gather_stats(), django.contrib.gis.tests.inspectapp.tests.get_ogr_db_string(), django.contrib.contenttypes.generic.GenericForeignKey.get_prefetch_queryset(), django.test.runner.setup_databases(), and yt().
def django.contrib.messages.tests.urls.add_template_response (request, message_type)
Definition at line 39 of file urls.py.
References django.db.models.fields.related.reverse.
def django.contrib.messages.tests.urls.show (request)
Definition at line 47 of file urls.py.
Referenced by showHide().
def django.contrib.messages.tests.urls.show_template_response (request)
Definition at line 52 of file urls.py.
Variable Documentation
string django.contrib.messages.tests.urls.TEMPLATE
Initial value:
 = """{% if messages %}
 <ul class="messages">
     {% for message in messages %}
     <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
         {{ message }}
     </li>
     {% endfor %}
 </ul>
 {% endif %}
 """
Definition at line 12 of file urls.py.
tuple django.contrib.messages.tests.urls.urlpatterns
Initial value:
 = patterns('',
     ('^add/(debug|info|success|warning|error)/$', add),
     url('^add/msg/$', ContactFormViewWithMsg.as_view(), name='add_success_msg'),
     ('^show/$', show),
     ('^template_response/add/(debug|info|success|warning|error)/$', add_template_response),
     ('^template_response/show/$', show_template_response),
 )
Definition at line 67 of file urls.py.