Django: django.utils.timesince Namespace Reference
django.utils.timesince Namespace Reference
Functions
def timesince
def timeuntil
Function Documentation
def django.utils.timesince.timesince (d, now = None, reversed = False)
Takes two datetime objects and returns the time between d and now
as a nicely formatted string, e.g. "10 minutes".  If d occurs after now,
then "0 minutes" is returned.
Units used are years, months, weeks, days, hours, and minutes.
Seconds and microseconds are ignored.  Up to two adjacent units will be
displayed.  For example, "2 weeks, 3 days" and "1 year, 3 months" are
possible outputs, but "2 weeks, 3 hours" and "1 year, 5 days" are not.
Adapted from
http://web.archive.org/web/20060617175230/http://blog.natbat.co.uk/archive/2003/Jun/14/time_since
Definition at line 9 of file timesince.py.
References django.utils.timezone.is_aware(), django.utils.translation.trans_real.ugettext, and django.utils.translation.ungettext_lazy().
Referenced by django.template.defaultfilters.timesince_filter(), and django.utils.timesince.timeuntil().
def django.utils.timesince.timeuntil (d, now = None)
Like timesince, but returns a string measuring the time until
the given time.
Definition at line 59 of file timesince.py.
References django.utils.timesince.timesince().
Referenced by django.template.defaultfilters.timeuntil_filter().