Django: django.contrib.admin.validation.ModelAdminValidator Class Reference
django.contrib.admin.validation.ModelAdminValidator Class Reference
Public Member Functions
def validate_save_as (self, cls, model)
def validate_save_on_top (self, cls, model)
def validate_inlines (self, cls, model)
def check_inline (self, cls, parent_model)
def validate_list_display (self, cls, model)
def validate_list_display_links (self, cls, model)
def validate_list_filter (self, cls, model)
def validate_list_select_related (self, cls, model)
def validate_list_per_page (self, cls, model)
def validate_list_max_show_all (self, cls, model)
def validate_list_editable (self, cls, model)
def validate_search_fields (self, cls, model)
def validate_date_hierarchy (self, cls, model)
Public Member Functions inherited from django.contrib.admin.validation.BaseValidator
def __init__ (self)
def validate (self, cls, model)
def check_field_spec (self, cls, model, flds, label)
def validate_raw_id_fields (self, cls, model)
def validate_fields (self, cls, model)
def validate_fieldsets (self, cls, model)
def validate_exclude (self, cls, model)
def validate_form (self, cls, model)
def validate_filter_vertical (self, cls, model)
def validate_filter_horizontal (self, cls, model)
def validate_radio_fields (self, cls, model)
def validate_prepopulated_fields (self, cls, model)
def validate_ordering (self, cls, model)
def validate_readonly_fields (self, cls, model)
Detailed Description
Definition at line 203 of file validation.py.
Member Function Documentation
def django.contrib.admin.validation.ModelAdminValidator.check_inline (self, cls, parent_model)
Definition at line 230 of file validation.py.
Referenced by django.contrib.admin.validation.ModelAdminValidator.validate_inlines().
def django.contrib.admin.validation.ModelAdminValidator.validate_date_hierarchy (self, cls, model)
Definition at line 366 of file validation.py.
References django.contrib.admin.validation.get_field().
def django.contrib.admin.validation.ModelAdminValidator.validate_inlines (self, cls, model)
Definition at line 212 of file validation.py.
References django.contrib.admin.validation.ModelAdminValidator.check_inline(), and django.contrib.admin.validation.check_isseq().
def django.contrib.admin.validation.ModelAdminValidator.validate_list_display (self, cls, model)
Definition at line 239 of file validation.py.
References django.utils.six.callable, django.contrib.admin.validation.check_isseq(), and django.contrib.admin.validation.fetch_attr().
def django.contrib.admin.validation.ModelAdminValidator.validate_list_display_links (self, cls, model)
Definition at line 259 of file validation.py.
References django.contrib.admin.validation.check_isseq().
def django.contrib.admin.validation.ModelAdminValidator.validate_list_editable (self, cls, model)
Validate that list_editable is a sequence of editable fields from
list_display without first element.
Definition at line 329 of file validation.py.
References django.contrib.admin.validation.check_isseq().
def django.contrib.admin.validation.ModelAdminValidator.validate_list_filter (self, cls, model)
Validate that list_filter is a sequence of one of three options:
    1: 'field' - a basic field filter, possibly w/ relationships (eg, 'field__rel')
    2: ('field', SomeFieldListFilter) - a field-based list filter class
    3: SomeListFilter - a non-field list filter class
Definition at line 269 of file validation.py.
References django.utils.six.callable, django.contrib.admin.validation.check_isseq(), and django.contrib.admin.util.get_fields_from_path().
def django.contrib.admin.validation.ModelAdminValidator.validate_list_max_show_all (self, cls, model)
Definition at line 325 of file validation.py.
References django.contrib.admin.validation.check_type().
def django.contrib.admin.validation.ModelAdminValidator.validate_list_per_page (self, cls, model)
Definition at line 321 of file validation.py.
References django.contrib.admin.validation.check_type().
def django.contrib.admin.validation.ModelAdminValidator.validate_list_select_related (self, cls, model)
Definition at line 311 of file validation.py.
def django.contrib.admin.validation.ModelAdminValidator.validate_save_as (self, cls, model)
Definition at line 204 of file validation.py.
References django.contrib.admin.validation.check_type().
def django.contrib.admin.validation.ModelAdminValidator.validate_save_on_top (self, cls, model)
Definition at line 208 of file validation.py.
References django.contrib.admin.validation.check_type().
def django.contrib.admin.validation.ModelAdminValidator.validate_search_fields (self, cls, model)
Definition at line 361 of file validation.py.
References django.contrib.admin.validation.check_isseq().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/admin/validation.py