Django: django.forms.models.ModelFormMetaclass Class Reference
django.forms.models.ModelFormMetaclass Class Reference
Public Member Functions
def __new__ (cls, name, bases, attrs)
Detailed Description
Definition at line 231 of file models.py.
Member Function Documentation
def django.forms.models.ModelFormMetaclass.__new__ (cls, name, bases, attrs)
Definition at line 232 of file models.py.
References django.forms.models.fields_for_model(), django.forms.forms.get_declared_fields(), django.template.defaultfilters.join(), and django.forms.widgets.media_property().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/forms/models.py