Django: django.contrib.auth.management Namespace Reference
django.contrib.auth.management Namespace Reference
Namespaces
commands
Functions
def create_permissions (app, created_models, verbosity, db=DEFAULT_DB_ALIAS, kwargs)
def create_superuser (app, created_models, verbosity, db, kwargs)
def get_system_username ()
def get_default_username
Detailed Description
Creates permissions for all installed apps that need permissions.
Function Documentation
def django.contrib.auth.management.create_permissions (app, created_models, verbosity, db = DEFAULT_DB_ALIAS, kwargs)
Definition at line 61 of file __init__.py.
References django.contrib.comments.get_model(), and django.db.models.loading.get_models.
Referenced by django.contrib.auth.tests.test_management.PermissionDuplicationTestCase.test_duplicated_permissions().
def django.contrib.auth.management.create_superuser (app, created_models, verbosity, db, kwargs)
Definition at line 107 of file __init__.py.
References django.core.management.call_command(), django.contrib.comments.get_model(), and django.contrib.auth.get_user_model().
Referenced by django.contrib.auth.management.commands.createsuperuser.Command.handle().
def django.contrib.auth.management.get_default_username (check_db = True)
Try to determine the current system user's username to use as a default.
:param check_db: If ``True``, requires that the username does not match an
    existing ``auth.User`` (otherwise returns an empty string).
:returns: The username, or an empty string if no username can be
    determined.
Definition at line 153 of file __init__.py.
References django.contrib.auth.management.get_system_username(), and django.template.defaultfilters.lower().
Referenced by django.contrib.auth.management.commands.createsuperuser.Command.handle().
def django.contrib.auth.management.get_system_username ()
Try to determine the current system user's username.
:returns: The username as a unicode string, or an empty string if the
    username could not be determined.
Definition at line 130 of file __init__.py.
Referenced by django.contrib.auth.management.get_default_username().