Django: django.utils.timezone.ReferenceLocalTimezone Class Reference
django.utils.timezone.ReferenceLocalTimezone Class Reference
Public Member Functions
def __init__ (self)
def __repr__ (self)
def utcoffset (self, dt)
def dst (self, dt)
def tzname (self, dt)
Public Attributes
STDOFFSET
DSTOFFSET
DSTDIFF
Detailed Description
Local time implementation taken from Python's docs.
Used only when pytz isn't available, and most likely inaccurate. If you're
having trouble with this class, don't waste your time, just install pytz.
Kept identical to the reference version. Subclasses contain improvements.
Definition at line 53 of file timezone.py.
Constructor & Destructor Documentation
def django.utils.timezone.ReferenceLocalTimezone.__init__ (self)
Definition at line 63 of file timezone.py.
Member Function Documentation
def django.utils.timezone.ReferenceLocalTimezone.__repr__ (self)
Definition at line 74 of file timezone.py.
def django.utils.timezone.ReferenceLocalTimezone.dst (self, dt)
Definition at line 83 of file timezone.py.
References django.utils.timezone.ReferenceLocalTimezone._isdst(), and django.utils.timezone.ReferenceLocalTimezone.DSTDIFF.
def django.utils.timezone.ReferenceLocalTimezone.tzname (self, dt)
Definition at line 89 of file timezone.py.
References django.utils.timezone.ReferenceLocalTimezone._isdst().
Referenced by django.utils.tzinfo.LocalTimezone.__init__().
def django.utils.timezone.ReferenceLocalTimezone.utcoffset (self, dt)
Definition at line 77 of file timezone.py.
References django.utils.timezone.ReferenceLocalTimezone._isdst(), django.utils.timezone.ReferenceLocalTimezone.DSTOFFSET, and django.utils.timezone.ReferenceLocalTimezone.STDOFFSET.
Member Data Documentation
django.utils.timezone.ReferenceLocalTimezone.DSTDIFF
Definition at line 71 of file timezone.py.
Referenced by django.utils.timezone.ReferenceLocalTimezone.dst().
django.utils.timezone.ReferenceLocalTimezone.DSTOFFSET
Definition at line 68 of file timezone.py.
Referenced by django.utils.timezone.ReferenceLocalTimezone.utcoffset().
django.utils.timezone.ReferenceLocalTimezone.STDOFFSET
Definition at line 66 of file timezone.py.
Referenced by django.utils.timezone.ReferenceLocalTimezone.utcoffset().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/utils/timezone.py