Django: django.contrib.admin.widgets.AdminURLFieldWidget Class Reference
django.contrib.admin.widgets.AdminURLFieldWidget Class Reference
Public Member Functions
def __init__
def render
Public Member Functions inherited from django.forms.widgets.TextInput
def __init__
Public Member Functions inherited from django.forms.widgets.Input
def render
Public Member Functions inherited from django.forms.widgets.Widget
def __init__
def __deepcopy__ (self, memo)
def subwidgets
def render
def build_attrs (self, extra_attrs=None, kwargs)
def value_from_datadict (self, data, files, name)
def id_for_label (self, id_)
Public Member Functions inherited from django.forms.widgets.MediaDefiningClass
def __new__ (cls, name, bases, attrs)
Additional Inherited Members
Public Attributes inherited from django.forms.widgets.TextInput
input_type
Public Attributes inherited from django.forms.widgets.Widget
attrs
Static Public Attributes inherited from django.forms.widgets.URLInput
string input_type = 'url'
Static Public Attributes inherited from django.forms.widgets.TextInput
string input_type = 'text'
Static Public Attributes inherited from django.forms.widgets.Input
input_type = None
Static Public Attributes inherited from django.forms.widgets.Widget
is_hidden = False
needs_multipart_form = False
is_localized = False
is_required = False
Detailed Description
Definition at line 297 of file widgets.py.
Constructor & Destructor Documentation
def django.contrib.admin.widgets.AdminURLFieldWidget.__init__ (self, attrs = None)
Definition at line 298 of file widgets.py.
Member Function Documentation
def django.contrib.admin.widgets.AdminURLFieldWidget.render (self, name, value, attrs = None)
Definition at line 304 of file widgets.py.
References django.forms.widgets.Input._format_value(), django.forms.util.flatatt(), and django.utils.encoding.force_text().
Referenced by django.forms.widgets.Media.__str__(), django.forms.widgets.ChoiceInput.__str__(), django.forms.widgets.ChoiceFieldRenderer.__str__(), django.contrib.formtools.wizard.views.WizardView.get(), django.contrib.formtools.wizard.views.NamedUrlWizardView.get(), django.contrib.gis.maps.google.gmap.GoogleMap.js(), django.contrib.formtools.wizard.views.WizardView.post(), django.templatetags.i18n.BlockTranslateNode.render(), django.contrib.formtools.wizard.views.WizardView.render_goto_step(), django.contrib.formtools.wizard.views.WizardView.render_next_step(), django.contrib.formtools.wizard.views.WizardView.render_revalidation_failure(), and django.template.loader_tags.BlockNode.super().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/admin/widgets.py