Django: django.conf.urls Namespace Reference
django.conf.urls Namespace Reference
Namespaces
i18n
shortcut
static
Functions
def include
def patterns (prefix, args)
def url
Variables
list __all__ = ['handler400', 'handler403', 'handler404', 'handler500', 'include', 'patterns', 'url']
string handler400 = 'django.views.defaults.bad_request'
string handler403 = 'django.views.defaults.permission_denied'
string handler404 = 'django.views.defaults.page_not_found'
string handler500 = 'django.views.defaults.server_error'
Function Documentation
def django.conf.urls.include (arg, namespace = None, app_name = None)
Definition at line 15 of file __init__.py.
References django.utils.importlib.import_module().
Referenced by django.contrib.admin.sites.AdminSite.get_urls().
def django.conf.urls.patterns (prefix, args)
Definition at line 41 of file __init__.py.
References django.conf.urls.url().
Referenced by django.contrib.auth.admin.UserAdmin.get_urls(), django.contrib.admin.sites.AdminSite.get_urls(), django.contrib.admin.options.ModelAdmin.get_urls(), django.conf.urls.i18n.i18n_patterns(), and django.conf.urls.static.static().
def django.conf.urls.url (regex, view, kwargs = None, name = None, prefix = '')
Definition at line 51 of file __init__.py.
Referenced by django.contrib.admin.sites.AdminSite.get_urls(), django.contrib.admin.options.ModelAdmin.get_urls(), django.conf.urls.patterns(), django.conf.urls.static.static(), and yt().
Variable Documentation
list django.conf.urls.__all__ = ['handler400', 'handler403', 'handler404', 'handler500', 'include', 'patterns', 'url']
Definition at line 8 of file __init__.py.
string django.conf.urls.handler400 = 'django.views.defaults.bad_request'
Definition at line 10 of file __init__.py.
string django.conf.urls.handler403 = 'django.views.defaults.permission_denied'
Definition at line 11 of file __init__.py.
string django.conf.urls.handler404 = 'django.views.defaults.page_not_found'
Definition at line 12 of file __init__.py.
string django.conf.urls.handler500 = 'django.views.defaults.server_error'
Definition at line 13 of file __init__.py.