Django: django.contrib.comments.models.CommentFlag.Meta Class Reference
django.contrib.comments.models.CommentFlag.Meta Class Reference
Static Public Attributes
string db_table = 'django_comment_flags'
list unique_together = [('user', 'comment', 'flag')]
tuple verbose_name = _('comment flag')
tuple verbose_name_plural = _('comment flags')
Detailed Description
Definition at line 187 of file models.py.
Member Data Documentation
string django.contrib.comments.models.CommentFlag.Meta.db_table = 'django_comment_flags' static
Definition at line 188 of file models.py.
Referenced by django.db.models.fields.related.ManyToManyField.get_choices_default(), and django.db.models.options.Options.setup_proxy().
list django.contrib.comments.models.CommentFlag.Meta.unique_together = [('user', 'comment', 'flag')] static
Definition at line 189 of file models.py.
tuple django.contrib.comments.models.CommentFlag.Meta.verbose_name = _('comment flag') static
Definition at line 190 of file models.py.
Referenced by django.db.models.fields.Field.formfield(), django.db.models.fields.NullBooleanField.formfield(), and django.db.models.options.Options.verbose_name_raw().
tuple django.contrib.comments.models.CommentFlag.Meta.verbose_name_plural = _('comment flags') static
Definition at line 191 of file models.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/comments/models.py