Django: django.test.runner Namespace Reference
django.test.runner Namespace Reference
Classes
class DiscoverRunner
Functions
def dependency_ordered (test_databases, dependencies)
def reorder_suite (suite, classes)
def partition_suite (suite, classes, bins)
def setup_databases (verbosity, interactive, kwargs)
Function Documentation
def django.test.runner.dependency_ordered (test_databases, dependencies)
Reorder test_databases into an order that honors the dependencies
described in TEST_DEPENDENCIES.
Definition at line 152 of file runner.py.
Referenced by django.test.runner.setup_databases().
def django.test.runner.partition_suite (suite, classes, bins)
Partitions a test suite by test type.
classes is a sequence of types
bins is a sequence of TestSuites, one more than classes
Tests of type classes[i] are added to bins[i],
tests with no match found in classes are place in bins[-1]
Definition at line 211 of file runner.py.
Referenced by django.test.runner.reorder_suite().
def django.test.runner.reorder_suite (suite, classes)
Reorders a test suite by test type.
`classes` is a sequence of types
All tests of type classes[0] are placed first, then tests of type
classes[1], etc. Tests with no match in classes are placed last.
Definition at line 194 of file runner.py.
References django.test.runner.partition_suite().
Referenced by django.test.runner.DiscoverRunner.build_suite().
def django.test.runner.setup_databases (verbosity, interactive, kwargs)
Definition at line 233 of file runner.py.
References django.contrib.messages.tests.urls.add(), and django.test.runner.dependency_ordered().