Django: dj16/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.js File Reference
jquery.js File Reference
Functions
function vendorPropName (style, name)
function isHidden (elem, el)
function showHide (elements, show)
jQuery fn extend ({css:function(name, value){return jQuery.access(this, function(elem, name, value){var len, styles, map={}, i=0;if(jQuery.isArray(name)){styles=getStyles(elem);len=name.length;for(;i< len;i++){map[name[i]]=jQuery.css(elem, name[i], false, styles);}return map;}return value!==undefined?jQuery.style(elem, name, value):jQuery.css(elem, name);}, name, value, arguments.length > 1);}, show:function(){return showHide(this, true);}, hide:function(){return showHide(this);}, toggle:function(state){var bool=typeof state==="boolean";return this.each(function(){if(bool?state:isHidden(this)){jQuery(this).show();}else{jQuery(this).hide();}});}})
if (window.getComputedStyle)
else if (document.documentElement.currentStyle)
function setPositiveNumber (elem, value, subtract)
function augmentWidthOrHeight (elem, name, extra, isBorderBox, styles)
function getWidthOrHeight (elem, name, extra)
function css_defaultDisplay (nodeName)
function actualDisplay (name, doc)
jQuery each (["height","width"], function(i, name){jQuery.cssHooks[name]={get:function(elem, computed, extra){if(computed){return elem.offsetWidth===0 &&rdisplayswap.test(jQuery.css(elem,"display"))?jQuery.swap(elem, cssShow, function(){return getWidthOrHeight(elem, name, extra);}):getWidthOrHeight(elem, name, extra);}}, set:function(elem, value, extra){var styles=extra &&getStyles(elem);return setPositiveNumber(elem, value, extra?augmentWidthOrHeight(elem, name, extra, jQuery.support.boxSizing &&jQuery.css(elem,"boxSizing", false, styles)==="border-box", styles):0);}};})
if (!jQuery.support.opacity)
jQuery (function(){if(!jQuery.support.reliableMarginRight){jQuery.cssHooks.marginRight={get:function(elem, computed){if(computed){return jQuery.swap(elem,{"display":"inline-block"}, curCSS, [elem,"marginRight"]);}}};}if(!jQuery.support.pixelPosition &&jQuery.fn.position){jQuery.each(["top","left"], function(i, prop){jQuery.cssHooks[prop]={get:function(elem, computed){if(computed){computed=curCSS(elem, prop);return rnumnonpx.test(computed)?jQuery(elem).position()[prop]+"px":computed;}}};});}})
if (jQuery.expr &&jQuery.expr.filters)
jQuery each ({margin:"", padding:"", border:"Width"}, function(prefix, suffix){jQuery.cssHooks[prefix+suffix]={expand:function(value){var i=0, expanded={}, parts=typeof value==="string"?value.split(" "):[value];for(;i< 4;i++){expanded[prefix+cssExpand[i]+suffix]=parts[i]||parts[i-2]||parts[0];}return expanded;}};if(!rmargin.test(prefix)){jQuery.cssHooks[prefix+suffix].set=setPositiveNumber;}})
function buildParams (prefix, obj, traditional, add)
catch (e)
function addToPrefiltersOrTransports (structure)
function inspectPrefiltersOrTransports (structure, options, originalOptions, jqXHR)
function ajaxExtend (target, src)
function ajaxHandleResponses (s, jqXHR, responses)
function ajaxConvert (s, response)
jQuery ajaxSetup ({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"}, contents:{script:/(?:java|ecma) script/}, converters:{"text script":function(text){jQuery.globalEval(text);return text;}}})
jQuery ajaxPrefilter ("script", function(s){if(s.cache===undefined){s.cache=false;}if(s.crossDomain){s.type="GET";s.global=false;}})
jQuery ajaxTransport ("script", function(s){if(s.crossDomain){var script, head=document.head||jQuery("head")[0]||document.documentElement;return{send:function(_, callback){script=document.createElement("script");script.async=true;if(s.scriptCharset){script.charset=s.scriptCharset;}script.src=s.url;script.onload=script.onreadystatechange=function(_, isAbort){if(isAbort||!script.readyState||/loaded|complete/.test(script.readyState)){script.onload=script.onreadystatechange=null;if(script.parentNode){script.parentNode.removeChild(script);}script=null;if(!isAbort){callback(200,"success");}}};head.insertBefore(script, head.firstChild);}, abort:function(){if(script){script.onload(undefined, true);}}};}})
function createStandardXHR ()
function createActiveXHR ()
if (xhrSupported)
function createFxNow ()
function createTweens (animation, props)
function Animation (elem, properties, options)
function propFilter (props, specialEasing)
function defaultPrefilter (elem, props, opts)
function Tween (elem, options, prop, end, easing)
function genFx (type, includeWidth)
function getWindow (elem)
if (typeof define==="function"&&define.amd &&define.amd.jQuery)
Variables
function window
function undefined
function Right
function Bottom
function Left
function cssPrefixes = [ "Webkit", "O", "Moz", "ms" ]
var r20 = /%20/g
var rbracket = /\[\]$/
var rCRLF = /\r?\n/g
var rsubmitterTypes = /^(?:submit|button|image|reset|file)$/i
var rsubmittable = /^(?:input|select|textarea|keygen)/i
jQuery param
jQuery fn hover
var ajaxLocParts = rurl.exec(ajaxLocation.toLowerCase()) || []
var ajaxLocation
var ajax_nonce = jQuery.now()
var ajax_rquery = /\?/
var rhash = /#.*$/
var rts = /([?&])_=[^&]*/
var rheaders = /^(.*?):[ \t]*([^\r\n]*)\r?$/mg
var rlocalProtocol = /^(?:about|app|app-storage|.+-extension|file|res|widget):$/
var rnoContent = /^(?:GET|HEAD)$/
var rprotocol
var _load = jQuery.fn.load
var prefilters = {}
var transports = {}
var allTypes = "*/".concat("*")
try
jQuery fn load
var oldCallbacks = []
var rjsonp = /(=)\?(?=&|$)|\?\?/
var xhrCallbacks
var xhrSupported = jQuery.ajaxSettings.xhr()
var xhrId = 0
var xhrOnUnloadAbort
jQuery ajaxSettings xhr
jQuery support cors = !!xhrSupported && ("withCredentials" in xhrSupported)
var fxNow
var timerId
var rfxtypes = /^(?:toggle|show|hide)$/
var rfxnum = new RegExp("^(?:([+-])=|)(" + core_pnum + ")([a-z%]*)$", "i")
var rrun = /queueHooks$/
var animationPrefilters = [ defaultPrefilter ]
var tweeners
jQuery Animation
jQuery Tween = Tween
Tween prototype
Tween propHooks
Tween propHooks scrollTop
jQuery speed
jQuery easing
jQuery timers = []
jQuery fx = Tween.prototype.init
jQuery fx tick
jQuery fx timer
jQuery fx interval = 13
jQuery fx start
jQuery fx stop
jQuery fx speeds
jQuery fx step = {}
jQuery fn offset
window jQuery = window.$ = jQuery
Function Documentation
function actualDisplay (name, doc)
Definition at line 7139 of file jquery.js.
References jQuery.
Referenced by css_defaultDisplay().
function addToPrefiltersOrTransports (structure)
Definition at line 7466 of file jquery.js.
References jQuery.
function ajaxConvert (s, response)
Definition at line 8178 of file jquery.js.
References i.
function ajaxExtend (target, src)
Definition at line 7525 of file jquery.js.
References jQuery.
function ajaxHandleResponses (s, jqXHR, responses)
Definition at line 8117 of file jquery.js.
References ct().
jQuery ajaxPrefilter ("script" , function(s){if(s.cache===undefined){s.cache=false;}if(s.crossDomain){s.type="GET";s.global=false;}})
jQuery ajaxSetup ({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"}, contents:{script:/(?:java|ecma) script/}, converters:{"text script":function(text){jQuery.globalEval(text);return text;}}})
jQuery ajaxTransport ("script" , function(s){if(s.crossDomain){var script, head=document.head||jQuery("head")[0]||document.documentElement;return{send:function(_, callback){script=document.createElement("script");script.async=true;if(s.scriptCharset){script.charset=s.scriptCharset;}script.src=s.url;script.onload=script.onreadystatechange=function(_, isAbort){if(isAbort||!script.readyState||/loaded|complete/.test(script.readyState)){script.onload=script.onreadystatechange=null;if(script.parentNode){script.parentNode.removeChild(script);}script=null;if(!isAbort){callback(200,"success");}}};head.insertBefore(script, head.firstChild);}, abort:function(){if(script){script.onload(undefined, true);}}};}})
function Animation (elem, properties, options)
Definition at line 8706 of file jquery.js.
References animationPrefilters, createFxNow(), django.contrib.gis.sitemaps.views::index(), jQuery, django.template.defaultfilters::length(), stop, and tick.
function augmentWidthOrHeight (elem, name, extra, isBorderBox, styles)
Definition at line 7024 of file jquery.js.
References jQuery.
Referenced by getWidthOrHeight().
function buildParams (prefix, obj, traditional, add)
Definition at line 7368 of file jquery.js.
References django.contrib.messages.tests.urls::add(), jQuery, django.utils.unittest.loader::obj, django.template.smartif::prefix(), and rbracket.
catch (e)
Definition at line 7454 of file jquery.js.
function createActiveXHR ()
Definition at line 8445 of file jquery.js.
References window.
function createFxNow ()
Definition at line 8684 of file jquery.js.
References jQuery, and undefined.
Referenced by Animation().
function createStandardXHR ()
Definition at line 8439 of file jquery.js.
References window.
function createTweens (animation, props)
Definition at line 8691 of file jquery.js.
References django.contrib.gis.sitemaps.views::index(), jQuery, django.template.defaultfilters::length(), and tweeners.
function css_defaultDisplay (nodeName)
Definition at line 7107 of file jquery.js.
References actualDisplay(), and jQuery.
Referenced by defaultPrefilter(), and showHide().
function defaultPrefilter (elem, props, opts)
Definition at line 8877 of file jquery.js.
References css_defaultDisplay(), hidden, django.contrib.gis.sitemaps.views::index(), isHidden(), jQuery, django.template.defaultfilters::length(), and rfxtypes.
jQuery each (function(i, name){jQuery.cssHooks[name]={get:function(elem, computed, extra){if(computed){return elem.offsetWidth===0 &&rdisplayswap.test(jQuery.css(elem,"display"))?jQuery.swap(elem, cssShow, function(){return getWidthOrHeight(elem, name, extra);}):getWidthOrHeight(elem, name, extra);}}, set:function(elem, value, extra){var styles=extra &&getStyles(elem);return setPositiveNumber(elem, value, extra?augmentWidthOrHeight(elem, name, extra, jQuery.support.boxSizing &&jQuery.css(elem,"boxSizing", false, styles)==="border-box", styles):0);}};})
b each ({margin:"", padding:"", border:"Width"} , function(prefix, suffix){jQuery.cssHooks[prefix+suffix]={expand:function(value){var i=0, expanded={}, parts=typeof value==="string"?value.split(" "):[value];for(;i< 4;i++){expanded[prefix+cssExpand[i]+suffix]=parts[i]||parts[i-2]||parts[0];}return expanded;}};if(!rmargin.test(prefix)){jQuery.cssHooks[prefix+suffix].set=setPositiveNumber;}})
Referenced by yt().
b fn extend ({css:function(name, value){return jQuery.access(this, function(elem, name, value){var len, styles, map={}, i=0;if(jQuery.isArray(name)){styles=getStyles(elem);len=name.length;for(;i< len;i++){map[name[i]]=jQuery.css(elem, name[i], false, styles);}return map;}return value!==undefined?jQuery.style(elem, name, value):jQuery.css(elem, name);}, name, value, arguments.length > 1);}, show:function(){return showHide(this, true);}, hide:function(){return showHide(this);}, toggle:function(state){var bool=typeof state==="boolean";return this.each(function(){if(bool?state:isHidden(this)){jQuery(this).show();}else{jQuery(this).hide();}});}})
Referenced by django.core.urlresolvers.RegexURLResolver::__repr__(), django.core.exceptions.ValidationError::message_dict(), django.db.models.sql.query.Query::names_to_path(), django.core.management.sql::sql_create(), django.contrib.gis.db.models.query.GeoQuerySet::unionagg(), django.utils.datastructures.MultiValueDict::update(), and django.core.exceptions.ValidationError::update_error_dict().
function genFx (type, includeWidth)
Definition at line 9230 of file jquery.js.
References i.
function getWidthOrHeight (elem, name, extra)
Definition at line 7063 of file jquery.js.
References augmentWidthOrHeight(), and jQuery.
function getWindow (elem)
Definition at line 9526 of file jquery.js.
References jQuery.
if (window. getComputedStyle)
Definition at line 6924 of file jquery.js.
References jQuery, undefined, and window.
else if (document.documentElement. currentStyle)
Definition at line 6967 of file jquery.js.
if (!jQuery.support. opacity)
Definition at line 7175 of file jquery.js.
References jQuery, and opacity().
if (jQuery.expr &&jQuery.expr. filters)
Definition at line 7256 of file jquery.js.
References jQuery.
if (xhrSupported)
Definition at line 8472 of file jquery.js.
References jQuery.
if (typeof define = == "function" && define.amd && define.amd.jQuery)
Definition at line 9593 of file jquery.js.
References jQuery.
function inspectPrefiltersOrTransports (structure, options, originalOptions, jqXHR)
Definition at line 7498 of file jquery.js.
References jQuery, and transports.
function isHidden (elem, el)
Definition at line 6662 of file jquery.js.
References jQuery.
Referenced by defaultPrefilter(), and showHide().
jQuery (function(){if(!jQuery.support.reliableMarginRight){jQuery.cssHooks.marginRight={get:function(elem, computed){if(computed){return jQuery.swap(elem,{"display":"inline-block"}, curCSS, [elem,"marginRight"]);}}};}if(!jQuery.support.pixelPosition &&jQuery.fn.position){jQuery.each(["top","left"], function(i, prop){jQuery.cssHooks[prop]={get:function(elem, computed){if(computed){computed=curCSS(elem, prop);return rnumnonpx.test(computed)?jQuery(elem).position()[prop]+"px":computed;}}};});}})
function propFilter (props, specialEasing)
Definition at line 8810 of file jquery.js.
References easing, django.contrib.gis.sitemaps.views::index(), and jQuery.
function setPositiveNumber (elem, value, subtract)
Definition at line 7016 of file jquery.js.
function showHide (elements, show)
Definition at line 6669 of file jquery.js.
References css_defaultDisplay(), hidden, django.contrib.gis.sitemaps.views::index(), isHidden(), jQuery, django.template.defaultfilters::length(), and django.contrib.messages.tests.urls::show().
function Tween (elem, options, prop, end, easing)
Definition at line 9004 of file jquery.js.
References easing, and Tween.
function vendorPropName (style, name)
Definition at line 6640 of file jquery.js.
References cssPrefixes, and i.
Variable Documentation
var _load = jQuery.fn.load
Definition at line 7427 of file jquery.js.
var ajax_nonce = jQuery.now()
Definition at line 7414 of file jquery.js.
var ajax_rquery = /\?/
Definition at line 7416 of file jquery.js.
var ajaxLocation
Definition at line 7412 of file jquery.js.
ajaxLocParts = rurl.exec(ajaxLocation.toLowerCase()) || []
Definition at line 7412 of file jquery.js.
var allTypes = "*/".concat("*")
Definition at line 7448 of file jquery.js.
jQuery Animation
Initial value:
= jQuery.extend(Animation, {
    tweener: function( props, callback ) {
        if ( jQuery.isFunction( props ) ) {
            callback = props;
            props = [ "*" ];
        } else {
            props = props.split(" ");
        }
        var prop,
            index = 0,
            length = props.length;
        for ( ; index < length ; index++ ) {
            prop = props[ index ];
            tweeners[ prop ] = tweeners[ prop ] || [];
            tweeners[ prop ].unshift( callback );
        }
    },
    prefilter: function( callback, prepend ) {
        if ( prepend ) {
            animationPrefilters.unshift( callback );
        } else {
            animationPrefilters.push( callback );
        }
    }
})
Definition at line 8847 of file jquery.js.
var animationPrefilters = [ defaultPrefilter ]
Definition at line 8638 of file jquery.js.
Referenced by Animation().
function Bottom
Definition at line 14 of file jquery.js.
jQuery support cors = !!xhrSupported && ("withCredentials" in xhrSupported)
Definition at line 8468 of file jquery.js.
function cssPrefixes = [ "Webkit", "O", "Moz", "ms" ]
Definition at line 6637 of file jquery.js.
Referenced by vendorPropName().
jQuery easing
Initial value:
= {
    linear: function( p ) {
        return p;
    },
    swing: function( p ) {
        return 0.5 - Math.cos( p*Math.PI ) / 2;
    }
}
Definition at line 9296 of file jquery.js.
Referenced by propFilter(), and Tween().
jQuery fx = Tween.prototype.init
Definition at line 9306 of file jquery.js.
var fxNow
Definition at line 8634 of file jquery.js.
jQuery fn hover
Initial value:
= function(fnOver, fnOut) {
    return this.mouseenter( fnOver ).mouseleave( fnOut || fnOver );
}
Definition at line 7407 of file jquery.js.
jQuery fx interval = 13
Definition at line 9334 of file jquery.js.
window jQuery = window.$ = jQuery
Definition at line 9579 of file jquery.js.
Referenced by actualDisplay(), addToPrefiltersOrTransports(), ajaxExtend(), Animation(), augmentWidthOrHeight(), buildParams(), createFxNow(), createTweens(), css_defaultDisplay(), defaultPrefilter(), getWidthOrHeight(), getWindow(), if(), inspectPrefiltersOrTransports(), isHidden(), propFilter(), and showHide().
function Left
Definition at line 14 of file jquery.js.
jQuery fn load
Definition at line 7541 of file jquery.js.
Referenced by django.contrib.sessions.tests.FileSessionTests::test_invalid_key_backslash().
jQuery offset
Definition at line 9364 of file jquery.js.
var oldCallbacks = []
Definition at line 8347 of file jquery.js.
jQuery param
Definition at line 7335 of file jquery.js.
var prefilters = {}
Definition at line 7438 of file jquery.js.
Tween propHooks
Definition at line 9055 of file jquery.js.
Tween prototype init prototype
Definition at line 9009 of file jquery.js.
var r20 = /%20/g
Definition at line 7296 of file jquery.js.
var rbracket = /\[\]$/
Definition at line 7297 of file jquery.js.
Referenced by buildParams().
var rCRLF = /\r?\n/g
Definition at line 7298 of file jquery.js.
var rfxnum = new RegExp("^(?:([+-])=|)(" + core_pnum + ")([a-z%]*)$", "i")
Definition at line 8636 of file jquery.js.
var rfxtypes = /^(?:toggle|show|hide)$/
Definition at line 8635 of file jquery.js.
Referenced by defaultPrefilter().
var rhash = /#.*$/
Definition at line 7417 of file jquery.js.
var rheaders = /^(.*?):[ \t]*([^\r\n]*)\r?$/mg
Definition at line 7419 of file jquery.js.
function Right
Definition at line 14 of file jquery.js.
var rjsonp = /(=)\?(?=&|$)|\?\?/
Definition at line 8348 of file jquery.js.
var rlocalProtocol = /^(?:about|app|app-storage|.+-extension|file|res|widget):$/
Definition at line 7421 of file jquery.js.
var rnoContent = /^(?:GET|HEAD)$/
Definition at line 7422 of file jquery.js.
var rprotocol
Initial value:
= /^\/\
    rurl = /^([\w.+-]+:)(?:\/\/([^\/?#:]*)(?::(\d+)|)|)/
Definition at line 7423 of file jquery.js.
var rrun = /queueHooks$/
Definition at line 8637 of file jquery.js.
var rsubmittable = /^(?:input|select|textarea|keygen)/i
Definition at line 7300 of file jquery.js.
var rsubmitterTypes = /^(?:submit|button|image|reset|file)$/i
Definition at line 7299 of file jquery.js.
var rts = /([?&])_=[^&]*/
Definition at line 7418 of file jquery.js.
Tween propHooks scrollTop
Initial value:
= Tween.propHooks.scrollLeft = {
    set: function( tween ) {
        if ( tween.elem.nodeType && tween.elem.parentNode ) {
            tween.elem[ tween.prop ] = tween.now;
        }
    }
}
Definition at line 9090 of file jquery.js.
jQuery speed
Definition at line 9264 of file jquery.js.
jQuery fx speeds
Initial value:
= {
    slow: 600,
    fast: 200,
    _default: 400
}
Definition at line 9347 of file jquery.js.
jQuery fx start
Initial value:
= function() {
    if ( !timerId ) {
        timerId = setInterval( jQuery.fx.tick, jQuery.fx.interval );
    }
}
Definition at line 9336 of file jquery.js.
jQuery fx step = {}
Definition at line 9355 of file jquery.js.
jQuery fx stop
Initial value:
= function() {
    clearInterval( timerId );
    timerId = null;
}
Definition at line 9342 of file jquery.js.
Referenced by Animation().
jQuery fx tick
Initial value:
= function() {
    var timer,
        timers = jQuery.timers,
        i = 0;
    fxNow = jQuery.now();
    for ( ; i < timers.length; i++ ) {
        timer = timers[ i ];
        if ( !timer() && timers[ i ] === timer ) {
            timers.splice( i--, 1 );
        }
    }
    if ( !timers.length ) {
        jQuery.fx.stop();
    }
    fxNow = undefined;
}
Definition at line 9307 of file jquery.js.
Referenced by Animation().
jQuery fx timer
Initial value:
= function(timer) {
    if ( timer() && jQuery.timers.push( timer ) ) {
        jQuery.fx.start();
    }
}
Definition at line 9328 of file jquery.js.
var timerId
Definition at line 8634 of file jquery.js.
jQuery timers = []
Definition at line 9305 of file jquery.js.
var transports = {}
Definition at line 7445 of file jquery.js.
Referenced by inspectPrefiltersOrTransports().
try
Initial value:
{
    ajaxLocation = location.href
Definition at line 7452 of file jquery.js.
jQuery Tween = Tween
Definition at line 9007 of file jquery.js.
Referenced by Tween().
var tweeners
Definition at line 8639 of file jquery.js.
Referenced by createTweens().
function undefined
Definition at line 14 of file jquery.js.
Referenced by createFxNow(), and if().
window
jQuery JavaScript Library v1.9.1 http://jquery.com/
Includes Sizzle.js http://sizzlejs.com/
Copyright 2005, 2012 jQuery Foundation, Inc. and other contributors Released under the MIT license http://jquery.org/license
Date: 2013-2-4
Definition at line 14 of file jquery.js.
Referenced by cancelEventPropagation(), createActiveXHR(), createStandardXHR(), if(), showAddAnotherPopup(), and showRelatedObjectLookupPopup().
jQuery ajaxSettings xhr
Initial value:
= window.ActiveXObject ?
    function() {
        return !this.isLocal && createStandardXHR() || createActiveXHR();
    } :
    createStandardXHR
Definition at line 8453 of file jquery.js.
var xhrCallbacks
Definition at line 8427 of file jquery.js.
var xhrId = 0
Definition at line 8428 of file jquery.js.
var xhrOnUnloadAbort
Initial value:
= window.ActiveXObject && function() {
        var key;
        for ( key in xhrCallbacks ) {
            xhrCallbacks[ key ]( undefined, true );
        }
    }
Definition at line 8430 of file jquery.js.
xhrSupported = jQuery.ajaxSettings.xhr()
Definition at line 8427 of file jquery.js.