Django: django.dispatch.dispatcher.Signal Class Reference
django.dispatch.dispatcher.Signal Class Reference
Public Member Functions
def __init__
def connect
def disconnect
def has_listeners
def send (self, sender, named)
def send_robust (self, sender, named)
Public Attributes
receivers
providing_args
lock
use_caching
sender_receivers_cache
Detailed Description
Base class for all signals
Internal attributes:
    receivers
        { receriverkey (id) : weakref(receiver) }
Definition at line 21 of file dispatcher.py.
Constructor & Destructor Documentation
def django.dispatch.dispatcher.Signal.__init__ (self, providing_args = None, use_caching = False)
Create a new signal.
providing_args
    A list of the arguments this signal can pass along in a send() call.
Definition at line 30 of file dispatcher.py.
Member Function Documentation
def django.dispatch.dispatcher.Signal.connect (self, receiver, sender = None, weak = True, dispatch_uid = None)
Connect receiver to sender for signal.
Arguments:
    receiver
A function or an instance method which is to receive signals.
Receivers must be hashable objects.
If weak is True, then receiver must be weak-referencable (more
precisely saferef.safeRef() must be able to create a reference
to the receiver).
Receivers must be able to accept keyword arguments.
If receivers have a dispatch_uid attribute, the receiver will
not be added if another receiver already exists with that
dispatch_uid.
    sender
The sender to which the receiver should respond. Must either be
of type Signal, or None to receive events from any sender.
    weak
Whether to use weak references to the receiver. By default, the
module will attempt to use weak references to the receiver
objects. If this parameter is false, then strong references will
be used.
    dispatch_uid
An identifier used to uniquely identify a particular instance of
a receiver. This will usually be a string, though it may be
anything hashable.
Definition at line 50 of file dispatcher.py.
References django.dispatch.dispatcher.Signal._remove_receiver(), django.utils.six.callable, django.dispatch.dispatcher.Signal.lock, and django.dispatch.dispatcher.Signal.receivers.
def django.dispatch.dispatcher.Signal.disconnect (self, receiver = None, sender = None, weak = True, dispatch_uid = None)
Disconnect receiver from sender for signal.
If weak references are used, disconnect need not be called. The receiver
will be remove from dispatch automatically.
Arguments:
    receiver
The registered receiver to disconnect. May be none if
dispatch_uid is specified.
    sender
The registered sender to disconnect
    weak
The weakref state to disconnect
    dispatch_uid
the unique identifier of the receiver to disconnect
Definition at line 124 of file dispatcher.py.
References django.dispatch.dispatcher.Signal.lock, and django.dispatch.dispatcher.Signal.receivers.
def django.dispatch.dispatcher.Signal.has_listeners (self, sender = None)
Definition at line 159 of file dispatcher.py.
References django.dispatch.dispatcher.Signal._live_receivers().
def django.dispatch.dispatcher.Signal.send (self, sender, named)
Send signal from sender to all connected receivers.
If any receiver raises an error, the error propagates back through send,
terminating the dispatch loop, so it is quite possible to not have all
receivers called if a raises an error.
Arguments:
    sender
The sender of the signal Either a specific object or None.
    named
Named arguments which will be passed to receivers.
Returns a list of tuple pairs [(receiver, response), ... ].
Definition at line 162 of file dispatcher.py.
References django.dispatch.dispatcher.Signal._live_receivers(), django.dispatch.dispatcher.receiver(), and django.dispatch.dispatcher.Signal.receivers.
def django.dispatch.dispatcher.Signal.send_robust (self, sender, named)
Send signal from sender to all connected receivers catching errors.
Arguments:
    sender
The sender of the signal. Can be any python object (normally one
registered with a connect if you actually want something to
occur).
    named
Named arguments which will be passed to receivers. These
arguments must be a subset of the argument names defined in
providing_args.
Return a list of tuple pairs [(receiver, response), ... ]. May raise
DispatcherKeyError.
If any receiver raises an error (specifically any subclass of
Exception), the error instance is returned as the result for that
receiver.
Definition at line 189 of file dispatcher.py.
References django.dispatch.dispatcher.Signal._live_receivers(), django.dispatch.dispatcher.Signal.lock, django.dispatch.dispatcher.receiver(), django.dispatch.dispatcher.Signal.receivers, django.dispatch.dispatcher.Signal.sender_receivers_cache, and django.dispatch.dispatcher.Signal.use_caching.
Member Data Documentation
django.dispatch.dispatcher.Signal.lock
Definition at line 41 of file dispatcher.py.
Referenced by django.dispatch.dispatcher.Signal.connect(), django.dispatch.dispatcher.Signal.disconnect(), and django.dispatch.dispatcher.Signal.send_robust().
django.dispatch.dispatcher.Signal.providing_args
Definition at line 40 of file dispatcher.py.
django.dispatch.dispatcher.Signal.receivers
Definition at line 37 of file dispatcher.py.
Referenced by django.dispatch.dispatcher.Signal.connect(), django.dispatch.dispatcher.Signal.disconnect(), django.dispatch.dispatcher.Signal.send(), and django.dispatch.dispatcher.Signal.send_robust().
django.dispatch.dispatcher.Signal.sender_receivers_cache
Definition at line 48 of file dispatcher.py.
Referenced by django.dispatch.dispatcher.Signal.send_robust().
django.dispatch.dispatcher.Signal.use_caching
Definition at line 42 of file dispatcher.py.
Referenced by django.dispatch.dispatcher.Signal.send_robust().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/dispatch/dispatcher.py