Django: django.template.loader.BaseLoader Class Reference
django.template.loader.BaseLoader Class Reference
Public Member Functions
def __init__ (self, args, kwargs)
def __call__
def load_template
def load_template_source
def reset (self)
Static Public Attributes
is_usable = False
Detailed Description
Definition at line 36 of file loader.py.
Constructor & Destructor Documentation
def django.template.loader.BaseLoader.__init__ (self, args, kwargs)
Definition at line 39 of file loader.py.
Member Function Documentation
def django.template.loader.BaseLoader.__call__ (self, template_name, template_dirs = None)
Definition at line 42 of file loader.py.
def django.template.loader.BaseLoader.load_template (self, template_name, template_dirs = None)
Definition at line 45 of file loader.py.
References django.template.loader.get_template_from_string(), django.template.loader.BaseLoader.load_template_source(), and django.template.loader.make_origin().
def django.template.loader.BaseLoader.load_template_source (self, template_name, template_dirs = None)
Returns a tuple containing the source and origin for the given template
name.
Definition at line 58 of file loader.py.
Referenced by django.template.loader.BaseLoader.load_template().
def django.template.loader.BaseLoader.reset (self)
Resets any state maintained by the loader instance (e.g., cached
templates or cached loader modules).
Definition at line 66 of file loader.py.
Member Data Documentation
django.template.loader.BaseLoader.is_usable = False static
Definition at line 37 of file loader.py.
Referenced by django.db.backends.BaseDatabaseWrapper.close_if_unusable_or_obsolete().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/template/loader.py