Django: django.db.models.query Namespace Reference
django.db.models.query Namespace Reference
Classes
class DateQuerySet
class DateTimeQuerySet
class EmptyQuerySet
class InstanceCheckMeta
class QuerySet
class RawQuerySet
class ValuesListQuerySet
class ValuesQuerySet
Functions
def get_klass_info
def get_cached_row
def insert_query
def prefetch_related_objects (result_cache, related_lookups)
def get_prefetcher (instance, attr)
def prefetch_one_level (instances, prefetcher, attname)
Variables
int REPR_OUTPUT_SIZE = 20
EmptyResultSet = sql.EmptyResultSet
Detailed Description
The main QuerySet implementation. This provides the public API for the ORM.
Function Documentation
def django.db.models.query.get_cached_row (row, index_start, using, klass_info, offset = 0, parent_data = ())
Helper function that recursively returns an object with the specified
related attributes already populated.
This method may be called recursively to populate deep select_related()
clauses.
Arguments:
     * row - the row of data returned by the database cursor
     * index_start - the index of the row at which data for this
       object is known to start
     * offset - the number of additional fields that are known to
       exist in row for `klass`. This usually means the number of
       annotated results on `klass`.
     * using - the database alias on which the query is being executed.
     * klass_info - result of the get_klass_info function
     * parent_data - parent model data in format (field, value). Used
       to populate the non-local fields of child models.
Definition at line 1269 of file query.py.
Referenced by django.db.models.query.get_klass_info(), and django.db.models.query.QuerySet.iterator().
def django.db.models.query.get_klass_info (klass, max_depth = 0, cur_depth = 0, requested = None, only_load = None, from_parent = None)
Helper function that recursively returns an information for a klass, to be
used in get_cached_row.  It exists just to compute this information only
once for entire queryset. Otherwise it would be computed for each row, which
leads to poor perfomance on large querysets.
Arguments:
 * klass - the class to retrieve (and instantiate)
 * max_depth - the maximum depth to which a select_related()
   relationship should be explored.
 * cur_depth - the current depth in the select_related() tree.
   Used in recursive calls to determin if we should dig deeper.
 * requested - A dictionary describing the select_related() tree
   that is to be retrieved. keys are field names; values are
   dictionaries describing the keys on that related object that
   are themselves to be select_related().
 * only_load - if the query has had only() or defer() applied,
   this is the list of field names that will be returned. If None,
   the full field list for `klass` can be assumed.
 * from_parent - the parent model used to get to this model
Note that when travelling from parent to child, we will only load child
fields which aren't in the parent.
Definition at line 1154 of file query.py.
References django.db.models.query_utils.deferred_class_factory(), django.db.models.query.get_cached_row(), and django.db.models.query_utils.select_related_descend().
Referenced by django.db.models.query.QuerySet.iterator().
def django.db.models.query.get_prefetcher (instance, attr)
For the attribute 'attr' on the given instance, finds
an object that has a get_prefetch_queryset().
Returns a 4 tuple containing:
(the object with get_prefetch_queryset (or None),
 the descriptor object representing this relationship (or None),
 a boolean that is False if the attribute was not found at all,
 a boolean that is True if the attribute has already been fetched)
Definition at line 1633 of file query.py.
Referenced by django.db.models.query.prefetch_related_objects().
def django.db.models.query.insert_query (model, objs, fields, return_id = False, raw = False, using = None)
Inserts a new record for the given model. This provides an interface to
the InsertQuery class and is how Model.save() is implemented. It is not
part of the public API.
Definition at line 1506 of file query.py.
Referenced by django.db.models.manager.Manager.exists().
def django.db.models.query.prefetch_one_level (instances, prefetcher, attname)
Helper function for prefetch_related_objects
Runs prefetches on all instances using the prefetcher object,
assigning results to relevant caches in instance.
The prefetched objects are returned, along with any additional
prefetches that must be done due to prefetch_related lookups
found from default managers.
Definition at line 1676 of file query.py.
Referenced by django.db.models.query.prefetch_related_objects().
def django.db.models.query.prefetch_related_objects (result_cache, related_lookups)
Helper function for prefetch_related functionality
Populates prefetched objects caches for a list of results
from a QuerySet
Definition at line 1517 of file query.py.
References django.db.models.query.get_prefetcher(), and django.db.models.query.prefetch_one_level().
Referenced by django.db.models.query.QuerySet.exists().
Variable Documentation
django.db.models.query.EmptyResultSet = sql.EmptyResultSet
Definition at line 27 of file query.py.
int django.db.models.query.REPR_OUTPUT_SIZE = 20
Definition at line 24 of file query.py.