Django: django.core.files.uploadedfile.InMemoryUploadedFile Class Reference
django.core.files.uploadedfile.InMemoryUploadedFile Class Reference
Public Member Functions
def __init__ (self, file, field_name, name, content_type, size, charset)
def open
def close (self)
def chunks
def multiple_chunks
Public Member Functions inherited from django.core.files.uploadedfile.UploadedFile
def __init__
def __repr__ (self)
Public Member Functions inherited from django.core.files.base.File
def __init__
def __str__ (self)
def __repr__ (self)
def __bool__ (self)
def __nonzero__ (self)
def __len__ (self)
def chunks
def multiple_chunks
def __iter__ (self)
def __enter__ (self)
def __exit__ (self, exc_type, exc_value, tb)
def open
def close (self)
Public Member Functions inherited from django.core.files.utils.FileProxyMixin
def __iter__ (self)
Public Attributes
field_name
Public Attributes inherited from django.core.files.uploadedfile.UploadedFile
size
content_type
charset
Public Attributes inherited from django.core.files.base.File
file
name
mode
Additional Inherited Members
Static Public Attributes inherited from django.core.files.uploadedfile.UploadedFile
int DEFAULT_CHUNK_SIZE = 64
Static Public Attributes inherited from django.core.files.base.File
int DEFAULT_CHUNK_SIZE = 64
Properties inherited from django.core.files.uploadedfile.UploadedFile
name = property(_get_name, _set_name)
Properties inherited from django.core.files.base.File
size = property(_get_size, _set_size)
closed = property(_get_closed)
Properties inherited from django.core.files.utils.FileProxyMixin
encoding = property(lambda self: self.file.encoding)
fileno = property(lambda self: self.file.fileno)
flush = property(lambda self: self.file.flush)
isatty = property(lambda self: self.file.isatty)
newlines = property(lambda self: self.file.newlines)
read = property(lambda self: self.file.read)
readinto = property(lambda self: self.file.readinto)
readline = property(lambda self: self.file.readline)
readlines = property(lambda self: self.file.readlines)
seek = property(lambda self: self.file.seek)
softspace = property(lambda self: self.file.softspace)
tell = property(lambda self: self.file.tell)
truncate = property(lambda self: self.file.truncate)
write = property(lambda self: self.file.write)
writelines = property(lambda self: self.file.writelines)
xreadlines = property(lambda self: self.file.xreadlines)
Detailed Description
A file uploaded into memory (i.e. stream-to-memory).
Definition at line 82 of file uploadedfile.py.
Constructor & Destructor Documentation
def django.core.files.uploadedfile.InMemoryUploadedFile.__init__ (self, file, field_name, name, content_type, size, charset)
Definition at line 86 of file uploadedfile.py.
Member Function Documentation
def django.core.files.uploadedfile.InMemoryUploadedFile.chunks (self, chunk_size = None)
Definition at line 96 of file uploadedfile.py.
def django.core.files.uploadedfile.InMemoryUploadedFile.close (self)
Definition at line 93 of file uploadedfile.py.
Referenced by django.utils.archive.Archive.__exit__(), django.db.backends.BaseDatabaseWrapper.close_if_unusable_or_obsolete(), django.core.servers.basehttp.ServerHandler.finish_response(), django.core.mail.backends.console.EmailBackend.send_messages(), django.core.mail.backends.smtp.EmailBackend.send_messages(), and django.db.backends.BaseDatabaseWrapper.temporary_connection().
def django.core.files.uploadedfile.InMemoryUploadedFile.multiple_chunks (self, chunk_size = None)
Definition at line 100 of file uploadedfile.py.
def django.core.files.uploadedfile.InMemoryUploadedFile.open (self, mode = None)
Definition at line 90 of file uploadedfile.py.
Referenced by django.contrib.staticfiles.storage.CachedFilesMixin.hashed_name(), django.core.mail.backends.console.EmailBackend.send_messages(), and django.core.mail.backends.smtp.EmailBackend.send_messages().
Member Data Documentation
django.core.files.uploadedfile.InMemoryUploadedFile.field_name
Definition at line 88 of file uploadedfile.py.
Referenced by django.db.models.query_utils.DeferredAttribute.__get__(), django.db.models.query_utils.DeferredAttribute.__set__(), django.core.files.uploadhandler.MemoryFileUploadHandler.file_complete(), django.db.models.fields.related.ManyToOneRel.get_related_field(), and django.db.models.fields.related.ManyToOneRel.set_field_name().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/core/files/uploadedfile.py