Django: django.utils.html Namespace Reference
django.utils.html Namespace Reference
Functions
def escape (text)
Variables
list TRAILING_PUNCTUATION = ['.', ',', ':', ';', '.)']
list WRAPPING_PUNCTUATION = [('(', ')'), ('<', '>'), ('[', ']'), ('&lt;', '&gt;')]
list DOTS = ['&middot;', '*', '\u2022', '&#149;', '&bull;', '&#8226;']
tuple unencoded_ampersands_re = re.compile(r'&(?!(\w+|#\d+);)')
tuple word_split_re = re.compile(r'(\s+)')
tuple simple_url_re = re.compile(r'^https?://\[?\w', re.IGNORECASE)
tuple simple_url_2_re = re.compile(r'^www\.|^(?!http)\w[^@]+\.(com|edu|gov|int|mil|net|org)$', re.IGNORECASE)
tuple simple_email_re = re.compile(r'^\S+@\S+\.\S+$')
tuple link_target_attribute_re = re.compile(r'(<a [^>]*?)target=[^\s>]+')
tuple html_gunk_re = re.compile(r'(?:<br clear="all">|<i><\/i>|<b><\/b>|<em><\/em>|<strong><\/strong>|<\/?smallcaps>|<\/?uppercase>)', re.IGNORECASE)
tuple hard_coded_bullets_re = re.compile(r'((?:<p>(?:%s).*?[a-zA-Z].*?</p>\s*)+)' % '|'.join([re.escape(x) for x in DOTS]), re.DOTALL)
tuple trailing_empty_content_re = re.compile(r'(?:<p>(?:&nbsp;|\s|<br \/>)*?</p>\s*)+\Z')
tuple escape = allow_lazy(escape, six.text_type)
Detailed Description
HTML utilities suitable for global use.
Function Documentation
def django.utils.html.escape (text)
Returns the given text with ampersands, quotes and angle brackets encoded for use in HTML.
Definition at line 35 of file html.py.
References django.utils.html.escape, django.utils.encoding.force_text(), and django.utils.safestring.mark_safe().
Variable Documentation
list django.utils.html.DOTS = ['&middot;', '*', '\u2022', '&#149;', '&bull;', '&#8226;']
Definition at line 22 of file html.py.
tuple django.utils.html.escape = allow_lazy(escape, six.text_type)
Definition at line 40 of file html.py.
Referenced by django.contrib.admin.options.ModelAdmin.change_view(), django.contrib.admin.options.ModelAdmin.delete_view(), django.utils.html.escape(), django.template.defaultfilters.force_escape(), django.views.debug.ExceptionReporter.get_template_exception_info(), django.contrib.humanize.tests.HumanizeTests.humanize_tester(), django.contrib.syndication.views.Feed.item_title(), django.contrib.admin.widgets.ForeignKeyRawIdWidget.label_for_value(), django.template.defaultfilters.linebreaksbr(), django.template.defaultfilters.linenumbers(), django.contrib.comments.views.comments.post_comment(), django.template.debug.DebugVariableNode.render(), django.template.base.render_value_in_context(), django.contrib.admin.options.ModelAdmin.response_add(), django.contrib.gis.tests.test_geoforms.CustomGeometryWidgetTest.test_custom_serialization_widget(), and django.contrib.auth.admin.UserAdmin.user_change_password().
tuple django.utils.html.hard_coded_bullets_re = re.compile(r'((?:<p>(?:%s).*?[a-zA-Z].*?</p>\s*)+)' % '|'.join([re.escape(x) for x in DOTS]), re.DOTALL)
Definition at line 31 of file html.py.
tuple django.utils.html.html_gunk_re = re.compile(r'(?:<br clear="all">|<i><\/i>|<b><\/b>|<em><\/em>|<strong><\/strong>|<\/?smallcaps>|<\/?uppercase>)', re.IGNORECASE)
Definition at line 30 of file html.py.
tuple django.utils.html.link_target_attribute_re = re.compile(r'(<a [^>]*?)target=[^\s>]+')
Definition at line 29 of file html.py.
tuple django.utils.html.simple_email_re = re.compile(r'^\S+@\S+\.\S+$')
Definition at line 28 of file html.py.
tuple django.utils.html.simple_url_2_re = re.compile(r'^www\.|^(?!http)\w[^@]+\.(com|edu|gov|int|mil|net|org)$', re.IGNORECASE)
Definition at line 27 of file html.py.
tuple django.utils.html.simple_url_re = re.compile(r'^https?://\[?\w', re.IGNORECASE)
Definition at line 26 of file html.py.
tuple django.utils.html.trailing_empty_content_re = re.compile(r'(?:<p>(?:&nbsp;|\s|<br \/>)*?</p>\s*)+\Z')
Definition at line 32 of file html.py.
list django.utils.html.TRAILING_PUNCTUATION = ['.', ',', ':', ';', '.)']
Definition at line 18 of file html.py.
tuple django.utils.html.unencoded_ampersands_re = re.compile(r'&(?!(\w+|#\d+);)')
Definition at line 24 of file html.py.
tuple django.utils.html.word_split_re = re.compile(r'(\s+)')
Definition at line 25 of file html.py.
list django.utils.html.WRAPPING_PUNCTUATION = [('(', ')'), ('<', '>'), ('[', ']'), ('&lt;', '&gt;')]
Definition at line 19 of file html.py.