Django: django.contrib.sessions.models.Session Class Reference
django.contrib.sessions.models.Session Class Reference
Classes
class Meta
Public Member Functions
def get_decoded (self)
Static Public Attributes
tuple session_key
tuple session_data = models.TextField(_('session data'))
tuple expire_date = models.DateTimeField(_('expire date'), db_index=True)
tuple objects = SessionManager()
Detailed Description
Django provides full support for anonymous sessions. The session
framework lets you store and retrieve arbitrary data on a
per-site-visitor basis. It stores data on the server side and
abstracts the sending and receiving of cookies. Cookies contain a
session ID -- not the data itself.
The Django sessions framework is entirely cookie-based. It does
not fall back to putting session IDs in URLs. This is an intentional
design decision. Not only does that behavior make URLs ugly, it makes
your site vulnerable to session-ID theft via the "Referer" header.
For complete documentation on using Sessions in your code, consult
the sessions documentation that is shipped with Django (also available
on the Django Web site).
Definition at line 21 of file models.py.
Member Function Documentation
def django.contrib.sessions.models.Session.get_decoded (self)
Definition at line 49 of file models.py.
References django.contrib.sessions.models.Session.session_data.
Member Data Documentation
tuple django.contrib.sessions.models.Session.expire_date = models.DateTimeField(_('expire date'), db_index=True) static
Definition at line 41 of file models.py.
tuple django.contrib.sessions.models.Session.objects = SessionManager() static
Definition at line 42 of file models.py.
Referenced by django.core.serializers.pyyaml.Serializer.end_serialization(), and django.core.serializers.python.Serializer.getvalue().
tuple django.contrib.sessions.models.Session.session_data = models.TextField(_('session data')) static
Definition at line 40 of file models.py.
Referenced by django.contrib.sessions.models.Session.get_decoded().
tuple django.contrib.sessions.models.Session.session_key static
Initial value:
 = models.CharField(_('session key'), max_length=40,
                                    primary_key=True)
Definition at line 38 of file models.py.
Referenced by django.contrib.sessions.backends.cached_db.SessionStore.delete(), django.contrib.sessions.backends.cached_db.SessionStore.flush(), and django.contrib.sessions.backends.cached_db.SessionStore.load().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/sessions/models.py