Django: django.db.utils Namespace Reference
django.db.utils Namespace Reference
Classes
class ConnectionDoesNotExist
class ConnectionHandler
class ConnectionRouter
class DatabaseError
class DatabaseErrorWrapper
class DataError
class Error
class IntegrityError
class InterfaceError
class InternalError
class NotSupportedError
class OperationalError
class ProgrammingError
Functions
def load_backend (backend_name)
Variables
string DEFAULT_DB_ALIAS = 'default'
Function Documentation
def django.db.utils.load_backend (backend_name)
Definition at line 110 of file utils.py.
References django.utils.importlib.import_module(), django.template.defaultfilters.join(), and django.utils._os.upath().
Referenced by django.db.utils.ConnectionHandler.__getitem__().
Variable Documentation
string django.db.utils.DEFAULT_DB_ALIAS = 'default'
Definition at line 16 of file utils.py.