Django: django.contrib.sessions.management.commands.clearsessions.Command Class Reference
django.contrib.sessions.management.commands.clearsessions.Command Class Reference
Public Member Functions
def handle_noargs (self, options)
Public Member Functions inherited from django.core.management.base.NoArgsCommand
def handle (self, args, options)
def handle_noargs (self, options)
Public Member Functions inherited from django.core.management.base.BaseCommand
def __init__ (self)
def get_version (self)
def usage (self, subcommand)
def create_parser (self, prog_name, subcommand)
def print_help (self, prog_name, subcommand)
def run_from_argv (self, argv)
def execute (self, args, options)
def validate
def handle (self, args, options)
Static Public Attributes
string help = "Can be run as a cronjob or directly to clean out expired sessions (only with the database backend at the moment)."
Static Public Attributes inherited from django.core.management.base.NoArgsCommand
string args = ''
Static Public Attributes inherited from django.core.management.base.BaseCommand
tuple option_list
string help = ''
string args = ''
can_import_settings = True
requires_model_validation = True
output_transaction = False
leave_locale_alone = False
Additional Inherited Members
Public Attributes inherited from django.core.management.base.BaseCommand
style
stdout
stderr
Detailed Description
Definition at line 6 of file clearsessions.py.
Member Function Documentation
def django.contrib.sessions.management.commands.clearsessions.Command.handle_noargs (self, options)
Definition at line 9 of file clearsessions.py.
References django.utils.importlib.import_module().
Referenced by django.core.management.base.NoArgsCommand.handle().
Member Data Documentation
string django.contrib.sessions.management.commands.clearsessions.Command.help = "Can be run as a cronjob or directly to clean out expired sessions (only with the database backend at the moment)." static
Definition at line 7 of file clearsessions.py.
Referenced by django.core.management.base.BaseCommand.usage().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/sessions/management/commands/clearsessions.py