Django: django.contrib.gis.geoip.tests.GeoIPTest Class Reference
django.contrib.gis.geoip.tests.GeoIPTest Class Reference
Public Member Functions
def test01_init (self)
def test02_bad_query (self)
def test03_country (self)
def test04_city (self)
def test05_unicode_response (self)
Detailed Description
Definition at line 28 of file tests.py.
Member Function Documentation
def django.contrib.gis.geoip.tests.GeoIPTest.test01_init (self)
Definition at line 30 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.geoip.tests.GeoIPTest.test02_bad_query (self)
Definition at line 59 of file tests.py.
References django.utils.unittest.case.TestCase.assertRaises().
def django.contrib.gis.geoip.tests.GeoIPTest.test03_country (self)
Definition at line 70 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.skipUnless().
def django.contrib.gis.geoip.tests.GeoIPTest.test04_city (self)
Definition at line 86 of file tests.py.
References django.utils.unittest.case.TestCase.assertAlmostEqual(), django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertTrue().
def django.contrib.gis.geoip.tests.GeoIPTest.test05_unicode_response (self)
Definition at line 116 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/geoip/tests.py