Django: django.views.debug Namespace Reference
django.views.debug Namespace Reference
Classes
class ExceptionReporter
class ExceptionReporterFilter
class SafeExceptionReporterFilter
Functions
def linebreak_iter (template_source)
def cleanse_setting (key, value)
def get_safe_settings ()
def technical_500_response (request, exc_type, exc_value, tb)
def get_exception_reporter_filter (request)
def technical_404_response (request, exception)
def default_urlconf (request)
Variables
tuple HIDDEN_SETTINGS = re.compile('API|TOKEN|KEY|SECRET|PASS|PROFANITIES_LIST|SIGNATURE')
string CLEANSED_SUBSTITUTE = '********************'
default_exception_reporter_filter = None
string TECHNICAL_500_TEMPLATE
string TECHNICAL_500_TEXT_TEMPLATE
string TECHNICAL_404_TEMPLATE
string DEFAULT_URLCONF_TEMPLATE
Function Documentation
def django.views.debug.cleanse_setting (key, value)
Cleanse an individual setting key/value of sensitive content.
If the value is a dictionary, recursively cleanse the keys in
that dictionary.
Definition at line 32 of file debug.py.
Referenced by django.views.debug.get_safe_settings().
def django.views.debug.default_urlconf (request)
Definition at line 493 of file debug.py.
Referenced by django.views.debug.technical_404_response().
def django.views.debug.get_exception_reporter_filter (request)
Definition at line 75 of file debug.py.
References django.utils.module_loading.import_by_path().
Referenced by django.utils.log.AdminEmailHandler.emit().
def django.views.debug.get_safe_settings ()
Definition at line 51 of file debug.py.
References django.views.debug.cleanse_setting().
Referenced by django.views.debug.ExceptionReporter.get_traceback_data(), and django.views.debug.technical_404_response().
def django.views.debug.linebreak_iter (template_source)
Definition at line 24 of file debug.py.
Referenced by django.views.debug.ExceptionReporter.get_template_exception_info().
def django.views.debug.technical_404_response (request, exception)
Definition at line 463 of file debug.py.
References django.views.debug.default_urlconf(), django.utils.encoding.force_bytes(), and django.views.debug.get_safe_settings().
def django.views.debug.technical_500_response (request, exc_type, exc_value, tb)
Create a technical server error response. The last three arguments are
the values returned from sys.exc_info() and friends.
Definition at line 59 of file debug.py.
Variable Documentation
string django.views.debug.CLEANSED_SUBSTITUTE = '********************'
Definition at line 22 of file debug.py.
django.views.debug.default_exception_reporter_filter = None
Definition at line 73 of file debug.py.
string django.views.debug.DEFAULT_URLCONF_TEMPLATE
Definition at line 1102 of file debug.py.
tuple django.views.debug.HIDDEN_SETTINGS = re.compile('API|TOKEN|KEY|SECRET|PASS|PROFANITIES_LIST|SIGNATURE')
Definition at line 20 of file debug.py.
string django.views.debug.TECHNICAL_404_TEMPLATE
Definition at line 1030 of file debug.py.
string django.views.debug.TECHNICAL_500_TEMPLATE
Definition at line 504 of file debug.py.
string django.views.debug.TECHNICAL_500_TEXT_TEMPLATE
Definition at line 969 of file debug.py.