Django: django.contrib.gis.sitemaps.georss.GeoRSSSitemap Class Reference
django.contrib.gis.sitemaps.georss.GeoRSSSitemap Class Reference
Public Member Functions
def __init__
def get_urls
def items (self)
def location (self, obj)
Public Member Functions inherited from django.contrib.sitemaps.Sitemap
def items (self)
def location (self, obj)
def get_urls
Public Attributes
feed_dict
locations
Additional Inherited Members
Static Public Attributes inherited from django.contrib.sitemaps.Sitemap
int limit = 50000
protocol = None
Properties inherited from django.contrib.sitemaps.Sitemap
paginator = property(_get_paginator)
Detailed Description
A minimal hook to produce sitemaps for GeoRSS feeds.
Definition at line 4 of file georss.py.
Constructor & Destructor Documentation
def django.contrib.gis.sitemaps.georss.GeoRSSSitemap.__init__ (self, feed_dict, slug_dict = None)
This sitemap object initializes on a feed dictionary (as would be passed
to `django.contrib.gis.views.feed`) and a slug dictionary.
If the slug dictionary is not defined, then it's assumed the keys provide
the URL parameter to the feed.  However, if you have a complex feed (e.g.,
you override `get_object`, then you'll need to provide a slug dictionary.
The slug dictionary should have the same keys as the feed dictionary, but
each value in the slug dictionary should be a sequence of slugs that may
be used for valid feeds.  For example, let's say we have a feed that
returns objects for a specific ZIP code in our feed dictionary:
    feed_dict = {'zipcode' : ZipFeed}
Then we would use a slug dictionary with a list of the zip code slugs
corresponding to feeds you want listed in the sitemap:
    slug_dict = {'zipcode' : ['77002', '77054']}
Definition at line 8 of file georss.py.
Member Function Documentation
def django.contrib.gis.sitemaps.georss.GeoRSSSitemap.get_urls (self, page = 1, site = None)
This method is overrridden so the appropriate `geo_format` attribute
is placed on each URL element.
Definition at line 39 of file georss.py.
def django.contrib.gis.sitemaps.georss.GeoRSSSitemap.items (self)
Definition at line 48 of file georss.py.
References django.contrib.gis.sitemaps.georss.GeoRSSSitemap.locations.
Referenced by django.forms.util.ErrorDict.as_text(), django.forms.util.ErrorDict.as_ul(), and django.contrib.sitemaps.Sitemap.location().
def django.contrib.gis.sitemaps.georss.GeoRSSSitemap.location (self, obj)
Definition at line 51 of file georss.py.
Member Data Documentation
django.contrib.gis.sitemaps.georss.GeoRSSSitemap.feed_dict
Definition at line 28 of file georss.py.
django.contrib.gis.sitemaps.georss.GeoRSSSitemap.locations
Definition at line 29 of file georss.py.
Referenced by django.contrib.staticfiles.finders.FileSystemFinder.find(), django.contrib.gis.sitemaps.georss.GeoRSSSitemap.items(), django.contrib.gis.sitemaps.kml.KMLSitemap.items(), and django.contrib.staticfiles.finders.FileSystemFinder.list().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/sitemaps/georss.py