Django: django.db.backends.oracle.base Namespace Reference
django.db.backends.oracle.base Namespace Reference
Classes
class _UninitializedOperatorsDescriptor
class CursorIterator
class DatabaseFeatures
class DatabaseOperations
class DatabaseWrapper
class FormatStylePlaceholderCursor
class InsertIdVar
class Oracle_datetime
class OracleParam
class VariableWrapper
Functions
def to_unicode (s)
Variables
pytz = None
DatabaseError = Database.DatabaseError
IntegrityError = Database.IntegrityError
convert_unicode = force_text
Detailed Description
Oracle database backend for Django.
Requires cx_Oracle: http://cx-oracle.sourceforge.net/
Function Documentation
def django.db.backends.oracle.base.to_unicode (s)
Convert strings to Unicode objects (and return all other data types
unchanged).
Definition at line 966 of file base.py.
References django.utils.encoding.force_text().
Referenced by django.db.backends.oracle.base.CursorIterator.__next__(), django.utils.feedgenerator.SyndicationFeed.add_item(), and django.db.backends.BaseDatabaseOperations.last_executed_query().
Variable Documentation
django.db.backends.oracle.base.convert_unicode = force_text
Definition at line 68 of file base.py.
Referenced by django.db.backends.oracle.base.DatabaseWrapper.get_new_connection(), django.db.backends.oracle.base.DatabaseOperations.savepoint_create_sql(), and django.db.backends.oracle.base.DatabaseOperations.savepoint_rollback_sql().
django.db.backends.oracle.base.DatabaseError = Database.DatabaseError
Definition at line 60 of file base.py.
django.db.backends.oracle.base.IntegrityError = Database.IntegrityError
Definition at line 61 of file base.py.
django.db.backends.oracle.base.pytz = None
Definition at line 50 of file base.py.