Django: django.contrib.webdesign.tests.WebdesignTest Class Reference
django.contrib.webdesign.tests.WebdesignTest Class Reference
Public Member Functions
def test_words (self)
def test_paragraphs (self)
def test_lorem_tag (self)
Detailed Description
Definition at line 10 of file tests.py.
Member Function Documentation
def django.contrib.webdesign.tests.WebdesignTest.test_lorem_tag (self)
Definition at line 19 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.webdesign.tests.WebdesignTest.test_paragraphs (self)
Definition at line 15 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.webdesign.lorem_ipsum.paragraphs().
def django.contrib.webdesign.tests.WebdesignTest.test_words (self)
Definition at line 12 of file tests.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.contrib.webdesign.lorem_ipsum.words().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/webdesign/tests.py