Django: django.contrib.gis.geos.prototypes.errcheck Namespace Reference
django.contrib.gis.geos.prototypes.errcheck Namespace Reference
Functions
def last_arg_byref (args)
ctypes error checking routines ###
def check_dbl (result, func, cargs)
def check_geom (result, func, cargs)
def check_minus_one (result, func, cargs)
def check_predicate (result, func, cargs)
def check_sized_string (result, func, cargs)
def check_string (result, func, cargs)
def check_zero (result, func, cargs)
Variables
tuple free = GEOSFunc('GEOSFree')
tuple libc = CDLL('msvcrt')
Detailed Description
 Error checking functions for GEOS ctypes prototype functions.
Function Documentation
def django.contrib.gis.geos.prototypes.errcheck.check_dbl (result, func, cargs)
Definition at line 33 of file errcheck.py.
References django.contrib.gis.geos.prototypes.errcheck.last_arg_byref().
def django.contrib.gis.geos.prototypes.errcheck.check_geom (result, func, cargs)
Definition at line 40 of file errcheck.py.
def django.contrib.gis.geos.prototypes.errcheck.check_minus_one (result, func, cargs)
Definition at line 46 of file errcheck.py.
def django.contrib.gis.geos.prototypes.errcheck.check_predicate (result, func, cargs)
Definition at line 53 of file errcheck.py.
def django.contrib.gis.geos.prototypes.errcheck.check_sized_string (result, func, cargs)
Error checking for routines that return explicitly sized strings.
This frees the memory allocated by GEOS at the result pointer.
Definition at line 61 of file errcheck.py.
References django.contrib.gis.geos.prototypes.errcheck.free, and django.contrib.gis.geos.prototypes.errcheck.last_arg_byref().
def django.contrib.gis.geos.prototypes.errcheck.check_string (result, func, cargs)
Error checking for routines that return strings.
This frees the memory allocated by GEOS at the result pointer.
Definition at line 77 of file errcheck.py.
References django.contrib.gis.geos.prototypes.errcheck.free.
def django.contrib.gis.geos.prototypes.errcheck.check_zero (result, func, cargs)
Definition at line 90 of file errcheck.py.
def django.contrib.gis.geos.prototypes.errcheck.last_arg_byref (args)
ctypes error checking routines ###
Definition at line 29 of file errcheck.py.
Referenced by django.contrib.gis.geos.prototypes.coordseq.check_cs_get(), django.contrib.gis.geos.prototypes.errcheck.check_dbl(), and django.contrib.gis.geos.prototypes.errcheck.check_sized_string().
Variable Documentation
django.contrib.gis.geos.prototypes.errcheck.free = GEOSFunc('GEOSFree')
Definition at line 15 of file errcheck.py.
Referenced by django.contrib.gis.geos.prototypes.errcheck.check_sized_string(), and django.contrib.gis.geos.prototypes.errcheck.check_string().
tuple django.contrib.gis.geos.prototypes.errcheck.libc = CDLL('msvcrt')
Definition at line 22 of file errcheck.py.