Django: django.core.serializers Namespace Reference
django.core.serializers Namespace Reference
Namespaces
base
json
python
pyyaml
xml_serializer
Classes
class BadSerializer
Functions
def register_serializer
def unregister_serializer (format)
def get_serializer (format)
def get_serializer_formats ()
def get_public_serializer_formats ()
def get_deserializer (format)
def serialize (format, queryset, options)
def deserialize (format, stream_or_string, options)
Variables
dictionary BUILTIN_SERIALIZERS
dictionary _serializers = {}
Detailed Description
Interfaces for serializing Django objects.
Usage::
    from django.core import serializers
    json = serializers.serialize("json", some_queryset)
    objects = list(serializers.deserialize("json", json))
To add your own serializers, use the SERIALIZATION_MODULES setting::
    SERIALIZATION_MODULES = {
"csv" : "path.to.csv.serializer",
"txt" : "path.to.txt.serializer",
    }
Function Documentation
def django.core.serializers.deserialize (format, stream_or_string, options)
Deserialize a stream or a string. Returns an iterator that yields ``(obj,
m2m_relation_dict)``, where ``obj`` is a instantiated -- but *unsaved* --
object, and ``m2m_relation_dict`` is a dictionary of ``{m2m_field_name :
list_of_related_objects}``.
Definition at line 125 of file __init__.py.
References django.core.serializers.get_deserializer(), and django.core.serializers.register_serializer().
Referenced by django.contrib.gis.tests.test_geoforms.CustomGeometryWidgetTest.test_custom_serialization_widget().
def django.core.serializers.get_deserializer (format)
Definition at line 109 of file __init__.py.
Referenced by django.core.serializers.deserialize().
def django.core.serializers.get_public_serializer_formats ()
Definition at line 104 of file __init__.py.
def django.core.serializers.get_serializer (format)
Definition at line 92 of file __init__.py.
Referenced by django.core.serializers.serialize().
def django.core.serializers.get_serializer_formats ()
Definition at line 99 of file __init__.py.
def django.core.serializers.register_serializer (format, serializer_module, serializers = None)
Register a new serializer.
``serializer_module`` should be the fully qualified module name
for the serializer.
If ``serializers`` is provided, the registration will be added
to the provided dictionary.
If ``serializers`` is not provided, the registration will be made
directly into the global register of serializers. Adding serializers
directly is not a thread-safe operation.
Definition at line 52 of file __init__.py.
Referenced by django.core.serializers.deserialize().
def django.core.serializers.serialize (format, queryset, options)
Serialize a queryset (or any iterator that returns database objects) using
a certain serializer.
Definition at line 116 of file __init__.py.
References django.core.serializers.get_serializer().
Referenced by django.contrib.gis.tests.test_geoforms.CustomGeometryWidgetTest.test_custom_serialization_widget().
def django.core.serializers.unregister_serializer (format)
Definition at line 84 of file __init__.py.
Variable Documentation
dictionary django.core.serializers._serializers = {}
Definition at line 32 of file __init__.py.
dictionary django.core.serializers.BUILTIN_SERIALIZERS
Initial value:
 = {
     "xml"    : "django.core.serializers.xml_serializer",
     "python" : "django.core.serializers.python",
     "json"   : "django.core.serializers.json",
     "yaml"   : "django.core.serializers.pyyaml",
 }
Definition at line 25 of file __init__.py.