Django: django.core.validators.URLValidator Class Reference
django.core.validators.URLValidator Class Reference
Public Member Functions
def __call__ (self, value)
Public Member Functions inherited from django.core.validators.RegexValidator
def __init__
def __call__ (self, value)
Static Public Attributes
tuple regex
tuple message = _('Enter a valid URL.')
Static Public Attributes inherited from django.core.validators.RegexValidator
string regex = ''
tuple message = _('Enter a valid value.')
string code = 'invalid'
Additional Inherited Members
Public Attributes inherited from django.core.validators.RegexValidator
regex
message
code
Detailed Description
Definition at line 42 of file validators.py.
Member Function Documentation
def django.core.validators.URLValidator.__call__ (self, value)
Definition at line 53 of file validators.py.
References django.utils.encoding.force_text().
Member Data Documentation
tuple django.core.validators.URLValidator.message = _('Enter a valid URL.') static
Definition at line 51 of file validators.py.
Referenced by django.core.validators.BaseValidator.__call__(), and django.test.testcases._AssertTemplateUsedContext.__exit__().
tuple django.core.validators.URLValidator.regex static
Initial value:
 = re.compile(
         r'^(?:http|ftp)s?://'  # http:// or https://
         r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}(?<!-)\.?)|'  # domain...
         r'localhost|'  # localhost...
         r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}|'  # ...or ipv4
         r'\[?[A-F0-9]*:[A-F0-9:]+\]?)'  # ...or ipv6
         r'(?::\d+)?'  # optional port
         r'(?:/?|[/?]\S+)$', re.IGNORECASE)
Definition at line 43 of file validators.py.
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/core/validators.py