Django: django.core.mail.message Namespace Reference
django.core.mail.message Namespace Reference
Classes
class BadHeaderError
class EmailMessage
class EmailMultiAlternatives
class MIMEMixin
class SafeMIMEMultipart
class SafeMIMEText
Functions
def make_msgid
def forbid_multi_line_headers (name, val, encoding)
def sanitize_address (addr, encoding)
Variables
tuple utf8_charset = Charset.Charset('utf-8')
string DEFAULT_ATTACHMENT_MIME_TYPE = 'application/octet-stream'
tuple ADDRESS_HEADERS
Function Documentation
def django.core.mail.message.forbid_multi_line_headers (name, val, encoding)
Forbids multi-line headers, to prevent header injection.
Definition at line 81 of file message.py.
References django.utils.encoding.force_text(), django.template.defaultfilters.join(), and django.core.mail.message.sanitize_address().
Referenced by django.core.mail.message.SafeMIMEText.__setitem__(), and django.core.mail.message.SafeMIMEMultipart.__setitem__().
def django.core.mail.message.make_msgid (idstring = None)
Returns a string suitable for RFC 2822 compliant Message-ID, e.g:
<20020201195627.33539.96671@nightshade.la.mastaler.com>
Optional idstring if given is a string used to strengthen the
uniqueness of the message id.
Definition at line 40 of file message.py.
Referenced by django.core.mail.message.EmailMessage.message().
def django.core.mail.message.sanitize_address (addr, encoding)
Definition at line 101 of file message.py.
References django.utils.encoding.force_text(), and django.template.defaultfilters.join().
Referenced by django.core.mail.message.forbid_multi_line_headers(), and django.core.mail.backends.smtp.EmailBackend.send_messages().
Variable Documentation
tuple django.core.mail.message.ADDRESS_HEADERS
Initial value:
 = set([
     'from',
     'sender',
     'reply-to',
     'to',
     'cc',
     'bcc',
     'resent-from',
     'resent-sender',
     'resent-to',
     'resent-cc',
     'resent-bcc',
 ])
Definition at line 66 of file message.py.
string django.core.mail.message.DEFAULT_ATTACHMENT_MIME_TYPE = 'application/octet-stream'
Definition at line 30 of file message.py.
tuple django.core.mail.message.utf8_charset = Charset.Charset('utf-8')
Definition at line 24 of file message.py.