Django: django.contrib.gis.gdal.tests.test_srs.SpatialRefTest Class Reference
django.contrib.gis.gdal.tests.test_srs.SpatialRefTest Class Reference
Public Member Functions
def test01_wkt (self)
def test02_bad_wkt (self)
def test03_get_wkt (self)
def test04_proj (self)
def test05_epsg (self)
def test07_boolean_props (self)
def test08_angular_linear (self)
def test09_authority (self)
def test10_attributes (self)
def test11_wellknown (self)
def test12_coordtransform (self)
def test13_attr_value (self)
Detailed Description
Definition at line 55 of file test_srs.py.
Member Function Documentation
def django.contrib.gis.gdal.tests.test_srs.SpatialRefTest.test01_wkt (self)
Definition at line 57 of file test_srs.py.
def django.contrib.gis.gdal.tests.test_srs.SpatialRefTest.test02_bad_wkt (self)
Definition at line 62 of file test_srs.py.
References django.utils.unittest.case.TestCase.fail().
def django.contrib.gis.gdal.tests.test_srs.SpatialRefTest.test03_get_wkt (self)
Definition at line 73 of file test_srs.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_srs.SpatialRefTest.test04_proj (self)
Definition at line 79 of file test_srs.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_srs.SpatialRefTest.test05_epsg (self)
Definition at line 87 of file test_srs.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_srs.SpatialRefTest.test07_boolean_props (self)
Definition at line 99 of file test_srs.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_srs.SpatialRefTest.test08_angular_linear (self)
Definition at line 106 of file test_srs.py.
References django.utils.unittest.case.TestCase.assertAlmostEqual(), and django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_srs.SpatialRefTest.test09_authority (self)
Definition at line 115 of file test_srs.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_srs.SpatialRefTest.test10_attributes (self)
Definition at line 124 of file test_srs.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_srs.SpatialRefTest.test11_wellknown (self)
Definition at line 133 of file test_srs.py.
References django.utils.unittest.case.TestCase.assertEqual().
def django.contrib.gis.gdal.tests.test_srs.SpatialRefTest.test12_coordtransform (self)
Definition at line 147 of file test_srs.py.
def django.contrib.gis.gdal.tests.test_srs.SpatialRefTest.test13_attr_value (self)
Definition at line 154 of file test_srs.py.
References django.utils.unittest.case.TestCase.assertEqual(), and django.utils.unittest.case.TestCase.assertRaises().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/gis/gdal/tests/test_srs.py