Django: django.contrib.admindocs.utils Namespace Reference
django.contrib.admindocs.utils Namespace Reference
Functions
def trim_docstring (docstring)
def parse_docstring (docstring)
def parse_rst
def create_reference_role (rolename, urlbase)
def default_reference_role
Variables
docutils_is_available = False
dictionary ROLES
Function Documentation
def django.contrib.admindocs.utils.create_reference_role (rolename, urlbase)
Definition at line 86 of file utils.py.
Referenced by django.contrib.admindocs.utils.default_reference_role().
def django.contrib.admindocs.utils.default_reference_role (name, rawtext, text, lineno, inliner, options = None, content = None)
Definition at line 94 of file utils.py.
References django.contrib.admindocs.utils.create_reference_role().
def django.contrib.admindocs.utils.parse_docstring (docstring)
Parse out the parts of a docstring.  Returns (title, body, metadata).
Definition at line 33 of file utils.py.
References django.template.defaultfilters.join(), and django.contrib.admindocs.utils.trim_docstring().
def django.contrib.admindocs.utils.parse_rst (text, default_reference_context, thing_being_parsed = None)
Convert the string from reST to an XHTML fragment.
Definition at line 58 of file utils.py.
References django.utils.encoding.force_bytes(), django.utils.safestring.mark_safe(), and django.db.models.fields.related.reverse.
def django.contrib.admindocs.utils.trim_docstring (docstring)
Uniformly trims leading/trailing whitespace from docstrings.
Based on http://www.python.org/peps/pep-0257.html#handling-docstring-indentation
Definition at line 19 of file utils.py.
References django.template.defaultfilters.join().
Referenced by django.contrib.admindocs.utils.parse_docstring().
Variable Documentation
django.contrib.admindocs.utils.docutils_is_available = False
Definition at line 15 of file utils.py.
dictionary django.contrib.admindocs.utils.ROLES
Initial value:
 = {
     'model'    : '%s/models/%s/',
     'view'     : '%s/views/%s/',
     'template' : '%s/templates/%s/',
     'filter'   : '%s/filters/#%s',
     'tag'      : '%s/tags/#%s',
 }
Definition at line 78 of file utils.py.