Django: django.utils.translation Namespace Reference
django.utils.translation Namespace Reference
Namespaces
trans_null
trans_real
Classes
class override
class Trans
class TranslatorCommentWarning
Functions
def gettext_noop (message)
def gettext (message)
def ngettext (singular, plural, number)
def ugettext (message)
def ungettext (singular, plural, number)
def pgettext (context, message)
def npgettext (context, singular, plural, number)
def lazy_number (func, resultclass, number=None, kwargs)
def ngettext_lazy
def ungettext_lazy
def npgettext_lazy
def activate (language)
def deactivate ()
def get_language ()
def get_language_bidi ()
def check_for_language (lang_code)
def to_locale (language)
def get_language_from_request
def get_language_from_path
def templatize
def deactivate_all ()
def get_language_info (lang_code)
Variables
list __all__
tuple _trans = Trans()
ugettext_noop = gettext_noop
tuple gettext_lazy = lazy(gettext, str)
tuple ugettext_lazy = lazy(ugettext, six.text_type)
tuple pgettext_lazy = lazy(pgettext, six.text_type)
tuple string_concat = lazy(_string_concat, six.text_type)
Detailed Description
Internationalization support.
Function Documentation
def django.utils.translation.activate (language)
Definition at line 129 of file __init__.py.
Referenced by django.utils.translation.override.__enter__(), and django.utils.translation.override.__exit__().
def django.utils.translation.check_for_language (lang_code)
Definition at line 159 of file __init__.py.
def django.utils.translation.deactivate ()
Definition at line 132 of file __init__.py.
def django.utils.translation.deactivate_all ()
Definition at line 174 of file __init__.py.
References django.utils.encoding.force_text(), and django.template.defaultfilters.join().
Referenced by django.utils.translation.override.__enter__(), and django.db.models.options.Options.verbose_name_raw().
def django.utils.translation.get_language ()
Definition at line 153 of file __init__.py.
def django.utils.translation.get_language_bidi ()
Definition at line 156 of file __init__.py.
def django.utils.translation.get_language_from_path (path, supported = None)
Definition at line 168 of file __init__.py.
def django.utils.translation.get_language_from_request (request, check_path = False)
Definition at line 165 of file __init__.py.
def django.utils.translation.get_language_info (lang_code)
Definition at line 185 of file __init__.py.
def django.utils.translation.gettext (message)
Definition at line 69 of file __init__.py.
def django.utils.translation.gettext_noop (message)
Definition at line 64 of file __init__.py.
def django.utils.translation.lazy_number (func, resultclass, number = None, kwargs)
Definition at line 91 of file __init__.py.
References django.utils.functional.lazy().
Referenced by django.utils.translation.ngettext_lazy(), django.utils.translation.npgettext_lazy(), and django.utils.translation.ungettext_lazy().
def django.utils.translation.ngettext (singular, plural, number)
Definition at line 72 of file __init__.py.
def django.utils.translation.ngettext_lazy (singular, plural, number = None)
Definition at line 120 of file __init__.py.
References django.utils.translation.lazy_number().
def django.utils.translation.npgettext (context, singular, plural, number)
Definition at line 84 of file __init__.py.
def django.utils.translation.npgettext_lazy (context, singular, plural, number = None)
Definition at line 126 of file __init__.py.
References django.utils.translation.lazy_number().
def django.utils.translation.pgettext (context, message)
Definition at line 81 of file __init__.py.
Referenced by django.utils.text.Truncator.add_truncation_text(), and django.contrib.humanize.templatetags.humanize.naturaltime().
def django.utils.translation.templatize (src, origin = None)
Definition at line 171 of file __init__.py.
Referenced by django.core.management.commands.makemessages.TranslatableFile.process().
def django.utils.translation.to_locale (language)
Definition at line 162 of file __init__.py.
Referenced by django.views.i18n.get_javascript_catalog(), django.utils.formats.iter_format_modules(), and django.views.i18n.javascript_catalog().
def django.utils.translation.ugettext (message)
Definition at line 75 of file __init__.py.
def django.utils.translation.ungettext (singular, plural, number)
Definition at line 78 of file __init__.py.
def django.utils.translation.ungettext_lazy (singular, plural, number = None)
Definition at line 123 of file __init__.py.
References django.utils.translation.lazy_number().
Referenced by django.contrib.comments.admin.CommentsAdmin.approve_comments(), django.contrib.comments.admin.CommentsAdmin.flag_comments(), django.contrib.comments.admin.CommentsAdmin.remove_comments(), and django.utils.timesince.timesince().
Variable Documentation
list django.utils.translation.__all__
Initial value:
 = [
     'activate', 'deactivate', 'override', 'deactivate_all',
     'get_language',  'get_language_from_request',
     'get_language_info', 'get_language_bidi',
     'check_for_language', 'to_locale', 'templatize', 'string_concat',
     'gettext', 'gettext_lazy', 'gettext_noop',
     'ugettext', 'ugettext_lazy', 'ugettext_noop',
     'ngettext', 'ngettext_lazy',
     'ungettext', 'ungettext_lazy',
     'pgettext', 'pgettext_lazy',
     'npgettext', 'npgettext_lazy',
 ]
Definition at line 11 of file __init__.py.
tuple django.utils.translation._trans = Trans()
Definition at line 59 of file __init__.py.
tuple django.utils.translation.gettext_lazy = lazy(gettext, str)
Definition at line 87 of file __init__.py.
tuple django.utils.translation.pgettext_lazy = lazy(pgettext, six.text_type)
Definition at line 89 of file __init__.py.
Referenced by django.template.base.Variable.resolve().
tuple django.utils.translation.string_concat = lazy(_string_concat, six.text_type)
Definition at line 183 of file __init__.py.
tuple django.utils.translation.ugettext_lazy = lazy(ugettext, six.text_type)
Definition at line 88 of file __init__.py.
Referenced by django.forms.widgets.NullBooleanSelect.__init__(), django.contrib.admin.actions.delete_selected(), django.template.base.Variable.resolve(), and django.contrib.messages.tests.base.BaseTests.test_add_lazy_translation().
django.utils.translation.ugettext_noop = gettext_noop
Definition at line 67 of file __init__.py.