Django: django.views.decorators.http Namespace Reference
django.views.decorators.http Namespace Reference
Functions
def require_http_methods (request_method_list)
def condition
def etag (etag_func)
def last_modified (last_modified_func)
Variables
tuple conditional_page = decorator_from_middleware(ConditionalGetMiddleware)
tuple logger = logging.getLogger('django.request')
tuple require_GET = require_http_methods(["GET"])
tuple require_POST = require_http_methods(["POST"])
tuple require_safe = require_http_methods(["GET", "HEAD"])
Detailed Description
Decorators for views based on HTTP headers.
Function Documentation
def django.views.decorators.http.condition (etag_func = None, last_modified_func = None)
Decorator to support conditional retrieval (or change) for a view
function.
The parameters are callables to compute the ETag and last modified time for
the requested resource, respectively. The callables are passed the same
parameters as the view itself. The Etag function should return a string (or
None if the resource doesn't exist), whilst the last_modified function
should return a datetime object (or None if the resource doesn't exist).
If both parameters are provided, all the preconditions must be met before
the view is processed.
This decorator will either pass control to the wrapped view function or
return an HTTP 304 response (unmodified) or 412 response (preconditions
failed), depending upon the request method.
Any behavior marked as "undefined" in the HTTP spec (e.g. If-none-match
plus If-modified-since headers) will result in the view function being
called.
Definition at line 54 of file http.py.
References django.utils.decorators.available_attrs(), and django.utils.six.wraps.
Referenced by django.views.decorators.http.etag(), django.contrib.formtools.wizard.views.WizardView.get_form_list(), and django.views.decorators.http.last_modified().
def django.views.decorators.http.etag (etag_func)
Definition at line 161 of file http.py.
References django.views.decorators.http.condition().
def django.views.decorators.http.last_modified (last_modified_func)
Definition at line 164 of file http.py.
References django.views.decorators.http.condition().
def django.views.decorators.http.require_http_methods (request_method_list)
Decorator to make a view only accept particular request methods.  Usage::
    @require_http_methods(["GET", "POST"])
    def my_view(request):
        # I can assume now that only GET or POST requests make it this far
        # ...
Note that request methods should be in uppercase.
Definition at line 19 of file http.py.
References django.utils.decorators.available_attrs(), and django.utils.six.wraps.
Variable Documentation
tuple django.views.decorators.http.conditional_page = decorator_from_middleware(ConditionalGetMiddleware)
Definition at line 14 of file http.py.
tuple django.views.decorators.http.logger = logging.getLogger('django.request')
Definition at line 16 of file http.py.
tuple django.views.decorators.http.require_GET = require_http_methods(["GET"])
Definition at line 45 of file http.py.
tuple django.views.decorators.http.require_POST = require_http_methods(["POST"])
Definition at line 48 of file http.py.
tuple django.views.decorators.http.require_safe = require_http_methods(["GET", "HEAD"])
Definition at line 51 of file http.py.