Django: django.contrib.redirects.models.Redirect Class Reference
django.contrib.redirects.models.Redirect Class Reference
Classes
class Meta
Public Member Functions
def __str__ (self)
Static Public Attributes
tuple site = models.ForeignKey(Site)
tuple old_path
tuple new_path
Detailed Description
Definition at line 7 of file models.py.
Member Function Documentation
def django.contrib.redirects.models.Redirect.__str__ (self)
Definition at line 21 of file models.py.
References django.contrib.redirects.models.Redirect.new_path, and django.contrib.redirects.models.Redirect.old_path.
Member Data Documentation
tuple django.contrib.redirects.models.Redirect.new_path static
Initial value:
 = models.CharField(_('redirect to'), max_length=200, blank=True,
         help_text=_("This can be either an absolute path (as above) or a full URL starting with 'http://'."))
Definition at line 11 of file models.py.
Referenced by django.contrib.redirects.models.Redirect.__str__().
tuple django.contrib.redirects.models.Redirect.old_path static
Initial value:
 = models.CharField(_('redirect from'), max_length=200, db_index=True,
         help_text=_("This should be an absolute path, excluding the domain name. Example: '/events/search/'."))
Definition at line 9 of file models.py.
Referenced by django.contrib.redirects.models.Redirect.__str__().
tuple django.contrib.redirects.models.Redirect.site = models.ForeignKey(Site) static
Definition at line 8 of file models.py.
Referenced by django.contrib.redirects.tests.RedirectTests.test_model(), django.contrib.redirects.tests.RedirectTests.test_redirect(), django.contrib.redirects.tests.RedirectTests.test_redirect_with_append_slash(), django.contrib.redirects.tests.RedirectTests.test_redirect_with_append_slash_and_query_string(), and django.contrib.redirects.tests.RedirectTests.test_response_gone().
The documentation for this class was generated from the following file:
dj16/lib/python2.7/site-packages/django/contrib/redirects/models.py