Django: django.core.mail Namespace Reference
django.core.mail Namespace Reference
Namespaces
backends
message
utils
Functions
def get_connection (backend=None, fail_silently=False, kwds)
def send_mail
def send_mass_mail
def mail_admins
def mail_managers
Detailed Description
Tools for sending email.
Function Documentation
def django.core.mail.get_connection (backend = None, fail_silently = False, kwds)
Load an email backend and return an instance of it.
If backend is None (default) settings.EMAIL_BACKEND is used.
Both fail_silently and other keyword arguments are used in the
constructor of the backend.
Definition at line 21 of file __init__.py.
References django.utils.module_loading.import_by_path(), and django.core.mail.send_mail().
Referenced by django.utils.log.AdminEmailHandler.connection(), django.core.mail.send_mail(), and django.core.mail.send_mass_mail().
def django.core.mail.mail_admins (subject, message, fail_silently = False, connection = None, html_message = None)
Sends a message to the admins, as defined by the ADMINS setting.
Definition at line 77 of file __init__.py.
References django.core.mail.mail_managers().
Referenced by django.core.mail.send_mass_mail().
def django.core.mail.mail_managers (subject, message, fail_silently = False, connection = None, html_message = None)
Sends a message to the managers, as defined by the MANAGERS setting.
Definition at line 90 of file __init__.py.
Referenced by django.core.mail.mail_admins(), and django.middleware.common.BrokenLinkEmailsMiddleware.process_response().
def django.core.mail.send_mail (subject, message, from_email, recipient_list, fail_silently = False, auth_user = None, auth_password = None, connection = None)
Easy wrapper for sending a single message to a recipient list. All members
of the recipient list will see the other recipients in the 'To' field.
If auth_user is None, the EMAIL_HOST_USER setting is used.
If auth_password is None, the EMAIL_HOST_PASSWORD setting is used.
Note: The API for this method is frozen. New code wanting to extend the
functionality should use the EmailMessage class directly.
Definition at line 35 of file __init__.py.
References django.core.mail.get_connection(), and django.core.mail.send_mass_mail().
Referenced by django.contrib.comments.moderation.CommentModerator.email(), django.contrib.auth.models.AbstractUser.email_user(), django.core.mail.get_connection(), and django.contrib.auth.forms.PasswordResetForm.save().
def django.core.mail.send_mass_mail (datatuple, fail_silently = False, auth_user = None, auth_password = None, connection = None)
Given a datatuple of (subject, message, from_email, recipient_list), sends
each message to each recipient list. Returns the number of emails sent.
If from_email is None, the DEFAULT_FROM_EMAIL setting is used.
If auth_user and auth_password are set, they're used to log in.
If auth_user is None, the EMAIL_HOST_USER setting is used.
If auth_password is None, the EMAIL_HOST_PASSWORD setting is used.
Note: The API for this method is frozen. New code wanting to extend the
functionality should use the EmailMessage class directly.
Definition at line 54 of file __init__.py.
References django.core.mail.get_connection(), and django.core.mail.mail_admins().
Referenced by django.core.mail.send_mail().